import test from 'node:test';import assert from 'node:assert/strict';
import {validateRawRecognition,publishRawRecognition,PILOT_SOURCE_SHA256} from '../../server/fia/preparation/hosted-asr/artifact.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const effectiveConfig={device:'cpu',computeType:'int8',cpuThreads:2,initialPrompt:null,prefix:null,hotwords:null,language:'en',modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120'};
const expected={sourceSha256:PILOT_SOURCE_SHA256,sourceBytes:867865,modelSha256:'b'.repeat(64),runtimeSha256:'c'.repeat(64),scriptSha256:'d'.repeat(64),configSha256:await sha256(canonicalJSONString(effectiveConfig))};
function raw(){return {schema:'fia-hosted-raw-recognition@1',status:'candidate',source:{sha256:expected.sourceSha256,bytes:867865},modelSha256:expected.modelSha256,runtimeSha256:expected.runtimeSha256,scriptSha256:expected.scriptSha256,configSha256:expected.configSha256,effectiveConfig,decoder:{samples:16000,sampleRate:16000,sha256:'e'.repeat(64)},durationSeconds:1,text:' example',segments:[{id:0,seek:0,start:0.1,end:0.5,text:' example',tokens:[123],avg_logprob:-0.2,compression_ratio:1,no_speech_prob:0.1,temperature:0,words:[{word:' example',start:0.1,end:0.5,probability:0.8}]}],uncertainty:['Uncalibrated model estimates; not playback acceptance.']};}
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));
function bucket(){const data=new Map();return {data,async get(key){const bytes=data.get(key);return bytes?{size:bytes.length,body:new Blob([bytes]).stream()}:null;},async put(key,bytes,options){assert.deepEqual(options,{onlyIf:{etagDoesNotMatch:'*'}});if(data.has(key))return null;data.set(key,bytes.slice());return {};}};}
test('raw candidate strictly binds provenance, finite clocks and probabilities',async()=>{assert.equal(await validateRawRecognition(encode(raw()),expected),true);for(const mutate of [r=>r.source.bytes++,r=>r.modelSha256='f'.repeat(64),r=>r.effectiveConfig={cpuThreads:4},r=>r.segments[0].words[0].end=2,r=>r.segments[0].words[0].probability=1.1,r=>r.status='accepted',r=>r.decoder.samples++]){const r=raw();mutate(r);await assert.rejects(validateRawRecognition(encode(r),expected));}});
test('create-only R2 objects and deterministic receipt refuse nondeterministic replacement',async()=>{const b=bucket(),nodeKey='f'.repeat(64),bytes=encode(raw());const first=await publishRawRecognition({bucket:b,ledger:'A',attemptId:'attempt',revision:1,bytes,expected,nodeKey});assert.deepEqual(await publishRawRecognition({bucket:b,ledger:'A',attemptId:'attempt',revision:1,bytes,expected,nodeKey}),first);assert.equal(b.data.size,2);const changed=raw();changed.segments[0].words[0].word=' different';await assert.rejects(publishRawRecognition({bucket:b,ledger:'A',attemptId:'attempt',revision:1,bytes:encode(changed),expected,nodeKey}),/conflict|size/);assert.equal(new TextDecoder().decode(b.data.get(`recognition/nodes/A/${nodeKey}.json`)).includes(first.sha256),true);});
test('corrupt existing body never overwritten',async()=>{const b=bucket(),bytes=encode(raw()),key=`recognition/sha256/${await sha256(bytes)}.json`;b.data.set(key,new Uint8Array(bytes.length));await assert.rejects(publishRawRecognition({bucket:b,ledger:'A',attemptId:'attempt',revision:1,bytes,expected,nodeKey:'f'.repeat(64)}),/conflict/);assert.equal(b.data.get(key)[0],0);});
