import test from 'node:test';
import assert from 'node:assert/strict';
import {createHostedDispatch} from '../../server/fia/preparation/hosted-asr/dispatch.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
function storage(){const rows=new Map();let queue=Promise.resolve();return {get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v)),setAlarm:async()=>{},transaction(fn){const p=queue.then(()=>fn(this));queue=p.catch(()=>{});return p;}};}
const identity={sourceSha256:'0f3fa9e77215f5050f9e22b7abee329c47e0e9ff71a5f0c4d248926a8f42268d',sourceBytes:867865,modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120',language:'eng',runtimeSha256:'e'.repeat(64),configSha256:'b'.repeat(64),modelSha256:'c'.repeat(64),scriptSha256:'d'.repeat(64)};
const bytes=new TextEncoder().encode('{}'),digest=await sha256(bytes),artifact={sha256:digest,reference:`recognition/sha256/${digest}.json`};
function setup(extra={}){return {storage:storage(),ledger:'A',identity,activation:{startedAt:0,expiresAt:1200000},now:()=>100,verifyArtifact:async()=>bytes,validateResult:async()=>true,executor:{limitsEnforced:true,start:async()=>artifact,stop:async()=>true},...extra};}
test('concurrent owner and durable warm reuse; two ledgers share two-start budget',async()=>{let release,calls=0;const options=setup({executor:{limitsEnforced:true,start:async()=>{calls++;await new Promise(r=>release=r);return artifact;},stop:async()=>true}});const first=createHostedDispatch(options).dispatch();while(!release)await new Promise(r=>setImmediate(r));assert.equal((await createHostedDispatch(options).dispatch()).state,'preparing');release();assert.equal((await first).state,'completed');assert.equal((await createHostedDispatch({...options,executor:{...options.executor,start:()=>{throw Error('offline');}}}).dispatch()).state,'completed');assert.equal(calls,1);const other=createHostedDispatch({...options,ledger:'B',executor:{...options.executor,start:async()=>artifact}});assert.equal((await other.dispatch()).state,'completed');assert.equal((await options.storage.get('hosted:budget')).starts,2);});
test('ambiguous dispatch never reruns; expiry stops process and refuses reconciliation',async()=>{let clock=100,calls=0,stops=0;const options=setup({now:()=>clock,executor:{limitsEnforced:true,start:async()=>{calls++;throw Error('lost');},stop:async()=>{stops++;return true;}}});const service=createHostedDispatch(options),row=await service.dispatch();assert.equal(row.state,'uncertain');await service.dispatch();assert.equal(calls,1);clock=400000;assert.equal((await service.watchdog()).stopVerified,true);assert.equal(stops,1);await assert.rejects(service.reconcile({...row,artifact}),/fence/);});
test('fail closed capability, identity budget conflict and corrupt warm bytes',async()=>{const options=setup();assert.equal((await createHostedDispatch({...options,executor:{limitsEnforced:false}}).dispatch()).reason,'enforced-executor-unavailable');await createHostedDispatch(options).dispatch();await assert.rejects(createHostedDispatch({...options,identity:{...identity,configSha256:'e'.repeat(64)}}).dispatch(),/conflict/);assert.equal((await createHostedDispatch({...options,verifyArtifact:async()=>new Uint8Array([1])}).dispatch()).state,'unavailable');});

test('other isolated ledger cannot overlap or retry uncertain compute',async()=>{const options=setup({executor:{limitsEnforced:true,start:async()=>{throw Error('unknown');},stop:async()=>true}});await createHostedDispatch(options).dispatch();assert.equal((await createHostedDispatch({...options,ledger:'B'}).dispatch()).reason,'singleton-unresolved');assert.equal((await options.storage.get('hosted:budget')).starts,1);});
test('verified result cannot complete or release singleton without verified stop',async()=>{for(const stop of [async()=>false,async()=>{throw Error('lost-stop');}]){const options=setup({executor:{limitsEnforced:true,start:async()=>artifact,stop}}),a=createHostedDispatch(options);assert.equal((await a.dispatch()).state,'uncertain');assert.equal((await createHostedDispatch({...options,ledger:'B'}).dispatch()).reason,'singleton-unresolved');}});
test('warm completed A remains reusable while isolated B is uncertain',async()=>{const options=setup();const a=createHostedDispatch(options);assert.equal((await a.dispatch()).stopVerified,true);await createHostedDispatch({...options,ledger:'B',executor:{...options.executor,start:async()=>{throw Error('lost');}}}).dispatch();assert.equal((await a.dispatch()).state,'completed');});
test('persisted malformed completion and opposite ledger fail closed before reuse/start',async()=>{for(const mutate of [row=>delete row.stopVerified,row=>row.state='invented',row=>row.unexpected='field']){const options=setup();await createHostedDispatch(options).dispatch();const budget=await options.storage.get('hosted:budget'),key=`hosted:A:${budget.nodeKey}`,row=await options.storage.get(key);mutate(row);await options.storage.put(key,row);await assert.rejects(createHostedDispatch(options).dispatch(),/corrupt/);await assert.rejects(createHostedDispatch({...options,ledger:'B'}).dispatch(),/corrupt/);}});
test('constructor rejects unbounded/unknown metadata and persisted missing debit',async()=>{assert.throws(()=>createHostedDispatch(setup({identity:{...identity,extra:'x'.repeat(17000)}})),/pins/);const options=setup();await createHostedDispatch(options).dispatch();await options.storage.put('hosted:budget',undefined);await assert.rejects(createHostedDispatch(options).dispatch(),/missing-budget/);});
test('failed dispatch immediately stops; failed stops retain finite retry budget and alarm',async()=>{let clock=100,calls=0,stops=0;const alarms=[];const options=setup({now:()=>clock,executor:{limitsEnforced:true,start:async()=>{calls++;throw Error('lost');},stop:async()=>{stops++;return false;}}});options.storage.setAlarm=async value=>alarms.push(value);const service=createHostedDispatch(options);let row=await service.dispatch();assert.equal(row.state,'uncertain');assert.equal(stops,1);for(let i=0;i<3;i++){clock+=31000;row=await service.watchdog();}assert.equal(stops,3);assert.equal(calls,1);assert.equal(row.reason,'stop-unresolved-manual-intervention');assert.equal(row.stopAttempts,3);assert(alarms.length>=3);await service.dispatch();assert.equal(calls,1);});
test('unresponsive stop is bounded rather than hanging dispatch forever',async t=>{t.mock.timers.enable({apis:['setTimeout']});let stops=0;const options=setup({executor:{limitsEnforced:true,start:async()=>{throw Error('lost');},stop:()=>{stops++;return new Promise(()=>{});}}});const pending=createHostedDispatch(options).dispatch();while(!stops)await new Promise(r=>setImmediate(r));t.mock.timers.tick(30000);const row=await pending;assert.equal(row.state,'uncertain');assert.equal(row.stopVerified,false);assert.equal(row.stopAttempts,1);});
