import test from 'node:test';import assert from 'node:assert/strict';
import {validateRawRecognition,publishRawRecognition,PILOT_SOURCE_SHA256} from '../../server/fia/preparation/hosted-asr/artifact.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const effectiveConfig={transcribeOptions:{language:'en',task:'transcribe',beam_size:5,word_timestamps:true,condition_on_previous_text:false,initial_prompt:null,prefix:null,hotwords:null,vad_filter:false},device:'cpu',computeType:'int8',cpuThreads:2,initialPrompt:null,prefix:null,hotwords:null,language:'en',modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120'};
const expected={sourceSha256:PILOT_SOURCE_SHA256,sourceBytes:867865,modelSha256:'b'.repeat(64),runtimeSha256:'c'.repeat(64),scriptSha256:'d'.repeat(64),configSha256:await sha256(canonicalJSONString(effectiveConfig))};
function raw(){return {schema:'fia-hosted-raw-recognition@1',status:'candidate',source:{sha256:expected.sourceSha256,bytes:867865},modelSha256:expected.modelSha256,runtimeSha256:expected.runtimeSha256,scriptSha256:expected.scriptSha256,configSha256:expected.configSha256,effectiveConfig,decoder:{samples:16000,sampleRate:16000,sha256:'e'.repeat(64)},durationSeconds:1,text:' example',segments:[{id:0,seek:0,start:0.1,end:0.5,text:' example',tokens:[123],avg_logprob:-0.2,compression_ratio:1,no_speech_prob:0.1,temperature:0,words:[{word:' example',start:0.1,end:0.5,probability:0.8}]}],uncertainty:['Uncalibrated model estimates; not playback acceptance.']};}
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));
function bucket(){const data=new Map();return {data,async get(key){const bytes=data.get(key);return bytes?{size:bytes.length,body:new Blob([bytes]).stream()}:null;},async put(key,bytes,options){assert.deepEqual(options,{onlyIf:{etagDoesNotMatch:'*'}});if(data.has(key))return null;data.set(key,bytes.slice());return {};}};}

import {createCloudflarePilot,requestPilotA,requestPilotB} from '../../server/fia/preparation/hosted-asr/cloudflare.mjs';
function storage(){const rows=new Map();let queue=Promise.resolve(),alarm=null;return {rows,get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v)),delete:async k=>rows.delete(k),setAlarm:async value=>{alarm=value;},deleteAlarm:async()=>{alarm=null;},getAlarm:async()=>alarm,transaction(fn){const p=queue.then(()=>fn(this));queue=p.catch(()=>{});return p;}};}
function fixture(){
 const store=storage(),r2=bucket(),identity={...expected,modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120',language:'eng'},config={enabled:true,identity,activation:{startedAt:0,expiresAt:1200000},image:'registry/image@sha256:'+ 'a'.repeat(64),enforcementSha256:'b'.repeat(64),enforcement:{offline:true}};
 let starts=0,stops=0,requests=0,clock=100,disabled=false;
 const container={running:false,inspect:async()=>container.running?{image:''}:null,start(options){assert.equal(options.enableInternet,false);assert.equal('image'in options,false);container.running=true;starts++;},monitor:()=>new Promise(()=>{}),setInactivityTimeout:async value=>assert.equal(value,30000),destroy:async()=>{stops++;container.running=false;},getTcpPort(port){assert.equal(port,8080);return {fetch:async(url,options)=>{if(url.endsWith('/ready'))return Response.json({schema:'fia-asr-ready@1',guards:{schema:'fia-image-guards@1',addressSpaceBytes:4294967296,scratchPolicy:'landlock-no-filesystem-writes',scratchBytes:0,landlockAbi:3,anonymousFilesDenied:true},...Object.fromEntries(['modelSha256','runtimeSha256','scriptSha256','configSha256'].map(k=>[k,identity[k]]))});requests++;assert.equal(options.method,'POST');assert.equal(options.headers['Content-Type'],'audio/mpeg');assert.equal(options.headers['X-Fia-Ledger'],'A');return Response.json(raw());}};}};
 const options={ctx:{id:{toString:()=>'singleton'},storage:store,container,waitUntil(){}},env:{FIA_ORIGINALS:r2,FIA_ASR_EXECUTOR:{idFromName:()=>({toString:()=>'singleton'})}},loadActivation:async()=>{if(disabled)throw Error('activation-disabled');return config;},now:()=>clock,readRetainedSource:async()=>new Uint8Array(867865)};
 return {options,container,store,r2,config,counters:()=>({starts,stops,requests}),disable:()=>{disabled=true;},advance:value=>{clock=value;}};
}

test('global quarantine precedes a gated emergency destroy and permanently blocks B admission',async()=>{const f=fixture(),pilot=createCloudflarePilot(f.options);assert.equal((await pilot.pilotA()).state,'completed');let release,stops=0;f.container.destroy=async()=>{stops++;await new Promise(r=>release=r);f.container.running=false;};let fail=true;const originalDelete=f.store.deleteAlarm;f.store.deleteAlarm=async()=>{if(fail){fail=false;throw Error('alarm-storage-failed');}return originalDelete();};const cleanup=pilot.alarm();while(!release)await new Promise(r=>setImmediate(r));assert.equal((await f.store.get('hosted:emergency-stop')).state,'pending');assert.equal((await pilot.pilotB()).reason,'singleton-quarantined');assert.equal((await f.store.get('hosted:budget')).starts,1);release();await cleanup;assert.equal((await pilot.pilotB()).reason,'singleton-quarantined');await pilot.alarm();assert.equal(stops,1);assert.equal((await pilot.statusA()).singletonQuarantine.state,'quarantined');});
test('a source read already in flight cannot start after emergency quarantine',async()=>{const f=fixture();let hold=false,release,waiting=false;f.options.readRetainedSource=async()=>{if(hold){waiting=true;await new Promise(r=>release=r);}return new Uint8Array(867865);};const pilot=createCloudflarePilot(f.options);await pilot.pilotA();hold=true;const pending=pilot.pilotB();while(!waiting)await new Promise(r=>setImmediate(r));let fail=true;const originalDelete=f.store.setAlarm;f.store.setAlarm=async(...args)=>{if(fail){fail=false;throw Error('alarm-storage-failed');}return originalDelete(...args);};await pilot.alarm();release();const result=await pending;assert.equal(result.state,'uncertain');assert.equal(f.counters().starts,1);assert.equal((await pilot.pilotB()).reason,'singleton-quarantined');});
