import test from 'node:test';import assert from 'node:assert/strict';
import {createHostedRecognitionAdapter,hostedModelRecipe,hostedAlignmentValidator} from '../../server/fia/preparation/hosted-asr/pipeline-adapter.mjs';
import {createAlignmentAdapter} from '../../server/fia/preparation/executor/alignment.mjs';
import {createAcceptanceAdapter} from '../../server/fia/preparation/executor/acceptance.mjs';
import {PILOT_SOURCE_SHA256} from '../../server/fia/preparation/hosted-asr/artifact.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));
async function fixture(){
 const effectiveConfig={transcribeOptions:{language:'en',task:'transcribe',beam_size:5,word_timestamps:true,condition_on_previous_text:false,initial_prompt:null,prefix:null,hotwords:null,vad_filter:false},device:'cpu',computeType:'int8',cpuThreads:2,initialPrompt:null,prefix:null,hotwords:null,language:'en',modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120'};
 const identity={sourceSha256:PILOT_SOURCE_SHA256,sourceBytes:867865,modelId:effectiveConfig.modelId,modelRevision:effectiveConfig.modelRevision,language:'eng',modelSha256:'b'.repeat(64),runtimeSha256:'c'.repeat(64),scriptSha256:'d'.repeat(64),configSha256:await sha256(canonicalJSONString(effectiveConfig))};
 const config={enabled:true,identity,image:'registry.example/fia@sha256:'+'1'.repeat(64),enforcementSha256:'2'.repeat(64),reviewSha256:'3'.repeat(64)};
 const raw={schema:'fia-hosted-raw-recognition@1',status:'candidate',source:{sha256:identity.sourceSha256,bytes:867865},modelSha256:identity.modelSha256,runtimeSha256:identity.runtimeSha256,scriptSha256:identity.scriptSha256,configSha256:identity.configSha256,effectiveConfig,decoder:{samples:16000,sampleRate:16000,sha256:'e'.repeat(64)},durationSeconds:1,text:' example',segments:[{id:0,seek:0,start:0.1,end:0.5,text:' example',tokens:[123],avg_logprob:-0.2,compression_ratio:1,no_speech_prob:0.1,temperature:0,words:[{word:' example',start:0.1,end:0.5,probability:0.8}]}],uncertainty:['Uncalibrated; not playback acceptance.']};
 const retained=new Map(),storeArtifact=async bytes=>{const sha=await sha256(bytes),reference=`recognition/sha256/${sha}.json`;retained.set(reference,bytes.slice());return {sha256:sha,reference};},resolveArtifact=async a=>retained.get(a.reference)?.slice();
 const artifact=await storeArtifact(encode(raw));let calls=0;
 const namespace={idFromName:name=>{assert.equal(name,'asr-pilot-v1');return name;},get:()=>({pilotA:async()=>{calls++;return {state:'completed',stopVerified:true,artifact};}})};
 const input={packId:'fixture',book:'MRK',language:'eng',edition:'publisher',passage:'1:14-20',resource:'S01',scriptSha256:'f'.repeat(64),policyRevision:'fixture@1',modelRecipe:await hostedModelRecipe(config)};
 return {config,raw,artifact,input,retained,storeArtifact,resolveArtifact,namespace,get calls(){return calls;},context:{input,nodeOutputs:{acquire:{sha256:PILOT_SOURCE_SHA256}}}};
}
test('private pipeline uses only A and preserves raw candidate for generic alignment and review',async()=>{const f=await fixture(),adapter=createHostedRecognitionAdapter(f);assert.equal(adapter.paid,true);const transcribe=await adapter.run(f.context);assert.deepEqual(transcribe,f.artifact);assert.equal(f.calls,1);const options={resolveArtifact:f.resolveArtifact,storeArtifact:f.storeArtifact,resolveUnits:async()=>({scriptSha256:f.input.scriptSha256,units:[{activityId:'a',sourceUnitId:'u',text:'example',sourceTextSha256:await sha256('example')}]})};const context={...f.context,nodeOutputs:{...f.context.nodeOutputs,transcribe}};const align=await createAlignmentAdapter({...options,recognitionSchema:'fia-hosted-raw-recognition@1',recognitionValidator:hostedAlignmentValidator(f.config)}).run(context);const report=JSON.parse(new TextDecoder().decode(await f.resolveArtifact(align)));assert.equal(report.mappings[0].status,'exact-candidate');assert.deepEqual(report.acceptedPlaybackRanges,[]);const decision=await createAcceptanceAdapter(options).run({...context,nodeOutputs:{...context.nodeOutputs,align}});assert.equal(JSON.parse(new TextDecoder().decode(await f.resolveArtifact(decision))).status,'review-required');});
test('each executor dependency invalidates recipe and wrong source refuses before RPC',async()=>{const f=await fixture();for(const field of ['runtimeSha256','scriptSha256','modelSha256','configSha256']){const changed=structuredClone(f.config);changed.identity[field]='0'.repeat(64);assert.notEqual((await hostedModelRecipe(changed)).configSha256,f.input.modelRecipe.configSha256);}for(const field of ['image','enforcementSha256','reviewSha256']){const changed=structuredClone(f.config);changed[field]+='x';assert.notEqual((await hostedModelRecipe(changed)).configSha256,f.input.modelRecipe.configSha256);}await assert.rejects(createHostedRecognitionAdapter(f).run({...f.context,nodeOutputs:{acquire:{sha256:'0'.repeat(64)}}}),/identity/);assert.equal(f.calls,0);});
test('unverified stop and corrupt stored bytes cannot enter downstream alignment',async()=>{const f=await fixture();const bad={...f,namespace:{idFromName:x=>x,get:()=>({pilotA:async()=>({state:'completed',stopVerified:false,artifact:f.artifact})})}};await assert.rejects(createHostedRecognitionAdapter(bad).run(f.context),/unresolved/);f.retained.set(f.artifact.reference,encode({}));await assert.rejects(createHostedRecognitionAdapter(f).run(f.context),/artifact/);});
test('real retained pilot source traverses generic pipeline and warm restart avoids RPC',{skip:!process.env.FIA_PILOT_SOURCE},async()=>{
 const {readFile}=await import('node:fs/promises');const {createPipeline}=await import('../../server/fia/preparation/executor/pipeline.mjs');const f=await fixture();
 const source=new Uint8Array(await readFile(process.env.FIA_PILOT_SOURCE));assert.equal(source.length,867865);assert.equal(await sha256(source),PILOT_SOURCE_SHA256);const acquired=await f.storeArtifact(source);const discovered=await f.storeArtifact(encode({schema:'test-discovery',sourceSha256:PILOT_SOURCE_SHA256}));
 const values=new Map();let tail=Promise.resolve();const storage={transaction(fn){const result=tail.then(async()=>{const stage=new Map(structuredClone([...values]));const out=await fn({get:async k=>structuredClone(stage.get(k)),put:async(k,v)=>stage.set(k,structuredClone(v))});values.clear();for(const pair of stage)values.set(...pair);return out;});tail=result.catch(()=>{});return result;}};
 const options={resolveArtifact:f.resolveArtifact,storeArtifact:f.storeArtifact,resolveUnits:async()=>({scriptSha256:f.input.scriptSha256,units:[{activityId:'a',sourceUnitId:'u',text:'example',sourceTextSha256:await sha256('example')}]})};
 let publishes=0;const adapters={discover:{paid:false,run:async()=>discovered},acquire:{paid:false,run:async()=>acquired},transcribe:createHostedRecognitionAdapter(f),align:createAlignmentAdapter({...options,recognitionSchema:'fia-hosted-raw-recognition@1',recognitionValidator:hostedAlignmentValidator(f.config)}),accept:createAcceptanceAdapter(options),publish:{paid:false,run:async()=>{publishes++;throw Error('must remain gated');}}};
 const input={...f.input,source:{publisherId:'official',resourceId:'pilot',version:'v2'}},base={storage,policyId:'hosted-composition-test',adapters,verifyArtifact:f.resolveArtifact,allowPaid:true};
 const first=await createPipeline(base).run(input);assert.equal(first.reason,'review-required');assert.equal(f.calls,1);assert.equal(publishes,0);
 const second=await createPipeline({...base,adapters:{...adapters,transcribe:{paid:true,run:()=>{throw Error('offline');}}}}).run(input);assert.equal(second.reason,'review-required');assert.equal(f.calls,1);assert.equal(publishes,0);
});

test('alignment refuses false or missing validation acknowledgement',async()=>{const f=await fixture();for(const value of [false,undefined])await assert.rejects(createAlignmentAdapter({resolveArtifact:f.resolveArtifact,storeArtifact:f.storeArtifact,resolveUnits:async()=>({}),recognitionSchema:'fia-hosted-raw-recognition@1',recognitionValidator:async()=>value}).run({...f.context,nodeOutputs:{...f.context.nodeOutputs,transcribe:f.artifact}}),/recognition-validation/);});
