import test from 'node:test';
import assert from 'node:assert/strict';
import {createHostedDispatch} from '../../server/fia/preparation/hosted-asr/dispatch.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
function storage(){const rows=new Map();let queue=Promise.resolve();return {get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v)),setAlarm:async()=>{},transaction(fn){const p=queue.then(()=>fn(this));queue=p.catch(()=>{});return p;}};}
const identity={sourceSha256:'0f3fa9e77215f5050f9e22b7abee329c47e0e9ff71a5f0c4d248926a8f42268d',sourceBytes:867865,modelId:'Systran/faster-whisper-small',modelRevision:'536b0662742c02347bc0e980a01041f333bce120',language:'eng',runtimeSha256:'e'.repeat(64),configSha256:'b'.repeat(64),modelSha256:'c'.repeat(64),scriptSha256:'d'.repeat(64)};
const bytes=new TextEncoder().encode('{}'),digest=await sha256(bytes),artifact={sha256:digest,reference:`recognition/sha256/${digest}.json`};
function setup(extra={}){return {storage:storage(),ledger:'A',identity,activation:{startedAt:0,expiresAt:1200000},now:()=>100,verifyArtifact:async()=>bytes,validateResult:async()=>true,executor:{limitsEnforced:true,start:async()=>artifact,stop:async()=>true},...extra};}
test('explicit reconciliation requires original attempt and revision and does not allocate a start',async()=>{let starts=0,stops=0;const options=setup({executor:{limitsEnforced:true,start:async()=>{starts++;throw Error('late-result');},stop:async()=>{stops++;return true;}}});const service=createHostedDispatch(options),row=await service.dispatch();assert.equal(row.state,'uncertain');await assert.rejects(service.reconcile({attemptId:'wrong',revision:row.revision,artifact}),/fence/);await assert.rejects(service.reconcile({attemptId:row.attemptId,revision:row.revision+1,artifact}),/fence/);const result=await service.reconcile({attemptId:row.attemptId,revision:row.revision,artifact});assert.equal(result.state,'completed');assert.equal(result.reconciled,true);assert.equal(result.stopVerified,true);assert.equal(starts,1);assert.equal(stops,1);assert.equal((await options.storage.get('hosted:budget')).starts,1);await assert.rejects(service.reconcile({attemptId:row.attemptId,revision:row.revision,artifact}),/fence/);});
