import {createControlledAuthority} from './controlled-authority.mjs';
import {observeNativeProgress} from './native-progress.mjs';
// Controlled protocol fixture, NOT a hosted/Worker pipeline test. Native media remains real.
import https from 'node:https';import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {resolve,join,extname} from 'node:path';import {createRequire} from 'node:module';import {createHash} from 'node:crypto';import {execFileSync} from 'node:child_process';import {assertCancellation,assertPlayback} from './assert-observation.mjs';
const [repoArg,mediaArg,tlsArg,outArg]=process.argv.slice(2);if(!outArg)throw Error('Usage: node controlled-pending.mjs EXACT_BUILT_REPO RETAINED_MP3 TLS_DIR OUTPUT_DIR');
const repo=resolve(repoArg),out=resolve(outArg),tls=resolve(tlsArg),origin='https://dev.fiaguide.app',sha=b=>createHash('sha256').update(b).digest('hex');mkdirSync(out,{recursive:true});
const commit=execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),stamp=JSON.parse(readFileSync(join(repo,'dist/version.json')));if(stamp.commit!==commit)throw Error('Built candidate mismatch');
const resultSha='186956fb526a0671025180f637c0f6e6b336129085e21951da6e59e89b33fcee',raw=readFileSync(join(repo,`apps/web/public/content/prepared-audio/${resultSha}.json`)),result=JSON.parse(raw),media=readFileSync(mediaArg);if(sha(raw)!==resultSha||sha(media)!==result.delivery.sha256)throw Error('Retained artifact hash mismatch');
const require=createRequire(join(repo,'package.json')),{chromium}=require('playwright');const job=sha('controlled-fixture-only'),events=[];let phase='preparing',operation=null;
const authority=await createControlledAuthority(repo,origin);
const server=https.createServer({key:readFileSync(join(tls,'local.key')),cert:readFileSync(join(tls,'local.crt'))},async(req,res)=>{try{const path=new URL(req.url,origin).pathname;const send=(status,body,type='application/json')=>{res.writeHead(status,{'content-type':type,'cache-control':'no-store'});res.end(body);};if(path.startsWith('/v1/preparations')){if(req.method==='POST'){let body='';for await(const c of req)body+=c;const identity=JSON.parse(body);const a=result.activities.find(a=>a.activityId===identity.activityId);if(identity.packId!==result.packId||identity.presentationRevision!==result.presentationRevision||!a||identity.sourceTextSha256!==a.sourceTextSha256)return send(422,'{}');operation={operationId:job,identity,startedAt:Date.now()};}
if(!operation)return send(404,'{}');const value={schema:'fia-preparation-status@1',jobId:job,state:phase,reason:null,sourceState:phase==='ready'?'verified':'queued',selection:{packId:result.packId,presentationRevision:result.presentationRevision,language:result.language,edition:result.edition,resource:'guide:S01',quality:'original'},result:phase==='ready'?result:null,resultSha256:phase==='ready'?resultSha:null,statusUrl:'/v1/preparations/'+job,reused:false};events.push({kind:'fixture-response',state:phase,operationId:job,at:Date.now()});return send(200,JSON.stringify(value));}
if(path===result.delivery.url)return send(200,media,'audio/mpeg');if(path==='/mcp'||path.startsWith('/v1/')){let body='';for await(const chunk of req)body+=chunk;const response=await authority.fetch(origin+req.url,{method:req.method,headers:req.headers,...(body?{body}:{})});res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));return;}const file=resolve(repo,'dist','.'+path);if(path!=='/'&&!file.startsWith(join(repo,'dist')+'/'))return send(403,'{}');let bytes;try{bytes=readFileSync(path==='/'?join(repo,'dist/index.html'):file);}catch{return send(404,'{}');}const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.woff2':'font/woff2','.svg':'image/svg+xml'}[extname(file)]||'application/octet-stream';send(200,bytes,path==='/'?'text/html':mime);}catch(error){res.writeHead(500);res.end(error.message);}});
await new Promise(r=>server.listen(5199,'127.0.0.1',r));const browser=await chromium.launch({headless:true,args:['--host-resolver-rules=MAP dev.fiaguide.app:443 127.0.0.1:5199','--no-proxy-server','--ignore-certificate-errors-spki-list='+readFileSync(join(tls,'cert-spki.txt'),'utf8').trim()]});const receipt={mode:'controlled-local-protocol-fixture',commit,origin,descriptorSha256:resultSha,mediaSha256:sha(media),claims:[],diagnostics:[],events,authority:{snapshotSha256:authority.snapshotSha256,observations:authority.observations}};
async function run(mode){const diagnostic={mode,samples:[]};receipt.diagnostics.push(diagnostic);phase='preparing';operation=null;const context=await browser.newContext({viewport:{width:393,height:852},isMobile:true,hasTouch:true});await context.route('**/*',route=>new URL(route.request().url()).origin===origin?route.continue():route.abort());await context.addInitScript(()=>{window.__audio=[];window.__playing=new WeakSet();window.Audio=new Proxy(window.Audio,{construct(t,args){const a=Reflect.construct(t,args);window.__audio.push(a);a.addEventListener('playing',()=>window.__playing.add(a));for(const event of ['pause','waiting','ended'])a.addEventListener(event,()=>window.__playing.delete(a));return a;}});});const p=await context.newPage();const snapshot=()=>p.evaluate(()=>window.__audio.map(a=>({src:a.currentSrc,time:a.currentTime,paused:a.paused,readyState:a.readyState,seeking:a.seeking,playing:window.__playing.has(a)})));const poll=async fn=>{const end=Date.now()+20000;while(Date.now()<end){if(await fn())return;await new Promise(r=>setTimeout(r,100));}throw Error('Timed out: '+mode);};const toggle=async value=>{await p.getByRole('button',{name:'More options',exact:true}).click();await p.getByRole('button',{name:'Settings',exact:true}).click();await p.getByRole('checkbox',{name:/Automatic guide narration/}).setChecked(value);await p.getByRole('button',{name:'Close',exact:true}).click();};
try{await p.goto(origin);const loadedCommit=await p.locator('meta[name="fia-source-commit"]').getAttribute('content');if(loadedCommit!==commit)throw Error('Loaded full candidate mismatch');receipt.loadedCommit=loadedCommit;const loaded=await p.locator('meta[name="fia-release"]').getAttribute('content');if(loaded!==`${stamp.version}+${commit.slice(0,7)}`)throw Error('Loaded candidate mismatch');await p.getByRole('button',{name:'Session progress: open section overview'}).click();await p.getByRole('button',{name:/^Passages/}).click();await p.locator('article.pack-card').filter({has:p.getByRole('heading',{name:'Mark 1:14–20',exact:true})}).getByRole('button',{name:'Open passage',exact:true}).click();await p.getByRole('dialog').waitFor({state:'hidden'});if(mode==='manual')await toggle(false);await p.getByRole('button',{name:mode==='manual'?/^Play$/:/^Begin$/}).click();await poll(()=>operation!==null);
if(mode==='cancel'){await toggle(false);await toggle(true);}if(mode==='cancel-button'){const cancel=p.getByRole('button',{name:'Cancel preparation',exact:true});await cancel.waitFor();if(await cancel.count()!==1)throw Error('Expected one actual Cancel control');if(await cancel.locator('svg.lucide-x').count()!==1)throw Error('Cancel icon/action mismatch');await cancel.click();}phase='ready';const completion={operationId:job,state:'ready',at:Date.now()};events.push({kind:'fixture-terminal',...completion});
if(mode==='manual')await p.getByText('Recording ready. Press Play to listen.',{exact:true}).waitFor({timeout:20000});await p.waitForTimeout(1700);const before=await snapshot();await p.waitForTimeout(700);const after=await snapshot(),observedAt=Date.now();if(after.some((a,i)=>!a.paused||a.time-(before[i]?.time||0)>0.1))throw Error('Playback after actual terminal completion');;
if(mode==='manual'){await p.getByRole('button',{name:/^Play$/}).click();const measured=await observeNativeProgress({snapshot,range:result.activities[0].playbackRange,onSample:sample=>diagnostic.samples.push(sample)});const a=measured.before,b=measured.after;const pauses=await p.getByRole('button',{name:'Pause',exact:true}).count();if(pauses!==1)throw Error('Duplicate Pause');const active=b.findIndex(x=>!x.paused);if(active<0||b[active].time-a[active].time<0.25||b[active].time>result.activities[0].playbackRange.endSeconds)throw Error('Native clock failure');await p.getByRole('button',{name:'Pause',exact:true}).click();if((await snapshot()).some(x=>!x.paused))throw Error('Pause failed');receipt.claims.push({mode,loadedCommit,outcome:'passed',completion,observedAt,readySilence:{before,after},before:a,after:b,pauseCount:pauses,range:result.activities[0].playbackRange,activityId:'S01-U001'});}else receipt.claims.push({mode,loadedCommit,outcome:'passed',completion,observedAt,before,after,registryObserved:true,cancellationAction:mode==='cancel-button'?'Cancel button':'Automatic guide OFF then ON'});await p.screenshot({path:join(out,mode+'.png')});}catch(error){diagnostic.error=error.message;diagnostic.final=await snapshot().catch(()=>null);await p.screenshot({path:join(out,mode+'-failure.png')}).catch(()=>{});throw error;}finally{await context.close();}}
try{await run('cancel');await run('cancel-button');await run('manual');receipt.outcome='passed';}catch(error){receipt.outcome='failed';receipt.error=error.stack;process.exitCode=1;}finally{writeFileSync(join(out,'controlled-pending.json'),JSON.stringify(receipt,null,2));await browser.close();await new Promise(r=>server.close(r));await authority.dispose();}console.log(JSON.stringify({outcome:receipt.outcome,error:receipt.error,output:out}));
