import test from 'node:test';import assert from 'node:assert/strict';
import {fixture,worker,packId} from './helpers/offline-execution.js';
const save=(w,f)=>w.message({type:'DOWNLOAD_START',packId:f.record.packId,selection:'audio',revision:f.record.revision,mediaIdentity:f.record.execution.mediaIdentity,mediaAssetsSha256:f.record.execution.mediaAssetsSha256});
async function client(w){return(await w.stores.get('fia-v3-download-metadata@1').get('/client-c').clone().json());}
for(const offline of [false,true])test(`${offline?'offline':'online'} catalog read of another passage does not alter selected native-media custody`,async()=>{
 const a=fixture(),b=fixture('B','eng.MRK-1-21-28'),w=worker(a);assert.equal((await save(w,a)).ok,true);w.setFixture(b);assert.equal((await save(w,b)).ok,true);await w.message({type:'PACK_SELECT',packId,revision:a.record.revision});const before=await client(w);
 w.reply(`/v1/artifacts/${a.dependency.sha256}`,new Response(a.boundBytes));w.offline(offline);const record=await w.fetch(`/v1/packs/${b.record.packId}`);assert.equal(record.status,200);assert.deepEqual(await client(w),before,'read must not relabel old cache/manifest before explicit PACK_SELECT');
 assert.equal(await(await w.fetch('/audio.wav')).text(),a.files['/audio.wav']);
 assert.equal(await(await w.fetch(`/v1/artifacts/${b.record.revision}`)).text(),b.bytes,'pending record artifact remains readable before activation');
 assert.equal(await(await w.fetch(`/v1/artifacts/${a.dependency.sha256}`)).text(),a.boundBytes,'prior selected dependency still resolves during pending selection');
 await w.message({type:'PACK_SELECT',packId:b.record.packId,revision:b.record.revision});assert.equal(await(await w.fetch('/audio.wav')).text(),b.files['/audio.wav']);
});
for(const overlap of ['prior-activation','late-aborted-read','concurrent-reads'])test(`in-flight catalog artifact survives ${overlap}`,async()=>{
 const a=fixture(),b=fixture('B','eng.MRK-1-21-28'),c=fixture('C','eng.MRK-1-29-34'),w=worker(a);for(const f of [a,b,c]){w.setFixture(f);assert.equal((await save(w,f)).ok,true);}await w.message({type:'PACK_SELECT',packId:a.record.packId,revision:a.record.revision});const before=await client(w);
 w.offline(true);if(overlap==='concurrent-reads'){const responses=await Promise.all([w.fetch('/v1/packs/'+b.record.packId),w.fetch('/v1/packs/'+c.record.packId)]);for(const response of responses){assert.equal(response.status,200);await response.text();}}else{assert.equal((await w.fetch('/v1/packs/'+b.record.packId)).status,200);if(overlap==='prior-activation')await w.message({type:'PACK_SELECT',packId:a.record.packId,revision:a.record.revision});else assert.equal((await w.fetch('/v1/packs/'+c.record.packId)).status,200);}
 for(const f of [b,c].slice(0,overlap==='prior-activation'?1:2)){const response=await w.fetch('/v1/artifacts/'+f.record.revision);assert.equal(response.status,200);assert.equal(await response.text(),f.bytes);}assert.deepEqual(await client(w),before);assert.equal(await(await w.fetch('/audio.wav')).text(),a.files['/audio.wav']);
});
test('late response from an aborted catalog consumer cannot displace another in-flight read',async()=>{
 const a=fixture(),b=fixture('B','eng.MRK-1-21-28'),c=fixture('C','eng.MRK-1-29-34'),w=worker(a);for(const f of [a,b,c]){w.setFixture(f);assert.equal((await save(w,f)).ok,true);}await w.message({type:'PACK_SELECT',packId:a.record.packId,revision:a.record.revision});const before=await client(w);let finish,started;const begun=new Promise(r=>started=r);w.reply('/v1/packs/'+c.record.packId,()=>{started();return new Promise(r=>finish=r);});const controller=new AbortController(),late=w.fetch('/v1/packs/'+c.record.packId,'c',{signal:controller.signal});await begun;controller.abort();w.offline(true);assert.equal((await w.fetch('/v1/packs/'+b.record.packId)).status,200);finish(Response.json(c.record));await late;const response=await w.fetch('/v1/artifacts/'+b.record.revision);assert.equal(response.status,200);assert.equal(await response.text(),b.bytes);assert.deepEqual(await client(w),before);
});
test('remembered contexts grant no fallback for revoked or corrupted saved dependencies',async()=>{
 const a=fixture(),b=fixture('B','eng.MRK-1-21-28'),w=worker(a);for(const f of [a,b]){w.setFixture(f);assert.equal((await save(w,f)).ok,true);}await w.message({type:'PACK_SELECT',packId:a.record.packId,revision:a.record.revision});w.offline(true);await w.fetch('/v1/packs/'+b.record.packId);w.offline(false);w.reply('/v1/artifacts/'+b.record.revision,new Response('corrupt',{status:200}));assert.equal((await w.fetch('/v1/artifacts/'+b.record.revision)).status,409);w.offline(true);assert.equal((await w.fetch('/v1/artifacts/'+b.record.revision)).status,503);assert.equal(await(await w.fetch('/audio.wav')).text(),a.files['/audio.wav']);
});
