import {it,expect,vi,afterEach} from 'vitest';
import {render,fireEvent,cleanup} from '@testing-library/svelte';
import ZoomableVisual from '../src/components/ZoomableVisual.svelte';
import {swipeNavigation} from '../src/lib/swipe.js';
afterEach(cleanup);
const asset={title:'Map',src:'/map.png'};
function pointer(node,type,x,y,id=1){const e=new Event(type,{bubbles:true,cancelable:true});Object.assign(e,{clientX:x,clientY:y,pointerId:id,button:0});node.dispatchEvent(e);}
function touch(node,type,x,y,count=1){const e=new Event(type,{bubbles:true,cancelable:true});const p={clientX:x,clientY:y};Object.assign(e,{touches:type==='touchend'?[]:Array(count).fill(p),changedTouches:[p]});node.dispatchEvent(e);return e;}
it('inline pointer down does not open; completed tap opens once',async()=>{const open=vi.fn();const {container}=render(ZoomableVisual,{asset,onexpand:open});const node=container.querySelector('.visual-viewport');pointer(node,'pointerdown',200,200);expect(open).not.toHaveBeenCalled();pointer(node,'pointerup',200,200);await fireEvent.click(node);expect(open).toHaveBeenCalledTimes(1);});
it('drag, cancel and pinch do not turn into open clicks; a later tap still works',async()=>{for(const mode of ['drag','cancel','pinch']){const open=vi.fn();const {container,unmount}=render(ZoomableVisual,{asset,onexpand:open});const node=container.querySelector('.visual-viewport');pointer(node,'pointerdown',200,200);if(mode==='drag')pointer(node,'pointermove',100,200);if(mode==='pinch'){pointer(node,'pointerdown',220,200,2);pointer(node,'pointerup',220,200,2);}pointer(node,mode==='cancel'?'pointercancel':'pointerup',100,200);await fireEvent.click(node);expect(open).not.toHaveBeenCalled();pointer(node,'pointerdown',200,200);pointer(node,'pointerup',200,200);await fireEvent.click(node);expect(open).toHaveBeenCalledTimes(1);unmount();}});
it('resting visual swipe navigates once and suppresses only its compatibility click',async()=>{const open=vi.fn();const {container}=render(ZoomableVisual,{asset,onexpand:open});const node=container.querySelector('.visual-viewport');const navigate=vi.fn(),action=swipeNavigation(container,()=>({identity:'a',next:true,back:true,navigate}));touch(node,'touchstart',270,200);touch(node,'touchmove',120,200);expect(touch(node,'touchend',120,200).defaultPrevented).toBe(true);await fireEvent.click(node,{clientX:120,clientY:200,detail:1});expect(navigate).toHaveBeenCalledExactlyOnceWith('next');expect(open).not.toHaveBeenCalled();touch(node,'touchstart',200,200);touch(node,'touchend',200,200);await fireEvent.click(node,{clientX:200,clientY:200});expect(open).toHaveBeenCalledTimes(1);action.destroy();});
it('video controls and fullscreen viewer reject swipe; resting video permits it',()=>{const host=document.createElement('div'),video=document.createElement('video');host.append(video);document.body.append(host);const navigate=vi.fn(),action=swipeNavigation(host,()=>({identity:'a',next:true,navigate}));video.controls=true;touch(video,'touchstart',270,200);touch(video,'touchend',120,200);expect(navigate).not.toHaveBeenCalled();video.controls=false;touch(video,'touchstart',270,200);touch(video,'touchend',120,200);expect(navigate).toHaveBeenCalledTimes(1);host.className='visual-explorer fullscreen';touch(video,'touchstart',270,200);touch(video,'touchend',120,200);expect(navigate).toHaveBeenCalledTimes(1);action.destroy();host.remove();});

it('asset change cancels pending tap even when the same component returns to its former asset',async()=>{const open=vi.fn();const {container,rerender}=render(ZoomableVisual,{asset,onexpand:open});const node=container.querySelector('.visual-viewport');pointer(node,'pointerdown',200,200);await rerender({asset:{...asset,title:'Other'},onexpand:open});await rerender({asset,onexpand:open});pointer(node,'pointerup',200,200);await fireEvent.click(node);expect(open).not.toHaveBeenCalled();pointer(node,'pointerdown',200,200);pointer(node,'pointerup',200,200);await fireEvent.click(node);expect(open).toHaveBeenCalledTimes(1);});
it('swipe compatibility guard does not consume keyboard clicks or unrelated controls',async()=>{const host=document.createElement('div'),surface=document.createElement('div'),button=document.createElement('button');host.append(surface,button);document.body.append(host);const clicked=vi.fn();button.onclick=clicked;const action=swipeNavigation(host,()=>({identity:'a',next:true,navigate:()=>{}}));touch(surface,'touchstart',270,200);touch(surface,'touchend',120,200);await fireEvent.click(button,{clientX:120,clientY:200,detail:1});expect(clicked).toHaveBeenCalledTimes(1);touch(surface,'touchstart',270,200);touch(surface,'touchend',120,200);surface.onclick=clicked;await fireEvent.click(surface,{clientX:120,clientY:200,detail:0});expect(clicked).toHaveBeenCalledTimes(2);action.destroy();host.remove();});
