import test from 'node:test';import assert from 'node:assert/strict';import {preparedDownloadSizes} from '../src/lib/media-options.js';
const manifest={files:[{group:'audio',deliveryURL:'https://transcode.klappy.dev/audio/preset=voice,q=medium,f=opus/x'},{group:'image',deliveryURL:'https://transcode.klappy.dev/image/q=medium,f=webp/x'},{group:'video',deliveryURL:'https://transcode.klappy.dev/video/preset=fia,q=medium,f=mp4/x'}]};
test('prepared mixed bundle is custom, audio-only medium and video Large despite q=medium',()=>{const all=preparedDownloadSizes(manifest,'all');assert.equal(all.preset,'custom');assert.equal(all.groups.video.size,'large');assert.equal(preparedDownloadSizes(manifest,'audio').preset,'medium');assert.equal(preparedDownloadSizes(manifest,'core').groups.audio.included,false);});
test('unknown raw files and mixed variants cannot masquerade as a prepared preset',()=>{assert.equal(preparedDownloadSizes({files:[{group:'audio'}]},'audio').preset,'custom');assert.equal(preparedDownloadSizes({files:[...manifest.files,{group:'audio',deliveryURL:'https://transcode.klappy.dev/audio/q=low,f=opus/x'}]},'audio').groups.audio.size,null);});
test('legacy declared large is a prepared default, not evidence of phone912 rendition',()=>{
 const legacy={group:'video',deliveryURL:'https://transcode.klappy.dev/video/preset=fia,q=medium,f=mp4/https://source.test/720p.mp4',sha256:'a'.repeat(64),bytes:10,sourceSha256:'b'.repeat(64),sourceBytes:20};const f={...legacy,defaultSize:'large',variants:{large:legacy}};
 const group=preparedDownloadSizes({files:[f]},'all').groups.video;assert.equal(group.prepared,true);assert.equal(group.requestable,true);assert.deepEqual(group.available,[]);
 const actual={...legacy,deliveryURL:legacy.deliveryURL.replace('f=mp4/','f=mp4,size=xlarge/')};assert.deepEqual(preparedDownloadSizes({files:[{...actual,variants:{large:actual}}]},'all').groups.video.available,['large']);
});
