import test from 'node:test';import assert from 'node:assert/strict';import {fixture,worker,packId} from './helpers/offline-execution.js';
const save=(w,f)=>w.message({type:'DOWNLOAD_START',selection:'audio',revision:f.record.revision,mediaIdentity:f.record.execution.mediaIdentity,mediaAssetsSha256:f.record.execution.mediaAssetsSha256});
test('only explicit Save retains coherent record/main/all declared JSON; cold offline reads are historical and media bytes reuse existing pack cache',async()=>{const f=fixture(),w=worker(f);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,200);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);w.offline(false);assert.equal((await save(w,f)).ok,true);const saved=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(saved.active.files.every(file=>saved.active.manifest.files.some(d=>d.path===file.path)),true);assert.equal(saved.active.serverSnapshot.files.length,2);await w.message({type:'PACK_SELECT',revision:f.record.revision});const cold=worker(f,w.stores);cold.offline(true);const record=await cold.fetch(`/v1/packs/${packId}`);assert.equal(record.headers.get('X-FIA-Offline-Snapshot'),'historical-verified');assert.deepEqual(await record.json(),f.record);assert.equal(await(await cold.fetch(`/v1/artifacts/${f.record.revision}`)).text(),f.bytes);assert.equal(await(await cold.fetch(`/v1/artifacts/${f.dependency.sha256}`)).text(),f.boundBytes);assert.equal(await(await cold.fetch('/audio.wav')).text(),f.files['/audio.wav']);assert.equal((await cold.fetch(`/v1/packs/${packId}?revision=${'f'.repeat(64)}`)).status,503);});
test('observed invalid/revoked record or corrupted dependency permanently disables old snapshot fallback',async()=>{for(const target of ['record','dependency']){const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);await w.message({type:'PACK_SELECT',revision:f.record.revision});const path=target==='record'?`/v1/packs/${packId}`:`/v1/artifacts/${f.dependency.sha256}`;w.reply(path,target==='record'?Response.json({status:'unavailable',reason:'revoked'},{status:404}):Response.json({schema:'wrong'}));assert.equal((await w.fetch(path)).status,target==='record'?404:200,'the server answer passes through; the snapshot is still retired');w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);assert.equal((await w.fetch('/audio.wav')).status,409);const cold=worker(f,w.stores);cold.offline(true);assert.equal((await cold.fetch('/audio.wav')).status,409);}});
test('partial update and evicted dependency cannot mix snapshots or produce false saved status',async()=>{const old=fixture(),next=fixture('next'),w=worker(old);assert.equal((await save(w,old)).ok,true);w.setFixture(next);w.fail(`/v1/artifacts/${next.dependency.sha256}`);assert.equal((await save(w,next)).ok,false);w.offline(true);assert.deepEqual(await(await w.fetch(`/v1/packs/${packId}`)).json(),old.record);const status=await w.message({type:'DOWNLOAD_STATUS'});w.stores.get(status.active.cache).delete(`/v1/artifacts/${old.dependency.sha256}`);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,false);});
test('schema, identity and declared media mismatches refuse saving instead of aliasing base revision',async()=>{for(const mutate of [f=>f.record.execution.mediaIdentity.revision='f'.repeat(64),f=>f.record.execution.artifacts[0].mime='text/plain',f=>f.record.execution.mediaAssetsSha256='f'.repeat(64),f=>f.record.execution.schema='unknown']){const f=fixture();mutate(f);const w=worker(f);assert.equal((await save(w,f)).ok,false);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);}});
test('transient HTTP failure retains last saved snapshot; malformed 200 clears it',async()=>{const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);w.reply(`/v1/packs/${packId}`,new Response('unavailable',{status:503}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).headers.get('X-FIA-Offline-Snapshot'),'historical-verified');w.reply(`/v1/packs/${packId}`,Response.json({schema:'wrong'}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,200);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);});
test('media identity must be server authorized and offline reuse still binds exact saved projection',async()=>{const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);const data={type:'MEDIA_STATUS',revision:f.record.revision,mediaIdentity:f.record.execution.mediaIdentity,mediaAssetsSha256:f.record.execution.mediaAssetsSha256};assert.equal((await w.message(data)).ok,true);assert.equal((await w.message({...data,mediaIdentity:{packId,revision:'f'.repeat(64)}})).ok,false);w.offline(true);assert.equal((await w.message({type:'MEDIA_PLAY',revision:f.record.revision,mediaIdentity:{packId,revision:'f'.repeat(64)},mediaAssetsSha256:f.record.execution.mediaAssetsSha256,requestId:'one'})).ok,false);});

test('observed revocation during an in-flight explicit Save cannot reactivate a formerly verified snapshot',async()=>{const old=fixture(),next=fixture('new'),w=worker(old);assert.equal((await save(w,old)).ok,true);w.setFixture(next);w.reply('/audio.wav',async()=>{w.reply(`/v1/packs/${packId}`,Response.json({status:'unavailable',reason:'revoked'},{status:404}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,404);return new Response(next.files['/audio.wav']);});assert.equal((await save(w,next)).ok,false);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);});

test('a newer coherent Save cannot resurrect revoked old-client bytes; explicit selection activates only new generation',async()=>{const old=fixture(),next=fixture('new'),w=worker(old);assert.equal((await save(w,old)).ok,true);await w.message({type:'PACK_SELECT',revision:old.record.revision});w.reply(`/v1/packs/${packId}`,Response.json({status:'unavailable',reason:'revoked'},{status:404}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,404);w.setFixture(next);w.reply(`/v1/packs/${packId}`,Response.json(next.record));assert.equal((await save(w,next)).ok,true);w.offline(true);assert.equal((await w.fetch('/audio.wav')).status,409);await w.message({type:'PACK_SELECT',revision:next.record.revision});assert.equal(await(await w.fetch('/audio.wav')).text(),next.files['/audio.wav']);});
test('explicit verified same-generation Save repairs eligibility without relying on another generation',async()=>{const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);await w.message({type:'PACK_SELECT',revision:f.record.revision});w.reply(`/v1/packs/${packId}`,Response.json({status:'unavailable'},{status:404}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,404);w.reply(`/v1/packs/${packId}`,Response.json(f.record));assert.equal((await save(w,f)).ok,true);await w.message({type:'PACK_SELECT',revision:f.record.revision});w.offline(true);assert.equal(await(await w.fetch('/audio.wav')).text(),f.files['/audio.wav']);});

test('R1/A1: the page receives the server status, content type and JSON body of /v1 reads; no 409 text rewrite',async()=>{
 const f=fixture(),w=worker(f),artifact=`/v1/artifacts/${'a'.repeat(64)}`;
 const answers=[[`/v1/packs/${packId}`,404,{status:'unavailable',reason:'execution-job-policy'}],[`/v1/packs/${packId}`,400,{status:'refused',code:'invalid-request'}],[`/v1/packs/${packId}`,500,{status:'refused',code:'internal-error'}],[`/v1/packs/${packId}`,200,{schema:'wrong'}],[artifact,404,{status:'unavailable',reason:'not-found'}]];
 for(const [path,status,body] of answers){
  w.reply(path,Response.json(body,{status}));const seen=await w.fetch(path);
  assert.equal(seen.status,status,`${path} ${status}`);assert.match(seen.headers.get('Content-Type'),/^application\/json/);assert.deepEqual(await seen.json(),body);
 }
});
test('R1/A1: an unavailable or refused server answer still retires the saved snapshot; only a network failure may use it',async()=>{
 for(const [status,body] of [[404,{status:'unavailable',reason:'revoked'}],[400,{status:'refused',code:'invalid-request'}]]){
  const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);
  w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).headers.get('X-FIA-Offline-Snapshot'),'historical-verified');w.offline(false);
  w.reply(`/v1/packs/${packId}`,Response.json(body,{status}));const seen=await w.fetch(`/v1/packs/${packId}`);assert.equal(seen.status,status);assert.deepEqual(await seen.json(),body);
  w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);
 }
});
