import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {createHash,webcrypto} from 'node:crypto';
const bytes={'/index.html':'app','/audio.m4a':'recording','/video.mp4':'012345'};
const manifest=(revision='r1')=>({schema:1,packId:'fia-mark-authentic',revision,files:Object.entries(bytes).map(([path,body])=>({path,bytes:Buffer.byteLength(body),sha256:createHash('sha256').update(body).digest('hex'),group:path.endsWith('.m4a')?'audio':path.endsWith('.mp4')?'video':'core'}))});
function worker(){
 const handlers={},stores=new Map();let current=manifest(),calls=[],options=[],fail=null;
 const open=async name=>{if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return {match:async key=>store.get(String(key))?.clone(),put:async(key,value)=>store.set(String(key),value.clone()),delete:async key=>store.delete(key),addAll:async()=>{}};};
 const context={self:{location:{origin:'https://fia.test'},addEventListener:(name,fn)=>handlers[name]=fn,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{open,keys:async()=>[...stores.keys()],delete:async name=>stores.delete(name)},fetch:async (url,init)=>{calls.push(String(url));options.push(init);if(fail===url)throw new Error('Network interrupted');return url==='/offline-manifest.json'?Response.json(current):new Response(bytes[String(url)]||'live');},Response,Request,Headers,URL,Promise,console,crypto:webcrypto,AbortController,setTimeout,clearTimeout};
 vm.runInNewContext(readFileSync('public/sw.js','utf8').replace('__BUILD_ID__','test123'),context);
 return {stores,calls,options,manifest:value=>current=value,fail:value=>fail=value,async fetch(request){let promise;handlers.fetch({request,respondWith:p=>promise=p});return promise;},async message(data,onprogress,clientId){let task,result;handlers.message({data,source:clientId?{id:clientId}:null,ports:[{postMessage:r=>{if(r.progress)onprogress?.(r.progress);else result=r;}}],waitUntil:p=>task=p});await task;return result;}};
}
test('selected downloads verify hashes, report exact progress and do not fetch unselected video',async()=>{const w=worker();const progress=[];assert.equal((await w.message({type:'DOWNLOAD_START',selection:'audio'},p=>progress.push(p))).ok,true);assert.equal(w.calls.includes('/video.mp4'),false);assert.equal(progress.at(-1).received,12);const status=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(status.saved,true);assert.equal(status.active.selection,'audio');assert.equal(status.choices.find(c=>c.id==='all').bytes,18);});
test('offline video supports byte ranges and rejects invalid ranges',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'all'});let r=await w.fetch(new Request('https://fia.test/video.mp4',{headers:{Range:'bytes=2-4'}}));assert.equal(r.status,206);assert.equal(r.headers.get('Content-Range'),'bytes 2-4/6');assert.equal(await r.text(),'234');r=await w.fetch(new Request('https://fia.test/video.mp4',{headers:{Range:'bytes=9-'}}));assert.equal(r.status,416);r=await w.fetch(new Request('https://fia.test/video.mp4',{headers:{Range:'bytes=-2'}}));assert.equal(await r.text(),'45');});
test('interrupted download retains verified partial files and resumes without fetching them again',async()=>{const w=worker();w.fail('/audio.m4a');assert.equal((await w.message({type:'DOWNLOAD_START',selection:'all'})).ok,false);let status=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(status.saved,false);assert.equal(status.pending.received,3);w.fail(null);w.calls.length=0;assert.equal((await w.message({type:'DOWNLOAD_START',selection:'all'})).ok,true);assert.equal(w.calls.includes('/index.html'),false);assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,true);});
test('failed update preserves last good copy; successful retry atomically activates new revision',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'all'});w.manifest(manifest('r2'));w.fail('/video.mp4');assert.equal((await w.message({type:'DOWNLOAD_START',selection:'all'})).ok,false);let s=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(s.saved,true);assert.equal(s.active.revision,'r1');assert.equal(s.updateAvailable,true);w.fail(null);await w.message({type:'DOWNLOAD_START',selection:'all'});s=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(s.active.revision,'r2');assert.equal(s.pending,null);assert.equal(s.updateAvailable,false);});
test('hash mismatch cannot activate and eviction cannot be reported as saved',async()=>{const w=worker();const bad=manifest();bad.files[1].sha256='a'.repeat(64);w.manifest(bad);assert.equal((await w.message({type:'DOWNLOAD_START',selection:'all'})).ok,false);assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,false);w.manifest(manifest());await w.message({type:'DOWNLOAD_START',selection:'all'});const s=await w.message({type:'DOWNLOAD_STATUS'});w.stores.get(s.active.cache).delete('/audio.m4a');assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,false);});
test('remove clears active and interrupted files',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'core'});w.manifest(manifest('r2'));w.fail('/video.mp4');await w.message({type:'DOWNLOAD_START',selection:'all'});await w.message({type:'DOWNLOAD_REMOVE'});const s=await w.message({type:'DOWNLOAD_STATUS'});assert.equal(s.saved,false);assert.equal(s.pending,null);assert.equal([...w.stores.keys()].some(k=>k.startsWith('fia-v3-pack-')),false);});
test('eviction during an update cannot activate or discard the prior saved revision',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'all'});w.manifest(manifest('r2'));const result=await w.message({type:'DOWNLOAD_START',selection:'all'},p=>{if(p.count===2)w.stores.get('fia-v3-pack-r2-all').delete('/index.html');});assert.equal(result.ok,false);assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).active.revision,'r1');assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,true);});
test('navigation stays on the installed app instead of mixing network HTML with old media',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'all'});const response=await w.fetch({url:'https://fia.test/',method:'GET',mode:'navigate'});assert.equal(await response.text(),'app');assert.equal(w.calls.includes('https://fia.test/'),false);});

test('repeated saves do not move an unchanged open page to another content revision',async()=>{const w=worker();await w.message({type:'DOWNLOAD_START',selection:'all'});w.manifest(manifest('r2'));await w.message({type:'DOWNLOAD_START',selection:'all'},null,'page-a');w.manifest(manifest('r3'));await w.message({type:'DOWNLOAD_START',selection:'all'},null,'page-a');const pin=await w.stores.get('fia-v3-download-metadata@1').get('/client-page-a').clone().json();assert.equal(pin.revision,'r1');assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).active.revision,'r3');});

test('live version bypasses a historic installed cache and never falls back to it offline',async()=>{
 const w=worker();await w.message({type:'DOWNLOAD_START',selection:'core'});const status=await w.message({type:'DOWNLOAD_STATUS'});
 w.stores.get(status.active.cache).set('/version.json',new Response('stale-installed-version'));
 const request=new Request('https://fia.test/version.json');
 assert.equal(await(await w.fetch(request)).text(),'live');assert.equal(w.options.at(-1).cache,'no-store');
 w.fail(request);await assert.rejects(w.fetch(request),/Network interrupted/);
});
