import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';import {createHash,webcrypto} from 'node:crypto';
const digest=b=>createHash('sha256').update(b).digest('hex'),encode=v=>JSON.stringify(v),packId='eng.MRK-1-14-20',baseRevision='c'.repeat(64),sourceRevision='d'.repeat(40),origin='https://fia.test';
const canonical=v=>JSON.stringify(v===null||typeof v!=='object'?v:Array.isArray(v)?v.map(x=>JSON.parse(canonical(x))):Object.fromEntries(Object.keys(v).sort().map(k=>[k,JSON.parse(canonical(v[k]))])));
function fixture(suffix=''){
 const media='retained-byte-fixture'+suffix,assets={s:{id:'s',kind:'scripture',title:'Edition',text:'Source'}},bound={schema:'fia-bound-narration-audio@1',id:'bound'+suffix,delivery:{url:'/audio.wav',sha256:digest(media),bytes:Buffer.byteLength(media),mime:'audio/wav'},playbackRange:null},boundBytes=encode(bound),dependency={id:bound.id,sha256:digest(boundBytes),bytes:Buffer.byteLength(boundBytes),mime:'application/json'};
 const presentation={id:packId,assets,activities:[{id:'unit',sectionId:'S01',kind:'guide',completion:'confirm',execution:{narration:{action:'play-bound-audio',artifact:{id:bound.id,sha256:dependency.sha256}},focalAssetId:null,completion:{action:'manual-continue'}}}],sections:[{id:'S01',title:'One'}],listContracts:[],execution:{schema:'fia-executable-presentation@1',sourceRevision,decisionEvidenceSha256:'e'.repeat(64),recipeRevision:'fixture'}},bytes=encode(presentation),revision=digest(bytes),record={status:'ready',packId,revision,identity:{packId,language:'eng',title:'Fixture',defaultScriptureId:'s'},capabilities:{text:{available:true}},artifact:{sha256:revision,bytes:Buffer.byteLength(bytes),mime:'application/json'},execution:{schema:'fia-executable-catalog@1',baseRevision,sourceRevision,artifacts:[dependency],mediaIdentity:{packId,revision:baseRevision},mediaAssetsSha256:digest(canonical(assets)),provenance:{}}};
 const files={'/index.html':'saved shell','/audio.wav':media};const manifest={schema:1,packId,revision:'manifest'+suffix,presentationRevision:baseRevision,files:Object.entries(files).map(([path,body])=>({path,bytes:Buffer.byteLength(body),sha256:digest(body),group:path.endsWith('.wav')?'audio':'core'}))};return {record,manifest,bytes,boundBytes,dependency,files};
}
function worker(f=fixture(),stores=new Map()){
 const handlers={},replies=new Map(),calls=[];let offline=false,failedPath=null;
 const open=async name=>{if(!stores.has(name))stores.set(name,new Map());const store=stores.get(name);return {match:async key=>store.get(String(key))?.clone(),put:async(key,value)=>store.set(String(key),value.clone()),delete:async key=>store.delete(key),addAll:async()=>{}};};
 const fetcher=async(input)=>{const url=new URL(typeof input==='string'?input:input.url,origin);calls.push(url.pathname+url.search);if(offline||failedPath===url.pathname)throw new TypeError('offline');if(replies.has(url.pathname))return replies.get(url.pathname).clone();if(url.pathname===`/v1/packs/${packId}`)return Response.json(f.record);if(url.pathname===`/v1/artifacts/${f.record.revision}`)return new Response(f.bytes,{headers:{'Content-Type':'application/json'}});if(url.pathname===`/v1/artifacts/${f.dependency.sha256}`)return new Response(f.boundBytes,{headers:{'Content-Type':'application/json'}});if(url.pathname===`/offline/${packId}.json`)return Response.json(f.manifest);if(f.files[url.pathname])return new Response(f.files[url.pathname]);return new Response('missing',{status:404});};
 const context={self:{location:{origin},addEventListener:(n,fn)=>handlers[n]=fn,clients:{claim:async()=>{}},skipWaiting:async()=>{}},caches:{open,keys:async()=>[...stores.keys()],delete:async n=>stores.delete(n)},fetch:fetcher,Response,Request,Headers,URL,Promise,console,crypto:webcrypto,AbortController,TextEncoder,setTimeout,clearTimeout};
 vm.runInNewContext(readFileSync('src/lib/media-delivery.js','utf8').replace(/export (?=(?:async )?function)/g,'')+'\n'+readFileSync('src/lib/proxy-request.js','utf8').replace(/export (?=(?:async )?function)/g,'')+'\n'+readFileSync('public/sw.js','utf8').replace('__BUILD_ID__','test'),context);
 return {stores,calls,setFixture:x=>f=x,offline:v=>offline=v,fail:path=>failedPath=path,reply:(path,response)=>replies.set(path,response),async fetch(path,clientId='c'){let result;handlers.fetch({request:new Request(origin+path),clientId,respondWith:p=>result=p});return result;},async message(data){let task,result;handlers.message({data:{packId,...data},source:{id:'c'},ports:[{postMessage:r=>{if(!r.progress)result=r;}}],waitUntil:p=>task=p});await task;return result;}};
}
const save=(w,f)=>w.message({type:'DOWNLOAD_START',selection:'audio',revision:f.record.revision,mediaIdentity:f.record.execution.mediaIdentity,mediaAssetsSha256:f.record.execution.mediaAssetsSha256});
test('only explicit Save retains coherent record/main/all declared JSON; cold offline reads are historical and media bytes reuse existing pack cache',async()=>{const f=fixture(),w=worker(f);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,200);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);w.offline(false);assert.equal((await save(w,f)).ok,true);await w.message({type:'PACK_SELECT',revision:f.record.revision});const cold=worker(f,w.stores);cold.offline(true);const record=await cold.fetch(`/v1/packs/${packId}`);assert.equal(record.headers.get('X-FIA-Offline-Snapshot'),'historical-verified');assert.deepEqual(await record.json(),f.record);assert.equal(await(await cold.fetch(`/v1/artifacts/${f.record.revision}`)).text(),f.bytes);assert.equal(await(await cold.fetch(`/v1/artifacts/${f.dependency.sha256}`)).text(),f.boundBytes);assert.equal(await(await cold.fetch('/audio.wav')).text(),f.files['/audio.wav']);assert.equal((await cold.fetch(`/v1/packs/${packId}?revision=${'f'.repeat(64)}`)).status,503);});
test('observed invalid/revoked record or corrupted dependency permanently disables old snapshot fallback',async()=>{for(const target of ['record','dependency']){const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);await w.message({type:'PACK_SELECT',revision:f.record.revision});const path=target==='record'?`/v1/packs/${packId}`:`/v1/artifacts/${f.dependency.sha256}`;w.reply(path,target==='record'?Response.json({status:'unavailable',reason:'revoked'},{status:404}):Response.json({schema:'wrong'}));assert.equal((await w.fetch(path)).status,409);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);}});
test('partial update and evicted dependency cannot mix snapshots or produce false saved status',async()=>{const old=fixture(),next=fixture('next'),w=worker(old);assert.equal((await save(w,old)).ok,true);w.setFixture(next);w.fail(`/v1/artifacts/${next.dependency.sha256}`);assert.equal((await save(w,next)).ok,false);w.offline(true);assert.deepEqual(await(await w.fetch(`/v1/packs/${packId}`)).json(),old.record);const status=await w.message({type:'DOWNLOAD_STATUS'});w.stores.get(status.active.cache).delete(`/v1/artifacts/${old.dependency.sha256}`);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);assert.equal((await w.message({type:'DOWNLOAD_STATUS'})).saved,false);});
test('schema, identity and declared media mismatches refuse saving instead of aliasing base revision',async()=>{for(const mutate of [f=>f.record.execution.mediaIdentity.revision='f'.repeat(64),f=>f.record.execution.artifacts[0].mime='text/plain',f=>f.record.execution.mediaAssetsSha256='f'.repeat(64),f=>f.record.execution.schema='unknown']){const f=fixture();mutate(f);const w=worker(f);assert.equal((await save(w,f)).ok,false);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);}});
test('transient HTTP failure retains last saved snapshot; malformed 200 clears it',async()=>{const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);w.reply(`/v1/packs/${packId}`,new Response('unavailable',{status:503}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).headers.get('X-FIA-Offline-Snapshot'),'historical-verified');w.reply(`/v1/packs/${packId}`,Response.json({schema:'wrong'}));assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,409);w.offline(true);assert.equal((await w.fetch(`/v1/packs/${packId}`)).status,503);});
test('media identity must be server authorized and offline reuse still binds exact saved projection',async()=>{const f=fixture(),w=worker(f);assert.equal((await save(w,f)).ok,true);const data={type:'MEDIA_STATUS',revision:f.record.revision,mediaIdentity:f.record.execution.mediaIdentity,mediaAssetsSha256:f.record.execution.mediaAssetsSha256};assert.equal((await w.message(data)).ok,true);assert.equal((await w.message({...data,mediaIdentity:{packId,revision:'f'.repeat(64)}})).ok,false);w.offline(true);assert.equal((await w.message({type:'MEDIA_PLAY',revision:f.record.revision,mediaIdentity:{packId,revision:'f'.repeat(64)},mediaAssetsSha256:f.record.execution.mediaAssetsSha256,requestId:'one'})).ok,false);});
