import {test} from 'node:test';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
import {canonicalPreparationJSON,preparationHash,verifyPreparedRecording,createPreparationTransport} from '../src/lib/prepared-audio.js';
globalThis.crypto??=webcrypto;
const h='a'.repeat(64),identity={packId:'spa.LUK-1-80-2-7',presentationRevision:h,language:'spa',edition:'fia-guide',activityId:'S01-U001',sourceUnitId:'S01-U001',sourceTextSha256:'b'.repeat(64),quality:'medium'};
async function fixture(){const audio=new TextEncoder().encode('verified fixture audio');const result={schema:'fia-prepared-audio@1',packId:identity.packId,language:identity.language,edition:identity.edition,presentationRevision:h,sourceVersion:'publisher-v2',recipeRevision:'reviewed@1',configSha256:h,source:{url:'https://publisher.example/official.mp3',sha256:h,bytes:123,duration:60},delivery:{url:'https://transcode.klappy.dev/audio/fixture.opus',sha256:await preparationHash(audio),bytes:audio.length,duration:60.1,mime:'audio/ogg',quality:'medium'},provenance:'official-recording',evidence:{acceptanceSha256:h,recordingLedgerSha256:h,timingSha256:h},activities:[{activityId:identity.activityId,sourceUnitId:identity.sourceUnitId,sourceTextSha256:identity.sourceTextSha256,playbackRange:{startSeconds:4,endSeconds:9}}]};const value={schema:'fia-preparation-status@1',jobId:h,state:'ready',reason:null,sourceState:'verified',selection:{packId:identity.packId,presentationRevision:h,language:identity.language,edition:identity.edition,resource:'guide:S01',quality:'medium'},result,resultSha256:await preparationHash(canonicalPreparationJSON(result)),statusUrl:'/v1/preparations/'+h,reused:true};return {value,audio};}
const response=value=>new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}});
test('canonical result binds generic Luke Spanish cross-chapter activity without logical source',async()=>{const {value}=await fixture();const d=await verifyPreparedRecording(value,identity);assert.equal(d.identity.packId,identity.packId);assert.deepEqual(d.playbackRange,{startSeconds:4,endSeconds:9});assert.equal(d.logicalSource,undefined);});
test('identity quality provenance range and result-hash corruption are refused',async()=>{const {value}=await fixture();for(const change of [v=>v.selection.packId='eng.MRK-1-1-13',v=>v.result.presentationRevision='c'.repeat(64),v=>v.result.language='eng',v=>v.result.edition='other',v=>v.result.delivery.quality='small',v=>v.result.provenance='generated',v=>v.result.activities[0].activityId='S01-U002',v=>v.result.activities[0].sourceTextSha256=h,v=>v.result.activities[0].playbackRange.endSeconds=70,v=>v.result.activities[0].playbackRange.startSeconds=-1,v=>v.result.evidence.timingSha256=null,v=>v.result.delivery.url='https://other.example/file',v=>v.resultSha256=h,v=>v.sourceState='queued',v=>delete v.sourceState]){const copy=structuredClone(value);change(copy);await assert.rejects(verifyPreparedRecording(copy,identity));}});
test('no URL from rejected descriptor is fetched; same-origin transport rejects non-HTTPS app',async()=>{let called=false;const transport=createPreparationTransport({origin:()=> 'http://localhost:5183',fetch:async()=>{called=true;}});await assert.rejects(transport.request(identity,new AbortController().signal),/HTTPS/);assert.equal(called,false);});
test('warm ready revalidates status and actual bytes before returning range playback',async()=>{const {value,audio}=await fixture(),calls=[];const transport=createPreparationTransport({origin:()=> 'https://fiaguide.app',fetch:async(url,options)=>{calls.push([url,options]);return url.startsWith('/v1/')?response(value):new Response(audio,{headers:{'Content-Type':'audio/ogg'}});}});const ready=await transport.request(identity,new AbortController().signal);const descriptor=await transport.verify(ready,identity);const media=await transport.play(descriptor,new AbortController().signal);assert.deepEqual(media.bytes,audio);assert.deepEqual(media.playbackRange,{startSeconds:4,endSeconds:9});assert.equal(calls.length,3);assert.equal(calls[0][1].method,'POST');assert.deepEqual(JSON.parse(calls[0][1].body),identity);assert.equal(calls[1][0],'/v1/preparations/'+h);assert.equal(calls[2][1].credentials,'omit');});
test('wrong audio bytes and wrong job status refuse playback',async()=>{const {value}=await fixture();let phase='bytes';const t=createPreparationTransport({origin:()=> 'https://fiaguide.app',fetch:async url=>url.startsWith('/v1/')?response(phase==='job'?{...value,jobId:'b'.repeat(64)}:value):new Response('wrong',{headers:{'Content-Type':'audio/ogg'}})});const d=await verifyPreparedRecording(value,identity);await assert.rejects(t.play(d,new AbortController().signal));phase='job';await assert.rejects(t.play(d,new AbortController().signal));});
test('unsupported and blocked responses stay unavailable; oversized status refuses',async()=>{const {value}=await fixture();let mode=0;const t=createPreparationTransport({origin:()=> 'https://fiaguide.app',fetch:async()=>mode===0?new Response('',{status:422}):mode===1?response({...value,state:'blocked',reason:'review-required',result:null,resultSha256:null}):response({padding:'x'.repeat(262145)})});assert.equal((await t.request(identity)).status,'unavailable');mode=1;assert.equal((await t.request(identity)).status,'unavailable');mode=2;await assert.rejects(t.request(identity),/too large/);});
test('original quality uses exact same-origin source-hash relay and never substitutes medium',async()=>{
 const {value,audio}=await fixture();const original={...identity,quality:'original'};
 value.selection.quality='original';value.result.source={...value.result.source,sha256:await preparationHash(audio),bytes:audio.length};
 value.result.delivery={...value.result.source,url:`/v1/preparation-audio/${value.result.source.sha256}.mp3`,mime:'audio/mpeg',quality:'original'};
 value.resultSha256=await preparationHash(canonicalPreparationJSON(value.result));
 const d=await verifyPreparedRecording(value,original);assert.equal(d.delivery.sha256,d.source.sha256);
 for(const mutate of [v=>v.result.delivery.url='https://publisher.example/official.mp3',v=>v.result.delivery.url+='?q=x',v=>v.result.delivery.url='/v1/preparation-audio/../file.mp3',v=>v.result.delivery.sha256=h,v=>v.result.delivery.duration+=.01,v=>v.result.delivery.quality='medium']){const copy=structuredClone(value);mutate(copy);await assert.rejects(verifyPreparedRecording(copy,original));}
 const calls=[];const t=createPreparationTransport({origin:()=> 'https://fiaguide.app',fetch:async(url,options)=>{calls.push([url,options]);return url.startsWith('/v1/preparations/')?response(value):new Response(audio,{headers:{'Content-Type':'audio/mpeg'}});}});
 const played=await t.play(d,new AbortController().signal);assert.deepEqual(played.bytes,audio);assert.equal(calls[1][0],d.delivery.url);assert.equal(calls[1][1].credentials,'same-origin');
});
