import test from 'node:test';import assert from 'node:assert/strict';import {createHash,webcrypto} from 'node:crypto';import {createProxyRequest,fetchProxyRequest,matchesObservedProxy,observedProxyMatchesRequest} from '../src/lib/proxy-request.js';
if(!globalThis.crypto)globalThis.crypto=webcrypto;
const sha=b=>createHash('sha256').update(b).digest('hex');
const file={path:'/audio/a.mp3',group:'audio',deliveryURL:'https://transcode.klappy.dev/audio/preset=voice,q=medium,f=opus/https://source.test/a.mp3',sourceSha256:'a'.repeat(64),sourceBytes:123,mime:'audio/ogg',bytes:3,sha256:sha('abc')};
test('missing profile discovers without copying old hash or timing; exact profile can reuse expected identity',()=>{const small=createProxyRequest(file,'small');assert.equal(small.expected,null);assert.match(small.proxyUrl,/q=low/);assert.equal(small.timingStatus,'pending-qualification');assert.deepEqual(createProxyRequest(file,'medium').expected,{bytes:3,sha256:sha('abc')});});
test('maps video320/540/912 without equating historical Small480 or Large720',()=>{const v={...file,group:'video',path:'/v.mp4',mime:'video/mp4',deliveryURL:'https://transcode.klappy.dev/video/preset=fia,q=medium,f=mp4,size=small/https://source.test/v.mp4'};for(const [size,profile]of[['small','xsmall'],['medium','medium'],['large','xlarge']]){const r=createProxyRequest(v,size);assert.match(r.proxyUrl,new RegExp('size='+profile+'/'));assert.equal(r.expected,null);}});
test('image preserves existing format and closed quality profile',()=>{const r=createProxyRequest({...file,group:'image',mime:'image/webp',deliveryURL:'https://transcode.klappy.dev/image/q=medium,f=webp/https://source.test/a.jpg'},'large');assert.match(r.proxyUrl,/image\/q=high,f=webp/);});
test('rejects unbound source and unapproved URL/options',()=>{for(const f of [{...file,sourceSha256:null},{...file,deliveryURL:file.deliveryURL.replace('transcode.klappy.dev','evil.test')},{...file,deliveryURL:file.deliveryURL.replace('q=medium','q=medium,w=5')}])assert.throws(()=>createProxyRequest(f,'small'));});
test('records actual new bytes, keeps timing pending and never copies range/alignment',async()=>{const r=await fetchProxyRequest(createProxyRequest({...file,playbackRange:{startSeconds:1,endSeconds:2}},'small'),{fetchImpl:async()=>new Response('xyz',{headers:{'Content-Type':'audio/ogg'}})});assert.equal(r.receipt.output.sha256,sha('xyz'));assert.equal(r.receipt.output.bytes,3);assert.equal(r.receipt.timingStatus,'pending-qualification');assert.equal(r.receipt.playbackRange,undefined);assert.equal(r.receipt.matchedDeclaredOutput,false);});
test('rejects status MIME oversized truncated or changed known output',async()=>{for(const response of [new Response('abc',{status:502}),new Response('abc',{headers:{'Content-Type':'text/html'}}),new Response('abcd',{headers:{'Content-Type':'audio/ogg'}}),new Response('abc',{headers:{'Content-Type':'audio/ogg','Content-Length':'4'}}),new Response('bad',{headers:{'Content-Type':'audio/ogg'}})])await assert.rejects(fetchProxyRequest(createProxyRequest(file,'medium'),{maxBytes:3,fetchImpl:async()=>response}));});
test('deadline bounds stalled body and cancels reader',async()=>{let canceled=false;await assert.rejects(fetchProxyRequest(createProxyRequest(file,'small'),{timeoutMs:10,fetchImpl:async()=>new Response(new ReadableStream({cancel(){canceled=true;}}),{headers:{'Content-Type':'audio/ogg'}})}),/timed out/);assert.equal(canceled,true);});
test('caller abort stops stalled fetch without retry',async()=>{const c=new AbortController();let calls=0;const p=fetchProxyRequest(createProxyRequest(file,'small'),{signal:c.signal,fetchImpl:()=>{calls++;return new Promise(()=>{});}});setTimeout(()=>c.abort(Error('user stop')),5);await assert.rejects(p,/user stop/);assert.equal(calls,1);});

test('observed local receipt cannot bypass current ranged or aligned recording policy',async()=>{
 const request=createProxyRequest(file,'small'),result=await fetchProxyRequest(request,{fetchImpl:async()=>new Response('xyz',{headers:{'Content-Type':'audio/ogg'}})}),saved={...file,selectedSize:'small',deliveryURL:request.proxyUrl,sha256:result.receipt.output.sha256,bytes:3,proxyReceipt:result.receipt,timing:{status:'not-applicable'}};
 assert.equal(observedProxyMatchesRequest(request,saved),true);assert.equal(matchesObservedProxy({...file,playbackRange:{startSeconds:1,endSeconds:2}},saved),false);assert.equal(matchesObservedProxy({...file,timing:{mapping:{scale:1,offsetSeconds:0}}},saved),false);assert.equal(matchesObservedProxy(file,{...saved,timing:{mapping:{scale:1,offsetSeconds:9}}}),false);assert.equal(observedProxyMatchesRequest(request,{...saved,proxyReceipt:{...result.receipt,profile:'high'}}),false);
});
