import test from 'node:test';import assert from 'node:assert/strict';import{readFile}from'node:fs/promises';import{webcrypto}from'node:crypto';
import{createPreparationTransport,preparationHash,canonicalPreparationJSON as canonical}from'../src/lib/prepared-audio.js';
import{qualifyUnitDerivative,P3_UNIT_QUALIFICATION_SHA256}from'../../../server/fia/preparation/unit-derivative-qualification.mjs';
globalThis.crypto??=webcrypto;const h='a'.repeat(64),j='b'.repeat(64);const json=v=>new Response(JSON.stringify(v),{headers:{'content-type':'application/json'}});
async function fixture(){const bytes=new Uint8Array(await readFile(new URL('../../../server/fia/preparation/fixtures/p3-unit-derivative-qualification.json',import.meta.url))),bundle=JSON.parse(new TextDecoder().decode(bytes)),unit=JSON.parse(bundle.manifestText).units.find(x=>x.sourceUnitId==='S01-U006'),consumer={...bundle.consumerScope,sourceUnitId:unit.sourceUnitId,sourceTextSha256:unit.provenance.sourceTextSha256};const r=await qualifyUnitDerivative({qualificationBytes:bytes,qualificationSha256:P3_UNIT_QUALIFICATION_SHA256,consumer,candidate:{state:'candidate',qualifiedForPlayback:false,acceptedPlaybackRanges:[],wav:{sha256:unit.deliverySha256,reference:'retained/'+unit.deliverySha256},provenance:unit.provenance,preparation:{identity:{canonicalSha256:unit.provenance.canonicalSha256,sourceUnitId:consumer.sourceUnitId,sourceTextSha256:consumer.sourceTextSha256}},projection:[{sourceUnitId:consumer.sourceUnitId,sourceTextSha256:consumer.sourceTextSha256,status:'exact-unique',qualifiedForPlayback:false,candidate:{sha256:unit.deliverySha256,reference:'retained/'+unit.deliverySha256}}]}});
 // Synthetic media for transport verification only; the qualification module has separate real-byte tests.
 const audio=new Uint8Array([1,2,3,4]);r.delivery.sha256=await preparationHash(audio);r.delivery.bytes=audio.length;r.bridge.deliverySha256=r.delivery.sha256;r.bridgeSha256=await preparationHash(canonical(r.bridge));r.delivery.url=`/v1/guide-unit-preparations/${h}/${j}/audio/${r.qualificationSha256}.wav`;
 const value={schema:'fia-guide-unit-preparation-status@1',jobId:j,sourceJobId:h,consumer,state:'ready',reason:null,statusUrl:`/v1/guide-unit-preparations/${h}/${j}`,candidateProjection:null,result:r,resultSha256:await preparationHash(canonical(r)),acceptedPlaybackRanges:[]};return{value,audio,identity:{...consumer,activityId:consumer.sourceUnitId,quality:'original'}};}
test('legacy unavailable falls back exact consumer, reobserves and verifies whole-file bytes',async()=>{const{value,audio,identity}=await fixture(),calls=[];const t=createPreparationTransport({origin:()=> 'https://example.test',browserProfile:()=>value.result.browserProfile,fetch:async(path,options)=>{calls.push([path,options]);return path==='/v1/preparations'?new Response(null,{status:404}):path.endsWith('.wav')?new Response(audio,{headers:{'content-type':'audio/wav'}}):json(value);}});const r=await t.request(identity),d=await t.verify(r,identity),played=await t.play(d);assert.deepEqual(played,{bytes:audio,mime:'audio/wav',playback:'whole-file-native-ended'});assert.deepEqual(JSON.parse(calls[1][1].body),value.consumer);assert.equal(calls.length,4);assert.equal(calls[2][0],value.statusUrl);assert.equal(calls[3][1].credentials,'same-origin');});
test('profile, consumer, controller, range, rate and hash changes cannot become qualified',async()=>{for(const mutate of [v=>v.result.browserProfile.platform='other',v=>v.result.consumer.sourceUnitId='S01-U001',v=>v.result.controllerSha256=h,v=>v.result.delivery.playbackRange={startSeconds:0,endSeconds:1},v=>v.result.delivery.rate=1.5,v=>v.result.bridge.currentPins.sourceSha256=h]){const{value,identity}=await fixture(),profile=structuredClone(value.result.browserProfile);mutate(value);const t=createPreparationTransport({origin:()=> 'https://example.test',browserProfile:()=>profile,fetch:async path=>path==='/v1/preparations'?new Response(null,{status:422}):json(value)});await assert.rejects(t.verify(await t.request(identity),identity));}});
test('candidate remains unavailable and media corruption/revocation never plays',async()=>{const{value,identity}=await fixture();let mode='ready';const t=createPreparationTransport({origin:()=> 'https://example.test',browserProfile:()=>value.result.browserProfile,fetch:async path=>path==='/v1/preparations'?new Response(null,{status:404}):path.endsWith('.wav')?new Response('wrong',{headers:{'content-type':'audio/wav'}}):mode==='revoked'?new Response(null,{status:409}):json(mode==='candidate'?{...value,state:'candidate',result:null,resultSha256:null}:value)});const d=await t.verify(await t.request(identity),identity);await assert.rejects(t.play(d));mode='revoked';await assert.rejects(t.play(d));mode='candidate';assert.equal((await t.request(identity)).status,'unavailable');});
test('polling keeps the exact unit URL and a changed browser profile refuses warm playback before media GET',async()=>{const{value,identity}=await fixture();let queued=true,profile=structuredClone(value.result.browserProfile),mediaReads=0;const t=createPreparationTransport({origin:()=> 'https://example.test',browserProfile:()=>profile,fetch:async path=>{if(path==='/v1/preparations')return new Response(null,{status:404});if(path.endsWith('.wav')){mediaReads++;throw Error('unexpected media');}return json(queued?{...value,state:'queued',result:null,resultSha256:null}:value);}});const initial=await t.request(identity);assert.equal(initial.status,'preparing');queued=false;const ready=await t.status(initial.id,identity),d=await t.verify(ready,identity);profile.platform='other';await assert.rejects(t.play(d));assert.equal(mediaReads,0);});
