import {it,expect,beforeEach,afterEach,vi} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/svelte';
import {readFileSync} from 'node:fs';import {webcrypto,createHash} from 'node:crypto';
const audio=vi.hoisted(()=>({play:vi.fn(),pause:vi.fn(),resume:vi.fn(),stop:vi.fn(),active:false}));
vi.mock('../src/lib/audio.js',()=>({createAudioController:(state,end)=>{audio.state=state;audio.end=end;return audio;}}));
import App from '../src/App.svelte';import {libraryAdapter} from '../src/lib/library.js';
const registry=JSON.parse(readFileSync('public/content/registry.json','utf8')),descriptor=registry.packs.find(p=>p.id==='eng.MRK-1-14-20'),presentation=JSON.parse(readFileSync('public'+descriptor.presentation.url,'utf8'));
const hash=v=>createHash('sha256').update(JSON.stringify(v)).digest('hex'),assetId=descriptor.defaultScriptureId,asset=presentation.assets[assetId];
const file={path:`/audio/scripture/${descriptor.id}/${assetId}.opus`,group:'audio',mime:'audio/ogg',bytes:3,sourceBytes:99,sha256:'a'.repeat(64),sourceSha256:'b'.repeat(64),deliveryURL:'https://transcode.klappy.dev/audio/test-only',deliveryRevision:'9'.repeat(64),duration:321,playbackRange:{startSeconds:96.8,endSeconds:144.375},scriptureLedgerEntryId:'p2-test-only',scriptureAssetId:assetId,scripturePlaybackMode:'passage-only',scriptureHighlighting:'disabled',scriptureAlignment:null,scriptureLedgerSha256:'c'.repeat(64),scriptureRangeReviewSha256:'d'.repeat(64),scriptureSourceRangeReviewSha256:'e'.repeat(64),scriptureCanonicalTextSha256:hash({text:asset.text,verses:asset.verses}),scriptureSourceEvidenceSha256:hash(asset.sourceEvidence),timing:{status:'verified',sourceAudioSha256:'b'.repeat(64),deliveryAudioSha256:'a'.repeat(64),mappingEvidenceSha256:'f'.repeat(64),mapping:{scale:1,offsetSeconds:0}}};
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();audio.active=false;HTMLDialogElement.prototype.showModal=function(){this.open=true;};HTMLDialogElement.prototype.close=function(){this.open=false;};HTMLMediaElement.prototype.pause=vi.fn();Element.prototype.scrollTo=vi.fn();vi.stubGlobal('crypto',webcrypto);URL.createObjectURL=vi.fn(()=> 'blob:scripture-test');URL.revokeObjectURL=vi.fn();localStorage.setItem('fia-v3-selected-pack',descriptor.id);vi.spyOn(libraryAdapter,'select').mockResolvedValue({descriptor,presentation});vi.spyOn(libraryAdapter,'activate').mockResolvedValue({selected:true});vi.spyOn(libraryAdapter,'downloadStatus').mockResolvedValue({saved:false});vi.spyOn(libraryAdapter,'mediaStatus').mockResolvedValue({files:[file],savedFiles:[],deliveryRevision:file.deliveryRevision});vi.spyOn(libraryAdapter,'playMedia').mockResolvedValue({file,bytes:new Uint8Array(3),mime:file.mime,timing:file.timing,playbackRange:file.playbackRange,scriptureAlignment:null});});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();localStorage.clear();});
// R5 checks before acting; R6 makes the admitted S01-U002 a Play screen, so Next (not Continue) moves past it.
async function scripture(){render(App);await waitFor(()=>expect(screen.getByRole('heading',{level:1}).textContent).toBe(presentation.activities[0].prompt));await waitFor(()=>expect(document.querySelector('.guide-primary').hasAttribute('aria-busy')).toBe(false));await fireEvent.click(screen.getByRole('button',{name:'More options'}));await fireEvent.click(screen.getByRole('button',{name:'Settings',exact:true}));await fireEvent.click(screen.getByRole('checkbox',{name:/Automatic Scripture reading/}));await fireEvent.click(screen.getByRole('button',{name:'Close',exact:true}));await fireEvent.click(screen.getByRole('button',{name:'Skip to next activity',exact:true}));await fireEvent.click(await screen.findByRole('button',{name:'Skip to next activity',exact:true}));}
for(const offline of [false,true])it(`test-only no-legacy passage binds ${offline?'saved':'online'} media and never highlights`,async()=>{expect(asset.descriptionAudio).toBeFalsy();if(offline){libraryAdapter.mediaStatus.mockResolvedValue({files:[],savedFiles:[],deliveryRevision:null});libraryAdapter.downloadStatus.mockResolvedValue({saved:true,active:{manifest:{presentationRevision:descriptor.revision,deliveryRevision:file.deliveryRevision,files:[file]},files:[file]}});}await scripture();await waitFor(()=>expect(screen.getByRole('button',{name:'Play',exact:true}).disabled).toBe(false));expect(audio.play).not.toHaveBeenCalled();await fireEvent.click(screen.getByRole('button',{name:'Play',exact:true}));await waitFor(()=>expect(audio.play).toHaveBeenCalledWith(expect.any(String),offline?file.path:'blob:scripture-test',1,file.playbackRange));audio.state({src:offline?file.path:'blob:scripture-test',elapsed:110,duration:321,playing:true,progressElapsed:13.2,progressDuration:47.575});expect(document.querySelectorAll('[data-align-word]').length).toBe(0);expect(document.querySelectorAll('.reading-verses [aria-current=true]').length).toBe(0);});
it('changed canonical binding does not offer passage playback',async()=>{libraryAdapter.mediaStatus.mockResolvedValue({files:[{...file,scriptureCanonicalTextSha256:'0'.repeat(64)}],deliveryRevision:file.deliveryRevision});await scripture();await new Promise(r=>setTimeout(r,20));expect(screen.queryByRole('button',{name:'Play',exact:true})).toBeNull();expect(screen.getByRole('button',{name:'Skip to next activity'}).disabled).toBe(false);expect(audio.play).not.toHaveBeenCalled();});
it('changed returned range is refused before native ownership',async()=>{libraryAdapter.playMedia.mockResolvedValue({file,bytes:new Uint8Array(3),mime:file.mime,timing:file.timing,scriptureAlignment:null,playbackRange:{startSeconds:0,endSeconds:1}});await scripture();await waitFor(()=>expect(screen.getByRole('button',{name:'Play',exact:true}).disabled).toBe(false));await fireEvent.click(screen.getByRole('button',{name:'Play',exact:true}));await waitFor(()=>expect(screen.getByText('Scripture playback binding changed.')).toBeTruthy());expect(audio.play).not.toHaveBeenCalled();});
it('accepts the verified selected saved variant rather than an unselected default',async()=>{const selected={...file,sha256:'8'.repeat(64),playbackRange:{startSeconds:97,endSeconds:144},timing:{...file.timing,deliveryAudioSha256:'8'.repeat(64)}};libraryAdapter.mediaStatus.mockResolvedValue({files:[file],savedFiles:[selected],deliveryRevision:file.deliveryRevision});libraryAdapter.playMedia.mockResolvedValue({file:selected,bytes:new Uint8Array(3),mime:selected.mime,timing:selected.timing,playbackRange:selected.playbackRange,scriptureAlignment:null});await scripture();await waitFor(()=>expect(screen.getByRole('button',{name:'Play',exact:true}).disabled).toBe(false));await fireEvent.click(screen.getByRole('button',{name:'Play',exact:true}));await waitFor(()=>expect(audio.play).toHaveBeenCalledWith(expect.any(String),'blob:scripture-test',1,selected.playbackRange));});
it('navigation cancels pending passage bytes and never transfers late audio ownership',async()=>{let resolve;libraryAdapter.playMedia.mockReturnValue(new Promise(r=>resolve=r));await scripture();await waitFor(()=>expect(screen.getByRole('button',{name:'Play',exact:true}).disabled).toBe(false));await fireEvent.click(screen.getByRole('button',{name:'Play',exact:true}));await waitFor(()=>expect(libraryAdapter.playMedia).toHaveBeenCalledTimes(1));const signal=libraryAdapter.playMedia.mock.calls[0][3];await fireEvent.click(screen.getByRole('button',{name:'Previous activity',exact:true}));expect(signal.aborted).toBe(true);resolve({file,bytes:new Uint8Array(3),mime:file.mime,timing:file.timing,playbackRange:file.playbackRange,scriptureAlignment:null});await new Promise(r=>setTimeout(r,20));expect(audio.play).not.toHaveBeenCalled();});
