import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createVideoPresentation} from '../src/lib/video-presentation.js';
function setup(){const document=new EventTarget();document.fullscreenElement=null;const node=new EventTarget();Object.assign(node,{ownerDocument:document,currentTime:17,paused:false,pause(){this.paused=true;},webkitDisplayingFullscreen:false,webkitPresentationMode:'inline'});let exits=0,quiet=0;const notices=[],timers=new Map();node.webkitSetPresentationMode=()=>{exits++;};const owner=createVideoPresentation({quiesce:()=>quiet++,notice:t=>notices.push(t),setTimer:fn=>{const id=Symbol();timers.set(id,fn);return id;},clearTimer:id=>timers.delete(id)});const clean=owner.register(node,'pack:revision:activity:video');const enter=()=>{node.webkitDisplayingFullscreen=true;node.webkitPresentationMode='fullscreen';node.dispatchEvent(new Event('webkitbeginfullscreen'));};const exit=()=>{node.webkitDisplayingFullscreen=false;node.webkitPresentationMode='inline';node.dispatchEvent(new Event('webkitendfullscreen'));};return {owner,node,document,clean,enter,exit,notices,timers,get exits(){return exits;},get quiet(){return quiet;}};}
test('native owner remains until real exit acknowledgement; latest pending intent commits once',()=>{const x=setup();x.enter();let a=0,b=0;assert.equal(x.owner.defer(()=>a++),true);assert.equal(x.owner.node,x.node);assert.equal(x.node.paused,true);assert.equal(x.node.currentTime,17);x.owner.defer(()=>b++);assert.equal(x.exits,1);x.node.dispatchEvent(new Event('ended'));x.node.dispatchEvent(new Event('pause'));assert.equal(a+b,0);x.node.dispatchEvent(new Event('webkitendfullscreen'));assert.equal(b,0);x.exit();x.exit();assert.equal(a,0);assert.equal(b,1);assert.equal(x.owner.pending,false);});
test('watchdog is truthful, does not detach or commit; explicit retry requests exit',()=>{const x=setup();x.enter();let moved=0;x.owner.defer(()=>moved++);for(const fn of x.timers.values())fn();assert.equal(moved,0);assert.equal(x.owner.node,x.node);assert.match(x.notices[0],/still pending/);x.owner.defer(()=>moved++,{retry:true});assert.equal(x.exits,2);x.exit();assert.equal(moved,1);});
test('inline and unsupported APIs do not block ordinary transitions; native unknown APIs retain owner',()=>{const x=setup();delete x.node.webkitSetPresentationMode;delete x.node.webkitPresentationMode;delete x.node.webkitDisplayingFullscreen;assert.equal(x.owner.defer(()=>assert.fail()),false);x.node.dispatchEvent(new Event('webkitbeginfullscreen'));assert.equal(x.owner.defer(()=>{}),true);assert.match(x.notices[0],/Done control/);x.node.dispatchEvent(new Event('webkitendfullscreen'));assert.equal(x.owner.pending,false);});
test('old events and rejected exit promises cannot modify a successor owner',async()=>{const x=setup();let reject; x.node.webkitSetPresentationMode=()=>new Promise((_,r)=>reject=r);x.enter();let moved=0;x.owner.defer(()=>moved++);const next=new EventTarget();Object.assign(next,{ownerDocument:x.document,pause(){},currentTime:9});x.owner.register(next,'next');x.exit();reject(Error('late'));await Promise.resolve();await Promise.resolve();assert.equal(moved,0);assert.equal(x.owner.node,next);assert.deepEqual(x.notices,[]);x.clean();assert.equal(x.owner.node,next);});
test('standard fullscreen releases only its owner; disposal cancels pending intent',()=>{const x=setup();x.document.fullscreenElement=x.node;let standardExits=0;x.document.exitFullscreen=()=>standardExits++;x.document.dispatchEvent(new Event('fullscreenchange'));let moved=0;x.owner.defer(()=>moved++);assert.equal(standardExits,1);assert.equal(x.exits,0);x.document.fullscreenElement=null;x.document.dispatchEvent(new Event('fullscreenchange'));assert.equal(moved,1);x.enter();x.owner.defer(()=>moved++);x.owner.dispose();x.exit();assert.equal(moved,1);assert.equal(x.owner.node,null);assert.equal(x.timers.size,0);});
test('spontaneous native exit preserves time and does not invent a transition or playback',()=>{const x=setup();x.enter();x.exit();assert.equal(x.owner.node,x.node);assert.equal(x.node.currentTime,17);assert.equal(x.node.paused,true);assert.equal(x.quiet,1);assert.equal(x.exits,0);});

test('deferred transition failures report only for the same owner and latest intent',async()=>{
 const x=setup();x.enter();x.owner.defer(async()=>{throw Error('Load failed');});x.exit();await Promise.resolve();await Promise.resolve();assert.deepEqual(x.notices,['Load failed']);
 let reject;x.enter();x.owner.defer(()=>new Promise((_,r)=>reject=r));x.exit();x.enter();x.owner.defer(()=>{});reject(Error('obsolete intent'));await Promise.resolve();await Promise.resolve();assert.deepEqual(x.notices,['Load failed']);
 x.exit();x.enter();x.owner.defer(()=>new Promise((_,r)=>reject=r));x.exit();x.owner.dispose();reject(Error('obsolete owner'));await Promise.resolve();await Promise.resolve();assert.deepEqual(x.notices,['Load failed']);
});
