import test from 'node:test';import assert from 'node:assert/strict';
import {sha256,canonicalJSONString} from '../../server/fia/preparation/contract.mjs';
import {createAlignmentAdapter,tokens} from '../../server/fia/preparation/executor/alignment.mjs';
import {LOCAL_RECOGNITION_CONFIG,localRecognitionConfigSha256} from '../../server/fia/preparation/executor/recognition-identity.mjs';
import {createAcceptanceAdapter} from '../../server/fia/preparation/executor/acceptance.mjs';
async function fixture(texts=['Listen now','Discuss together'],spoken=['Listen','now','Discuss','together']){
 const data=new Map(),storeArtifact=async bytes=>{const digest=await sha256(bytes);data.set(digest,bytes.slice());return {sha256:digest,reference:digest};},resolveArtifact=async artifact=>data.get(artifact.reference)?.slice(),input={packId:'eng.MRK-fixture',book:'MRK',language:'eng',edition:'fixture',passage:'1:21-28',resource:'S01',policyRevision:'fixture@1',scriptSha256:'a'.repeat(64)},sourceSha256='b'.repeat(64);
 const units=await Promise.all(texts.map(async(text,i)=>({activityId:`a${i}`,sourceUnitId:`u${i}`,sourceTextSha256:await sha256(text),text})));
 const raw={schema:'fia-local-raw-recognition@1',status:'candidate',source:{sha256:sourceSha256},durationSeconds:100,segments:[{words:spoken.map((word,i)=>({word,start:i,end:i+.8}))}]};
 const runtime={python:'fixture',av:'fixture',ctranslate2:'fixture','faster-whisper':'fixture',numpy:'fixture'},files={'model.bin':{sha256:'c'.repeat(64),bytes:10}},manifest=await sha256(canonicalJSONString(files));
 Object.assign(raw,{runtime,scriptSha256:'d'.repeat(64),model:{id:'tiny.en',manifestSha256:manifest,files,device:'cpu',computeType:'int8',cpuThreads:4},recognitionConfig:{...LOCAL_RECOGNITION_CONFIG,language:'en'}});input.modelRecipe={modelId:'tiny.en',modelRevision:manifest,configSha256:await localRecognitionConfigSha256(raw.scriptSha256,runtime)};
 const transcribe=await storeArtifact(new TextEncoder().encode(canonicalJSONString(raw))),context={input,nodeOutputs:{acquire:{sha256:sourceSha256,reference:sourceSha256},transcribe}},options={resolveArtifact,storeArtifact,resolveUnits:async()=>({scriptSha256:input.scriptSha256,units})};
 return {data,raw,units,context,options,async updateRaw(){context.nodeOutputs.transcribe=await storeArtifact(new TextEncoder().encode(canonicalJSONString(raw)));},async read(artifact){return JSON.parse(new TextDecoder().decode(await resolveArtifact(artifact)));}};
}
test('exact ordered matches retain real ASR spans but acceptance remains review-required',async()=>{const f=await fixture(),aligned=await createAlignmentAdapter(f.options).run(f.context),report=await f.read(aligned);assert(report.mappings.every(m=>m.status==='exact-candidate'));assert.deepEqual(report.mappings[0].candidateRange,{startSeconds:0,endSeconds:1.8,clockDomain:'decoded-source-samples-asr-estimate'});assert.deepEqual(report.acceptedPlaybackRanges,[]);const accepted=await createAcceptanceAdapter(f.options).run({...f.context,nodeOutputs:{...f.context.nodeOutputs,align:aligned}}),decision=await f.read(accepted);assert.equal(decision.status,'review-required');assert.equal(decision.alignmentSha256,aligned.sha256);assert(decision.reasons.includes('browser-clock-evidence-missing'));});
test('normalization is explicit and does not expand numbers or fuzzy spelling',()=>{assert.deepEqual(tokens('ＬＩＳＴＥＮ John’s 1:21–28'),['listen',"john's",'1','21','28']);assert.notDeepEqual(tokens('one'),tokens('1'));});
test('drift missing words repeated phrases and out of order never fabricate ranges',async()=>{for(const [texts,spoken,status] of [[['Listen now'],['Listen','later'],'unmatched'],[['listen'],['listen','listen'],'ambiguous-repeated-phrase'],[['later','first'],['first','later'],'out-of-order']]){const f=await fixture(texts,spoken),report=await f.read(await createAlignmentAdapter(f.options).run(f.context)),row=report.mappings.at(-1);assert.equal(row.status,status);assert.equal(row.candidateRange,undefined);}});
test('source script text and raw byte mismatches refuse alignment',async()=>{for(const mutate of [f=>f.context.nodeOutputs.acquire.sha256='c'.repeat(64),f=>f.units[0].text+=' changed',f=>f.data.set(f.context.nodeOutputs.transcribe.reference,new TextEncoder().encode('{}'))]){const f=await fixture();mutate(f);await assert.rejects(createAlignmentAdapter(f.options).run(f.context));}});
test('invalid word clock and bounded input refuse rather than invent timing',async()=>{for(const change of [r=>r.segments[0].words[0].start=-1,r=>r.segments[0].words[0].end=101,r=>r.segments[0].words[2].start=.2,r=>r.segments[0].words=Array.from({length:10001},()=>({word:'a',start:0,end:1}))]){const f=await fixture();change(f.raw);await f.updateRaw();await assert.rejects(createAlignmentAdapter(f.options).run(f.context));}});
test('zero duration estimate stays candidate and extra speech forces review reason',async()=>{const f=await fixture(['Listen'],['extra','Listen']);f.raw.segments[0].words[1].end=1;await f.updateRaw();const align=await createAlignmentAdapter(f.options).run(f.context),report=await f.read(align);assert.equal(report.mappings[0].status,'zero-duration-candidate');const decision=await f.read(await createAcceptanceAdapter(f.options).run({...f.context,nodeOutputs:{...f.context.nodeOutputs,align}}));assert(decision.reasons.includes('unassigned-recognized-speech'));assert(decision.reasons.includes('unresolved-unit-correspondence'));});
test('acceptance cannot consume another consumer alignment or substituted store digest',async()=>{const f=await fixture(),align=await createAlignmentAdapter(f.options).run(f.context);await assert.rejects(createAcceptanceAdapter(f.options).run({input:{...f.context.input,passage:'other'},nodeOutputs:{...f.context.nodeOutputs,align}}));await assert.rejects(createAlignmentAdapter({...f.options,storeArtifact:async()=>({sha256:'d'.repeat(64),reference:'wrong'})}).run(f.context),/store-mismatch/);});

test('hash-valid same-source recognition from another model runtime language or settings refuses',async()=>{
 for(const change of [r=>r.model.id='other-model',r=>r.model.manifestSha256='e'.repeat(64),r=>r.model.files['model.bin'].bytes++,r=>r.runtime.numpy='changed',r=>r.runtime.extra='unexpected',r=>r.recognitionConfig.language='es',r=>r.recognitionConfig.beam_size=1,r=>r.recognitionConfig.initial_prompt='forced text',r=>r.model.cpuThreads=8,r=>r.scriptSha256='e'.repeat(64)]){const f=await fixture();change(f.raw);await f.updateRaw();await assert.rejects(createAlignmentAdapter(f.options).run(f.context),/recognition/);}
});
