import test from 'node:test';
import assert from 'node:assert/strict';
import {createPipeline} from '../../server/fia/preparation/executor/pipeline.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
const input={packId:'fixture',book:'MRK',language:'eng',edition:'fia-guide',passage:'fixture',resource:'S01',scriptSha256:'a'.repeat(64),source:{publisherId:'publisher',resourceId:'fixture',version:'1'},modelRecipe:{modelId:'fixture',modelRevision:'1',configSha256:'b'.repeat(64)},policyRevision:'fixture@1'};
async function fixture(change=x=>x){const map=new Map(),bytes=new TextEncoder().encode('discovery'),sha=await sha256(bytes),source={sha256:'c'.repeat(64),reference:`originals/sha256/${'c'.repeat(64)}.mp3`};let sourceCalls=0,byteSourceCalls=0;const options={storage:{transaction:fn=>fn({get:async k=>map.get(k),put:async(k,v)=>map.set(k,structuredClone(v))})},policyId:'stream-fixture@1',adapters:{discover:{paid:false,run:async()=>({sha256:sha,reference:'discovery'})},acquire:{paid:false,run:async()=>source}},verifyArtifact:async d=>{if(d.reference===source.reference){byteSourceCalls++;throw Error('must not materialize source');}return bytes;},verifySource:async(d,{node})=>{sourceCalls++;assert.equal(node,'acquire');return change({...d,bytes:12823388});}};return {options,counts:()=>({sourceCalls,byteSourceCalls})};}
test('typed acquire verified descriptor is replayed without whole-source byte callback',async()=>{const f=await fixture(),p=createPipeline(f.options);assert.equal((await p.run(input)).node,'transcribe');assert.equal((await createPipeline(f.options).run(input)).node,'transcribe');assert.deepEqual(f.counts(),{sourceCalls:2,byteSourceCalls:0});});
test('typed source verifier rejects forged or malformed receipt, with no fallback',async()=>{for(const change of [x=>({...x,sha256:'d'.repeat(64)}),x=>({...x,reference:'other'}),x=>({...x,bytes:NaN}),x=>({...x,bytes:16777217}),x=>({...x,extra:true}),x=>({sha256:x.sha256,reference:x.reference})]){const f=await fixture(change),r=await createPipeline(f.options).run(input);assert.equal(r.node,'acquire');assert.equal(r.state,'uncertain');assert.equal(f.counts().byteSourceCalls,0);}});
test('absent typed callback retains byte verification; typed callback cannot bypass JSON nodes',async()=>{const f=await fixture();delete f.options.verifySource;assert.equal((await createPipeline(f.options).run(input)).state,'uncertain');assert.equal(f.counts().byteSourceCalls,1);const g=await fixture();g.options.verifyArtifact=async()=>({sha256:'c'.repeat(64),reference:'fake',bytes:3});const r=await createPipeline(g.options).run(input);assert.equal(r.node,'discover');assert.equal(r.state,'uncertain');assert.equal(g.counts().sourceCalls,0);});
