import test from 'node:test';import assert from 'node:assert/strict';
import {createCoherentSnapshots,SNAPSHOT_EDGES} from '../../server/fia/preparation/executor/coherent-snapshot.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const encode=v=>new TextEncoder().encode(canonicalJSONString(v)),clone=x=>structuredClone(x);
function storage(){const values=new Map();let tail=Promise.resolve();return {values,get:async k=>clone(values.get(k)),put:async(k,v)=>values.set(k,clone(v)),transaction(fn){const p=tail.then(()=>fn(this));tail=p.catch(()=>{});return p;}};}
async function fixture(){const data=new Map(),store=storage();let builds=0,eligible=true,failure=null,gate=null,policyValue=true;const gets=[];
 async function put(bytes){const hash=await sha256(bytes);data.set(`snapshots/artifacts/${hash}.json`,bytes.slice());return {sha256:hash,bytes:bytes.length,reference:`snapshots/artifacts/${hash}.json`,parents:{}};}
 const roots={};for(const role of ['source','script','recognitionConfig','alignmentConfig','deliveryConfig','acceptancePolicy'])roots[role]=await put(encode({role,revision:1}));
 function ident(r=roots){return Object.fromEntries(Object.entries(r).map(([role,item])=>[role+'Sha256',item.sha256]));}
 const identity=ident(),policy={sha256:identity.acceptancePolicySha256,validateSnapshot:()=>policyValue};
 async function candidate(input){const artifacts={};for(const [role,parents] of Object.entries(SNAPSHOT_EDGES)){if(!parents.length){const rootSHA=input[role+'Sha256'],bytes=data.get(`snapshots/artifacts/${rootSHA}.json`);artifacts[role]={sha256:rootSHA,bytes:bytes.length,reference:`snapshots/artifacts/${rootSHA}.json`,parents:{}};continue;}const edge=Object.fromEntries(parents.map(p=>[p,artifacts[p].sha256]));const content=role==='acceptance'?{schema:'fia-snapshot-acceptance@1',status:'review-accepted',identity:input,parents:edge}:{schema:'fixture-node@1',role,parents:edge};artifacts[role]={...await put(encode(content)),parents:edge};}return {schema:'fia-coherent-snapshot@1',logicalId:'eng.MRK/example',identity:clone(input),artifacts};}
 const bucket={async get(key){gets.push(key);const bytes=data.get(key);return bytes?{size:bytes.length,body:new Blob([bytes]).stream()}:null;}};
 const builder={paid:false,async run({identity}){builds++;if(gate)await gate;if(failure==='throw')throw Error('publisher-offline');if(failure==='review')return {state:'blocked'};return candidate(identity);}};
 const options={storage:store,bucket,policy,builder,eligibility:()=>eligible};const coordinator=createCoherentSnapshots(options);
 async function obs(sequence=1,previous=null,input=identity){return {logicalId:'eng.MRK/example',sequence,expectedPreviousObservationSha256:previous,provenance:{checkId:'authorized-'+sequence,sourceVersionKind:'discovery-snapshot',sourceVersion:'presentation-v1',publisherVersion:null,observedAt:sequence},identity:clone(input)};}
 return {data,store,options,coordinator,identity,obs,put,candidate,builds:()=>builds,gets,fail:v=>failure=v,eligibility:v=>eligible=v,policyResult:v=>policyValue=v,gate:p=>gate=p};}
async function hash(v){return sha256(canonicalJSONString(v));}
test('same bytes and newer provenance reuse graph and refresh while preserving truthful snapshot version kind',async()=>{const f=await fixture(),one=await f.obs();const a=await f.coordinator.demand(one);assert.equal(a.state,'ready');const two=await f.obs(2,await hash(one));const b=await f.coordinator.demand(two);assert.equal(f.builds(),1);assert.equal(b.served.revision,a.served.revision);assert.equal(b.desired.observationSha256,await hash(two));assert.equal(b.desired.provenance.sourceVersionKind,'discovery-snapshot');assert.equal(b.desired.provenance.publisherVersion,null);await f.coordinator.read(one.logicalId);assert.equal(f.builds(),1);});
test('source, config and script changes change only actual downstream graph hashes',async()=>{for(const root of ['source','recognitionConfig','script','alignmentConfig','deliveryConfig']){const f=await fixture(),a=await f.candidate(f.identity),changed=await f.put(encode({role:root,revision:2})),next={...f.identity,[root+'Sha256']:changed.sha256},b=await f.candidate(next);const dirty=new Set([root]);for(const [role,parents] of Object.entries(SNAPSHOT_EDGES))if(parents.some(p=>dirty.has(p)))dirty.add(role);for(const role of Object.keys(SNAPSHOT_EDGES))assert.equal(a.artifacts[role].sha256!==b.artifacts[role].sha256,dirty.has(role),root+'/'+role);}});
test('failure/review preserves whole eligible served snapshot and never mixes changed source timing',async()=>{for(const failure of ['throw','review']){const f=await fixture(),one=await f.obs(),a=await f.coordinator.demand(one),root=await f.put(encode({role:'source',revision:2}));f.fail(failure);const b=await f.coordinator.demand(await f.obs(2,await hash(one),{...f.identity,sourceSha256:root.sha256}));assert.equal(b.state,'ready');assert.deepEqual(b.served,a.served);assert.notEqual(b.desired.revision,b.served.revision);assert.equal(b.reason,'retained-coherent-snapshot');assert.equal(f.builds(),2);}});
test('concurrent identical demands coalesce and delayed old observations cannot move head',async()=>{const f=await fixture();let release;f.gate(new Promise(r=>release=r));const one=await f.obs(),pending=f.coordinator.demand(one);while(f.builds()===0)await new Promise(r=>setImmediate(r));const concurrent=await f.coordinator.demand(one);assert.equal(concurrent.refresh.state,'preparing');assert.equal(f.builds(),1);release();await pending;const two=await f.obs(2,await hash(one));await f.coordinator.demand(two);await assert.rejects(f.coordinator.demand(one),/stale-observation/);});
test('new desired revision fences late old completion and a previous revision can be safely reverified and repromoted',async()=>{const f=await fixture(),one=await f.obs();let release;f.gate(new Promise(r=>release=r));const old=f.coordinator.demand(one);while(f.builds()===0)await new Promise(r=>setImmediate(r));f.gate(null);const source=await f.put(encode({role:'source',revision:2})),two=await f.obs(2,await hash(one),{...f.identity,sourceSha256:source.sha256}),b=await f.coordinator.demand(two);release();await old;assert.equal((await f.coordinator.read(one.logicalId)).served.revision,b.served.revision);const three=await f.obs(3,await hash(two)),restored=await f.coordinator.demand(three);assert.notEqual(restored.served.revision,b.served.revision);assert.equal(restored.served.revision,restored.desired.revision);assert.equal(f.builds(),2);});
test('corrupt/missing dependencies and changed actual clock parents cannot promote, old snapshot stays intact',async()=>{const f=await fixture(),one=await f.obs(),a=await f.coordinator.demand(one),nextRoot=await f.put(encode({role:'source',revision:2})),next={...f.identity,sourceSha256:nextRoot.sha256};f.options.builder.run=async()=>{throw Error('must-not-replace-captured-function');};f.data.delete(a.served.manifest.artifacts.timing.reference);assert.equal((await f.coordinator.read(one.logicalId)).state,'unavailable');assert.equal(f.builds(),1);const wrong=await f.candidate(next);wrong.artifacts.timing.parents.delivery=a.served.manifest.artifacts.delivery.sha256;const custom=createCoherentSnapshots({...f.options,builder:{paid:false,run:async()=>wrong}});const out=await custom.demand(await f.obs(2,await hash(one),next));assert.match(out.refreshError,/parent-mismatch/);assert.equal(out.served,null);});
test('rights revocation during verification refuses promotion and warm serving; async/truthy policy never accepts',async()=>{for(const result of [1,Promise.resolve(true),false]){const f=await fixture();f.policyResult(result);const out=await f.coordinator.demand(await f.obs());assert.equal(out.served,null);assert.equal(out.refresh.state,'uncertain');}const f=await fixture(),one=await f.obs();let calls=0;const get=f.options.bucket.get;f.options.bucket.get=async key=>{const object=await get(key);if(++calls===12)f.eligibility(false);return object;};const out=await f.coordinator.demand(one);assert.equal(out.served,null);assert.equal(out.state,'unavailable');f.eligibility(true);await f.coordinator.demand(one);f.eligibility(false);assert.equal((await f.coordinator.read(one.logicalId)).served,null);});
test('caller input and policy/builder containers cannot be mutated across awaits',async()=>{const f=await fixture(),one=await f.obs();const pending=f.coordinator.demand(one);one.identity.sourceSha256='f'.repeat(64);f.options.policy.validateSnapshot=()=>false;f.options.builder.run=()=>{throw Error('changed');};const result=await pending;assert.equal(result.state,'ready');assert.equal(result.served.manifest.identity.sourceSha256,f.identity.sourceSha256);});
test('promotion rechecks latest desired after verification completed but before its transaction enters',async()=>{const f=await fixture(),original=f.store.transaction.bind(f.store);let count=0,release,waiting=false;f.store.transaction=async fn=>{if(++count===3){waiting=true;await new Promise(r=>release=r);}return original(fn);};const one=await f.obs(),pending=f.coordinator.demand(one);while(!waiting)await new Promise(r=>setImmediate(r));const root=await f.put(encode({role:'source',revision:2})),two=await f.obs(2,await hash(one),{...f.identity,sourceSha256:root.sha256}),newer=await f.coordinator.demand(two);release();await pending;assert.equal((await f.coordinator.read(one.logicalId)).served.revision,newer.served.revision);});
test('same dependencies with newer provenance can adopt the shared pending refresh without losing newest observation',async()=>{const f=await fixture();let release;f.gate(new Promise(r=>release=r));const one=await f.obs(),pending=f.coordinator.demand(one);while(!f.builds())await new Promise(r=>setImmediate(r));const two=await f.obs(2,await hash(one));await f.coordinator.demand(two);release();const result=await pending;assert.equal(result.state,'ready');assert.equal(result.desired.observationSha256,await hash(two));assert.equal(f.builds(),1);});
test('transplanted heads, falsy served records, invalid refresh attempt, and foreign policy pins fail closed',async()=>{const f=await fixture(),one=await f.obs(),result=await f.coordinator.demand(one),key='snapshot-head:'+await sha256(one.logicalId),original=clone(f.store.values.get(key));f.store.values.set('snapshot-head:'+await sha256('other'),clone(original));await assert.rejects(f.coordinator.read('other'),/corrupt-snapshot-head/);for(const served of [false,0,'']){f.store.values.set(key,{...original,served});await assert.rejects(f.coordinator.read(one.logicalId),/snapshot-shape/);}f.store.values.set(key,original);const alternate=createCoherentSnapshots({...f.options,policy:{sha256:'f'.repeat(64),validateSnapshot:()=>true}});assert.equal((await alternate.read(one.logicalId)).reason,'snapshot-policy-identity');const refreshKey='snapshot-refresh:'+result.desired.revision;f.store.values.get(refreshKey).attemptId='';await assert.rejects(f.coordinator.read(one.logicalId),/corrupt-snapshot-refresh/);});

test('timed out builder cannot later promote; retained-stream cancellation cannot extend read deadline',async()=>{const f=await fixture(),one=await f.obs();await f.coordinator.demand(one);let release;f.gate(new Promise(r=>release=r));const bounded=createCoherentSnapshots({...f.options,totalMs:30,progressMs:10}),root=await f.put(encode({role:'source',revision:2})),two=await f.obs(2,await hash(one),{...f.identity,sourceSha256:root.sha256});const result=await bounded.demand(two);assert.equal(result.refresh.state,'uncertain');assert.equal(result.state,'ready');release();await new Promise(r=>setImmediate(r));assert.equal((await bounded.read(one.logicalId)).served.revision,result.served.revision);const get=f.options.bucket.get;let cancelled=0;f.options.bucket.get=async key=>{const object=await get(key);if(key===result.served.manifest.artifacts.source.reference)return {size:object.size,body:new ReadableStream({pull(){return new Promise(()=>{});},cancel(){cancelled++;return new Promise(()=>{});}})};return object;};const unavailable=await bounded.read(one.logicalId);assert.equal(unavailable.reason,'snapshot-progress-timeout');assert.equal(cancelled,1);});

test('non-Error builder rejection preserves old snapshot and records a bounded uncertain reason',async()=>{for(const failure of [null,undefined,'private source payload']){const f=await fixture(),one=await f.obs(),initial=await f.coordinator.demand(one),root=await f.put(encode({role:'source',revision:2}));const broken=createCoherentSnapshots({...f.options,builder:{paid:false,run:async()=>{throw failure;}}});const result=await broken.demand(await f.obs(2,await hash(one),{...f.identity,sourceSha256:root.sha256}));assert.equal(result.state,'ready');assert.deepEqual(result.served,initial.served);assert.equal(result.refresh.state,'uncertain');assert.equal(result.refresh.reason,'snapshot-operation-failed');assert.equal(result.refreshError,'snapshot-operation-failed');}});
test('read failures and hostile Error.message getters expose no payload or secondary exception',async()=>{const f=await fixture(),one=await f.obs();await f.coordinator.demand(one);const error=new Error();Object.defineProperty(error,'message',{get(){throw Error('private-message-getter');}});f.options.bucket.get=async()=>{throw error;};assert.equal((await f.coordinator.read(one.logicalId)).reason,'snapshot-operation-failed');f.options.bucket.get=async()=>{throw undefined;};assert.equal((await f.coordinator.read(one.logicalId)).reason,'snapshot-operation-failed');});
