import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {fileURLToPath} from 'node:url';
const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),{build}=require('esbuild');
const modulePath=fileURLToPath(new URL('../../server/fia/preparation/executor/coherent-snapshot.mjs',import.meta.url)),contractPath=fileURLToPath(new URL('../../server/fia/preparation/contract.mjs',import.meta.url));
const worker=`import {createCoherentSnapshots,SNAPSHOT_EDGES} from ${JSON.stringify(modulePath)};import {canonicalJSONString,sha256} from ${JSON.stringify(contractPath)};
const enc=v=>new TextEncoder().encode(canonicalJSONString(v)),logicalId='eng.MRK/example';
export class Job {
 constructor(ctx,env){this.ctx=ctx;this.env=env;this.builds=0;this.eligible=true;this.init=this.setup();}
 async setup(){this.data=new Map();this.identities=[];for(let revision=1;revision<=2;revision++){const identity={};for(const role of ['source','script','recognitionConfig','alignmentConfig','deliveryConfig','acceptancePolicy']){const bytes=enc({role,revision:role==='source'?revision:1}),hash=await sha256(bytes);identity[role+'Sha256']=hash;this.data.set(hash,bytes);}this.identities.push(identity);}
 const retain=async bytes=>{const hash=await sha256(bytes),reference='snapshots/artifacts/'+hash+'.json';await this.env.OBJECTS.put(reference,bytes,{onlyIf:{etagDoesNotMatch:'*'}});return {sha256:hash,bytes:bytes.length,reference,parents:{}};};
 this.coordinator=createCoherentSnapshots({storage:this.ctx.storage,bucket:this.env.OBJECTS,policy:{sha256:this.identities[0].acceptancePolicySha256,validateSnapshot:({manifest,metadata})=>{const timing=JSON.parse(new TextDecoder().decode(metadata.timing));return timing.clockSha256===manifest.artifacts.delivery.sha256;}},eligibility:()=>this.eligible,builder:{paid:false,run:async({identity})=>{this.builds++;if(this.env.OFFLINE||this.fail)throw Error('upstream-offline');if(this.gate)await new Promise(r=>this.release=r);const artifacts={};for(const [role,parents] of Object.entries(SNAPSHOT_EDGES)){if(!parents.length){artifacts[role]=await retain(this.data.get(identity[role+'Sha256']));continue;}const edge=Object.fromEntries(parents.map(p=>[p,artifacts[p].sha256])),content=role==='acceptance'?{schema:'fia-snapshot-acceptance@1',status:'review-accepted',identity,parents:edge}:{schema:'fixture-node@1',role,parents:edge,...(role==='timing'?{clockSha256:artifacts.delivery.sha256}:{})};artifacts[role]={...await retain(enc(content)),parents:edge};}return {schema:'fia-coherent-snapshot@1',logicalId,identity,artifacts};}}});}
 async fetch(request){await this.init;const input=await request.json();if(input.op==='counts')return Response.json({builds:this.builds,waiting:!!this.release});if(input.op==='control'){this.fail=input.fail;this.gate=input.gate;if(input.eligible!==undefined)this.eligible=input.eligible;if(input.release)this.release?.();return Response.json({ok:true});}if(input.op==='read')return Response.json(await this.coordinator.read(logicalId));const obs={logicalId,sequence:input.sequence,expectedPreviousObservationSha256:input.previous??null,provenance:{checkId:'trusted-check-'+input.sequence,sourceVersionKind:'discovery-snapshot',sourceVersion:'presentation-v1',publisherVersion:null,observedAt:input.sequence},identity:this.identities[(input.source||1)-1]};return Response.json(await this.coordinator.demand(obs));}
}
export default{fetch(request,env){return env.JOBS.get(env.JOBS.idFromName('fixture')).fetch(request);}};`;
const bundle=await build({stdin:{contents:worker,resolveDir:resolve('.')},bundle:true,format:'esm',platform:'browser',external:['node:crypto'],write:false});
function runtime(path,options={}){return new Miniflare({...convertV4MiniflareOptions({name:'coherent-snapshot-fixture',modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:options,durableObjects:{JOBS:{className:'Job',useSQLite:true}},r2Buckets:['OBJECTS']}),resourcePersistencePath:path});}
const call=(mf,input)=>mf.dispatchFetch('https://fixture.invalid/',{method:'POST',body:JSON.stringify(input)}).then(r=>r.json());
async function poll(mf){for(let i=0;i<100;i++){if((await call(mf,{op:'counts'})).waiting)return;await new Promise(r=>setTimeout(r,5));}throw Error('gate-timeout');}
test('actual SQLite/R2 snapshot survives runtime restart, preserves coherent served state on replacement outage and excludes revoked data',async t=>{const directory=await mkdtemp(join(tmpdir(),'coherent-snapshot-'));t.after(()=>rm(directory,{recursive:true,force:true}));let mf=runtime(directory);try{const initial=await call(mf,{sequence:1});assert.equal(initial.state,'ready');await mf.dispose();mf=runtime(directory,{OFFLINE:true});const warm=await call(mf,{op:'read'});assert.deepEqual(warm.served,initial.served);assert.equal((await call(mf,{op:'counts'})).builds,0);const refresh=await call(mf,{sequence:2,previous:initial.desired.observationSha256,source:2});assert.deepEqual(refresh.served,initial.served);assert.equal(refresh.refresh.state,'uncertain');assert.notEqual(refresh.desired.revision,refresh.served.revision);await mf.dispose();mf=runtime(directory,{OFFLINE:true});assert.deepEqual((await call(mf,{op:'read'})).served,initial.served);await call(mf,{op:'control',eligible:false});assert.equal((await call(mf,{op:'read'})).served,null);}finally{await mf.dispose();}});
test('actual SQLite coalesces identical refresh and records newest same-byte provenance during pending build',async t=>{const directory=await mkdtemp(join(tmpdir(),'coherent-pending-'));t.after(()=>rm(directory,{recursive:true,force:true}));const mf=runtime(directory);try{await call(mf,{op:'control',gate:true});const pending=call(mf,{sequence:1});await poll(mf);const shared=await call(mf,{sequence:1});assert.equal(shared.refresh.state,'preparing');const newer=await call(mf,{sequence:2,previous:shared.desired.observationSha256});assert.equal(newer.refresh.state,'preparing');assert.equal((await call(mf,{op:'counts'})).builds,1);await call(mf,{op:'control',release:true});const result=await pending;assert.equal(result.state,'ready');assert.equal(result.desired.observationSha256,newer.desired.observationSha256);assert.equal((await call(mf,{op:'counts'})).builds,1);}finally{await mf.dispose();}});
