import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {createCompleteGuideUnitsResolver} from '../../server/fia/preparation/executor/complete-guide-units.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
const read=p=>readFile(new URL('../../'+p,import.meta.url));
async function setup(){const metadataBytes=await read('server/fia/preparation/guide-sources.json'),registryBytes=await read('apps/web/public/content/registry.json');const canonicalP1={};for(const[k,p]of Object.entries({ledgerBytes:'server/fia/preparation/executor/p1-canonical-unit-ledger.json',sourcePackBytes:'server/fia/compiler/presentation/source-packs.json.gz',presentationBytes:'server/fia/publication/approved-presentation.json',bundleBytes:'apps/web/public/content/bundle.json'}))canonicalP1[k]=await read(p);
 const options={metadataBytes,metadataSha256:await sha256(metadataBytes),registryBytes,registrySha256:await sha256(registryBytes),canonicalP1,presentationAliases:[{packId:'eng.MRK-1-1-13',presentationSha256:'ccd72f23c23f932651b500b730b285f32fabd37e50037b5af91d8881f1403975',presentationId:'fia-mark-authentic@1'}],readPresentation:d=>read('apps/web/public'+d.url)};return{options,rows:JSON.parse(metadataBytes).rows};}
const input=r=>({packId:r.packId,book:r.book,language:r.language,edition:r.edition,passage:r.publisherPassage,resource:r.stepId,scriptSha256:r.guideContentSha256,source:{publisherId:'fia-guide',resourceId:r.publisherSourceId,version:r.presentationRevision}});
test('all408 retained EnglishMark sections preserve5977 canonical units; only3 require disposition adapter',async()=>{const {options,rows}=await setup(),resolve=await createCompleteGuideUnitsResolver(options);let count=0,blocked=[];for(const row of rows){const r=await resolve(input(row));count+=r.canonicalUnits.length;assert.deepEqual(r.canonicalUnits.map(({sourceUnitId,sourceTextSha256})=>({sourceUnitId,sourceTextSha256})),row.sourceUnits);for(const u of r.canonicalUnits)assert.equal(await sha256(u.text),u.sourceTextSha256);if(!r.alignmentInput)blocked.push(row.packId+'/'+row.stepId);assert.deepEqual(r.acceptedPlaybackRanges,[]);}assert.equal(rows.length,408);assert.equal(count,5977);assert.deepEqual(blocked,['eng.MRK-1-1-13/S02','eng.MRK-1-1-13/S05','eng.MRK-1-1-13/S06']);});
test('specialP1 units remain distinct, notes not spoken and no flattened units API',async()=>{const{options,rows}=await setup(),resolve=await createCompleteGuideUnitsResolver(options),r=await resolve(input(rows.find(r=>r.packId==='eng.MRK-1-1-13'&&r.stepId==='S05')));assert.equal(r.units,undefined);assert.equal(r.alignmentInput,null);const notes=r.canonicalUnits.filter(u=>u.narrationRole==='not-spoken-production-note');assert.equal(notes.length,2);assert(notes.every(u=>u.associatedActivityId==='S05-U043'&&u.activityIds.length===0));});
test('missing-unit fallback does not bypass wrong selection or corrupted presentation',async()=>{const{options,rows}=await setup(),row=rows.find(r=>r.packId==='eng.MRK-1-1-13'&&r.stepId==='S02'),resolve=await createCompleteGuideUnitsResolver(options);await assert.rejects(resolve({...input(row),language:'spa'}));const broken=await createCompleteGuideUnitsResolver({...options,readPresentation:async d=>{const b=await options.readPresentation(d);b[0]^=1;return b;}});await assert.rejects(broken(input(row)),/hash/);});
