import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createDecisionJobs} from '../../server/fia/preparation/executor/decision-jobs.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
const h=n=>String(n).repeat(64),bytes=new TextEncoder().encode('{"status":"unknown"}'),input={identity:{source:'fixture',language:'spa'},dependencies:{source:h(1),policy:h(2)}};
async function fixture(){const dir=await mkdtemp(join(tmpdir(),'fia-decisions-'));let db,queue=Promise.resolve(),allowed=true;const counts={run:0,writes:0,reads:0};function open(){db=new DatabaseSync(join(dir,'state.db'));db.exec('CREATE TABLE IF NOT EXISTS kv(k TEXT PRIMARY KEY,v TEXT NOT NULL)');}open();const storage={transaction(fn){const p=queue.then(async()=>{db.exec('BEGIN');try{const result=await fn({get:async k=>{await Promise.resolve();const row=db.prepare('SELECT v FROM kv WHERE k=?').get(k);return row?JSON.parse(row.v):undefined;},put:async(k,v)=>{await Promise.resolve();db.prepare('INSERT OR REPLACE INTO kv VALUES (?,?)').run(k,JSON.stringify(v));}});db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}});queue=p.catch(()=>{});return p;}};const artifacts={async write(b){counts.writes++;const hash=await sha256(b);await writeFile(join(dir,hash),b);return {reference:hash,sha256:hash};},async read(d){counts.reads++;return new Uint8Array(await readFile(join(dir,d.reference)));}};const options={storage,artifacts,dependencySha256:h(3),run:async()=>{counts.run++;return bytes;},validate:async b=>new TextDecoder().decode(b)==='{"status":"unknown"}',eligibility:()=>allowed};return {dir,storage,artifacts,counts,make:o=>createDecisionJobs({...options,...o}),setAllowed:v=>allowed=v,reopen:()=>{db.close();open();},close:async()=>{await queue;db.close();await rm(dir,{recursive:true,force:true});}};}
test('async SQLite claim precedes invocation; concurrent join and restart reads never rerun',async()=>{const f=await fixture();try{let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);const jobs=f.make({run:async(_,{attemptId})=>{f.counts.run++;assert.match(attemptId,/^[a-f0-9-]{36}$/);assert.equal((await jobs.read(input)).state,'preparing');entered();await gate;return bytes;}});assert.equal((await jobs.read(input)).state,'missing');assert.equal(f.counts.run,0);const pending=jobs.request(input);await started;assert.equal((await jobs.request(input)).state,'preparing');assert.equal((await jobs.read(input)).state,'preparing');release();const completed=await pending;assert.equal(completed.state,'completed');assert.deepEqual(completed.bytes,bytes);assert.equal(completed.automaticReplay,false);assert.equal(f.counts.run,1);f.reopen();const restarted=f.make();assert.equal((await restarted.request(input)).state,'completed');assert.equal((await restarted.read(input)).state,'completed');assert.equal(f.counts.run,1);assert.equal(f.counts.writes,1);}finally{await f.close();}});
test('changed trusted input, dependencies and recipe isolate only dependent jobs',async()=>{const f=await fixture();try{const jobs=f.make(),first=await jobs.request(input);for(const changed of [{...input,identity:{...input.identity,language:'eng'}},{...input,dependencies:{...input.dependencies,source:h(4)}}]){assert.equal((await jobs.read(changed)).state,'missing');assert.notEqual((await jobs.request(changed)).decisionSha256,first.decisionSha256);}assert.equal((await f.make({dependencySha256:h(5)}).read(input)).state,'missing');assert.equal((await jobs.read(input)).decisionSha256,first.decisionSha256);}finally{await f.close();}});
test('deadline records uncertainty once; late provider result cannot publish or retry',async()=>{const f=await fixture();try{let release;const gate=new Promise(r=>release=r);const jobs=f.make({stepMs:10,run:async()=>{f.counts.run++;await gate;return bytes;}});assert.equal((await jobs.request(input)).state,'uncertain');release();await new Promise(r=>setTimeout(r,20));assert.equal((await jobs.request(input)).state,'uncertain');assert.equal((await jobs.read(input)).state,'uncertain');assert.equal(f.counts.run,1);assert.equal(f.counts.writes,0);}finally{await f.close();}});
test('explicit interruption fences live attempt and remains uncertain across restart',async()=>{const f=await fixture();try{let release,entered;const gate=new Promise(r=>release=r),started=new Promise(r=>entered=r);const jobs=f.make({run:async()=>{f.counts.run++;entered();await gate;return bytes;}}),pending=jobs.request(input);await started;assert.equal((await jobs.recoverInterrupted(input)).reason,'interrupted');release();assert.equal((await pending).state,'uncertain');f.reopen();assert.equal((await f.make().request(input)).reason,'interrupted');assert.equal(f.counts.run,1);assert.equal(f.counts.writes,0);}finally{await f.close();}});
test('corrupt retained bytes, invalid validator and forged readback cannot become completed',async()=>{const f=await fixture();try{const jobs=f.make(),first=await jobs.request(input);await writeFile(join(f.dir,first.artifact.reference),'corrupt');assert.equal((await jobs.read(input)).state,'unavailable');assert.equal((await jobs.request(input)).state,'unavailable');assert.equal(f.counts.run,1);const other={...input,identity:{source:'other'}};assert.equal((await f.make({validate:async()=>false}).request(other)).state,'uncertain');const third={...input,identity:{source:'third'}};assert.equal((await f.make({artifacts:{...f.artifacts,read:async()=>new Uint8Array([0])}}).request(third)).state,'uncertain');assert.equal((await jobs.read(third)).state,'uncertain');}finally{await f.close();}});
test('revocation at commit and during warm validator prevents delivery; async authority refused',async()=>{const f=await fixture();try{assert.equal((await f.make({eligibility:async()=>true}).request(input)).state,'blocked');assert.equal(f.counts.run,0);assert.equal((await f.make({eligibility:(_i,phase)=>phase!=='commit'}).request(input)).state,'uncertain');const second={...input,identity:{source:'second'}};await f.make().request(second);const jobs=f.make({validate:async()=>{f.setAllowed(false);return true;}});assert.equal((await jobs.read(second)).state,'blocked');assert.equal((await jobs.read(second)).state,'blocked');assert.equal(f.counts.run,2);}finally{await f.close();}});
test('closed bounded input/output and corrupted durable identity fail closed',async()=>{const f=await fixture();try{const jobs=f.make();for(const bad of [{...input,extra:true},{...input,dependencies:{}},{...input,identity:{bad:undefined}},{...input,identity:{bad:Infinity}},{...input,identity:{huge:'x'.repeat(65537)}}])await assert.rejects(jobs.request(bad));assert.equal(f.counts.run,0);assert.equal((await f.make({run:async()=>new Uint8Array(65537)}).request(input)).state,'uncertain');const id=await jobs.read(input);await f.storage.transaction(async tx=>{const key='decision-job:'+id.decisionSha256,row=await tx.get(key);row.identity.input.identity.source='forged';await tx.put(key,row);});await assert.rejects(jobs.read(input),/decision-job-invalid/);}finally{await f.close();}});
test('artifact written before failed pointer commit remains uncertain and is never regenerated',async()=>{const f=await fixture();try{let fail=true;const storage={transaction:fn=>f.storage.transaction(tx=>fn({...tx,put:async(k,v)=>{if(v.state==='completed'&&fail){fail=false;throw Error('simulated-crash-before-pointer');}return tx.put(k,v);}}))};const jobs=f.make({storage});assert.equal((await jobs.request(input)).state,'uncertain');assert.equal(f.counts.run,1);assert.equal(f.counts.writes,1);f.reopen();assert.equal((await f.make().request(input)).state,'uncertain');assert.equal(f.counts.run,1);assert.equal(f.counts.writes,1);}finally{await f.close();}});
