import test from 'node:test';
import assert from 'node:assert/strict';
import {createGuideDiscoveryAdapter,publishedGuideMetadataFromAudit} from '../../server/fia/preparation/executor/discovery.mjs';
import {createObservedSourceAdapter} from '../../server/fia/preparation/executor/observed-source.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const encode=value=>new TextEncoder().encode(canonicalJSONString(value));
function bucket(){const values=new Map();return {values,async get(key){const value=values.get(key);return value?{body:new Response(value.slice()).body}:null;},async put(key,bytes,options){if(options?.onlyIf?.etagDoesNotMatch==='*'&&values.has(key))return null;values.set(key,bytes.slice());return {};}};}
function row(overrides={}){return {packId:'eng.MRK-1-14-20',presentationRevision:'a'.repeat(64),language:'eng',book:'MRK',edition:'fia-guide',publisherSourceId:'eng-mrk-p2-v2.1',publisherPassage:'1:14-20',stepId:'S01',sourceURL:'https://s3.amazonaws.com/cbbt-er.public/pericopes/eng/mrk/p2/s1/v2.2/vbr0.mp3',sourceMetadataSha256:'b'.repeat(64),guideContentSha256:'c'.repeat(64),sourceUnits:[{sourceUnitId:'S01-U001',sourceTextSha256:'d'.repeat(64)},{sourceUnitId:'S01-U002',sourceTextSha256:'e'.repeat(64)}],...overrides};}
const request=r=>({packId:r.packId,presentationRevision:r.presentationRevision,language:r.language,edition:r.edition,sourceUnitId:r.sourceUnits[0].sourceUnitId,sourceTextSha256:r.sourceUnits[0].sourceTextSha256});
async function fixture(rows=[row()]){const storage=bucket(),metadataBytes=encode({schema:'fia-published-guide-sources@1',rows}),metadataSha256=await sha256(metadataBytes);return {storage,metadataBytes,metadataSha256,guide:await createGuideDiscoveryAdapter({metadataBytes,metadataSha256,bucket:storage})};}
test('exact consumer binding resolves section and copies literal versioned publisher URL',async()=>{const f=await fixture(),{input}=await f.guide.resolveRequest(request(row()));const result=await f.guide.adapter.run({input}),stored=JSON.parse(new TextDecoder().decode(f.storage.values.get(result.reference)));assert.equal(stored.source.url,row().sourceURL);assert.equal(stored.source.version,row().presentationRevision);assert.equal(stored.metadataSha256,f.metadataSha256);assert.equal(stored.source.sha256,undefined);assert.equal(stored.source.bytes,undefined);assert.equal(await f.guide.validatePublisherURL(stored.source.url,{input,discovery:stored}),true);});
test('different units of one section share source discovery, with exact unit text validation',async()=>{const f=await fixture(),first=await f.guide.resolveRequest(request(row())),second=await f.guide.resolveRequest({...request(row()),sourceUnitId:'S01-U002',sourceTextSha256:'e'.repeat(64)});assert.deepEqual(first.input,second.input);assert.deepEqual(await f.guide.adapter.run(first),await f.guide.adapter.run(second));for(const change of [{sourceTextSha256:'f'.repeat(64)},{presentationRevision:'f'.repeat(64)},{language:'spa'},{sourceUnitId:'S01-U999'}])await assert.rejects(f.guide.resolveRequest({...request(row()),...change}),/unresolved/);});
test('book passage and section are metadata parameters rather than a hardcoded passage',async()=>{const other=row({packId:'eng.LUK-2-1-10',book:'LUK',publisherSourceId:'eng-luk-p20-v3',publisherPassage:'2:1-10',sourceURL:'https://s3.amazonaws.com/cbbt-er.public/pericopes/eng/luk/p20/s1/v7/vbr0.mp3'}),f=await fixture([row(),other]);const resolved=await f.guide.resolveRequest(request(other));assert.equal(resolved.input.book,'LUK');const artifact=await f.guide.adapter.run(resolved);assert.equal(JSON.parse(new TextDecoder().decode(f.storage.values.get(artifact.reference))).source.url,other.sourceURL);});
test('metadata hash ambiguity and untrusted publisher URLs fail before storage',async()=>{const f=await fixture();await assert.rejects(createGuideDiscoveryAdapter({...f,metadataBytes:f.metadataBytes,metadataSha256:'f'.repeat(64),bucket:f.storage}),/identity/);await assert.rejects(fixture([row(),row()]),/ambiguous/);for(const sourceURL of ['https://example.org/audio.mp3','https://s3.amazonaws.com/unrelated/audio.mp3',row().sourceURL+'?override=1'])await assert.rejects(fixture([row({sourceURL})]),/publisher/);assert.equal(f.storage.values.size,0);});
test('corrupt immutable discovery is never overwritten',async()=>{const f=await fixture(),resolved=await f.guide.resolveRequest(request(row())),artifact=await f.guide.adapter.run(resolved);f.storage.values.set(artifact.reference,encode({corrupt:true}));await assert.rejects(f.guide.adapter.run(resolved),/conflict/);assert.deepEqual(JSON.parse(new TextDecoder().decode(f.storage.values.get(artifact.reference))),{corrupt:true});});
test('observed acquisition hashes actual bytes and reuses them with publisher offline',async()=>{const f=await fixture(),resolved=await f.guide.resolveRequest(request(row())),discover=await f.guide.adapter.run(resolved);let calls=0;const original=new TextEncoder().encode('actual publisher bytes');const adapter=createObservedSourceAdapter({bucket:f.storage,validatePublisherURL:f.guide.validatePublisherURL,fetchSource:async url=>{calls++;assert.equal(url,row().sourceURL);return new Response(original,{headers:{'Content-Type':'audio/mpeg'}});}});const context={...resolved,nodeOutputs:{discover}},first=await adapter.run(context);assert.equal(first.sha256,await sha256(original));const offline=createObservedSourceAdapter({bucket:f.storage,validatePublisherURL:f.guide.validatePublisherURL,fetchSource:async()=>{throw Error('offline');}});assert.deepEqual(await offline.run(context),first);assert.equal(calls,1);});
test('audit conversion pins audited input and removes private paths and placeholder readiness',async()=>{const audit={schema:'fia-dynamic-discovery-resolver-audit@1',inputs:{'/private/source':{sha256:'a'.repeat(64)}},guideSources:[{...row(),sourceMetadataPath:'/private/path',packaged:true,sourceSha256:'0'.repeat(64),derivatives:{status:'pending'}}]},bytes=encode(audit),result=await publishedGuideMetadataFromAudit(bytes,await sha256(bytes));const text=new TextDecoder().decode(result.bytes);assert.ok(!text.includes('/private'));assert.ok(!text.includes('packaged'));assert.ok(!text.includes('derivatives'));assert.ok(!text.includes('0'.repeat(64)));assert.equal((await createGuideDiscoveryAdapter({metadataBytes:result.bytes,metadataSha256:result.sha256,bucket:bucket()})).count,1);await assert.rejects(publishedGuideMetadataFromAudit(bytes,'f'.repeat(64)),/identity/);});
