import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {gunzipSync} from 'node:zlib';
import {createExecutablePresentationResolver} from '../../server/fia/preparation/executable-presentation-resolver.mjs';
import {sha256,canonicalJSONString} from '../../server/fia/preparation/contract.mjs';
const encode=v=>new TextEncoder().encode(canonicalJSONString(v));
const registry=JSON.parse(await readFile('apps/web/public/content/registry.json')),source=JSON.parse(gunzipSync(await readFile('server/fia/compiler/presentation/source-packs.json.gz')));
async function fixture(packId='spa.MRK-1-14-20'){
 const descriptor=registry.packs.find(d=>d.id===packId),content=await readFile('apps/web/public'+descriptor.presentation.url,'utf8'),artifact={sha256:descriptor.revision,bytes:Buffer.byteLength(content),mime:'application/json',path:'/v1/artifacts/'+descriptor.revision},record={status:'ready',packId,revision:descriptor.revision,artifact,authority:{rawInventoryCommit:source.revision}},args={packId,baseRevision:descriptor.revision,sourceRevision:source.revision,capability:'executable-presentation'},sourceBytes=encode(source.packs[packId].guide),calls=[];
 const options={reads:{async readPack(arg){calls.push(['pack',arg]);return structuredClone(record);},async readArtifact(arg){calls.push(['artifact',arg]);return {status:'ready',artifact:structuredClone(artifact),content};}},resolveCanonicalSource:async arg=>{calls.push(['source',arg]);return {bytes:sourceBytes,sha256:await sha256(sourceBytes),sourceRevision:source.revision};}};
 return {args,record,content,artifact,sourceBytes,calls,options,make:o=>createExecutablePresentationResolver({...options,...o})};
}
test('actual nonfirst EN/ES published bytes bind canonical units/order without fabricated decisions',async()=>{for(const pack of ['eng.MRK-1-14-20','spa.MRK-1-14-20','eng.MRK-1-21-28','spa.MRK-1-21-28']){const f=await fixture(pack),result=await f.make()(f.args);assert.equal(result.baseRevision,f.args.baseRevision);assert.equal(result.language,pack.slice(0,3));assert.ok(result.canonicalUnits.length>50);assert.equal(result.canonicalOrderSha256,await sha256(encode(result.canonicalUnits.map(({text,...a})=>a))));assert.deepEqual(result.decisions,[]);assert.deepEqual(result.transitionEvidence,[]);assert.deepEqual(result.boundArtifacts,[]);assert.deepEqual(f.calls.map(c=>c[0]),['pack','artifact','source']);assert.deepEqual(f.calls[0][1],{packId:pack,revision:f.args.baseRevision});}});
test('wrong source revision and corrupt exact artifact refuse before trusted composition',async()=>{const f=await fixture();let composed=0;const composeDecisionInputs=async()=>{composed++;return [];};await assert.rejects(f.make({composeDecisionInputs})({...f.args,sourceRevision:'a'.repeat(40)}),/source-revision/);await assert.rejects(f.make({composeDecisionInputs,reads:{...f.options.reads,readArtifact:async()=>({status:'ready',artifact:f.artifact,content:f.content+' '})}})(f.args),/artifact-integrity/);assert.equal(composed,0);});
test('canonical source hash, text and guide binding are independently checked',async()=>{const f=await fixture();await assert.rejects(f.make({resolveCanonicalSource:async()=>({bytes:f.sourceBytes,sha256:'a'.repeat(64),sourceRevision:source.revision})})(f.args),/canonical-integrity/);for(const mutate of [g=>g.steps[0].units[0].text+=' changed',g=>g.contentSha256='b'.repeat(64),g=>g.steps[1].id=g.steps[0].id]){const g=JSON.parse(new TextDecoder().decode(f.sourceBytes));mutate(g);const bytes=encode(g);await assert.rejects(f.make({resolveCanonicalSource:async()=>({bytes,sha256:await sha256(bytes),sourceRevision:source.revision})})(f.args));}});
test('trusted composer gets verified immutable context; malformed schema cannot launch semantic work',async()=>{const f=await fixture();await assert.rejects(f.make({composeDecisionInputs:async context=>{context.basePresentation.activities=[];return [{input:{arbitraryPrompt:'pick first'}}];}})(f.args),/decision-input/);const result=await f.make({composeDecisionInputs:async context=>{context.basePresentation.activities=[];return [];},resolveBindings:async()=>({transitionEvidence:[],boundArtifacts:[],narrationBindings:{}})})(f.args);assert.ok(result.basePresentation.activities.length>0);assert.deepEqual(result.narrationBindings,{});});
test('exact demand and unavailable base reject without canonical lookup',async()=>{const f=await fixture();await assert.rejects(f.make()({...f.args,url:'https://invalid/'}),/resolver-request/);await assert.rejects(f.make({reads:{...f.options.reads,readPack:async()=>({status:'unavailable'})}})(f.args),/base-unavailable/);assert.equal(f.calls.length,0);});
test('trusted source archive export and demanded snapshot reader compose real source once',async()=>{const {mkdtemp,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{exportGuideSources}=await import('../../server/fia/compiler/presentation/export-guide-sources.mjs'),{createCanonicalGuideReader}=await import('../../server/fia/preparation/executable-presentation-resolver.mjs');const dir=await mkdtemp(join(tmpdir(),'fia-source-export-'));try{const descriptors=exportGuideSources({outputRoot:dir,sourceRevision:source.revision});assert.equal(descriptors.length,136);const seen=[];const reader=createCanonicalGuideReader({canonicalSources:descriptors,fetchAsset:async path=>{seen.push(path);return new Response(await readFile(dir+path),{headers:{'Content-Type':'application/json'}});}});assert.equal(seen.length,0);const f=await fixture(),context=await f.make({resolveCanonicalSource:reader})(f.args);assert.equal(context.language,'spa');assert.equal(seen.length,1);const retained=await reader(f.args);assert.equal(await sha256(retained.bytes),retained.sha256);assert.equal(seen.length,2);await assert.rejects(reader({...f.args,sourceRevision:'a'.repeat(40)}),/unavailable/);assert.equal(seen.length,2);assert.throws(()=>exportGuideSources({outputRoot:dir,sourceRevision:source.revision,archiveBytes:new Uint8Array([1])}),/archive-pin/);assert.throws(()=>exportGuideSources({outputRoot:dir,sourceRevision:source.revision,sourceBindings:{}}),/guide-pin/);}finally{await rm(dir,{recursive:true,force:true});}});
test('snapshot source reader rejects corrupted bytes, unknown paths, HTML and length mismatch',async()=>{const {createCanonicalGuideReader}=await import('../../server/fia/preparation/executable-presentation-resolver.mjs'),f=await fixture(),digest=await sha256(f.sourceBytes),d={packId:f.args.packId,sourceRevision:source.revision,sha256:digest,bytes:f.sourceBytes.length,staticPath:`/content/source-guides/${digest}.json`};for(const fetchAsset of [async()=>new Response('html',{headers:{'Content-Type':'text/html'}}),async()=>new Response(f.sourceBytes,{headers:{'Content-Type':'application/json','Content-Length':'1'}}),async()=>new Response(new Uint8Array(f.sourceBytes.length),{headers:{'Content-Type':'application/json'}})])await assert.rejects(createCanonicalGuideReader({canonicalSources:[d],fetchAsset})(f.args));assert.throws(()=>createCanonicalGuideReader({canonicalSources:[{...d,staticPath:'/secret'}],fetchAsset:async()=>{}}),/descriptor/);});
test('source reader total deadline bounds stalled fetch/body and never awaits stalled cancellation',async()=>{const {createCanonicalGuideReader}=await import('../../server/fia/preparation/executable-presentation-resolver.mjs'),f=await fixture(),digest=await sha256(f.sourceBytes),d={packId:f.args.packId,sourceRevision:source.revision,sha256:digest,bytes:f.sourceBytes.length,staticPath:`/content/source-guides/${digest}.json`};let calls=0,aborted=false;for(const fetchAsset of [async(_,{signal})=>{calls++;signal.addEventListener('abort',()=>aborted=true);return new Promise(()=>{});},async()=>{calls++;return new Response(new ReadableStream({pull(){return new Promise(()=>{});},cancel(){return new Promise(()=>{});}}),{headers:{'Content-Type':'application/json'}});}]){const reader=createCanonicalGuideReader({canonicalSources:[d],fetchAsset,stepMs:15});await assert.rejects(reader(f.args),/deadline/);}assert.equal(calls,2);assert.equal(aborted,true);const invalid=createCanonicalGuideReader({canonicalSources:[d],stepMs:15,fetchAsset:async()=>new Response(new ReadableStream({cancel(){return new Promise(()=>{});}}),{headers:{'Content-Type':'text/html'}})});await assert.rejects(invalid(f.args),/response/);});
test('bounded composer context must be adjacent and candidate content must match exact retained metadata',async()=>{const f=await fixture();const compose=({distant=false,forge=false}={})=>async c=>{const u=c.canonicalUnits[0],context=c.canonicalUnits[distant?20:1],activity=c.basePresentation.activities.find(a=>a.sourceUnitId===u.sourceUnitId),asset=Object.values(c.basePresentation.assets).find(a=>a.kind==='term'),{canonicalSourceActionCandidate}=await import('../../server/fia/compiler/presentation/source-action-candidates.mjs'),candidate=await canonicalSourceActionCandidate(asset,c.language);if(forge){candidate.sourceText='invented definition';candidate.sourceTextSha256=await sha256(candidate.sourceText);}return [{input:{contract:'fia-source-action-input@1',packId:c.basePresentation.id,presentationRevision:c.baseRevision,sourceRevision:c.sourceRevision,guideContentSha256:c.guideContentSha256,language:c.language,source:{unitId:u.sourceUnitId,text:u.text,sha256:u.sourceTextSha256},context:[{unitId:context.sourceUnitId,text:context.text,sha256:context.sourceTextSha256}],requestedDecisions:['resource-association'],candidates:[candidate],explicitAssociations:[],sourceAnchor:(({text,...a})=>a)(u),canonicalOrderSha256:c.canonicalOrderSha256,existingActivityBindings:[{activityId:activity.id,sourceUnitId:u.sourceUnitId,sourceTextSha256:u.sourceTextSha256,sectionId:u.sectionId}],intentSlots:[{slotId:'term',resourceKind:'term',relation:'requested-medium',candidateResourceIds:[candidate.resourceId]}]}}];};const good=await f.make({composeDecisionInputs:compose()})(f.args);assert.equal(good.decisions.length,1);await assert.rejects(f.make({composeDecisionInputs:compose({distant:true})})(f.args),/adjacency/);await assert.rejects(f.make({composeDecisionInputs:compose({forge:true})})(f.args),/candidate/);});
