import test from 'node:test';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,resolve} from 'node:path';import {fileURLToPath} from 'node:url';
const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),{build}=require('esbuild');
const modulePath=fileURLToPath(new URL('../../server/fia/preparation/executor/fresh-source-observation.mjs',import.meta.url));
const worker=`import {createFreshSourceObservations} from ${JSON.stringify(modulePath)};
export class Job {constructor(ctx,env){this.ctx=ctx;this.env=env;this.gets=0;this.cancelled=0;this.eligible=true;this.gates=new Map();}
 async fetch(request){const args=await request.json();if(args.op==='revoke'){this.eligible=false;return Response.json({revoked:true});}if(args.op==='counts')return Response.json({gets:this.gets,cancelled:this.cancelled,waiting:[...this.gates.keys()]});if(args.op==='corrupt-status'){const entries=await this.ctx.storage.list({prefix:'fresh-ticket:'});for(const [key,value] of entries){value.promoted=true;value.reason='fresh-stale-head';await this.ctx.storage.put(key,value);}return Response.json({corrupted:true});}if(args.op==='release'){this.gates.get(args.checkId)?.();return Response.json({released:true});}
 const source={logicalId:'eng.MRK/fixture',url:args.url||'https://publisher.invalid/original.mp3',sourceVersionKind:'discovery-snapshot',sourceVersion:'presentation-revision-1',publisherVersion:null},policy={revision:args.policyRevision||'fresh-v1',maxBytes:args.maxBytes||8388608,totalMs:args.totalMs||5000,progressMs:args.progressMs||1000};
 const admissions=args.admissions||[{checkId:args.checkId||'check-one',sequence:args.sequence||1,expectedPreviousObservationSha256:args.previous??null,previousSourceSha256:args.previousSource??null}];
 const cancellation=new AbortController(),storage={get:(...a)=>this.ctx.storage.get(...a),transaction:fn=>this.ctx.storage.transaction(tx=>fn({get:(...a)=>tx.get(...a),put:(key,value)=>{if(args.failCommit&&value?.schema==='fia-source-check@1'&&value.state==='completed')throw Error('fixture-commit-failure');return tx.put(key,value);}}))};let task;try{task=createFreshSourceObservations({storage,bucket:this.env.OBJECTS,source,policy,admissions,eligibility:({observedContent})=>args.asyncEligibility?Promise.resolve(true):this.eligible&&!(args.blockObserved&&observedContent),now:()=>1000,fetchSource:async(url,options)=>{this.gets++;if(this.env.OFFLINE||args.fail)throw null;if(options.redirect!=='manual')throw Error('wrong-redirect');if(args.gate)await new Promise(r=>this.gates.set(args.checkId,r));let position=0;const size=args.size||131072,actual=size+(args.extra||0),owner=this;const body=new ReadableStream({async pull(c){if(args.abort){cancellation.abort();return;}if(args.stall)return new Promise(()=>{});if(args.slow)await new Promise(r=>setTimeout(r,5));if(position===actual){c.close();return;}const bytes=new Uint8Array(Math.min(args.hugeChunk?1048577:65536,actual-position)).fill(args.changed?98:97);position+=bytes.length;c.enqueue(bytes);},cancel(){owner.cancelled++;if(args.hungCancel)return new Promise(()=>{});}});const headers={'content-type':args.mime||'audio/mpeg'};if(!args.noLength)headers['content-length']=String(args.length??size);return new Response(body,{status:args.httpStatus||200,headers});}});
 const result=args.op==='read'?await task.read():args.op==='status'?await task.status(args.checkId):args.op==='reconcile'?await task.reconcile(args.checkId,args.fence):await task.observe(args.checkId||'check-one',{signal:cancellation.signal});return Response.json({result,gets:this.gets,objects:(await this.env.OBJECTS.list()).objects.map(x=>({key:x.key,size:x.size}))});}catch(error){return Response.json({error:error?.message||'fixture-error',gets:this.gets,status:task?await task.status(args.checkId||'check-one').catch(()=>null):null,cancelled:this.cancelled});}}
}
export default {fetch(request,env){return env.JOBS.get(env.JOBS.idFromName('fixture')).fetch(request);}};`;
const bundle=await build({stdin:{contents:worker,resolveDir:resolve('.')},bundle:true,format:'esm',platform:'browser',external:['node:crypto'],write:false});
function runtime(path,bindings={}){return new Miniflare({...convertV4MiniflareOptions({name:'fresh-source-fixture',modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings,durableObjects:{JOBS:{className:'Job',useSQLite:true}},r2Buckets:['OBJECTS']}),resourcePersistencePath:path});}
const call=(mf,args={})=>mf.dispatchFetch('https://fixture.invalid/',{method:'POST',body:JSON.stringify(args)}).then(r=>r.json());
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),'fresh-source-'));t.after(()=>rm(directory,{recursive:true,force:true}));return {directory,mf:runtime(directory)};}
const next=(head,checkId,sequence)=>({checkId,sequence,previous:head.observationSha256,previousSource:head.observation.sha256});
async function waiting(mf,checkId){for(let n=0;n<100;n++){if((await call(mf,{op:'counts'})).waiting.includes(checkId))return;await new Promise(r=>setTimeout(r,5));}throw Error('gate-timeout');}
test('actual SQLite/R2 later admitted check always fetches while unchanged bytes reuse original; changed bytes retain old immutable content',async t=>{const {mf}=await fixture(t);try{const first=await call(mf);assert.equal(first.result.state,'completed',JSON.stringify(first));const head1=(await call(mf,{op:'read'})).result;assert.equal(head1.acceptedPlayback,false);assert.equal(head1.observation.binding.source.sourceVersionKind,'discovery-snapshot');const again=await call(mf);assert.equal(again.gets,1);const twoArgs=next(head1,'check-two',2),two=await call(mf,twoArgs);assert.equal(two.gets,2);assert.equal(two.result.promoted,true);let head2=(await call(mf,{op:'read'})).result;assert.equal(head2.observation.sha256,head1.observation.sha256);assert.equal(head2.observation.changed,false);assert.notEqual(head2.observationSha256,head1.observationSha256);assert.equal(two.objects.filter(x=>x.key.startsWith('originals/sha256/')).length,1);const three=await call(mf,{...next(head2,'check-three',3),changed:true});assert.equal(three.gets,3);assert.equal(three.objects.filter(x=>x.key.startsWith('originals/sha256/')).length,2);const head3=(await call(mf,{op:'read'})).result;assert.notEqual(head3.observation.sha256,head2.observation.sha256);assert.equal(head3.observation.binding.source.sourceVersion,'presentation-revision-1');assert.equal(head3.observation.binding.source.publisherVersion,null);assert.equal((await call(mf,{op:'counts'})).gets,3);}finally{await mf.dispose();}});
test('actual SQLite coalesces identical admission and late older completion records historical receipt without replacing head',async t=>{const {mf}=await fixture(t);try{const one=call(mf,{checkId:'one',sequence:1,gate:true});await waiting(mf,'one');const duplicate=await call(mf,{checkId:'one',sequence:1});assert.equal(duplicate.result.state,'preparing');assert.equal(duplicate.gets,1);const two=await call(mf,{checkId:'two',sequence:2,changed:true});assert.equal(two.result.promoted,true);const head2=(await call(mf,{op:'read'})).result;await call(mf,{op:'release',checkId:'one'});const old=await one;assert.equal(old.result.state,'completed');assert.equal(old.result.promoted,false);assert.deepEqual((await call(mf,{op:'read'})).result,head2);}finally{await mf.dispose();}});
test('actual SQLite persisted ticket rejects source/policy rebinding, sequence aliases and false previous source before network',async t=>{const {mf}=await fixture(t);try{await call(mf);for(const changed of [{policyRevision:'fresh-v2'},{url:'https://publisher.invalid/other.mp3'}]){const result=await call(mf,changed);assert.equal(result.error,'fresh-ticket-conflict');assert.equal(result.gets,1);}const h=(await call(mf,{op:'read'})).result;const falsePrior=await call(mf,{...next(h,'two',2),previousSource:'f'.repeat(64)});assert.equal(falsePrior.error,'fresh-stale-admission');assert.equal(falsePrior.gets,1);const alias=await call(mf,{checkId:'alias',sequence:1});assert.equal(alias.error,'fresh-sequence-conflict');assert.equal(alias.gets,1);const unknown=await call(mf,{checkId:'other',admissions:[{checkId:'approved',sequence:4,expectedPreviousObservationSha256:null,previousSourceSha256:null}]});assert.equal(unknown.error,'fresh-not-admitted');assert.equal(unknown.gets,1);}finally{await mf.dispose();}});
test('actual SQLite/R2 restart verifies head and completed receipt with zero GET; failed new check preserves prior head',async t=>{const {directory,mf:first}=await fixture(t);let mf=first;try{await call(mf);const original=(await call(mf,{op:'read'})).result;await mf.dispose();mf=runtime(directory,{OFFLINE:true});assert.deepEqual((await call(mf,{op:'read'})).result,original);assert.equal((await call(mf)).gets,0);const failure=await call(mf,next(original,'two',2));assert.equal(failure.status.operation.state,'uncertain');assert.equal(failure.error,'fresh-operation-failed');const repeated=await call(mf,next(original,'two',2));assert.equal(repeated.result.state,'uncertain');assert.equal(repeated.gets,1);assert.deepEqual((await call(mf,{op:'read'})).result,original);}finally{await mf.dispose();}});
test('actual R2 CL-required path enforces actual bounds and never completes absent/false length or stalled source',async t=>{for(const [name,args] of Object.entries({abort:{abort:true},missing:{noLength:true,hungCancel:true},invalid:{length:'-1'},short:{extra:-1},long:{extra:1},mime:{mime:'text/plain'},redirect:{httpStatus:302},stall:{stall:true,progressMs:10,hungCancel:true},total:{slow:true,totalMs:10},oversizedHeader:{length:8388609},oversizedChunk:{size:2097152,hugeChunk:true}})){const {mf}=await fixture(t);try{const result=await call(mf,args);assert.ok(result.error,name+JSON.stringify(result));assert.equal(result.status.operation.state,'uncertain',name);assert.equal((await call(mf,{...args,op:'read'})).result.state,'unobserved',name);const repeated=await call(mf,args);assert.equal(repeated.result.state,'uncertain',name);assert.equal(repeated.gets,1,name);}finally{await mf.dispose();}}});
test('actual R2 accepts exact 8MiB and rejects cap+1 actual bytes despite matching cap header',async t=>{for(const extra of [0,1]){const {mf}=await fixture(t);try{const result=await call(mf,{size:8388608,extra,totalMs:10000});if(extra===0){assert.equal(result.result?.state,'completed',JSON.stringify(result));assert.equal((await call(mf,{op:'read',totalMs:10000})).result.observation.bytes,8388608);}else assert.equal(result.status.operation.state,'uncertain');}finally{await mf.dispose();}}});

test('current eligibility refuses stale tickets before GET and refuses head promotion after revocation during transfer',async t=>{for(const mode of ['before','during','async']){const {mf}=await fixture(t);try{if(mode==='before')await call(mf,{op:'revoke'});if(mode==='during'){const pending=call(mf,{checkId:'one',gate:true});await waiting(mf,'one');await call(mf,{op:'revoke'});await call(mf,{op:'release',checkId:'one'});const result=await pending;assert.equal(result.result.state,'completed');assert.equal(result.result.promoted,false);assert.equal(result.result.reason,'fresh-ineligible');assert.equal((await call(mf,{op:'read'})).result.state,'unobserved');}else{const result=await call(mf,{asyncEligibility:mode==='async'});assert.equal(result.error,'fresh-ineligible');assert.equal(result.gets,0);}}finally{await mf.dispose();}}});
test('corrupt retained originals fail warm integrity without a publisher request or overwrite',async t=>{const {mf}=await fixture(t);try{await call(mf);const bucket=await mf.getR2Bucket('OBJECTS'),object=(await bucket.list({prefix:'originals/sha256/'})).objects[0];await bucket.put(object.key,new Uint8Array([1,2,3]));const result=await call(mf,{op:'read'});assert.equal(result.error,'fresh-retained-size');assert.equal(result.gets,1);const repeat=await call(mf);assert.equal(repeat.error,'fresh-retained-size');assert.equal(repeat.gets,1);assert.equal((await bucket.get(object.key)).size,3);}finally{await mf.dispose();}});

test('completed operation metadata rejects contradictory promoted/stale state',async t=>{const {mf}=await fixture(t);try{await call(mf);await call(mf,{op:'corrupt-status'});assert.equal((await call(mf,{op:'status',checkId:'check-one'})).error,'fresh-state-corrupt');}finally{await mf.dispose();}});

test('actual SQLite interrupted final commit leaves retained receipt historical, survives restart and reconciles without GET or head promotion',async t=>{const {directory,mf:first}=await fixture(t);let mf=first;try{const interrupted=await call(mf,{failCommit:true});assert.equal(interrupted.status.operation.state,'uncertain');assert.equal((await call(mf,{op:'read'})).result.state,'unobserved');const fence={attemptId:interrupted.status.operation.attemptId,revision:1};await mf.dispose();mf=runtime(directory,{OFFLINE:true});const receipt=await call(mf,{op:'reconcile',checkId:'check-one',fence});assert.equal(receipt.result.state,'uncertain');assert.equal(receipt.result.evidence,'verified-retained-historical-only');assert.equal(receipt.result.promoted,false);assert.equal(receipt.gets,0);assert.equal((await call(mf)).result.state,'uncertain');assert.equal((await call(mf,{op:'read'})).result.state,'unobserved');}finally{await mf.dispose();}});

test('eligibility receives newly observed content identity and can exclude a known-bad hash before head advancement',async t=>{const {mf}=await fixture(t);try{const result=await call(mf,{blockObserved:true});assert.equal(result.gets,1);assert.equal(result.result.state,'completed');assert.equal(result.result.promoted,false);assert.equal(result.result.reason,'fresh-ineligible');assert.equal((await call(mf,{op:'read'})).result.state,'unobserved');}finally{await mf.dispose();}});
