import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
import {createGuideExecutor} from '../../server/fia/preparation/executor/guide-executor.mjs';
import {createGuideDiscoveryAdapter} from '../../server/fia/preparation/executor/discovery.mjs';
import {createObservedSourceAdapter} from '../../server/fia/preparation/executor/observed-source.mjs';
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));
const metadata={"auditSha256":"4c7c053cee9bc40536148efafaffc193772c25b9116986c1b3c9716801698726","rows":[{"book":"MRK","edition":"fia-guide","guideContentSha256":"d0b5c7d9f92ad6faa97bb8b2718d627e4044804c18e4bf7ef1432cb207ed5ec9","language":"eng","packId":"eng.MRK-1-14-20","presentationRevision":"92ad518474f159f6567124052ae12d180a482c949509da0b725593442e62f746","publisherPassage":"1:14-20","publisherSourceId":"eng-mrk-p2-v2.2","sourceMetadataSha256":"a2b8206f53219181af1bd5b69caf4e3d3d774f3b2d0bf7cdb3e2b7e0dd93be0d","sourceURL":"https://s3.amazonaws.com/cbbt-er.public/pericopes/eng/mrk/p2/s1/v2/vbr0.mp3","sourceUnits":[{"sourceTextSha256":"0878d96b6158892fbe45a734a35e5017a172bc3ffbbfbd3d8478611327b18890","sourceUnitId":"S01-U001"},{"sourceTextSha256":"63fc098411c6228d314f6b5bc64a048a86130679b3b484fe56dcc774bd73258f","sourceUnitId":"S01-U002"},{"sourceTextSha256":"c6ef6ed4d31b97cf4a0d03a8228505d052a8a780a5fe0413ebc441860df97b5d","sourceUnitId":"S01-U003"},{"sourceTextSha256":"e8a93c2c61fe1a0f6f81fa58997b305e6fc98309b710e3a31ff8334e8644a3eb","sourceUnitId":"S01-U004"},{"sourceTextSha256":"5df74ebc5c4225c3d54e1629cff92f39a1cc058f2ac30b59d75d68d496d1d0f5","sourceUnitId":"S01-U005"},{"sourceTextSha256":"5ec46dee57eb35404b2cea3f9aaa67f2973ac8781088fa05d8073f9e72fdf4c3","sourceUnitId":"S01-U006"},{"sourceTextSha256":"97dd8ff3c182bdac8fd7e57ffe1bf62350452bd66178db6560b7909eb5237842","sourceUnitId":"S01-U007"},{"sourceTextSha256":"d7a5f7f06349c901d886647055b1f48f7251a9fbfe2b37e509b26e0538704e46","sourceUnitId":"S01-U008"}],"stepId":"S01"}],"schema":"fia-published-guide-sources@1"};
const metadataSha256='3a937573a1d878a91bd514f501913247bf912df212c359bb559afaa3e1cfdeb2',metadataBytes=encode(metadata);
const row=metadata.rows[0],registryBytes=new Uint8Array(await readFile(new URL('../../apps/web/public/content/registry.json',import.meta.url))),registrySha256=await sha256(registryBytes);
const rawBytes=new Uint8Array(await readFile(new URL('./fixtures/p2-raw-recognition.json',import.meta.url))),rawPin='4fe40977fbb85f6fea043a9cadeb6f1662a0b3397413256b07096f1b922a1658';assert.equal(await sha256(rawBytes),rawPin);const raw=JSON.parse(new TextDecoder().decode(rawBytes));
const modelRecipe={modelId:'Systran/faster-whisper-tiny.en',modelRevision:'60a1e73109aa75058f81191da437d3fa4ea57f1127bef81d4500e242988ad16d',configSha256:'dcc8d5382c56cf886dd548a687002dd6f1020598880b096b5b3dedb75e5b9ce6'};
const request={packId:row.packId,presentationRevision:row.presentationRevision,language:row.language,edition:row.edition,...row.sourceUnits[0]};
const readPresentation=async d=>new Uint8Array(await readFile(new URL('../../apps/web/public'+d.url,import.meta.url)));
function storage(){const rows=new Map();let queue=Promise.resolve();return {rows,transaction(fn){const work=queue.then(()=>fn({get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v))}));queue=work.catch(()=>{});return work;}};}
function bucket(){const data=new Map();return {data,async get(k){const b=data.get(k);return b?{size:b.length,body:new Response(b).body}:null;},async put(k,b,o){if(o?.onlyIf&&data.has(k))return null;data.set(k,new Uint8Array(b));return {};}};}
async function setup({source=new Uint8Array([1,2,3]),retainedRaw=false,admitted=true,mutateRaw=null,recognitionGate=null,state=storage(),objects=bucket(),counts={fetch:0,recognize:0}}={}){
 const artifacts={dependencySha256:'a'.repeat(64),async read(d){const b=objects.data.get(d.reference);if(!b)throw Error('missing');return Buffer.from(b);},async write(b){const digest=await sha256(b),reference=`preparation/executor/${digest}.json`;await objects.put(reference,b,{onlyIf:{etagDoesNotMatch:'*'}});return {sha256:digest,reference};}};
 const discovery=await createGuideDiscoveryAdapter({metadataBytes,metadataSha256,bucket:objects});
 const acquisition={...createObservedSourceAdapter({bucket:objects,validatePublisherURL:discovery.validatePublisherURL,fetchSource:async()=>{counts.fetch++;return new Response(source,{headers:{'Content-Type':'audio/mpeg'}});}}),dependencySha256:'b'.repeat(64)};
 const recognition={paid:false,dependencySha256:'c'.repeat(64),async run(){counts.recognize++;if(recognitionGate)await recognitionGate;let body;if(retainedRaw)body=rawBytes;else{const synthetic=structuredClone(raw);synthetic.source={sha256:await sha256(source),bytes:source.length};synthetic.executionClass='synthetic-control-fixture';if(mutateRaw)mutateRaw(synthetic);body=encode(synthetic);}return artifacts.write(body);}};
 const options={metadataBytes,metadataSha256,registryBytes,registrySha256,readPresentation,storage:state,bucket:objects,modelRecipe,policyRevision:'guide-executor-composition-test@1',admission:{dependencySha256:'d'.repeat(64),check:()=>admitted},acquisition,recognition,artifacts};
 return {options,counts,state,objects,artifacts,source,create:extra=>createGuideExecutor({...options,...extra})};
}
async function report(f,result){return JSON.parse(new TextDecoder().decode(await f.artifacts.read(result.artifact)));}

test('default missing admission/recognition and paid capability refuse without source work',async()=>{const f=await setup();for(const [extra,reason]of [[{admission:null},'execution-admission-unavailable'],[{recognition:null},'recognition-capability-unavailable'],[{acquisition:null},'acquisition-capability-unavailable'],[{admission:{dependencySha256:'d'.repeat(64),check:async()=>true}},'execution-admission-refused']]){const result=await(await f.create(extra)).request(request);assert.equal(result.reason,reason);assert.equal(result.state,'blocked');}await assert.rejects(f.create({recognition:{...f.options.recognition,paid:true}}),/capability/);assert.deepEqual(f.counts,{fetch:0,recognize:0});});
test('synthetic control fixture composes real acquisition, alignment and review-required acceptance; warm restart does no upstream work',async()=>{const f=await setup(),executor=await f.create(),result=await executor.request(request);assert.equal(result.state,'blocked');assert.equal(result.reason,'review-required');const acceptance=await report(f,result);assert.equal(acceptance.status,'review-required');assert.equal(acceptance.units.length,8);assert.deepEqual(acceptance.acceptedPlaybackRanges,[]);assert.ok(acceptance.reasons.includes('browser-clock-evidence-missing'));assert.deepEqual(f.counts,{fetch:1,recognize:1});const warm=await(await f.create()).request(request);assert.deepEqual(warm.artifact,result.artifact);assert.deepEqual(f.counts,{fetch:1,recognize:1});});
test('actual retained full P2 original and untouched offline recognition compose without a new recognizer invocation',{skip:!process.env.FIA_RETAINED_P2},async()=>{const source=new Uint8Array(await readFile(process.env.FIA_RETAINED_P2));assert.equal(await sha256(source),raw.source.sha256);assert.equal(source.length,raw.source.bytes);const f=await setup({source,retainedRaw:true}),result=await(await f.create()).request(request);assert.equal(result.reason,'review-required');const acceptance=await report(f,result);assert.equal(acceptance.rawRecognitionSha256,rawPin);assert.deepEqual(acceptance.units.map(u=>u.correspondenceStatus),['unmatched','unmatched',...Array(6).fill('exact-candidate')]);assert.equal(acceptance.diagnostics.unassignedRecognizedTokens,64);assert.equal(acceptance.sourceSha256,raw.source.sha256);assert.equal(acceptance.units.length,8);assert.deepEqual(acceptance.acceptedPlaybackRanges,[]);assert.deepEqual(f.counts,{fetch:1,recognize:1});});
test('wrong raw source, byte length or model config cannot reach alignment',async()=>{for(const mutateRaw of [r=>r.source.sha256='f'.repeat(64),r=>r.source.bytes++,r=>r.runtime.numpy='changed']){const f=await setup({mutateRaw}),result=await(await f.create()).request(request);assert.equal(result.state,'uncertain');assert.equal(result.node,'transcribe');assert.equal([...f.state.rows.values()].some(r=>r.identity.node==='align'),false);await(await f.create()).request(request);assert.deepEqual(f.counts,{fetch:1,recognize:1});}});
test('cross-section or changed guide selection refuses before acquisition',async()=>{const f=await setup(),executor=await f.create();for(const delta of [{language:'spa'},{sourceUnitId:'S02-U001'},{presentationRevision:'f'.repeat(64)}])await assert.rejects(executor.request({...request,...delta}));assert.deepEqual(f.counts,{fetch:0,recognize:0});});
test('concurrent requests own one recognizer and interrupted timeout stays uncertain without replay',{timeout:10000},async t=>{let release,entered;const gate=new Promise(r=>release=r),seen=new Promise(r=>entered=r);const f=await setup({recognitionGate:gate});const run=f.options.recognition.run;f.options.recognition.run=async a=>{entered();return run(a);};const executor=await f.create(),first=executor.request(request);await seen;const duplicate=await executor.request(request);assert.equal(duplicate.state,'preparing');release();assert.equal((await first).reason,'review-required');assert.deepEqual(f.counts,{fetch:1,recognize:1});const stalled=await setup({recognitionGate:new Promise(()=>{})});
 // Advance the real executor's deadline only after its recognition port starts.
 // A wall-clock 5ms budget can expire in presentation lookup or acquisition under CI load.
 let recognizeEntered;const recognitionSeen=new Promise(r=>recognizeEntered=r),recognize=stalled.options.recognition.run;
 stalled.options.recognition.run=async args=>{const pending=recognize(args);recognizeEntered();return pending;};
 t.mock.timers.enable({apis:['setTimeout']});
 try{const short=await stalled.create({stepMs:5});let settled=false;const pending=short.request(request).then(value=>{settled=true;return value;});await recognitionSeen;
  assert.deepEqual(stalled.counts,{fetch:1,recognize:1});t.mock.timers.tick(4);await new Promise(r=>setImmediate(r));assert.equal(settled,false);
  t.mock.timers.tick(1);assert.equal((await pending).state,'uncertain');assert.equal((await short.request(request)).state,'uncertain');assert.deepEqual(stalled.counts,{fetch:1,recognize:1});
 }finally{t.mock.timers.reset();}
});
test('captured buffers/functions and warm current admission are enforced; changed dependency pin separates cache',async()=>{const f=await setup(),mb=Buffer.from(metadataBytes),rb=Buffer.from(registryBytes);let eligible=true;const admission={dependencySha256:'d'.repeat(64),check:()=>eligible},pending=f.create({metadataBytes:mb,registryBytes:rb,admission});mb.fill(0);rb.fill(0);const original=f.options.recognition.run;f.options.recognition.run=()=>{throw Error('mutated');};const executor=await pending;assert.equal((await executor.request(request)).reason,'review-required');eligible=false;assert.equal((await executor.request(request)).reason,'execution-admission-refused');assert.deepEqual(f.counts,{fetch:1,recognize:1});f.options.recognition.run=original;const changed=await f.create({recognition:{...f.options.recognition,dependencySha256:'e'.repeat(64)}});assert.notEqual(changed.dependencySha256,executor.dependencySha256);assert.equal((await changed.request(request)).reason,'review-required');assert.deepEqual(f.counts,{fetch:1,recognize:2});});
test('corrupt retained acceptance does not auto-rerun or become ready',async()=>{const f=await setup(),executor=await f.create(),first=await executor.request(request);f.objects.data.set(first.artifact.reference,encode({status:'machine-accepted'}));const next=await executor.request(request);assert.equal(next.state,'unavailable');assert.equal(next.reason,'retained-artifact-invalid');assert.deepEqual(f.counts,{fetch:1,recognize:1});});
test('Buffer artifact aliases are copied before asynchronous hashing and stock adapters see immutable bytes',async()=>{
 const f=await setup();let shared,mutated=false;const read=f.artifacts.read;f.artifacts.read=async d=>{shared=await read(d);return shared;};const executor=await f.create(),digest=crypto.subtle.digest,bound=digest.bind(crypto.subtle);
 crypto.subtle.digest=function(algorithm,data){if(shared?.length>10000&&data.byteLength===shared.length&&!mutated){mutated=true;shared.fill(0);}return bound(algorithm,data);};
 try{assert.equal((await executor.request(request)).reason,'review-required');assert.equal(mutated,true);}finally{crypto.subtle.digest=digest;}
});

async function canonicalInputs(){const result={};for(const[key,path]of Object.entries({ledgerBytes:'server/fia/preparation/executor/p1-canonical-unit-ledger.json',sourcePackBytes:'server/fia/compiler/presentation/source-packs.json.gz',presentationBytes:'server/fia/publication/approved-presentation.json',bundleBytes:'apps/web/public/content/bundle.json'}))result[key]=await readFile(new URL('../../'+path,import.meta.url));return result;}
test('factory executes three P1 disposition sections without dropping provenance or narrating notes/associated pauses',async()=>{
 const fullBytes=await readFile(new URL('../../server/fia/preparation/guide-sources.json',import.meta.url)),full=JSON.parse(fullBytes),pin=await sha256(fullBytes),canonicalP1=await canonicalInputs();
 for(const section of ['S02','S05','S06']){
  const f=await setup(),discovery=await createGuideDiscoveryAdapter({metadataBytes:fullBytes,metadataSha256:pin,bucket:f.objects});
  const acquisition={...createObservedSourceAdapter({bucket:f.objects,validatePublisherURL:discovery.validatePublisherURL,fetchSource:async()=>new Response(f.source,{headers:{'Content-Type':'audio/mpeg'}})}),dependencySha256:'b'.repeat(64)};
  const r=full.rows.find(r=>r.packId==='eng.MRK-1-1-13'&&r.stepId===section),executor=await f.create({metadataBytes:fullBytes,metadataSha256:pin,canonicalP1,presentationAliases:[{packId:r.packId,presentationSha256:r.presentationRevision,presentationId:'fia-mark-authentic@1'}],acquisition});
  const request={packId:r.packId,presentationRevision:r.presentationRevision,language:r.language,edition:r.edition,...r.sourceUnits[0]},result=await executor.request(request);
  assert.equal(result.reason,'review-required');const accepted=await report(f,result),d=accepted.canonicalDisposition;
  assert.equal(d.canonicalUnits.length,r.sourceUnits.length);assert.equal(d.excluded.length,section==='S02'?1:section==='S05'?2:3);
  assert.equal(accepted.units.length,r.sourceUnits.length-d.excluded.length);assert(d.excluded.every(x=>!accepted.units.some(u=>u.sourceUnitId===x.sourceUnitId)));
  assert(d.excluded.every(x=>x.reason===(section==='S05'?'nonspoken-production-note':'associated-pause-correspondence-unresolved')));
  const {projectionSha256,...payload}=d;assert.equal(projectionSha256,await sha256(encode(payload)));assert.deepEqual(accepted.acceptedPlaybackRanges,[]);
  const warm=await executor.request(request);assert.deepEqual(warm.artifact,result.artifact);
 }
});
test('canonical factory preserves P2 raw words under explicit synthetic source identity',async()=>{
 const f=await setup(),executor=await f.create({canonicalP1:await canonicalInputs()}),result=await executor.request(request),accepted=await report(f,result);
 assert.equal(result.reason,'review-required');assert.equal(accepted.canonicalDisposition.canonicalUnits.length,8);assert.deepEqual(accepted.canonicalDisposition.excluded,[]);
 assert.deepEqual(accepted.units.map(u=>u.correspondenceStatus),['unmatched','unmatched',...Array(6).fill('exact-candidate')]);
});

test('default composition retains pre-canonical dependency identity and warm nodes',async()=>{
 const f=await setup(),legacyDependency={schema:'fia-guide-executor-composition@1',metadataSha256,registrySha256,presentationAliases:[],modelRecipe,policyRevision:'guide-executor-composition-test@1',recognitionPolicy:'fia-local-raw-recognition@1/validateRecognitionIdentity@1',acceptancePolicy:'review-required-only@1',ports:{admission:'d'.repeat(64),acquisition:'b'.repeat(64),recognition:'c'.repeat(64),artifacts:{read:'a'.repeat(64),write:'a'.repeat(64)}}};
 const expected=await sha256(encode(legacyDependency)),first=await f.create();assert.equal(first.dependencySha256,expected);
 const old=await first.request(request),warm=await(await f.create()).request(request);assert.deepEqual(warm.artifact,old.artifact);assert.deepEqual(f.counts,{fetch:1,recognize:1});
});
test('canonical factory joins actual retained P2 source and untouched raw recognition',{skip:!process.env.FIA_RETAINED_P2},async()=>{
 const source=new Uint8Array(await readFile(process.env.FIA_RETAINED_P2));assert.equal(await sha256(source),raw.source.sha256);assert.equal(source.length,raw.source.bytes);
 const f=await setup({source,retainedRaw:true}),executor=await f.create({canonicalP1:await canonicalInputs()}),result=await executor.request(request),accepted=await report(f,result);
 assert.equal(result.reason,'review-required');assert.equal(accepted.rawRecognitionSha256,rawPin);assert.equal(accepted.sourceSha256,raw.source.sha256);assert.equal(accepted.canonicalDisposition.canonicalUnits.length,8);assert.deepEqual(accepted.canonicalDisposition.excluded,[]);assert.equal(accepted.diagnostics.unassignedRecognizedTokens,64);assert.deepEqual(accepted.units.map(u=>u.correspondenceStatus),['unmatched','unmatched',...Array(6).fill('exact-candidate')]);assert.deepEqual(accepted.acceptedPlaybackRanges,[]);
 const warm=await executor.request(request);assert.deepEqual(warm.artifact,result.artifact);assert.deepEqual(f.counts,{fetch:1,recognize:1});
});

test('typed window recognition retains independent raw traces and unresolved review through factory; warm reuse verifies every window',async()=>{
 const {createWindowGuideRecognition}=await import('../../server/fia/preparation/executor/window-guide-adapter.mjs');
 const f=await setup();let windows=0;
 const recognition=createWindowGuideRecognition({storage:f.state,artifacts:f.artifacts,dependencySha256:'9'.repeat(64),windowSamples:32000,overlapSamples:8000,
  prepare:async()=>({pcmSha256:'1'.repeat(64),decoderSha256:'2'.repeat(64),totalSamples:56000,sampleRate:16000}),
  recognition:{paid:false,dependencySha256:'8'.repeat(64),async run({planIdentity,window}){windows++;return encode({schema:'fia-window-raw-words@1',windowSha256:window.windowSha256,planIdentity,window,runtimeEvidence:{scriptSha256:'3'.repeat(64),modelManifestSha256:modelRecipe.modelRevision,runtimeManifest:{fixture:'synthetic'}},roundingPolicy:'seconds-floor-start-ceil-end@1',originalSegments:[],words:[{word:'overlap',startSample:window.index?1:25000,endSampleExclusive:window.index?1000:26000}]});}}});
 const executor=await f.create({recognition}),result=await executor.request(request);assert.equal(result.reason,'review-required');const review=await report(f,result);assert.equal(review.schema,'fia-window-guide-review@1');assert.equal(review.units.length,8);assert(review.units.every(u=>u.correspondenceStatus==='unmatched'));assert.equal(review.overlapConflicts.length,1);assert.deepEqual(review.acceptedPlaybackRanges,[]);assert.equal(windows,2);
 const warm=await(await f.create({recognition})).request(request);assert.deepEqual(warm.artifact,result.artifact);assert.equal(windows,2);assert.equal(f.counts.fetch,1);
 const aggregate=[...f.objects.data.entries()].map(([reference,b])=>{try{return {reference,body:JSON.parse(new TextDecoder().decode(b))};}catch{return {};}}).find(x=>x.body?.schema==='fia-window-guide-recognition@1');
 assert(aggregate);const {verifyWindowGuideRecognition}=await import('../../server/fia/preparation/executor/window-guide-adapter.mjs');const context={input:{language:'eng',modelRecipe},source:aggregate.body.source,resolveArtifact:f.artifacts.read};
 for(const mutate of [x=>x.source.sha256='0'.repeat(64),x=>x.recognitionInput.modelRecipe.configSha256='0'.repeat(64),x=>x.plan.windows[0].startSample++,x=>x.projection.words[0].word='substitution',x=>x.artifacts.reverse()]){const bad=structuredClone(aggregate.body);mutate(bad);await assert.rejects(verifyWindowGuideRecognition(bad,context));}
 f.objects.data.set(aggregate.body.artifacts[0].reference,encode({tampered:true}));assert.equal((await executor.request(request)).state,'unavailable');assert.equal(windows,2);
});
test('unknown typed recognition marker refuses before any acquisition',async()=>{const f=await setup();await assert.rejects(f.create({recognition:{...f.options.recognition,resultSchema:'pretend-local'}}),/recognition-schema/);assert.deepEqual(f.counts,{fetch:0,recognize:0});});
