import test from 'node:test';import assert from 'node:assert/strict';import{EventEmitter}from'node:events';import{mkdtemp,writeFile,readFile,rm}from'node:fs/promises';import{join}from'node:path';import{tmpdir}from'node:os';
import{createLocalWindowAdapter}from'../../server/fia/preparation/executor/local-window-adapter.mjs';import{planRecognitionWindows}from'../../server/fia/preparation/executor/recognition-window-plan.mjs';import{sha256}from'../../server/fia/preparation/contract.mjs';
async function fixture(t){const dir=await mkdtemp(join(tmpdir(),'fia-window-adapter-'));t.after(()=>rm(dir,{recursive:true,force:true}));const scriptPath=join(dir,'runtime.py');await writeFile(scriptPath,'# immutable fake runtime');const runtimeManifest={python:'3',av:'1',numpy:'1','faster-whisper':'1',ctranslate2:'1'},pcm=Buffer.alloc(16000*4);let calls=0,mutate=()=>{},hold=false,child;
 const options={pythonPath:'/usr/bin/python3',scriptPath,scriptSha256:await sha256(await readFile(scriptPath)),modelDirectory:dir,modelId:'tiny.en',modelManifestSha256:'a'.repeat(64),runtimeManifest,workDirectory:dir,spawnProcess(command,args,settings){calls++;assert.equal(settings.env.HF_HUB_OFFLINE,'1');assert.equal(settings.env.TRANSFORMERS_OFFLINE,'1');assert.equal(settings.shell,false);child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>true;if(!hold)queueMicrotask(async()=>{try{const job=JSON.parse(await readFile(args[args.indexOf('--input')+1]));let raw;if(['decode','decode-spooled'].includes(job.mode)){await writeFile(job.pcmPath,pcm);raw={schema:'fia-local-window-pcm@1',sourceSha256:job.sourceSha256,sourceBytes:job.sourceBytes,pcmSha256:await sha256(pcm),totalSamples:16000,sampleRate:16000,format:'mono-f32le',decoderSha256:job.decoderSha256};}else raw={schema:'fia-window-raw-words@1',windowSha256:job.window.windowSha256,planIdentity:job.planIdentity,window:job.window,runtimeEvidence:{scriptSha256:job.scriptSha256,modelManifestSha256:job.planIdentity.modelSha256,runtimeManifest:job.runtimeManifest},roundingPolicy:'seconds-floor-start-ceil-end@1',originalSegments:[],words:[]};mutate(raw);await writeFile(args[args.indexOf('--output')+1],JSON.stringify(raw));child.emit('close',0);}catch(e){child.emit('error',e);child.emit('close',1);}});return child;}};
 const source={sourcePath:join(dir,'source.mp3'),sourceSha256:'b'.repeat(64),sourceBytes:10};return{options,source,calls:()=>calls,child:()=>child,hold:()=>hold=true,mutate:f=>mutate=f};}
test('local window bridge binds decoder PCM model config and raw identity',async t=>{const f=await fixture(t),adapter=await createLocalWindowAdapter(f.options),decoded=await adapter.decode(f.source);const r=decoded.receipt,plan=await planRecognitionWindows({sourceSha256:r.sourceSha256,pcmSha256:r.pcmSha256,decoderSha256:r.decoderSha256,totalSamples:r.totalSamples,sampleRate:16000,windowSamples:16000,overlapSamples:0,modelSha256:adapter.modelSha256,configSha256:adapter.configSha256});const bytes=await decoded.recognition.run({planIdentity:plan.identity,window:plan.windows[0]});assert.equal(JSON.parse(new TextDecoder().decode(bytes)).windowSha256,plan.windows[0].windowSha256);assert.equal(f.calls(),2);await assert.rejects(decoded.recognition.run({planIdentity:{...plan.identity,pcmSha256:'c'.repeat(64)},window:plan.windows[0]}));assert.equal(f.calls(),2);await decoded.dispose();});
test('decode refuses forged PCM receipt and unsupported language before model use',async t=>{const f=await fixture(t);await assert.rejects(createLocalWindowAdapter({...f.options,language:'spa'}),/language/);f.mutate(r=>r.pcmSha256='c'.repeat(64));await assert.rejects((await createLocalWindowAdapter(f.options)).decode(f.source),/pcm-binding/);});
test('pre-abort and changed script dispatch no child',async t=>{const f=await fixture(t),adapter=await createLocalWindowAdapter(f.options),c=new AbortController();c.abort();await assert.rejects(adapter.decode({...f.source,signal:c.signal}),/cancelled/);await writeFile(f.options.scriptPath,'changed');await assert.rejects(adapter.decode(f.source),/script-pin/);assert.equal(f.calls(),0);});
test('cancel sends kill but does not settle until process closure',async t=>{const f=await fixture(t);f.hold();const adapter=await createLocalWindowAdapter(f.options),c=new AbortController();let settled=false;const result=adapter.decode({...f.source,signal:c.signal}).then(()=>{settled=true;},e=>{settled=true;return e;});while(!f.child())await new Promise(r=>setTimeout(r,1));let killed=0;f.child().kill=()=>{killed++;return true;};c.abort();await new Promise(r=>setTimeout(r,10));assert.equal(killed,1);assert.equal(settled,false);f.child().emit('close',null);assert.match((await result).message,/cancelled/);});

test('typed stream decode waits for producer verification before starting Python',async t=>{const f=await fixture(t),adapter=await createLocalWindowAdapter(f.options),content=Buffer.from('verified source'),sha256Value=await sha256(content),source={sha256:sha256Value,reference:`originals/sha256/${sha256Value}.mp3`,bytes:content.length};let release,opened;const gate=new Promise(r=>release=r),seen=new Promise(r=>opened=r);const pending=adapter.decodeStream({source,openSource:async(descriptor,options)=>{assert.equal(options.maxBytes,2097152);opened();return{...descriptor,stream:new ReadableStream({start(c){c.enqueue(content);c.close();}}),verified:gate};}});await seen;await new Promise(r=>setTimeout(r,10));assert.equal(f.calls(),0);release();const decoded=await pending;assert.equal(decoded.receipt.sourceSha256,source.sha256);assert.equal(f.calls(),1);await decoded.dispose();});
test('typed producer verification refusal never starts a decoder or falls back to source bytes',async t=>{const f=await fixture(t),adapter=await createLocalWindowAdapter(f.options),content=Buffer.from('source'),sha256Value=await sha256(content),source={sha256:sha256Value,reference:`originals/sha256/${sha256Value}.mp3`,bytes:content.length};await assert.rejects(adapter.decodeStream({source,openSource:async descriptor=>({...descriptor,stream:new ReadableStream({start(c){c.enqueue(content);c.close();}}),verified:Promise.reject(Error('revoked'))})}),/revoked/);assert.equal(f.calls(),0);});
