import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createLocalRecognitionAdapter,LOCAL_RECOGNITION_CONFIG,localRecognitionConfigSha256} from '../../server/fia/preparation/executor/local-adapter.mjs';
import {sha256,canonicalJSONString} from '../../server/fia/preparation/contract.mjs';
async function fixture(t){
 const dir=await mkdtemp(join(tmpdir(),'fia-local-adapter-'));t.after(()=>rm(dir,{recursive:true,force:true}));const scriptPath=join(dir,'script.py'),sourcePath=join(dir,'source.mp3');await writeFile(scriptPath,'# fixture script');await writeFile(sourcePath,'source bytes');const scriptSha256=await sha256(await readFile(scriptPath)),files={'model.bin':{sha256:'a'.repeat(64),bytes:10}},modelManifestSha256=await sha256(canonicalJSONString(files));let calls=0,stored=0,mutate=()=>{},badStore=false;
 const options={pythonPath:'/usr/bin/python3',scriptPath,scriptSha256,modelDirectory:dir,modelId:'tiny.en',modelManifestSha256,workDirectory:dir,resolveSource:async()=>({path:sourcePath,sha256:await sha256('source bytes'),bytes:12}),storeArtifact:async bytes=>{stored++;return {sha256:badStore?'b'.repeat(64):await sha256(bytes),reference:'immutable:raw'};},spawnProcess(command,args,settings){calls++;assert.equal(command,'/usr/bin/python3');assert.equal(settings.shell,false);assert.equal(settings.env.HF_HUB_OFFLINE,'1');assert.equal(settings.env.TRANSFORMERS_OFFLINE,'1');const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>{};queueMicrotask(async()=>{try{const job=JSON.parse(await readFile(args[args.indexOf('--input')+1],'utf8'));assert.equal(job.language,'en');const result={schema:'fia-local-raw-recognition@1',status:'candidate',executionClass:'local-offline-development-reference',source:{sha256:job.sourceSha256,bytes:job.sourceBytes},model:{id:job.modelId,manifestSha256:job.modelManifestSha256,files,device:'cpu',computeType:'int8',cpuThreads:4},recognitionConfig:{...LOCAL_RECOGNITION_CONFIG,language:job.language},scriptSha256,durationSeconds:1,segments:[]};mutate(result);await writeFile(args[args.indexOf('--output')+1],JSON.stringify(result));child.emit('close',0);}catch(error){child.emit('error',error);}});return child;}};
 const context={input:{language:'eng',modelRecipe:{modelId:'tiny.en',modelRevision:modelManifestSha256,configSha256:await localRecognitionConfigSha256(scriptSha256)}},nodeOutputs:{acquire:{sha256:'a'.repeat(64),reference:'immutable:source'}}};return {options,context,sourcePath,calls:()=>calls,stored:()=>stored,mutate:fn=>mutate=fn,badStore:()=>badStore=true};
}
test('bridge binds source script model config and raw result before immutable storage',async t=>{const f=await fixture(t),adapter=createLocalRecognitionAdapter(f.options);assert.equal(adapter.paid,false);const output=await adapter.run(f.context);assert.equal(output.status,'candidate');assert.equal(output.executionClass,'local-offline-development-reference');assert.equal(f.calls(),1);assert.equal(f.stored(),1);});
test('wrong source bytes and model configuration refuse before spawning',async t=>{const f=await fixture(t),adapter=createLocalRecognitionAdapter(f.options);await assert.rejects(adapter.run({...f.context,input:{...f.context.input,modelRecipe:{...f.context.input.modelRecipe,configSha256:'c'.repeat(64)}}}),/recipe/);await writeFile(f.sourcePath,'wrong bytes!');await assert.rejects(adapter.run(f.context),/source-hash/);assert.equal(f.calls(),0);});
test('tiny English model cannot claim Spanish recognition',async t=>{const f=await fixture(t);assert.throws(()=>createLocalRecognitionAdapter({...f.options,supportedLanguages:['eng','spa']}),/language/);await assert.rejects(createLocalRecognitionAdapter(f.options).run({...f.context,input:{...f.context.input,language:'spa'}}),/language/);assert.equal(f.calls(),0);});
test('mismatched candidate binding and recognition settings never store artifacts',async t=>{for(const change of [r=>r.source.sha256='c'.repeat(64),r=>r.status='accepted',r=>r.model.manifestSha256='c'.repeat(64),r=>r.recognitionConfig.hotwords='script prompt',r=>r.recognitionConfig.language='es',r=>r.model.files['model.bin'].bytes++]){const f=await fixture(t);f.mutate(change);await assert.rejects(createLocalRecognitionAdapter(f.options).run(f.context));assert.equal(f.stored(),0);}});
test('immutable artifact store cannot substitute another digest',async t=>{const f=await fixture(t);f.badStore();await assert.rejects(createLocalRecognitionAdapter(f.options).run(f.context),/store-mismatch/);});
test('nonzero process completion fails without parsing or storing output',async t=>{const f=await fixture(t);f.options.spawnProcess=()=>{const child=new EventEmitter();child.stdout=new EventEmitter();child.stderr=new EventEmitter();child.kill=()=>{};queueMicrotask(()=>child.emit('close',1));return child;};await assert.rejects(createLocalRecognitionAdapter(f.options).run(f.context),/failed/);assert.equal(f.stored(),0);});
