import test from 'node:test';import assert from 'node:assert/strict';
import {createObservedStreamAcquisition} from '../../server/fia/preparation/executor/observed-stream-acquisition.mjs';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));
async function fixture({length=4,body=new Uint8Array([1,2,3,4]),gate=null,stall=false}={}){
 const data=new Map(),state=new Map();let queue=Promise.resolve(),gets=0,eligible=true;
 const storage={get:async k=>structuredClone(state.get(k)),transaction(fn){const run=queue.then(()=>fn({get:async k=>structuredClone(state.get(k)),put:async(k,v)=>state.set(k,structuredClone(v))}));queue=run.catch(()=>{});return run;}};
 const bucket={get:async k=>data.has(k)?{size:data.get(k).length,body:new Response(data.get(k)).body}:null,put:async(k,b,o)=>{if(o?.onlyIf&&data.has(k))return null;data.set(k,b instanceof Uint8Array?new Uint8Array(b):new Uint8Array(await new Response(b).arrayBuffer()));return {};}};
 const input={book:'MRK',language:'eng',edition:'fia-guide',passage:'1:1-13',resource:'S01',source:{publisherId:'fia-guide',resourceId:'fixture',version:'snapshot'}},discovery={schema:'fia-source-discovery@1',metadataSha256:'a'.repeat(64),source:{...input.source,url:'https://s3.amazonaws.com/cbbt-er.public/pericopes/fixture.mp3'},selection:Object.fromEntries(['book','language','edition','passage','resource'].map(k=>[k,input[k]]))};
 const bytes=encode(discovery),digest=await sha256(bytes),descriptor={sha256:digest,reference:`preparation/discovery/${digest}.json`};data.set(descriptor.reference,bytes);
 const options={storage,bucket,policy:{revision:'fixture@1',maxBytes:8388608,totalMs:500,progressMs:30},eligibility:()=>eligible,validatePublisherURL:async u=>u===discovery.source.url,makeStream:()=>new TransformStream(),fetchSource:async()=>{gets++;if(gate)await gate;const headers={'content-type':'audio/mpeg'};if(length!==null)headers['content-length']=String(length);return new Response(stall?new ReadableStream({pull:()=>new Promise(()=>{})}):body,{headers});}};
 return {data,state,options,args:{input,nodeOutputs:{discover:descriptor}},counts:()=>gets,revoke:()=>eligible=false,create:()=>createObservedStreamAcquisition(options)};
}
test('unknown hash acquisition returns immutable actual identity; warm verification zero GET',async()=>{const f=await fixture(),a=await f.create(),r=await a.run(f.args);assert.equal(r.sha256,await sha256(new Uint8Array([1,2,3,4])));assert.equal(r.reference,`originals/sha256/${r.sha256}.mp3`);assert.deepEqual(await(await f.create()).run(f.args),r);assert.equal(f.counts(),1);f.data.set(r.reference,new Uint8Array([9]));await assert.rejects(a.run(f.args));assert.equal(f.counts(),1);});
for(const[name,options]of Object.entries({missingLength:{length:null},overCap:{length:8388609},truncated:{length:5},excess:{length:3},stalled:{stall:true}}))test(name+' refuses and never retries uncertain attempt',async()=>{const f=await fixture(options),a=await f.create();await assert.rejects(a.run(f.args));await assert.rejects(a.run(f.args));assert.equal(f.counts(),1);});
test('concurrent claim performs one GET and late revocation prevents publication',async()=>{let release;const gate=new Promise(r=>release=r),f=await fixture({gate}),a=await f.create(),first=a.run(f.args);while(!f.counts())await new Promise(r=>setTimeout(r,1));await assert.rejects(a.run(f.args),/preparing/);f.revoke();release();await assert.rejects(first);assert.equal(f.counts(),1);assert(![...f.state.keys()].some(k=>k.startsWith('fresh-head:')));});
test('warm read revocation refuses without fetching',async()=>{const f=await fixture(),a=await f.create();await a.run(f.args);f.revoke();await assert.rejects(a.run(f.args),/ineligible/);assert.equal(f.counts(),1);});
