import test from 'node:test';import assert from 'node:assert/strict';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
import {createObservedSourceAdapter} from '../../server/fia/preparation/executor/observed-source.mjs';
async function fixture(change=()=>{}){
 const input={book:'MRK',language:'eng',edition:'publisher',passage:'1:14-20',resource:'S01',source:{publisherId:'publisher',resourceId:'p2s1',version:'v2'}},discovery={schema:'fia-source-discovery@1',source:{...input.source,url:'https://s3.amazonaws.com/cbbt-er.public/pericopes/eng/mrk/p2/s1/v2/vbr0.mp3'},selection:Object.fromEntries(['book','language','edition','passage','resource'].map(key=>[key,input[key]])),metadataSha256:'a'.repeat(64)};change(discovery);
 const raw=new TextEncoder().encode(canonicalJSONString(discovery)),digest=await sha256(raw),reference=`preparation/discovery/${digest}.json`,data=new Map([[reference,raw]]),writes=[];let calls=0,failAfterReceipt=false;
 const bucket={data,writes,get:async key=>data.has(key)?{body:new Response(data.get(key)).body}:null,async put(key,bytes,options){assert.deepEqual(options.onlyIf,{etagDoesNotMatch:'*'});writes.push(key);if(!data.has(key))data.set(key,bytes.slice());if(failAfterReceipt&&key.startsWith('originals/acquisitions/'))throw Error('connection-lost-after-write');}};
 const bytes=new TextEncoder().encode('original bytes'),context={input,nodeOutputs:{discover:{sha256:digest,reference}}};const options={bucket,validatePublisherURL:()=>true,fetchSource:async(url,options)=>{calls++;assert.equal(url,discovery.source.url);assert.equal(options.redirect,'manual');assert(options.signal instanceof AbortSignal);return new Response(bytes,{headers:{'Content-Type':'audio/mpeg'}});}};
 return {bucket,bytes,context,options,calls:()=>calls,receipt:`originals/acquisitions/${digest}.json`,failAfterReceipt:()=>failAfterReceipt=true};
}
test('unknown source hash observed once and immutable warm reuse avoids upstream',async()=>{const f=await fixture(),adapter=createObservedSourceAdapter(f.options),first=await adapter.run(f.context);assert.equal(first.sha256,await sha256(f.bytes));assert.equal(first.reference,`originals/sha256/${first.sha256}.mp3`);f.options.fetchSource=()=>{throw Error('offline');};assert.deepEqual(await createObservedSourceAdapter(f.options).run(f.context),first);assert.equal(f.calls(),1);});
test('late receipt write can be reconciled by retained verification without repeat fetch',async()=>{const f=await fixture();f.failAfterReceipt();await assert.rejects(createObservedSourceAdapter(f.options).run(f.context),/lost-after/);const result=await createObservedSourceAdapter({...f.options,fetchSource:()=>{throw Error('must not fetch');}}).run(f.context);assert.equal(result.sha256,await sha256(f.bytes));assert.equal(f.calls(),1);});
test('corrupt retained bytes or receipt never overwrite or refetch',async()=>{for(const target of ['source','receipt']){const f=await fixture(),adapter=createObservedSourceAdapter(f.options),result=await adapter.run(f.context);f.bucket.data.set(target==='source'?result.reference:f.receipt,new TextEncoder().encode('{}'));const writes=f.bucket.writes.length;await assert.rejects(adapter.run(f.context));assert.equal(f.calls(),1);assert.equal(f.bucket.writes.length,writes);}});
test('cross consumer discovery untrusted URL and malformed metadata refuse before fetch',async()=>{for(const change of [d=>d.selection.language='spa',d=>d.source.version='v3',d=>d.metadataSha256='bad',d=>d.source.url='https://other.example/file',d=>d.source.url+='?download=1',d=>d.source.url='https://s3.amazonaws.com/other-bucket/file']){const f=await fixture(change);await assert.rejects(createObservedSourceAdapter(f.options).run(f.context));assert.equal(f.calls(),0);}});
test('publisher policy must explicitly return true and discovery body must hash match',async()=>{const f=await fixture();await assert.rejects(createObservedSourceAdapter({...f.options,validatePublisherURL:()=>({})}).run(f.context));f.bucket.data.set(f.context.nodeOutputs.discover.reference,new TextEncoder().encode('{}'));await assert.rejects(createObservedSourceAdapter(f.options).run(f.context));assert.equal(f.calls(),0);});
test('redirects wrong MIME empty and oversized source reject without publication',async()=>{for(const response of [new Response(null,{status:302}),new Response('wrong',{headers:{'Content-Type':'text/html'}}),new Response(new Uint8Array(),{headers:{'Content-Type':'audio/mpeg'}}),new Response(new Uint8Array(2097153),{headers:{'Content-Type':'audio/mpeg'}})]){const f=await fixture();await assert.rejects(createObservedSourceAdapter({...f.options,fetchSource:async()=>response}).run(f.context));assert.equal(f.bucket.writes.length,0);}});
test('competing acquisition receipt cannot be overwritten and conflicting winner fails',async()=>{const f=await fixture(),put=f.bucket.put.bind(f.bucket);f.bucket.put=async(key,bytes,options)=>{if(key===f.receipt){const receipt=JSON.parse(new TextDecoder().decode(bytes));receipt.sourceSha256='b'.repeat(64);receipt.sourceKey=`originals/sha256/${receipt.sourceSha256}.mp3`;f.bucket.data.set(key,new TextEncoder().encode(canonicalJSONString(receipt)));}return put(key,bytes,options);};await assert.rejects(createObservedSourceAdapter(f.options).run(f.context));assert.equal(JSON.parse(new TextDecoder().decode(f.bucket.data.get(f.receipt))).sourceSha256,'b'.repeat(64));assert.equal(f.calls(),1);});
test('arbitrary discovery key cannot select another bucket object',async()=>{const f=await fixture();f.context.nodeOutputs.discover.reference='arbitrary/key';await assert.rejects(createObservedSourceAdapter(f.options).run(f.context),/reference/);assert.equal(f.calls(),0);});
