import test from 'node:test';import assert from 'node:assert/strict';
import {sha256} from '../../server/fia/preparation/contract.mjs';
import {assessUnitQualityEvidence} from '../../server/fia/preparation/executor/quality-evidence.mjs';
const H=n=>String(n).repeat(64);
function data(){
 const row={activityId:'u',sourceUnitId:'u',sourceTextSha256:H(4),status:'exact-candidate',wordSpan:{first:0,lastExclusive:1},candidateRange:{startSeconds:1,endSeconds:2}};
 const edge=(start,end)=>{const q={startSample:start,endSampleExclusive:end,startSeconds:start/16000,endSeconds:end/16000,maximum10msDbfs:-60};return {state:'measured',quietRuns:[q],selectedQuietRun:q,cutSample:(start+end)/2,cutSeconds:(start+end)/32000,leftMarginSeconds:(end-start)/32000,rightMarginSeconds:(end-start)/32000,centered60msDbfs:-60,searchInterval:{startSeconds:start/16000,endSeconds:end/16000}};};
 const u={...row,state:'measured',envelope:{startSeconds:1,endSeconds:2},left:edge(8000,12000),right:edge(36000,40000)};
 const a={schema:'fia-exact-word-alignment@1',status:'candidate',sourceSha256:H(1),rawRecognitionSha256:H(2),scriptSha256:H(3),mappings:[row,{...row,activityId:'v',sourceUnitId:'v',status:'unmatched'}]};
 const s={schema:'fia-signal-boundary-measurements@1',status:'candidate',sourceSha256:H(1),rawRecognitionSha256:H(2),guideScriptSha256:H(3),scriptSha256:H(5),pcm:{sampleRate:16000,samples:48000,sha256:H(6)},policy:{windowSamples:160,minimumQuietSamples:960,thresholdDbfsExclusive:-45,selection:'single-qualifying-run-only-midpoint'},sourceMetadata:{sampleRate:48000,channels:1,codec:'mp3float'},runtime:{av:'19.0.1'},units:[u,{activityId:'v',sourceUnitId:'v',sourceTextSha256:H(4),state:'blocked',reason:'no-unique-exact-mapping'}]};
 const b={schema:'fia-browser-clock-measurement@1',status:'measurement-complete-not-acceptance',sourceSha256:H(1),nativeClockMappingQualified:false,userAgent:'test',platform:'test',nativeDuration:3,nativeMinusDecodedDuration:0,pcm:{sampleRate:16000,samples:48000,duration:3,sha256:H(7)},clockLandmarks:[],cuts:['left','right'].map(edge=>({activityId:'u',edge,cutSeconds:u[edge].cutSeconds,sourceQuietRun:u[edge].selectedQuietRun,centered60msDbfs:-60})),trials:[1,1.5].flatMap(rate=>[1,2,3].map(repeat=>({activityId:'u',rate,repeat,start:.625,end:2.375,seekError:0,stopTime:2.38,overshoot:.005,visibility:'visible',visibilityChanged:false})))};
 return {a,s,b};
}
async function run(d,{signal=true,browser=true,tamper=false}={}){const blobs=new Map();async function put(o){const bytes=new TextEncoder().encode(JSON.stringify(o)),h=await sha256(bytes);blobs.set(h,bytes);return {sha256:h,reference:h};}const alignment=await put(d.a);d.s.alignmentSha256=alignment.sha256;const sd=await put(d.s);d.b.measurementSha256=sd.sha256;const bd=await put(d.b);if(tamper)blobs.set(sd.sha256,new TextEncoder().encode('{}'));return assessUnitQualityEvidence({alignment,signal:signal?sd:null,browser:browser?bd:null,sourceSha256:H(1),rawRecognitionSha256:H(2),guideScriptSha256:H(3),resolveArtifact:async d=>blobs.get(d.sha256)});}
test('reports measured unit separately while never accepting clock/confidence/ranges',async()=>{const r=await run(data());assert.equal(r.units[0].signal,'measured');assert.equal(r.units[0].browser,'measured-unqualified');assert.equal(r.units[1].signal,'blocked');assert.equal(r.units[0].recognition,'uncalibrated');assert.equal(r.units[0].nativeClock,'unqualified');assert.deepEqual(r.acceptedPlaybackRanges,[]);assert.equal(r.evidence.measurementProgramSha256,H(5));});
test('missing evidence is distinct from invalid evidence',async()=>{assert.equal((await run(data(),{signal:false,browser:false})).units[0].signal,'missing');assert.match((await run(data(),{tamper:true})).units[0].reasons.join(),/hash/);});
for(const [name,mutate] of Object.entries({wrongGuide:d=>d.s.guideScriptSha256=H(5),wrongRaw:d=>d.s.rawRecognitionSha256=H(9),wrongSource:d=>d.s.sourceSha256=H(9),wrongMargin:d=>d.s.units[0].left.leftMarginSeconds=99,wrongEnvelope:d=>d.s.units[0].envelope.startSeconds=.9,duplicateRun:d=>d.s.units[0].left.quietRuns.push(d.s.units[0].left.selectedQuietRun),wrongPolicy:d=>d.s.policy.thresholdDbfsExclusive=0})){test(name,async()=>{const d=data();mutate(d);const r=await run(d);assert.notEqual(r.units[0].signal,'measured');assert.deepEqual(r.acceptedPlaybackRanges,[]);});}
for(const [name,mutate] of Object.entries({fakeQualification:d=>d.b.nativeClockMappingQualified=true,wrongProfile:d=>d.b.pcm.samples++,duplicateTrial:d=>d.b.trials[1]={...d.b.trials[0]},wrongTrialUnit:d=>d.b.trials[0].activityId='unknown',wrongStop:d=>d.b.trials[0].overshoot=10,nonfiniteTrial:d=>d.b.trials[0].seekError=Infinity})){test(name,async()=>{const d=data();mutate(d);const r=await run(d);assert.equal(r.units[0].signal,'measured');assert.notEqual(r.units[0].browser,'measured-unqualified');assert.deepEqual(r.acceptedPlaybackRanges,[]);});}
