import test from 'node:test';import assert from 'node:assert/strict';
import {planRecognitionWindows as plan,projectRecognitionWindows as project} from '../../server/fia/preparation/executor/recognition-window-plan.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
const request={sourceSha256:'a'.repeat(64),pcmSha256:'b'.repeat(64),decoderSha256:'c'.repeat(64),modelSha256:'d'.repeat(64),configSha256:'e'.repeat(64),totalSamples:40000,sampleRate:16000,windowSamples:24000,overlapSamples:4000};
async function record(w,words=[]){const rawBytes=Buffer.from(JSON.stringify({schema:'fia-window-raw-words@1',windowSha256:w.windowSha256,words}));return {windowSha256:w.windowSha256,state:'completed',rawBytes,rawSha256:await sha256(rawBytes)};}
test('deterministic restart identities and bounded final window',async()=>{const p=await plan(request);assert.deepEqual(p,await plan(request));assert.deepEqual(p.windows.map(w=>[w.startSample,w.endSampleExclusive]),[[0,24000],[20000,40000]]);for(const k of ['sourceSha256','pcmSha256','decoderSha256','modelSha256','configSha256'])assert.notEqual((await plan({...request,[k]:'f'.repeat(64)})).windows[0].windowSha256,p.windows[0].windowSha256);});
test('sample offsets preserve raw words and final boundary',async()=>{const p=await plan({...request,overlapSamples:0}),r=await project(p,[await record(p.windows[0],[{word:' Hello!',startSample:0,endSampleExclusive:24000}]),await record(p.windows[1],[{word:'end',startSample:15000,endSampleExclusive:16000}])]);assert.equal(r.status,'projected');assert.equal(r.words[1].endSampleExclusive,40000);assert.equal(r.words[1].trace.localEndSampleExclusive,16000);assert.equal(r.words[0].word,' Hello!');assert.equal(r.qualifiedForPlayback,false);});
test('repeated words in overlap never silently disappear',async()=>{const p=await plan(request),r=await project(p,[await record(p.windows[0],[{word:'go',startSample:21000,endSampleExclusive:22000}]),await record(p.windows[1],[{word:'go',startSample:1000,endSampleExclusive:2000}])]);assert.equal(r.status,'overlap-unresolved');assert.equal(r.words.length,2);assert.equal(r.overlapConflicts[0].traces.length,2);});
test('missing and uncertain are distinct and never replayed',async()=>{const p=await plan(request),r=await project(p,[{windowSha256:p.windows[0].windowSha256,state:'uncertain'}]);assert.deepEqual(r.windows.map(w=>w.state),['uncertain','missing']);assert.equal(r.status,'incomplete');assert.equal(r.automaticReplay,false);});
test('out-of-order records projected in clock order; completed means reuse only',async()=>{const p=await plan({...request,overlapSamples:0}),r=await project(p,[await record(p.windows[1],[{word:'b',startSample:0,endSampleExclusive:1}]),await record(p.windows[0],[{word:'a',startSample:0,endSampleExclusive:1}])]);assert.deepEqual(r.words.map(w=>w.word),['a','b']);assert(r.windows.every(w=>w.dispatch==='reuse-retained-only'));});
test('plan tamper, duplicate records, wrong raw identity/hash refused',async()=>{const p=await plan(request),r=await record(p.windows[0]);await assert.rejects(project({...p,windows:[]},[]),/plan-binding/);await assert.rejects(project(p,[r,r]),/record-binding/);await assert.rejects(project(p,[{...r,rawSha256:'f'.repeat(64)}]),/raw-hash/);const wrong=await record({...p.windows[0],windowSha256:'f'.repeat(64)});await assert.rejects(project(p,[{...wrong,windowSha256:r.windowSha256}]),/raw-binding/);});
test('invalid and nonmonotonic clocks refused',async()=>{const p=await plan(request);for(const words of [[{word:'x',startSample:-1,endSampleExclusive:1}],[{word:'x',startSample:0,endSampleExclusive:24001}],[{word:'x',startSample:5,endSampleExclusive:8},{word:'y',startSample:4,endSampleExclusive:9}]])await assert.rejects(project(p,[await record(p.windows[0],words)]),/word-clock/);});
test('bounded policy refuses excessive overlap, duration and windows',async()=>{for(const delta of [{overlapSamples:12000},{totalSamples:16000*86400+1},{windowSamples:16000,totalSamples:16000*2000},{sampleRate:44100}])await assert.rejects(plan({...request,...delta}));});
test('caller Buffer mutation after call cannot change raw projection',async()=>{const p=await plan(request),r=await record(p.windows[0],[{word:'safe',startSample:0,endSampleExclusive:1}]),pending=project(p,[r]);r.rawBytes.fill(0);p.windows.length=0;const result=await pending;assert.equal(result.words[0].word,'safe');});
