import test from 'node:test';import assert from 'node:assert/strict';import {createWindowRecognitionExecutor}from'../../server/fia/preparation/executor/recognition-window-executor.mjs';import{planRecognitionWindows}from'../../server/fia/preparation/executor/recognition-window-plan.mjs';import{sha256}from'../../server/fia/preparation/contract.mjs';
const encode=x=>new TextEncoder().encode(JSON.stringify(x));
async function fixture({count=1,stepMs=1000,run=null}={}){const data=new Map(),objects=new Map();let chain=Promise.resolve(),calls=0;const storage={transaction(fn){const result=chain.then(()=>fn({get:async k=>structuredClone(data.get(k)),put:async(k,v)=>data.set(k,structuredClone(v))}));chain=result.catch(()=>{});return result;}},artifacts={async write(bytes){const copy=new Uint8Array(bytes),digest=await sha256(copy);objects.set(digest,copy);return{sha256:digest,reference:'raw/'+digest};},async read(d){return objects.get(d.sha256);}},plan=await planRecognitionWindows({sourceSha256:'a'.repeat(64),pcmSha256:'b'.repeat(64),decoderSha256:'c'.repeat(64),modelSha256:'d'.repeat(64),configSha256:'e'.repeat(64),totalSamples:count*16000,sampleRate:16000,windowSamples:16000,overlapSamples:0});
 const raw=({planIdentity,window})=>encode({schema:'fia-window-raw-words@1',windowSha256:window.windowSha256,planIdentity,window,runtimeEvidence:{scriptSha256:'f'.repeat(64),modelManifestSha256:planIdentity.modelSha256,runtimeManifest:{python:'test'}},roundingPolicy:'seconds-floor-start-ceil-end@1',originalSegments:[{text:'word',avg_logprob:-.2}],words:[{word:'word',startSample:0,endSampleExclusive:100}]});const recognition={paid:false,dependencySha256:'1'.repeat(64),async run(args){calls++;assert(args.signal instanceof AbortSignal);return run?run(args,raw):raw(args);}},options={storage,artifacts,recognition,maxWindows:3,stepMs};return{plan,data,objects,options,calls:()=>calls,raw,create:()=>createWindowRecognitionExecutor(options)};}
test('window execution retains exact raw and warm verified projection without repeated calls',async()=>{const f=await fixture({count:2}),first=await f.create().request({plan:f.plan});assert.equal(first.state,'completed');assert.equal(first.projection.words.length,2);assert.equal(f.calls(),2);const warm=await f.create().request({plan:f.plan});assert.deepEqual(warm,first);assert.equal(f.calls(),2);assert.equal(first.qualifiedForPlayback,false);});
test('simultaneous requests share one durable attempt and do not label live owner crashed',async()=>{let enter,release;const seen=new Promise(r=>enter=r),gate=new Promise(r=>release=r),f=await fixture({run:async(a,raw)=>{enter();await gate;return raw(a);}}),executor=f.create();const first=executor.request({plan:f.plan});await seen;assert.equal((await executor.request({plan:f.plan})).state,'preparing');assert.equal(f.calls(),1);release();assert.equal((await first).state,'completed');});
test('explicit recovery fences late completion and no automatic restart replay',async()=>{let enter,release;const seen=new Promise(r=>enter=r),gate=new Promise(r=>release=r),f=await fixture({run:async(a,raw)=>{enter();await gate;return raw(a);}}),first=f.create().request({plan:f.plan});await seen;assert.equal((await f.create().recoverInterrupted({plan:f.plan})).interrupted,1);release();assert.equal((await first).state,'uncertain');assert.equal((await f.create().request({plan:f.plan})).state,'uncertain');assert.equal(f.calls(),1);assert.equal(f.objects.size,0);});
test('timeout aborts signal and persists uncertainty even if late adapter later resolves',async()=>{let signal,release;const gate=new Promise(r=>release=r),f=await fixture({stepMs:10,run:async(a,raw)=>{signal=a.signal;await gate;return raw(a);}});assert.equal((await f.create().request({plan:f.plan})).state,'uncertain');assert.equal(signal.aborted,true);release();await new Promise(r=>setTimeout(r,5));assert.equal((await f.create().request({plan:f.plan})).state,'uncertain');assert.equal(f.calls(),1);});
test('budget and paid capability refuse before dispatch',async()=>{const f=await fixture({count:2});assert.equal((await createWindowRecognitionExecutor({...f.options,maxWindows:1}).request({plan:f.plan})).state,'blocked');assert.equal(f.calls(),0);assert.throws(()=>createWindowRecognitionExecutor({...f.options,recognition:{...f.options.recognition,paid:true}}));});
test('corrupt retained output fails unavailable without re-recognition',async()=>{const f=await fixture();await f.create().request({plan:f.plan});for(const key of f.objects.keys())f.objects.set(key,encode({}));assert.equal((await f.create().request({plan:f.plan})).state,'unavailable');assert.equal(f.calls(),1);});
test('invalid source/model/window identity and zero-duration words remain uncertain',async()=>{for(const change of [x=>x.planIdentity.sourceSha256='0'.repeat(64),x=>x.runtimeEvidence.modelManifestSha256='0'.repeat(64),x=>x.window.endSampleExclusive++,x=>x.words[0].endSampleExclusive=0]){const f=await fixture({run:async(a,raw)=>{const x=JSON.parse(new TextDecoder().decode(raw(a)));change(x);return encode(x);}});assert.equal((await f.create().request({plan:f.plan})).state,'uncertain');assert.equal(f.objects.size,0);}});
test('request and raw buffers are copied across awaits; caller abort before claim does no work',async()=>{const f=await fixture(),plan=structuredClone(f.plan),pending=f.create().request({plan});plan.identity.sourceSha256='0'.repeat(64);assert.equal((await pending).state,'completed');const controller=new AbortController();controller.abort();const other=await fixture();assert.equal((await other.create().request({plan:other.plan,signal:controller.signal})).state,'aborted');assert.equal(other.calls(),0);});

test('abort before final completion transaction prevents evidence adoption',async()=>{const f=await fixture(),controller=new AbortController(),base=f.options.storage.transaction;let transactions=0;f.options.storage.transaction=fn=>{transactions++;if(transactions===3)controller.abort();return base(fn);};const result=await f.create().request({plan:f.plan,signal:controller.signal});assert.equal(result.state,'uncertain');assert.equal(result.artifacts.length,0);assert.equal([...f.data.values()].find(x=>x.schema==='fia-window-attempt@1').state,'uncertain');});
test('tampered budget and wrong written digest cannot authorize reuse or completion',async()=>{const f=await fixture();await f.create().request({plan:f.plan});const key=[...f.data.keys()].find(k=>k.startsWith('window-budget:'));f.data.set(key,{...f.data.get(key),starts:0});await assert.rejects(f.create().request({plan:f.plan}));await assert.rejects(f.create().recoverInterrupted({plan:f.plan}));assert.equal(f.calls(),1);const other=await fixture();other.options.artifacts.write=async()=>({sha256:'0'.repeat(64),reference:'raw/wrong'});assert.equal((await other.create().request({plan:other.plan})).state,'uncertain');});
