import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createPipeline} from '../../server/fia/preparation/executor/pipeline.mjs';
import {createRequestSidecars} from '../../server/fia/preparation/executor/request-sidecars.mjs';
import {sha256} from '../../server/fia/preparation/contract.mjs';
const h=n=>String(n).repeat(64),encode=x=>new TextEncoder().encode(JSON.stringify(x));
async function fixture(){
 const dir=await mkdtemp(join(tmpdir(),'fia-sidecars-'));let db,queue=Promise.resolve(),allowed=true,policy=h(1),delay=null;const counts={};
 const open=()=>{db=new DatabaseSync(join(dir,'state.db'));db.exec('CREATE TABLE IF NOT EXISTS kv (k TEXT PRIMARY KEY,v TEXT NOT NULL)');};open();
 const storage={transaction(fn){const run=queue.then(async()=>{db.exec('BEGIN');try{const result=await fn({get:async k=>{const r=db.prepare('SELECT v FROM kv WHERE k=?').get(k);return r?JSON.parse(r.v):undefined;},put:async(k,v)=>db.prepare('INSERT OR REPLACE INTO kv VALUES (?,?)').run(k,JSON.stringify(v))});db.exec('COMMIT');return result;}catch(e){db.exec('ROLLBACK');throw e;}});queue=run.catch(()=>{});return run;}};
 const artifacts={async write(bytes){const hash=await sha256(bytes);await writeFile(join(dir,hash),bytes);return {reference:hash,sha256:hash};},async read(d){return new Uint8Array(await readFile(join(dir,d.reference)));}};
 const sharedInput={packId:'fixture',book:'MRK',language:'eng',edition:'fixture',passage:'fixture',resource:'S01',scriptSha256:h(2),source:{publisherId:'fixture',resourceId:'fixture',version:'1'},modelRecipe:{modelId:'fixture',modelRevision:'1',configSha256:h(3)},policyRevision:'fixture-v1'};
 const adapters=Object.fromEntries(['discover','acquire','transcribe','align','accept','publish'].map(node=>[node,{paid:false,async run(){counts[node]=(counts[node]??0)+1;if(node==='acquire'&&delay)await delay;return artifacts.write(encode(node==='accept'?{status:'machine-accepted'}:{node}));}}]));
 const pipeline=()=>createPipeline({storage,policyId:'fixture-shared',adapters,verifyArtifact:d=>artifacts.read(d)});
 const make=(overrides={})=>createRequestSidecars({storage,artifacts,resolve:async request=>({consumer:{id:request.id},sharedRequest:sharedInput,dependencies:{source:h(2),policy},capability:'fixture-resource',contractSha256:h(4)}),shared:{request:r=>pipeline().run(r)},eligible:()=>allowed,project:async({preparation})=>preparation.state==='ready'?{outcome:'accept',reason:'fixture-verified',capability:'fixture-resource',evidence:[preparation.artifact],result:{artifact:preparation.artifact}}:null,validate:async value=>{for(const d of value.decision.evidence)if(await sha256(await artifacts.read(d))!==d.sha256)return false;return true;},...overrides});
 return {dir,counts,make,artifacts,setAllowed:v=>allowed=v,setPolicy:v=>policy=v,setDelay:v=>delay=v,reopen:()=>{db.close();open();},close:async()=>{await queue;db.close();await rm(dir,{recursive:true,force:true});}};
}
test('two consumers share existing pipeline, SQLite restart and warm read perform zero preparation',async()=>{const f=await fixture();try{assert.deepEqual(f.counts,{});const a=f.make();const results=await Promise.all([a.request({id:'one'},{subscriberId:'a'}),a.request({id:'two'},{subscriberId:'b'})]);assert.ok(results.some(r=>r.state==='ready'));for(const [id,subscriberId] of [['one','a'],['two','b']])assert.equal((await a.request({id},{subscriberId})).state,'ready');assert.deepEqual(Object.values(f.counts),[1,1,1,1,1,1]);const before={...f.counts};f.reopen();const restored=f.make();assert.equal((await restored.read({id:'one'})).state,'ready');assert.equal((await restored.request({id:'two'},{subscriberId:'b'})).state,'ready');assert.deepEqual(f.counts,before);f.setPolicy(h(9));assert.equal((await restored.read({id:'one'})).state,'missing');assert.equal((await restored.request({id:'one'},{subscriberId:'a'})).state,'ready');assert.deepEqual(f.counts,before);}finally{await f.close();}});
test('detach during shared acquisition does not cancel other consumer or publish detached result',async()=>{const f=await fixture();try{let release;f.setDelay(new Promise(r=>release=r));const a=f.make(),pending=a.request({id:'one'},{subscriberId:'a'});while(!f.counts.acquire)await new Promise(r=>setTimeout(r,1));await a.detach({id:'one'},{subscriberId:'a'});const b=await a.request({id:'two'},{subscriberId:'b'});assert.equal(b.state,'preparing');release();assert.equal((await pending).state,'detached');assert.equal((await a.request({id:'two'},{subscriberId:'b'})).state,'ready');assert.equal(f.counts.acquire,1);assert.equal((await a.read({id:'one'},{subscriberId:'a'})).state,'detached');}finally{await f.close();}});
test('revocation and corrupt retained media refuse warm ready without reacquisition',async()=>{const f=await fixture();try{const a=f.make(),r=await a.request({id:'one'},{subscriberId:'a'}),before={...f.counts};f.setAllowed(false);assert.equal((await a.read({id:'one'})).state,'blocked');f.setAllowed(true);await writeFile(join(f.dir,r.sidecar.decision.evidence[0].reference),'corrupt');await assert.rejects(a.read({id:'one'}),/evidence-refused/);assert.deepEqual(f.counts,before);}finally{await f.close();}});

test('uncertain existing job is not rewritten into ready; invalid decision cannot persist',async()=>{const f=await fixture();try{let calls=0;const a=f.make({shared:{request:async()=>{calls++;return {state:'uncertain',reason:'interrupted'};}}});const r=await a.request({id:'one'},{subscriberId:'a'});assert.equal(r.state,'uncertain');assert.equal(r.automaticReplay,false);assert.equal((await a.read({id:'one'})).state,'missing');const invalid=f.make({project:async()=>({outcome:'accept',reason:'forged',capability:'other',evidence:[],result:{}})});await assert.rejects(invalid.request({id:'two'},{subscriberId:'b'}),/sidecar-invalid/);assert.equal((await invalid.read({id:'two'})).state,'missing');assert.equal(calls,1);}finally{await f.close();}});

test('detach while final eligibility waits fences ready delivery',async()=>{const f=await fixture();try{await f.make().request({id:'one'},{subscriberId:'a'});let checks=0,entered,release;const atFinal=new Promise(r=>entered=r),wait=new Promise(r=>release=r);const a=f.make({eligible:async()=>{if(++checks===4){entered();await wait;}return true;}});const pending=a.read({id:'one'},{subscriberId:'a'});await atFinal;await a.detach({id:'one'},{subscriberId:'a'});release();assert.equal((await pending).state,'detached');}finally{await f.close();}});
