import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readdir,readFile,stat,rm}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{createHash}from'node:crypto';
import{spoolVerifiedSource}from'../../server/fia/preparation/executor/source-stream-spool.mjs';
const digest=b=>createHash('sha256').update(b).digest('hex');
async function fixture(t,n=100000){const directory=await mkdtemp(join(tmpdir(),'spool-test-'));t.after(()=>rm(directory,{recursive:true,force:true}));const data=Buffer.alloc(n,17),sha256=digest(data),source={sha256,bytes:n,reference:`originals/sha256/${sha256}.mp3`};let opens=0;const openSource=()=>{opens++;let position=0;return{...source,verified:Promise.resolve(),stream:new ReadableStream({pull(c){if(position===data.length)return c.close();const end=Math.min(position+65536,data.length);c.enqueue(data.subarray(position,end));position=end;}})}};return{directory,data,source,openSource,opens:()=>opens,args:{source,openSource,workDirectory:directory}};}
test('streams 12.8MB with explicit policy and private file, default refuses before open',async t=>{const f=await fixture(t,12823388);await assert.rejects(spoolVerifiedSource(f.args),/budget/);assert.equal(f.opens(),0);const result=await spoolVerifiedSource({...f.args,maxBytes:16777216});assert.equal(result.bytes,f.data.length);assert.equal(digest(await readFile(result.path)),f.source.sha256);assert.equal((await stat(result.path)).mode&0o777,0o600);assert.equal((await stat(join(result.path,'..'))).mode&0o777,0o700);await result.dispose();await result.dispose();assert.deepEqual(await readdir(f.directory),[]);});
test('truncation, overflow, wrong hash, oversized chunks and reader errors clean files',async t=>{for(const mode of ['short','long','hash','chunk','error']){const f=await fixture(t);let sent=false;const openSource=()=>({...f.source,verified:Promise.resolve(),stream:new ReadableStream({pull(c){if(mode==='error')return c.error(Error('reader'));if(sent)return c.close();sent=true;const size=mode==='short'?12:mode==='chunk'?65537:65536;c.enqueue(Buffer.alloc(size,mode==='hash'?18:17));if(mode==='long'){c.enqueue(Buffer.alloc(65536,17));}else if(mode==='hash')c.enqueue(Buffer.alloc(f.data.length-size,18));}})});await assert.rejects(spoolVerifiedSource({...f.args,openSource}));assert.deepEqual(await readdir(f.directory),[]);}});
test('producer verification must settle successfully before exposure, rejection cleans',async t=>{const f=await fixture(t);let done,entered;const verify=new Promise(r=>done=r),seen=new Promise(r=>entered=r);let returned=false;const pending=spoolVerifiedSource({...f.args,openSource:()=>{const r=f.openSource();r.verified=verify;entered();return r;}}).then(r=>{returned=true;return r;});await seen;await new Promise(r=>setTimeout(r,15));assert.equal(returned,false);done();await(await pending).dispose();await assert.rejects(spoolVerifiedSource({...f.args,openSource:()=>({...f.openSource(),verified:Promise.reject(Error('revoked'))})}),/revoked/);assert.deepEqual(await readdir(f.directory),[]);});
test('stalled read and unending cancel do not defeat total deadline; pending verification rejection is observed',async t=>{const f=await fixture(t);let reject;const verified=new Promise((_,r)=>reject=r);await assert.rejects(spoolVerifiedSource({...f.args,totalMs:20,openSource:()=>({...f.source,verified,stream:new ReadableStream({pull:()=>new Promise(()=>{}),cancel:()=>new Promise(()=>{})})})}),/deadline/);reject(Error('late'));await new Promise(r=>setImmediate(r));assert.deepEqual(await readdir(f.directory),[]);});
test('abort while waiting verification prevents exposure and removes spool',async t=>{const f=await fixture(t),controller=new AbortController();const pending=spoolVerifiedSource({...f.args,signal:controller.signal,openSource:()=>({...f.openSource(),verified:new Promise(()=>{})})});setTimeout(()=>controller.abort(),20);await assert.rejects(pending,/aborted/);assert.deepEqual(await readdir(f.directory),[]);});
test('deadline includes verification and late open results are cancelled without a spool',async t=>{const f=await fixture(t);await assert.rejects(spoolVerifiedSource({...f.args,totalMs:10,openSource:()=>({...f.openSource(),verified:new Promise(()=>{})})}),/deadline/);let finish,cancelled=0;const pending=spoolVerifiedSource({...f.args,totalMs:10,openSource:()=>new Promise(r=>finish=r)});await assert.rejects(pending,/deadline/);finish({...f.source,verified:Promise.reject(Error('late verification')),stream:new ReadableStream({cancel(){cancelled++;}})});await new Promise(r=>setImmediate(r));assert.equal(cancelled,1);assert.deepEqual(await readdir(f.directory),[]);});
test('descriptor captured before asynchronous producer and mismatched producer cancelled',async t=>{const f=await fixture(t);const source={...f.source};const pending=spoolVerifiedSource({...f.args,source});source.sha256='0'.repeat(64);await(await pending).dispose();let cancelled=0;await assert.rejects(spoolVerifiedSource({...f.args,openSource:()=>({...f.source,bytes:1,verified:Promise.resolve(),stream:new ReadableStream({cancel(){cancelled++;}})})}),/producer-binding/);assert.equal(cancelled,1);assert.deepEqual(await readdir(f.directory),[]);});
