import test from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';import{resolve,join}from'node:path';import{readFile,mkdtemp,rm,mkdir,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{createHash}from'node:crypto';import{canonicalJSONString}from'../../server/fia/preparation/contract.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),encode=x=>new TextEncoder().encode(canonicalJSONString(x));
const worker=`import{createUnitDerivativeJobs}from ${JSON.stringify(resolve('server/fia/preparation/executor/unit-derivative-jobs.mjs'))};import{sha256}from ${JSON.stringify(resolve('server/fia/preparation/contract.mjs'))};
export class Job{constructor(ctx,env){this.ctx=ctx;this.env=env;}async fetch(r){const u=new URL(r.url),demand=await r.json();if(u.pathname==='/revoke'){await this.ctx.storage.put('revoked',true);return Response.json({revoked:true});}let admitted=!(await this.ctx.storage.get('revoked'));const increment=async key=>this.ctx.storage.put(key,(await this.ctx.storage.get(key)||0)+1);const read=async d=>{const object=await this.env.R2.get(d.reference);if(!object||object.size>4194304)throw Error('fixture-bound');const reader=object.body.getReader(),chunks=[];let count=0;for(;;){const p=await reader.read();if(p.done)break;count+=p.value.length;if(count>4194304)throw Error('fixture-bound');chunks.push(p.value);}const bytes=new Uint8Array(count);let n=0;for(const c of chunks){bytes.set(c,n);n+=c.length;}return bytes;};
const jobs=createUnitDerivativeJobs({storage:this.ctx.storage,dependencySha256:this.env.DEPENDENCY,stepMs:15000,eligibility:()=>admitted,artifacts:{read,write:async(bytes,{kind})=>{await increment('writes');const digest=await sha256(bytes),reference='unit-derivatives/'+kind+'/'+digest;await this.env.R2.put(reference,bytes,{onlyIf:{etagDoesNotMatch:'*'}});if(u.searchParams.has('revokeAfterWrite'))admitted=false;return{sha256:digest,reference};}},resolveInputs:async d=>{await increment('resolves');const input=JSON.parse(new TextDecoder().decode(await read({reference:'fixture/input.json'})));const load=key=>read({reference:'fixture/'+key});return {sourceUnitId:d.sourceUnitId,pcmBytes:await load('pcm.f32'),correspondenceBytes:await load('correspondence.json'),correspondenceSha256:input.correspondenceSha256,measurementBytes:await load('measurements.json'),measurementSha256:input.measurementSha256,correspondenceInput:{...input.correspondenceInput,canonicalBytes:await load('canonical.json'),records:await Promise.all(input.correspondenceInput.records.map(async record=>({...record,rawBytes:await load(record.rawSha256+'.json')})))}};}});
const result=await jobs[u.pathname==='/read'?'read':u.pathname==='/recover'?'recoverInterrupted':'request'](demand);return Response.json({result,resolves:await this.ctx.storage.get('resolves')||0,writes:await this.ctx.storage.get('writes')||0});}}export default{fetch(r,e){return e.JOBS.get(e.JOBS.idFromName('derivatives')).fetch(r)}};`;

test('real SQLite/R2 one-unit derivative demand persists exact PCM delivery, warm zero work and revoked/tampered refusal',{skip:!process.env.FIA_UNIT_DERIVATIVE_PROOF},async()=>{
 const proof=resolve(process.env.FIA_UNIT_DERIVATIVE_PROOF),require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),dir=await mkdtemp(join(tmpdir(),'fia-unit-node-'));
 const fixture=JSON.parse(await readFile(resolve('tests/preparation-executor/fixtures/window-p3/units.json'))),correspondenceBytes=await readFile(join(proof,'correspondence.json')),measurementBytes=await readFile(join(proof,'measurements.json')),pcmBytes=await readFile(join(proof,'source.f32')),correspondence=JSON.parse(correspondenceBytes),canonicalBytes=encode(fixture.canonical);
 const records=[];for(const artifact of correspondence.rawArtifacts){records.push({state:'completed',windowSha256:artifact.windowSha256,rawSha256:artifact.sha256,rawBytes:await readFile(resolve('tests/preparation-executor/fixtures/window-p3/'+artifact.sha256+'.json'))});}
 const input={correspondenceSha256:sha(correspondenceBytes),measurementSha256:sha(measurementBytes),correspondenceInput:{canonicalSha256:sha(canonicalBytes),plan:correspondence.plan,candidateSpans:fixture.candidateSpans,records:records.map(({rawBytes,...r})=>r)}};
 const unit=correspondence.units.find(u=>u.sourceUnitId==='S01-U006'),alternative=unit.alternatives[0],demand={sourceUnitId:unit.sourceUnitId,sourceTextSha256:unit.sourceTextSha256,pins:{sourceSha256:correspondence.plan.identity.sourceSha256,pcmSha256:correspondence.plan.identity.pcmSha256,canonicalSha256:correspondence.canonicalSha256,correspondenceSha256:input.correspondenceSha256,measurementSha256:input.measurementSha256,planSha256:correspondence.plan.planSha256,windowSha256:alternative.windowSha256,rawSha256:alternative.rawSha256}};
 const dependency=sha(await readFile(resolve('server/fia/preparation/executor/unit-derivative-jobs.mjs'))),bundle=await build({stdin:{contents:worker,resolveDir:resolve('.')},bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false});
 const options={...convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{DEPENDENCY:dependency},durableObjects:{JOBS:{className:'Job',useSQLite:true}},r2Buckets:['R2'],outboundService:()=>{throw Error('No network');}}),resourcePersistencePath:dir};let mf=new Miniflare(options);
 const call=async(path,d=demand)=>{const response=await mf.dispatchFetch('https://fixture.invalid'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});const body=await response.text();assert.equal(response.status,200,body);return JSON.parse(body);};
 try{let bucket=await mf.getR2Bucket('R2');for(const[key,bytes]of[['input.json',encode(input)],['canonical.json',canonicalBytes],['correspondence.json',correspondenceBytes],['measurements.json',measurementBytes],['pcm.f32',pcmBytes],...records.map(r=>[r.rawSha256+'.json',r.rawBytes])])await bucket.put('fixture/'+key,bytes);
  const cold=await call('/request');assert.equal(cold.result.state,'candidate',JSON.stringify(cold));assert.equal(cold.resolves,1);assert.equal(cold.writes,2);assert.equal(cold.result.projection.filter(u=>u.candidate).length,1);assert.equal(cold.result.projection.find(u=>u.candidate).sourceUnitId,'S01-U006');assert.deepEqual(cold.result.acceptedPlaybackRanges,[]);
  const wav=await(await bucket.get(cold.result.wav.reference)).arrayBuffer(),range=cold.result.provenance.sourceSampleRange;assert.equal(sha(new Uint8Array(wav).subarray(58)),sha(pcmBytes.subarray(range.startSample*4,range.endSampleExclusive*4)));
  await mf.dispose();mf=new Miniflare(options);bucket=await mf.getR2Bucket('R2');const warm=await call('/request');assert.deepEqual(warm,cold);
  const changed=structuredClone(demand);changed.pins.measurementSha256='f'.repeat(64);const stale=await call('/read',changed);assert.equal(stale.result.state,'missing');assert.equal(stale.resolves,1);
  const secondUnit=correspondence.units.find(u=>u.sourceUnitId==='S01-U005'),second={...demand,sourceUnitId:secondUnit.sourceUnitId,sourceTextSha256:secondUnit.sourceTextSha256};const refused=await call('/request?revokeAfterWrite',second);assert.equal(refused.result.state,'uncertain');const again=await call('/request',second);assert.equal(again.result.state,'uncertain');assert.equal(again.resolves,2);
  await bucket.put(cold.result.wav.reference,new Uint8Array([1,2,3]));const corrupt=await call('/request');assert.equal(corrupt.result.state,'unavailable');assert.equal(corrupt.resolves,2);assert.equal(corrupt.writes,3);
  await call('/revoke');const revoked=await call('/read');assert.equal(revoked.result.state,'blocked');assert.equal(revoked.resolves,2);
  if(process.env.FIA_WINDOW_PROOF_DIR){await mkdir(process.env.FIA_WINDOW_PROOF_DIR,{recursive:true});await writeFile(join(process.env.FIA_WINDOW_PROOF_DIR,'unit-derivative-storage.json'),JSON.stringify({status:'PASS',demand,dependency,cold,warm,stale,refused,again,corrupt,revoked,modelInvocations:0,scope:'Actual retained P3 PCM, real SQLite/R2, builder and demand node; fixture resolver port, no deployed route'},null,2));}
 }finally{await mf.dispose();await rm(dir,{recursive:true,force:true});}
});
