import test from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';import{resolve,join}from'node:path';import{readFile,mkdtemp,rm,mkdir,writeFile}from'node:fs/promises';import{createReadStream}from'node:fs';import{tmpdir}from'node:os';import{createHash}from'node:crypto';import{createLocalWindowAdapter}from'../../server/fia/preparation/executor/local-window-adapter.mjs';import{createBoundedSourceReader}from'../../server/fia/preparation/executor/observed-stream-acquisition.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),root=resolve('.');
const modulePath=name=>JSON.stringify(resolve('server/fia/preparation/executor/'+name+'.mjs'));
const worker=`import{createGuideExecutor}from ${modulePath('guide-executor')};import{createGuideDiscoveryAdapter}from ${modulePath('discovery')};import{createObservedStreamAcquisition}from ${modulePath('observed-stream-acquisition')};import{createVerifiedPcmStore}from ${modulePath('verified-pcm-store')};import{createUnitDerivativePreparation}from ${modulePath('unit-derivative-preparation')};import{planRecognitionWindows,projectRecognitionWindows}from ${modulePath('recognition-window-plan')};import{canonicalJSONString,sha256}from ${JSON.stringify(resolve('server/fia/preparation/contract.mjs'))};
export class Job{constructor(ctx,env){this.ctx=ctx;this.env=env;}async fetch(r){const u=new URL(r.url);if(u.pathname==='/revoke'){await this.ctx.storage.put('revoked',true);return Response.json({revoked:true});}const allowed=!(await this.ctx.storage.get('revoked')),readInput=async path=>new Uint8Array(await(await this.env.INPUT.fetch('https://input.invalid/'+path)).arrayBuffer()),metadataBytes=await readInput('metadata'),registryBytes=await readInput('registry'),metadata=JSON.parse(new TextDecoder().decode(metadataBytes)),row=metadata.rows.find(r=>r.packId==='eng.MRK-1-21-28'&&r.stepId==='S01'),selected=row.sourceUnits.find(x=>x.sourceUnitId===(u.searchParams.get('unit')||'S01-U006')),request={packId:row.packId,presentationRevision:row.presentationRevision,language:row.language,edition:row.edition,...selected},bucket=this.env.R2,metadataSha256=await sha256(metadataBytes),guide=await createGuideDiscoveryAdapter({metadataBytes,metadataSha256,bucket}),resolved=await guide.resolveRequest(request);
const acquire=await createObservedStreamAcquisition({storage:this.ctx.storage,bucket,validatePublisherURL:guide.validatePublisherURL,eligibility:()=>allowed,policy:{revision:'actual-p3-unit-factory@1',maxBytes:2097152,totalMs:30000,progressMs:15000},fetchSource:(url,options)=>this.env.SOURCE.fetch(new Request(url,options))});
const decodeJSON=b=>JSON.parse(new TextDecoder().decode(b)),encode=x=>new TextEncoder().encode(canonicalJSONString(x));
const verifySource=async d=>{const input=resolved.input,discovery={schema:'fia-source-discovery@1',source:{url:row.sourceURL,...input.source},selection:Object.fromEntries(['book','language','edition','passage','resource'].map(k=>[k,input[k]])),metadataSha256},digest=await sha256(encode(discovery)),verified=await acquire.verifySource({input,nodeOutputs:{discover:{sha256:digest,reference:'preparation/discovery/'+digest+'.json'}}});if(verified.sha256!==d.sha256||verified.reference!==d.reference||(d.bytes!==undefined&&verified.bytes!==d.bytes))throw Error('source-join');return verified;};
const readBytes=async(d,max=4194304)=>{const object=await bucket.get(d.reference);if(!object||object.size>max)throw Error('artifact-limit');const reader=object.body.getReader(),parts=[];let size=0;for(;;){const p=await reader.read();if(p.done)break;size+=p.value.length;if(size>max)throw Error('artifact-limit');parts.push(p.value);}const b=new Uint8Array(size);let offset=0;for(const p of parts){b.set(p,offset);offset+=p.length;}return b;};
const artifacts={dependencySha256:'a'.repeat(64),verifySource,read:async d=>{if(d.reference.startsWith('originals/sha256/'))throw Error('source-use-stream');return readBytes(d);},write:async(bytes,{kind='receipt'}={})=>{const digest=await sha256(bytes),reference='preparation/executor/'+digest+(kind==='wav'?'.wav':'.json');await bucket.put(reference,bytes,{onlyIf:{etagDoesNotMatch:'*'}});return{sha256:digest,reference};}};
const rawBytes=[await readInput('raw0'),await readInput('raw1')],raws=rawBytes.map(decodeJSON),pi=raws[0].planIdentity,{policy,...planInput}=pi,plan=await planRecognitionWindows(planInput),recipe={modelId:'Systran/faster-whisper-tiny.en',modelRevision:pi.modelSha256,configSha256:pi.configSha256};
const pcmStore=createVerifiedPcmStore({storage:this.ctx.storage,bucket,dependencySha256:this.env.PCM_POLICY,eligibility:()=>allowed,verifySource,decode:async(req,{signal})=>{const response=await this.env.PCM.fetch('https://local.invalid/decode',{method:'POST',body:JSON.stringify(req),signal});if(!response.ok)throw Error('local-decode');return{receipt:JSON.parse(response.headers.get('X-PCM-Receipt')),stream:response.body,dispose:async()=>{}};}});
const prep=createUnitDerivativePreparation({storage:this.ctx.storage,artifacts,pcmStore,readPCM:(d,{maxBytes})=>readBytes(d,maxBytes),eligibility:()=>allowed,dependencySha256:this.env.UNIT_POLICY});
const executor=await createGuideExecutor({metadataBytes,metadataSha256,registryBytes,registrySha256:await sha256(registryBytes),readPresentation:d=>readInput('public'+d.url),storage:this.ctx.storage,bucket,artifacts,modelRecipe:recipe,policyRevision:'actual-p3-derivative-factory@1',admission:{dependencySha256:'b'.repeat(64),check:()=>allowed},acquisition:acquire,...(u.searchParams.has('baseline')?{}:{unitDerivativePreparation:prep}),recognition:{paid:false,dependencySha256:'c'.repeat(64),resultSchema:'fia-window-guide-recognition@1',run:async({input,nodeOutputs})=>{await this.env.COUNT.fetch('https://count.invalid/recognition');const source=await verifySource(nodeOutputs.acquire),records=raws.map((raw,i)=>({state:'completed',windowSha256:raw.windowSha256,rawSha256:'',rawBytes:rawBytes[i]})),stored=[];for(const record of records){const artifact=await artifacts.write(record.rawBytes);record.rawSha256=artifact.sha256;stored.push({...artifact,windowSha256:record.windowSha256});}return artifacts.write(encode({schema:'fia-window-guide-recognition@1',status:'candidate',recognitionInput:{language:input.language,modelRecipe:input.modelRecipe},source:{sha256:source.sha256,bytes:source.bytes},plan,artifacts:stored,projection:await projectRecognitionWindows(plan,records)}));}}});
const outcome=await executor.request(request);return Response.json(outcome);}}
export default{fetch(r,e){return e.JOBS.get(e.JOBS.idFromName('p3')).fetch(r)}};`;

test('actual requested factory persists verified decoded PCM and derives one unit; cold restart reuses source/model/PCM/derivative',{skip:!process.env.FIA_WINDOW_RAW_PROOF||!process.env.FIA_WINDOW_PYTHON||!process.env.FIA_RETAINED_P3},async()=>{
 const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),dir=await mkdtemp(join(tmpdir(),'fia-unit-factory-')),workDirectory=join(dir,'local');await mkdir(workDirectory);
 const rawDir=resolve(process.env.FIA_WINDOW_RAW_PROOF),proof=JSON.parse(await readFile(join(rawDir,'p3-dispatch-proof.json'))),source=await readFile(process.env.FIA_RETAINED_P3),rawPaths=proof.rawSha256s.map(h=>join(rawDir,h+'.json')),firstRaw=JSON.parse(await readFile(rawPaths[0]));assert.equal(sha(source),firstRaw.planIdentity.sourceSha256);
 const scriptPath=resolve('server/fia/preparation/executor/local-window-runtime.py'),local=await createLocalWindowAdapter({pythonPath:process.env.FIA_WINDOW_PYTHON,scriptPath,scriptSha256:sha(await readFile(scriptPath)),modelDirectory:process.env.FIA_WINDOW_MODEL,modelId:'Systran/faster-whisper-tiny.en',modelManifestSha256:firstRaw.planIdentity.modelSha256,runtimeManifest:JSON.parse(await readFile(process.env.FIA_WINDOW_RUNTIME_MANIFEST)),workDirectory});assert.equal(local.decoderSha256,firstRaw.planIdentity.decoderSha256);
 let mf,bucket;const counts={source:0,recognition:0,decode:0,external:0},bundle=await build({stdin:{contents:worker,resolveDir:root},bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false});
 const options={...convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{PCM_POLICY:sha(await readFile(resolve('server/fia/preparation/executor/verified-pcm-store.mjs'))),UNIT_POLICY:sha(await readFile(resolve('server/fia/preparation/executor/unit-derivative-preparation.mjs')))},durableObjects:{JOBS:{className:'Job',useSQLite:true}},r2Buckets:['R2'],serviceBindings:{INPUT:async r=>{const p=new URL(r.url).pathname.slice(1),path=p==='metadata'?resolve('server/fia/preparation/guide-sources.json'):p==='registry'?resolve('apps/web/public/content/registry.json'):p==='raw0'?rawPaths[0]:p==='raw1'?rawPaths[1]:join(root,'apps/web',p);return new Response(await readFile(path));},SOURCE:()=>{counts.source++;return new Response(source,{headers:{'Content-Type':'audio/mpeg','Content-Length':String(source.length)}});},COUNT:()=>{counts.recognition++;return new Response('counted');},PCM:async r=>{counts.decode++;const request=await r.json(),producer=createBoundedSourceReader({bucket}),decoded=await local.decodeStream({source:request.source,openSource:producer.openSource,signal:r.signal}),iterator=createReadStream(decoded.pcmPath,{highWaterMark:65536})[Symbol.asyncIterator]();const receipt=Object.fromEntries(['sourceSha256','pcmSha256','totalSamples','sampleRate','decoderSha256'].map(k=>[k,decoded.receipt[k]]));return new Response(new ReadableStream({async pull(c){try{const p=await iterator.next();if(p.done){await decoded.dispose();c.close();}else c.enqueue(new Uint8Array(p.value));}catch(e){await decoded.dispose();c.error(e);}},async cancel(){await iterator.return();await decoded.dispose();}}),{headers:{'Content-Length':String(decoded.receipt.totalSamples*4),'X-PCM-Receipt':JSON.stringify(receipt)}});}},outboundService:()=>{counts.external++;throw Error('No external');}}),resourcePersistencePath:join(dir,'storage')};
 const call=async path=>{const r=await mf.dispatchFetch('https://fixture.invalid'+path),b=await r.text();assert.equal(r.status,200,b);return JSON.parse(b);};
 try{mf=new Miniflare(options);bucket=await mf.getR2Bucket('R2');const baseline=await call('/?baseline');assert.equal(baseline.reason,'review-required',JSON.stringify(baseline));assert.deepEqual(counts,{source:1,recognition:1,decode:0,external:0});
  const cold=await call('/');assert.equal(cold.unitDerivative?.state,'candidate',JSON.stringify(cold));assert.equal(cold.unitDerivative.provenance.sourceUnitId,'S01-U006');assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});assert.equal(cold.unitDerivative.wav.sha256,'abe816e6b551dcb5d569b1301315e498f2b624e0f4c05aa5e71051201d8d9113');assert.equal(cold.unitDerivative.projection.filter(u=>u.candidate).length,1);
  await mf.dispose();mf=new Miniflare(options);bucket=await mf.getR2Bucket('R2');const warm=await call('/');assert.deepEqual(warm,cold);assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
  const unresolved=await call('/?unit=S01-U001');assert.equal(unresolved.unitDerivative.state,'blocked');assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
  const next=await call('/?unit=S01-U008');assert.equal(next.unitDerivative.state,'candidate');assert.equal(next.unitDerivative.provenance.sourceUnitId,'S01-U008');assert.equal(next.unitDerivative.wav.sha256,'c4d685909e5860ae37ac5fa89e0cc9919a5726df1a5efa6ebbff77521ea5269d');assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
  await call('/revoke');const revoked=await call('/');assert.equal(revoked.state,'blocked');assert.equal(revoked.reason,'execution-admission-refused');
  if(process.env.FIA_WINDOW_PROOF_DIR){await mkdir(process.env.FIA_WINDOW_PROOF_DIR,{recursive:true});await writeFile(join(process.env.FIA_WINDOW_PROOF_DIR,'unit-factory-storage.json'),JSON.stringify({status:'PASS',counts,modelInvocations:0,baseline,cold,warm,unresolved,next,revoked,scope:'Real acquisition SQLite/R2, retained actual window raw evidence, actual local decoder, streaming PCM retention, recomputed quiet evidence, demand derivative job, factory projection. Optional capability only; no deployed route or playback grant.'},null,2));}
 }finally{await mf?.dispose();await rm(dir,{recursive:true,force:true});}
});
