import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{canonicalJSONString,sha256}from'../../server/fia/preparation/contract.mjs';import{planRecognitionWindows}from'../../server/fia/preparation/executor/recognition-window-plan.mjs';import{correspondWindowUnits}from'../../server/fia/preparation/executor/window-unit-correspondence.mjs';
const encode=x=>new TextEncoder().encode(canonicalJSONString(x));const root=new URL('./fixtures/window-p3/',import.meta.url),fixture=JSON.parse(await readFile(new URL('units.json',root)));const hashes=['65676f6962670f5eea6ae27455189c95c527ed0c668d6911383bfc98f2991c49','a037531cefd5b817e916120ac532a9091e4dd0bfb9196324db577cdd95aabb3c'];
async function inputs(){const records=[];let identity;for(const hash of hashes){const rawBytes=await readFile(new URL(hash+'.json',root));assert.equal(await sha256(rawBytes),hash);const raw=JSON.parse(rawBytes);identity=raw.planIdentity;records.push({state:'completed',windowSha256:raw.windowSha256,rawSha256:hash,rawBytes});}const{policy,...request}=identity,plan=await planRecognitionWindows(request),canonicalBytes=encode(fixture.canonical);return{canonicalBytes,canonicalSha256:await sha256(canonicalBytes),plan,records,candidateSpans:fixture.candidateSpans};}
test('retained P3 yields independent exact U5–8 and explicit drift/overlap diagnostics, never playback',async()=>{const args=await inputs(),result=await correspondWindowUnits(args);assert.deepEqual(result.units.map(u=>u.status),['unmatched','unmatched','unmatched','unmatched','exact-unique','exact-unique','exact-unique','exact-unique']);assert(result.units.slice(0,4).every(u=>u.diagnostics.some(d=>d.operations.some(o=>o.op!=='equal'))));assert(result.units[3].diagnostics.some(d=>d.overlapAlternatives.length));assert(result.units.slice(4).every(u=>u.alternatives[0].words.length));assert.deepEqual(result.acceptedPlaybackRanges,[]);assert(result.units.every(u=>u.qualifiedForPlayback===false));for(const u of result.units)for(const t of u.canonicalTokens)assert.equal(u.canonicalText.slice(t.start,t.end),t.original);});
test('canonical P3 fixture exactly matches retained published activity sourceText and SHA',async()=>{const pack=JSON.parse(await readFile(new URL('../../apps/web/public/content/packs/eng.MRK-1-21-28/c947cc85704f9b26216ef48c56065682b4cbed0b8384554b460afec1d1fb4348.json',import.meta.url)));const activities=pack.activities;for(const u of fixture.canonical.units){const a=activities.find(a=>a.id===u.sourceUnitId&&a.sourceUnitId===u.sourceUnitId);assert.equal(a.sourceText,u.text);assert.equal(a.sourceSha256,u.sourceTextSha256);}});
test('raw/projection identity and canonical text tamper refuse',async()=>{for(const mutate of [a=>a.records[0].rawBytes.fill(0),a=>a.plan.identity.configSha256='0'.repeat(64),a=>a.canonicalBytes.fill(0),a=>a.candidateSpans=[{...a.candidateSpans[0],startWordIndex:99999}]]){const args=await inputs();mutate(args);await assert.rejects(correspondWindowUnits(args));}});
test('repeated exact words across overlapping windows remain alternative traces',async()=>{const args=await inputs(),first=JSON.parse(args.records[0].rawBytes),second=JSON.parse(args.records[1].rawBytes);first.words=[{word:'Same phrase.',startSample:450000,endSampleExclusive:460000}];second.words=[{word:'same phrase',startSample:2000,endSampleExclusive:12000}];for(const[i,raw]of[first,second].entries()){args.records[i].rawBytes=encode(raw);args.records[i].rawSha256=await sha256(args.records[i].rawBytes);}const unit={activityId:'unit',sourceUnitId:'unit',text:'SAME phrase',sourceTextSha256:await sha256('SAME phrase')};args.canonicalBytes=encode({...fixture.canonical,units:[unit]});args.canonicalSha256=await sha256(args.canonicalBytes);args.candidateSpans=[];const r=await correspondWindowUnits(args);assert.equal(r.units[0].status,'ambiguous-repetition');assert.equal(r.units[0].alternatives.length,2);assert.notEqual(r.units[0].alternatives[0].rawSha256,r.units[0].alternatives[1].rawSha256);});
test('Buffer inputs captured before hash awaits',async()=>{const args=await inputs(),pending=correspondWindowUnits(args);args.canonicalBytes.fill(0);args.records[0].rawBytes.fill(0);assert.equal((await pending).units[4].status,'exact-unique');});
test('two canonical units cannot both claim one unique raw phrase',async()=>{const args=await inputs(),u=fixture.canonical.units[4];args.canonicalBytes=encode({...fixture.canonical,units:[u,{...u,activityId:'other',sourceUnitId:'other'}]});args.canonicalSha256=await sha256(args.canonicalBytes);args.candidateSpans=[];const result=await correspondWindowUnits(args);assert(result.units.every(u=>u.status==='ambiguous-unit-assignment'));assert(result.units.every(u=>u.competingSourceUnitIds.length===1));});
test('no hidden Scripture number expansion or fuzzy drift acceptance',async()=>{const args=await inputs(),result=await correspondWindowUnits(args),u=result.units[1];assert.equal(u.status,'unmatched');assert(u.diagnostics.some(d=>d.operations.some(o=>o.op==='insert'&&d.tokens[o.recognizedTokenIndex].value==='through')));assert.equal(result.units[0].diagnostics.some(d=>d.operations.some(o=>o.op==='replace')),true);});
test('nonexact raw model/plan identity refuses despite a recomputed content hash',async()=>{const args=await inputs(),raw=JSON.parse(args.records[0].rawBytes);raw.runtimeEvidence.modelManifestSha256='f'.repeat(64);args.records[0].rawBytes=encode(raw);args.records[0].rawSha256=await sha256(args.records[0].rawBytes);await assert.rejects(correspondWindowUnits(args));});
