import test from'node:test';import assert from'node:assert/strict';
import{canonicalJSONString,sha256}from'../../server/fia/preparation/contract.mjs';
import{createWindowGuideRecognition}from'../../server/fia/preparation/executor/window-guide-adapter.mjs';
const encode=x=>new TextEncoder().encode(canonicalJSONString(x)),pin=x=>x.repeat(64);
function fixture(){const source={sha256:pin('1'),reference:`originals/sha256/${pin('1')}.mp3`,bytes:12823388},rows=new Map(),objects=new Map();let reads=0,prepares=0,runs=0;let queue=Promise.resolve();const storage={transaction(fn){const p=queue.then(()=>fn({get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v))}));queue=p.catch(()=>{});return p;}};const openSource=async()=>{throw Error('prepare fixture does not decode');};const artifacts={async read(d){if(d.reference.startsWith('originals/')){reads++;throw Error('source materialized');}return objects.get(d.reference);},async write(b){const sha=await sha256(b),reference=`raw/${sha}`;objects.set(reference,new Uint8Array(b));return{sha256:sha,reference};},verifySource:async()=>structuredClone(source),openSource};const input={language:'eng',modelRecipe:{modelId:'fixture',modelRevision:pin('2'),configSha256:pin('3')}};
 const options={storage,artifacts,dependencySha256:pin('4'),sourceMaxBytes:16777216,windowSamples:16000,overlapSamples:0,prepare:async args=>{prepares++;assert.equal('sourceBytes'in args,false);assert.deepEqual(args.source,source);assert.equal(typeof args.openSource,'function');assert.equal(args.maxBytes,16777216);assert(args.signal instanceof AbortSignal);return{pcmSha256:pin('5'),decoderSha256:pin('6'),totalSamples:16000,sampleRate:16000};},recognition:{paid:false,dependencySha256:pin('7'),async run({planIdentity,window}){runs++;return encode({schema:'fia-window-raw-words@1',planIdentity,window,windowSha256:window.windowSha256,runtimeEvidence:{scriptSha256:pin('8'),modelManifestSha256:pin('2'),runtimeManifest:{test:'synthetic'}},roundingPolicy:'seconds-floor-start-ceil-end@1',originalSegments:[],words:[{word:'fixture',startSample:1,endSampleExclusive:100}]});}}};return{source,input,options,objects,counts:()=>({reads,prepares,runs}),args:{input,nodeOutputs:{acquire:source},signal:new AbortController().signal}};}
test('typed source port passes streaming custody without reading/materializing the source; raw windows warm reuse',async()=>{const f=fixture(),adapter=createWindowGuideRecognition(f.options),result=await adapter.run(f.args);assert.deepEqual(f.counts(),{reads:0,prepares:1,runs:1});const aggregate=JSON.parse(new TextDecoder().decode(f.objects.get(result.reference)));assert.deepEqual(aggregate.source,{sha256:f.source.sha256,bytes:f.source.bytes});assert.deepEqual(aggregate.projection.acceptedPlaybackRanges,[]);await adapter.run(f.args);assert.deepEqual(f.counts(),{reads:0,prepares:2,runs:1});});
test('typed identity, size and verifier failures refuse before prepare without legacy fallback',async()=>{for(const change of [x=>({...x,sha256:pin('0')}),x=>({...x,reference:'wrong'}),x=>({...x,bytes:x.bytes+1}),x=>({...x,bytes:16777217}),x=>({...x,bytes:0}),x=>({...x,extra:true}),()=>{throw Error('revoked');}]){const f=fixture();f.options.artifacts.verifySource=async()=>change(f.source);await assert.rejects(createWindowGuideRecognition(f.options).run(f.args));assert.deepEqual(f.counts(),{reads:0,prepares:0,runs:0});}});
test('partial typed ports never silently fall back and default 2MiB refuses large source',async()=>{for(const field of ['verifySource','openSource']){const f=fixture();delete f.options.artifacts[field];assert.throws(()=>createWindowGuideRecognition(f.options));}const f=fixture();delete f.options.sourceMaxBytes;await assert.rejects(createWindowGuideRecognition(f.options).run(f.args));assert.deepEqual(f.counts(),{reads:0,prepares:0,runs:0});});
test('typed port references captured before run and cancellation after verifier prevents preparation',async()=>{const f=fixture(),adapter=createWindowGuideRecognition(f.options);f.options.artifacts.verifySource=()=>{throw Error('mutated');};f.options.artifacts.openSource=()=>{throw Error('mutated');};await adapter.run(f.args);const g=fixture(),controller=new AbortController();g.options.artifacts.verifySource=async()=>{controller.abort();return g.source;};await assert.rejects(createWindowGuideRecognition(g.options).run({...g.args,signal:controller.signal}));assert.deepEqual(g.counts(),{reads:0,prepares:0,runs:0});});
