import {canonicalJSONString,sha256} from '../contract.mjs';
const hash=v=>typeof v==='string'&&/^[a-f0-9]{64}$/.test(v);
const exact=(v,keys)=>v&&Object.getPrototypeOf(v)===Object.prototype&&Object.keys(v).sort().join()===keys.toSorted().join();
const need=(v,reason='decision-job-invalid')=>{if(!v)throw Error(reason);};
const encode=v=>new TextEncoder().encode(canonicalJSONString(v));
const same=(a,b)=>canonicalJSONString(a)===canonicalJSONString(b);
function json(value,depth=0){need(depth<=24);if(value===null||typeof value==='boolean'||typeof value==='string')return; if(typeof value==='number'){need(Number.isFinite(value));return;}need(Array.isArray(value)||value&&Object.getPrototypeOf(value)===Object.prototype);for(const v of Object.values(value))json(v,depth+1);}
function descriptor(d){need(exact(d,['reference','sha256'])&&hash(d.sha256)&&typeof d.reference==='string'&&d.reference.length>0&&d.reference.length<=2048);return structuredClone(d);}
/** Generic single-attempt custody, adapted from unit-derivative-jobs fencing.
 * No scheduler, semantic policy, retry, audio assumptions or readiness grant.
 * Eligibility is a trusted synchronous current-authority guard. validate owns
 * domain semantics and may be async; run owns at most one bounded invocation.
 */
export function createDecisionJobs({storage,artifacts,dependencySha256,run,validate,eligibility,stepMs=10000,maxBytes=65536}){
 need(typeof storage?.transaction==='function'&&typeof artifacts?.read==='function'&&typeof artifacts?.write==='function'&&hash(dependencySha256)&&typeof run==='function'&&typeof validate==='function'&&typeof eligibility==='function'&&Number.isSafeInteger(stepMs)&&stepMs>0&&stepMs<=120000&&Number.isSafeInteger(maxBytes)&&maxBytes>0&&maxBytes<=1048576,'decision-job-ports');
 const transaction=storage.transaction.bind(storage),get=artifacts.read.bind(artifacts),put=artifacts.write.bind(artifacts),execute=run,check=validate,eligible=eligibility;
 async function context(raw){json(raw);const input=structuredClone(raw);need(exact(input,['identity','dependencies'])&&input.identity&&Object.getPrototypeOf(input.identity)===Object.prototype&&input.dependencies&&Object.getPrototypeOf(input.dependencies)===Object.prototype&&Object.keys(input.dependencies).length>0&&Object.keys(input.dependencies).length<=64&&Object.entries(input.dependencies).every(([k,v])=>k.length>0&&k.length<=128&&hash(v)));need(encode(input).length<=65536);const identity={schema:'fia-decision-operation@1',input,dependencySha256,stepMs,maxBytes},key=await sha256(encode(identity));return {input,identity,key,storageKey:'decision-job:'+key};}
 function allowed(c,phase){try{const answer=eligible(structuredClone(c.input),phase);if(answer&&typeof answer.then==='function')Promise.resolve(answer).catch(()=>{});return answer===true;}catch{return false;}}
 const response=(c,state,extra={})=>({state,decisionSha256:c.key,automaticReplay:false,...extra});
 function valid(row,c){need(exact(row,['schema','identity','attemptId','revision','state','reason','artifact'])&&row.schema==='fia-decision-job@1'&&same(row.identity,c.identity)&&typeof row.attemptId==='string'&&/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/.test(row.attemptId)&&Number.isSafeInteger(row.revision)&&row.revision>=1&&row.revision<Number.MAX_SAFE_INTEGER&&['preparing','completed','uncertain'].includes(row.state));if(row.state==='completed'){need(row.reason===null);descriptor(row.artifact);}else need(row.artifact===null&&(row.state==='preparing'?row.reason===null:['execution-uncertain','interrupted'].includes(row.reason)));return row;}
 async function bounded(fn){const controller=new AbortController();let timer;try{return await Promise.race([Promise.resolve().then(()=>fn(controller.signal)),new Promise((_,reject)=>{timer=setTimeout(()=>{controller.abort();reject(Error('decision-job-deadline'));},stepMs);})]);}finally{clearTimeout(timer);controller.abort();}}
 function copy(bytes){need(bytes instanceof Uint8Array&&bytes.length>0&&bytes.length<=maxBytes,'decision-job-output');return new Uint8Array(bytes);}
 async function verified(bytes,c){const captured=copy(bytes);need(await bounded(signal=>check(new Uint8Array(captured),{input:structuredClone(c.input),signal}))===true,'decision-job-output-refused');return captured;}
 async function retained(d,c){const artifact=descriptor(d),bytes=copy(await bounded(signal=>get(artifact,{signal})));need(await sha256(bytes)===artifact.sha256,'decision-job-retained-corrupt');return verified(bytes,c);}
 async function complete(c,row){if(!allowed(c,'read'))return response(c,'blocked',{reason:'execution-admission-refused'});try{const bytes=await retained(row.artifact,c);if(!allowed(c,'verified'))return response(c,'blocked',{reason:'execution-admission-refused'});return response(c,'completed',{artifact:descriptor(row.artifact),bytes});}catch{return response(c,'unavailable',{reason:'retained-evidence-unavailable'});}}
 async function current(c){return transaction(async tx=>{const row=await tx.get(c.storageKey);return row?valid(row,c):null;});}
 async function read(input){const c=await context(input);if(!allowed(c,'read'))return response(c,'blocked',{reason:'execution-admission-refused'});const row=await current(c);if(!allowed(c,'read'))return response(c,'blocked',{reason:'execution-admission-refused'});return row?(row.state==='completed'?complete(c,row):response(c,row.state,{reason:row.reason})):response(c,'missing');}
 async function request(input){const c=await context(input);if(!allowed(c,'request'))return response(c,'blocked',{reason:'execution-admission-refused'});const claim=await transaction(async tx=>{need(allowed(c,'claim'),'decision-job-ineligible');const old=await tx.get(c.storageKey);if(old)return {owner:false,row:valid(old,c)};const row={schema:'fia-decision-job@1',identity:c.identity,attemptId:crypto.randomUUID(),revision:1,state:'preparing',reason:null,artifact:null};await tx.put(c.storageKey,row);return {owner:true,row};});if(!allowed(c,'request'))return response(c,'blocked',{reason:'execution-admission-refused'});if(!claim.owner)return claim.row.state==='completed'?complete(c,claim.row):response(c,claim.row.state,{reason:claim.row.reason});const row=claim.row;
  async function fence(){await transaction(async tx=>{const now=valid(await tx.get(c.storageKey),c);need(now.state==='preparing'&&now.attemptId===row.attemptId&&now.revision===row.revision&&allowed(c,'dispatch'),'decision-job-stale-attempt');});}
  try{await fence();const bytes=await verified(await bounded(signal=>execute(structuredClone(c.input),{signal,attemptId:row.attemptId})),c);await fence();const digest=await sha256(bytes),artifact=descriptor(await bounded(signal=>put(new Uint8Array(bytes),{signal})));need(artifact.sha256===digest);await retained(artifact,c);await transaction(async tx=>{const now=valid(await tx.get(c.storageKey),c);need(now.state==='preparing'&&now.attemptId===row.attemptId&&now.revision===row.revision&&allowed(c,'commit'),'decision-job-stale-attempt');await tx.put(c.storageKey,{...now,state:'completed',revision:now.revision+1,artifact});});return complete(c,{...row,state:'completed',revision:row.revision+1,artifact});
  }catch{await transaction(async tx=>{const now=valid(await tx.get(c.storageKey),c);if(now.state==='preparing'&&now.attemptId===row.attemptId&&now.revision===row.revision)await tx.put(c.storageKey,{...now,state:'uncertain',reason:'execution-uncertain',revision:now.revision+1});});return response(c,'uncertain',{reason:'execution-uncertain'});}
 }
 // Called only by lifecycle owner after establishing interruption. A live owner
 // is fenced out if explicitly recovered; this never executes or retries work.
 async function recoverInterrupted(input){const c=await context(input);if(!allowed(c,'recover'))return response(c,'blocked',{reason:'execution-admission-refused'});await transaction(async tx=>{const old=await tx.get(c.storageKey);if(!old)return;const row=valid(old,c);if(row.state==='preparing')await tx.put(c.storageKey,{...row,state:'uncertain',reason:'interrupted',revision:row.revision+1});});return read(input);}
 return Object.freeze({request,read,recoverInterrupted});
}
