import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync,mkdtempSync,mkdirSync,writeFileSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {createHash,webcrypto} from 'node:crypto';
import {buildGeneralizedSnapshot} from '../../server/fia/publication/generalized.mjs';import {createService} from '../../server/fia/publication/service.mjs';import {exportSnapshot} from '../../server/faces/worker/export-snapshot.mjs';import {snapshotStorage,readStaticArtifact} from '../../server/faces/worker/snapshot.mjs';import {createReadOperations} from '../../server/fia/publication/read-operations.mjs';import {createWorker} from '../../server/faces/worker/adapter.mjs';import {serveRead} from '../../server/faces/http.mjs';import {serveMcp} from '../../server/faces/mcp.mjs';
const hash=b=>createHash('sha256').update(b).digest('hex');globalThis.crypto??=webcrypto;
const authority=JSON.parse(readFileSync('server/fia/publication/trusted-generalized.json')),extension=buildGeneralizedSnapshot('apps/web/public',authority),legacy=exportSnapshot(createService(),JSON.parse(readFileSync('server/faces/worker/authority.json')));
const snapshot={...legacy,records:[...legacy.records,...extension.records],current:{...legacy.current,...extension.current},staticArtifacts:extension.staticArtifacts.filter(a=>!legacy.artifacts.some(b=>b.descriptor.sha256===a.descriptor.sha256))};
const origin='https://dev.fiaguide.app',paths=[];
const fetchAsset=async path=>{paths.push(path);return new Response(readFileSync('apps/web/public'+path),{headers:{'content-type':'application/json'}});};
const worker=createWorker({origin,operations:createReadOperations(snapshotStorage(snapshot,{fetchAsset})),serveRead,serveMcp});
const get=path=>worker.fetch(new Request(origin+path),{ASSETS:{fetch:()=>new Response('static')}});
const rpc=async(name,args)=>{const r=await worker.fetch(new Request(origin+'/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})}),{});assert.equal(r.status,200);return (await r.json()).result.structuredContent;};
async function check(id){const record=extension.records.find(r=>r.packId===id);const response=await get('/v1/packs/'+id+'?revision='+record.revision);assert.equal(response.status,200);assert.deepEqual(await response.json(),record);assert.deepEqual(await rpc('read_pack',{packId:id,revision:record.revision}),record);const before=paths.length;const bytes=Buffer.from(await(await get(record.artifact.path)).arrayBuffer());assert.equal(hash(bytes),record.revision);assert.equal(bytes.length,record.artifact.bytes);const viaMcp=await rpc('read_artifact',{sha256:record.revision});assert.equal(hash(viaMcp.content),record.revision);assert.equal(viaMcp.artifact.bytes,bytes.length);const expected=snapshot.staticArtifacts.find(a=>a.descriptor.sha256===record.revision);assert.deepEqual(paths.slice(before),expected?[expected.staticPath,expected.staticPath]:[]);}
test('prove four cross-language HTTP/MCP samples before the same all136 operation',async()=>{for(const id of ['eng.MRK-1-1-13','spa.MRK-1-1-13','eng.MRK-1-14-20','spa.MRK-1-14-20'])await check(id);for(const r of extension.records.filter(r=>r.packId!=='fia-mark-catalog'))await check(r.packId);await check('fia-mark-catalog');for(const record of legacy.records){assert.deepEqual(await(await get('/v1/packs/'+record.packId)).json(),record);const b=Buffer.from(await(await get(record.artifact.path)).arrayBuffer());assert.equal(hash(b),record.revision);}});
test('precise source ID grammar, unknown ID and cross-pack revisions fail closed',async()=>{for(const id of ['eng.MRK-1-14-20/escape','ENG.MRK-1-14-20','eng.MRK-a-1-2'])assert.equal((await get('/v1/packs/'+encodeURIComponent(id))).status,400);assert.equal((await get('/v1/packs/eng.MRK-999-1-2')).status,404);assert.equal((await get('/v1/packs/spa.MRK-1-14-20?revision='+extension.records[1].revision)).status,404);});
test('static artifacts reject missing, redirects, HTML, invalid bytes/length/hash and overlimit streams',async()=>{const item=snapshot.staticArtifacts[0];for(const make of [()=>new Response('missing',{status:404}),()=>new Response(null,{status:302,headers:{location:'/elsewhere'}}),()=>new Response('<html>',{headers:{'content-type':'text/html'}}),()=>new Response('x',{headers:{'content-type':'application/json'}}),()=>new Response(new Uint8Array([255]),{headers:{'content-type':'application/json'}}),()=>new Response('x',{headers:{'content-type':'application/json','content-length':'9999999'}})])assert.equal((await readStaticArtifact(item,async()=>make())).status,'unavailable');let cancelled=false;const stream=new ReadableStream({pull(c){c.enqueue(new Uint8Array(1048577));},cancel(){cancelled=true;}});assert.equal((await readStaticArtifact(item,async()=>new Response(stream,{headers:{'content-type':'application/json'}}))).reason,'artifact-integrity-failed');assert.equal(cancelled,true);const bytes=readFileSync('apps/web/public'+item.staticPath),changed=Buffer.from(bytes);changed[20]^=1;assert.equal((await readStaticArtifact(item,async()=>new Response(changed,{headers:{'content-type':'application/json'}}))).reason,'artifact-integrity-failed');});
test('catalog/authority tampering is refused before publication',()=>{for(const mutate of [a=>a.catalog.sha256='f'.repeat(64),a=>a.records[0].envelopeSha256='f'.repeat(64),a=>a.records[1].packId='eng.MRK-9-9-9']){const a=structuredClone(authority);mutate(a);assert.throws(()=>buildGeneralizedSnapshot('apps/web/public',a));}});

test('actual payload corruption or absence cannot package a trusted catalog',()=>{const dir=mkdtempSync(join(tmpdir(),'fia-publication-'));try{mkdirSync(join(dir,'content'));writeFileSync(join(dir,'content/registry.json'),readFileSync('apps/web/public/content/registry.json'));assert.throws(()=>buildGeneralizedSnapshot(dir,authority),/ENOENT/);const item=extension.staticArtifacts[1],path=join(dir,item.staticPath);mkdirSync(dirname(path),{recursive:true});const bytes=readFileSync('apps/web/public'+item.staticPath);bytes[10]^=1;writeFileSync(path,bytes);assert.throws(()=>buildGeneralizedSnapshot(dir,authority),/unaccepted-generalized-bytes/);}finally{rmSync(dir,{recursive:true,force:true});}});
test('invalid UTF8 with otherwise matching integrity is unavailable',async()=>{const bytes=new Uint8Array([255]),item={staticPath:'/content/registry.json',descriptor:{bytes:1,sha256:hash(bytes),mime:'application/json'}};assert.equal((await readStaticArtifact(item,async()=>new Response(bytes,{headers:{'content-type':'application/json'}}))).reason,'artifact-integrity-failed');});
test('HTTP and MCP preserve the same typed unavailable integrity outcome',async()=>{const record=extension.records.find(r=>r.packId==='spa.MRK-1-14-20');const broken=createWorker({origin,operations:createReadOperations(snapshotStorage(snapshot,{fetchAsset:async()=>new Response('<html>',{headers:{'content-type':'text/html'}})})),serveRead,serveMcp});const http=await broken.fetch(new Request(origin+record.artifact.path),{});assert.equal(http.status,404);const expected=await http.json();const response=await broken.fetch(new Request(origin+'/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'read_artifact',arguments:{sha256:record.revision}}})}),{});assert.deepEqual((await response.json()).result.structuredContent,expected);assert.equal(expected.reason,'artifact-integrity-failed');});

test('unexpected storage and ASSETS faults preserve shared HTTP/MCP internal-error response',async()=>{for(const kind of ['assets','storage','stream']){const record=extension.records.find(r=>r.packId==='spa.MRK-1-14-20');const fail=()=>{throw Error('private unexpected fault');};const fetchAsset=kind==='stream'?async()=>new Response(new ReadableStream({start(controller){controller.error(Error('private stream fault'));}}),{headers:{'content-type':'application/json'}}):fail;const operations=kind!=='storage'?createReadOperations(snapshotStorage(snapshot,{fetchAsset})):{readPack:fail,readArtifact:fail};const broken=createWorker({origin,operations,serveRead,serveMcp});const http=await broken.fetch(new Request(origin+record.artifact.path),{});assert.equal(http.status,500);const expected=await http.json();assert.deepEqual(expected,{status:'refused',code:'internal-error'});const mcp=await broken.fetch(new Request(origin+'/mcp',{method:'POST',headers:{'content-type':'application/json',accept:'application/json, text/event-stream','mcp-protocol-version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name:'read_artifact',arguments:{sha256:record.revision}}})}),{});assert.equal(mcp.status,500);assert.deepEqual(await mcp.json(),expected);const malformed=await broken.fetch(new Request(origin+'/v1/artifacts/%ZZ'),{});assert.equal(malformed.status,400);assert.deepEqual(await malformed.json(),{status:'refused',code:'invalid-request'});}});
