import test from 'node:test';import assert from 'node:assert/strict';
import {verifyPromotion} from '../../scripts/promotion-source-evidence.mjs';
const sha='a'.repeat(40),repo='example/app',source='reviewed workflow bytes';
function fixture(change=()=>{}){const pr={state:'open',base:{ref:'staging'},head:{sha,ref:'main',repo:{full_name:repo}}};const objects={pr,runs:{'ci.yml':{id:1,head_sha:sha,head_branch:'main',event:'push',path:'.github/workflows/ci.yml',status:'completed',conclusion:'success'},'post-deploy.yml':{id:2,head_sha:sha,head_branch:'main',event:'push',path:'.github/workflows/post-deploy.yml',status:'completed',conclusion:'success'}},jobs:{1:{id:11,name:'check',status:'completed',conclusion:'success',steps:[{name:'Controlled local listening and cancellation',status:'completed',conclusion:'success'}]},2:{id:12,name:'deployed-listening',status:'completed',conclusion:'success',steps:['Wait for version.json to report the commit (10 min)','Controlled local listening','Hosted listening journey','Verify separate hosted and controlled listening receipts'].map(name=>({name,status:'completed',conclusion:'success'}))}},content:source};change(objects);let calls=0;return {repo,prNumber:3,readWorkflow:()=>Buffer.from(source),api:async path=>{if(path.endsWith('/pulls/3')){calls++;const result=structuredClone(objects.pr);if(objects.move&&calls>1)result.head.sha='b'.repeat(40);return result;}if(path.includes('/contents/'))return {encoding:'base64',content:Buffer.from(objects.content).toString('base64')};if(path.includes('/workflows/'))return {workflow_runs:[objects.runs[path.match(/workflows\/([^/]+)/)[1]]]};if(path.includes('/jobs?'))return {jobs:[objects.jobs[path.match(/runs\/(\d+)/)[1]]]};throw Error(path);}};}
test('exact push source head and required evidence accepted',async()=>{const r=await verifyPromotion(fixture());assert.equal(r.sourceSha,sha);assert.equal(r.upstreamEnvironment,'dev');assert.equal(r.receipts.length,2);});
for(const[name,mutate]of Object.entries({fork:o=>o.pr.head.repo.full_name='other/app',wrongBranch:o=>o.pr.head.ref='feature',oldSmoke:o=>o.jobs[2].name='verify',wrongHead:o=>o.runs['post-deploy.yml'].head_sha='b'.repeat(40),dispatch:o=>o.runs['post-deploy.yml'].event='workflow_dispatch',pending:o=>o.runs['post-deploy.yml'].status='in_progress',failed:o=>o.runs['ci.yml'].conclusion='failure',skippedReceipt:o=>o.jobs[2].steps[3].conclusion='skipped',workflowDrift:o=>o.content='changed',movedHead:o=>o.move=true}))test('reject '+name,async()=>{await assert.rejects(verifyPromotion(fixture(mutate)));});
test('production requires staging push evidence',async()=>{const options=fixture(o=>{o.pr.base.ref='production';o.pr.head.ref='staging';for(const r of Object.values(o.runs))r.head_branch='staging';});assert.equal((await verifyPromotion(options)).upstreamEnvironment,'staging');});
function clocked(options,{onSleep=()=>{}}={}){let t=0;const sleeps=[];return Object.assign(options,{waitMs:60000,pollMs:20000,now:()=>t,sleep:async ms=>{sleeps.push(ms);t+=ms;onSleep(sleeps.length);},sleeps});}
test('wait: pending exact-head run that completes with success passes',async()=>{let o;const options=clocked(fixture(x=>{o=x;x.runs['ci.yml'].status='in_progress';x.runs['ci.yml'].conclusion=null;x.runs['post-deploy.yml'].status='queued';x.runs['post-deploy.yml'].conclusion=null;}),{onSleep:n=>{if(n===1){o.runs['ci.yml'].status='completed';o.runs['ci.yml'].conclusion='success';}if(n===2){o.runs['post-deploy.yml'].status='completed';o.runs['post-deploy.yml'].conclusion='success';}}});const r=await verifyPromotion(options);assert.equal(r.receipts.length,2);assert.deepEqual(options.sleeps,[20000,20000]);});
test('wait: run still pending past the deadline fails',async()=>{const options=clocked(fixture(o=>{o.runs['post-deploy.yml'].status='in_progress';o.runs['post-deploy.yml'].conclusion=null;}));await assert.rejects(verifyPromotion(options),/Latest exact-head run did not succeed: post-deploy.yml/);assert.deepEqual(options.sleeps,[20000,20000,20000]);});
test('wait: completed failure is not retried',async()=>{const options=clocked(fixture(o=>{o.runs['ci.yml'].conclusion='failure';}));await assert.rejects(verifyPromotion(options),/did not succeed: ci.yml/);assert.deepEqual(options.sleeps,[]);});
test('wait: waitMs 0 keeps the single-read behaviour',async()=>{const sleeps=[];const options=Object.assign(fixture(o=>{o.runs['ci.yml'].status='in_progress';}),{sleep:async ms=>{sleeps.push(ms);}});await assert.rejects(verifyPromotion(options),/did not succeed: ci.yml/);assert.deepEqual(sleeps,[]);});
test('wait: one shared deadline covers both workflows',async()=>{let o;const options=clocked(fixture(x=>{o=x;x.runs['ci.yml'].status='in_progress';x.runs['ci.yml'].conclusion=null;x.runs['post-deploy.yml'].status='in_progress';x.runs['post-deploy.yml'].conclusion=null;}),{onSleep:n=>{if(n===2){o.runs['ci.yml'].status='completed';o.runs['ci.yml'].conclusion='success';}}});await assert.rejects(verifyPromotion(options),/did not succeed: post-deploy.yml/);assert.deepEqual(options.sleeps,[20000,20000,20000]);});
