import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {verifyScriptureAudioReplacement} from '../../scripts/scripture-audio-publication.mjs';
import {validateDelivery,validateScriptureAlignment} from '../../apps/web/src/lib/media-delivery.js';
const hash=b=>createHash('sha256').update(b).digest('hex');
function fixture(){
 const evidence=new Map(),put=v=>{const b=Buffer.from(typeof v==='string'?v:JSON.stringify(v)),h=hash(b);evidence.set(h,b);return h;};
 const descriptor={id:'eng.MRK-1-1-13',revision:'a'.repeat(64)},file={path:'/audio/source/BSB.mp3',group:'audio',sha256:hash('logical'),bytes:7};
 const verse={verse:1,text:'This is good.',sourceId:'MRK.1.1',start:4.4,end:6,highlightMode:'word',words:[{from:0,to:4,start:4.4,end:4.8},{from:5,to:7,start:4.9,end:5.1},{from:8,to:12,start:5.2,end:6}]};
 const pack={assets:{BSB:{kind:'scripture',descriptionAudio:file.path,alignment:{sourceSha256:hash('text'),verses:[verse]}}},activities:[]};
 const recording={url:'https://publisher.example/BSB.mp3',sha256:hash('official'),bytes:100,duration:100,rightsEvidenceSha256:null};recording.rightsEvidenceSha256=put({status:'accepted',recordingSha256:recording.sha256,recordingUrl:recording.url});
 const row={id:'bsb',assetId:'BSB',logicalAudio:{path:file.path,sha256:file.sha256,bytes:file.bytes},recording,sourceRange:{startSeconds:4.4,endSeconds:6}};
 const accepted={status:'accepted',packId:descriptor.id,presentationRevision:descriptor.revision,recipeRevision:'recipe',entry:row,transcriptSha256:put('raw ASR'),textSha256:put('text'),driftReportSha256:put('drift'),rangeEvidenceSha256:put('range')};
 const ledger={schema:'fia-scripture-audio-sources@1',packId:descriptor.id,presentationRevision:descriptor.revision,entries:[{...row,review:{recipeRevision:'recipe',evidenceSha256:put(accepted)}}]};
 const delivery={kind:'audio',status:'transformed',format:'opus',preset:'voice',q:'medium',url:'https://transcode.klappy.dev/audio/preset=voice,q=medium,f=opus/'+recording.url,sha256:hash('output'),bytes:20,mime:'audio/ogg',duration:100};
 const timing={status:'verified',sourceAudioSha256:recording.sha256,deliveryAudioSha256:delivery.sha256,method:'correlation',evidence:'fixture',mapping:{scale:1,offsetSeconds:0},mappingEvidenceSha256:null};timing.mappingEvidenceSha256=put({status:'accepted',sourceAudioSha256:recording.sha256,deliveryAudioSha256:delivery.sha256,deliveryDuration:100,sourceClockDomain:'decoded-pcm-seconds',mapping:timing.mapping});
 const alignment={schemaVersion:2,id:'BSB',clockDomain:'delivery-media-seconds',audioSha256:delivery.sha256,duration:100,sourceSha256:hash('text'),verses:[verse]},ab=Buffer.from(JSON.stringify(alignment)),ah=hash(ab),range={startSeconds:4.4,endSeconds:6};
 const entry={path:file.path,source:{url:recording.url,sha256:recording.sha256,bytes:100},delivery,timing,scriptureReplacement:{ledgerEntryId:'bsb',assetId:'BSB',logicalSource:{sha256:file.sha256,bytes:7}},playbackRange:range,scriptureAlignment:{url:`/content/scripture-alignments/${ah}.json`,sha256:ah,bytes:ab.length,evidenceSha256:put({status:'accepted',sourceAudioSha256:recording.sha256,deliveryAudioSha256:delivery.sha256,alignmentSha256:ah,clockEvidenceSha256:timing.mappingEvidenceSha256,playbackRange:range,mapping:timing.mapping})}};
 return {entry,ledger,pack,descriptor,file,evidence,alignment,readEvidence:h=>evidence.get(h),readAlignment:()=>ab};
}
test('official chapter replacement keeps logical identity and output-clock alignment',()=>{const f=fixture(),out=verifyScriptureAudioReplacement(f);assert.deepEqual(out.scriptureAlignment,f.alignment);assert.equal(out.logicalSourceSha256,f.file.sha256);assert.deepEqual(out.playbackRange,f.entry.playbackRange);});
for(const [name,mutate] of [
 ['logical bytes',f=>f.file.bytes++],['old TTS text',f=>f.pack.assets.BSB.alignment.verses[0]={...f.pack.assets.BSB.alignment.verses[0],text:'Wrong.'}],['range',f=>f.entry.playbackRange.endSeconds=7],['clock',f=>f.entry.timing.mapping.offsetSeconds=.012],['evidence bytes',f=>f.evidence.set(f.entry.timing.mappingEvidenceSha256,Buffer.from('{}'))],['unreviewed chapter',f=>f.ledger.entries[0].recording.sha256='f'.repeat(64)],['alignment bytes',f=>f.readAlignment=()=>Buffer.from('{}')]
])test('rejects '+name,()=>{const f=fixture();mutate(f);assert.throws(()=>verifyScriptureAudioReplacement(f));});
test('untimed verses cannot carry fabricated word intervals; positive intervals required',()=>{const f=fixture(),a=f.alignment,opts={audioSha256:a.audioSha256,duration:a.duration,assetId:a.id};a.verses[0].words[0].end=a.verses[0].words[0].start;assert.throws(()=>validateScriptureAlignment(a,opts));a.verses[0].highlightMode='verse';a.verses[0].reason='unmatched ASR tokens';assert.throws(()=>validateScriptureAlignment(a,opts));a.verses[0].words=[];assert.equal(validateScriptureAlignment(a,opts),a);});
test('schema5 alone admits explicit Scripture replacement and enforces default alignment',()=>{const f=fixture(),e=f.entry;e.defaultSize='medium';e.variants={medium:{delivery:e.delivery,timing:e.timing,playbackRange:e.playbackRange,scriptureAlignment:e.scriptureAlignment}};const ref=(kind,h)=>({url:`/content/${kind}/${h}.json`,sha256:h,bytes:10}),s={schema:5,packId:f.descriptor.id,presentationRevision:f.descriptor.revision,recipeRevision:'r',sourceLedger:ref('video-sources','1'.repeat(64)),recordingLedger:ref('recording-sources','2'.repeat(64)),scriptureSourceLedger:ref('scripture-sources','3'.repeat(64)),entries:[e]},id={packId:s.packId,presentationRevision:s.presentationRevision};assert.equal(validateDelivery(s,id),s);const bad=structuredClone(s);bad.entries[0].variants.medium.scriptureAlignment.sha256='4'.repeat(64);assert.throws(()=>validateDelivery(bad,id));const old={...s,schema:4};delete old.scriptureSourceLedger;assert.throws(()=>validateDelivery(old,id));});
test('actual finalizer embeds selected alignment and pins its core dependency',async()=>{
 const {mkdtempSync,mkdirSync,writeFileSync,readFileSync,cpSync,rmSync}=await import('node:fs'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{execFileSync}=await import('node:child_process');
 const root=mkdtempSync(join(tmpdir(),'fia-scripture-finalizer-')),write=(path,b)=>{const full=join(root,path);mkdirSync(join(full,'..'),{recursive:true});writeFileSync(full,b);};
 try{const f=fixture(),e=f.entry;e.defaultSize='medium';e.variants={medium:{delivery:e.delivery,timing:e.timing,playbackRange:e.playbackRange,scriptureAlignment:e.scriptureAlignment}};
 const ledgerBytes=Buffer.from(JSON.stringify(f.ledger)),empty=Buffer.from('{}'),ref=(kind,b)=>({url:`/content/${kind}/${hash(b)}.json`,sha256:hash(b),bytes:b.length});
 const sidecar={schema:5,packId:f.descriptor.id,presentationRevision:f.descriptor.revision,recipeRevision:'r',sourceLedger:ref('video-sources',empty),recordingLedger:ref('recording-sources',empty),scriptureSourceLedger:ref('scripture-sources',ledgerBytes),entries:[e]},bytes=Buffer.from(JSON.stringify(sidecar)),descriptor={...f.descriptor,presentation:{url:'/content/packs/fixture.json'}};
 write('dist/index.html','app');write('dist/content/registry.json',JSON.stringify({packs:[descriptor]}));write('dist'+descriptor.presentation.url,JSON.stringify(f.pack));for(const r of [sidecar.sourceLedger,sidecar.recordingLedger])write('dist'+r.url,empty);write('dist'+sidecar.scriptureSourceLedger.url,ledgerBytes);write(`dist/content/delivery/${descriptor.id}/${hash(bytes)}.json`,bytes);write('dist'+e.path,'logical');write('dist'+e.scriptureAlignment.url,f.readAlignment());for(const [h,b] of f.evidence)write(`dist/content/scripture-evidence/${h}.json`,b);
 write('apps/web/public/sw.js',readFileSync(new URL('../../apps/web/public/sw.js',import.meta.url)));cpSync(new URL('../../apps/web/docs',import.meta.url),join(root,'apps/web/docs'),{recursive:true});execFileSync(process.execPath,[new URL('../../scripts/finalize-build.mjs',import.meta.url).pathname],{cwd:root,stdio:'pipe'});
 const manifest=JSON.parse(readFileSync(join(root,`dist/offline/${descriptor.id}.json`))),file=manifest.files.find(x=>x.path===e.path);assert.deepEqual(file.scriptureAlignment,f.alignment);assert.deepEqual(file.variants.medium.scriptureAlignment,f.alignment);assert.equal(file.scriptureLedgerSha256,hash(ledgerBytes));assert(manifest.files.some(x=>x.path===e.scriptureAlignment.url));
 const {verifyManifestFile}=await import('../release/delivery-closure.js');verifyManifestFile(file,Buffer.from('logical'),sidecar,hash(bytes),f.readAlignment);const bad=structuredClone(file);bad.scriptureAlignment.verses[0].words[0].end=99;assert.throws(()=>verifyManifestFile(bad,Buffer.from('logical'),sidecar,hash(bytes),f.readAlignment));
 }finally{rmSync(root,{recursive:true,force:true});}
});
