import {test} from 'node:test';import assert from 'node:assert/strict';import {required,verify} from '../../scripts/live-listening/verify.mjs';
const commit='a'.repeat(40),opts={commit,environment:'dev'};
function report(){return {suites:[{specs:[...required].map(([title,claims])=>{const sample={binding:{activityId:'S01-U002',sourceUnitId:'u2',sourceTextSha256:'b'.repeat(64),sha256:'a'.repeat(64),range:{startSeconds:0,endSeconds:5}},currentActivityId:'S01-U002',controls:[{label:'Pause'}],media:[{src:'blob:actual',paused:false,sha256:'a'.repeat(64),sourceUnitId:'u2',sourceTextSha256:'b'.repeat(64),before:1,after:1.5}],before:[{src:'blob:actual',time:1}],after:[{src:'blob:actual',time:1.5,paused:false,readyState:4}]};const e={schemaVersion:1,outcome:'passed',environment:'dev',origin:'https://dev.fiaguide.app',expectedCommit:commit,networkVersion:{commit,version:'test'},loadedRelease:'test+aaaaaaa',packId:'eng.MRK-1-14-20',claims:Object.fromEntries(['firstUnitVisible',...claims].map(c=>[c,true])),observations:[],nativePlayback:(claims.includes('nextPlayed')?['S01-U001','S01-U002']:claims.includes('scripturePlayed')?['S01-U002-reading-1']:claims.includes('explicitPlay')?['S01-U001']:[]).map(id=>({...structuredClone(sample),currentActivityId:id,binding:{...sample.binding,activityId:id}})),cancellation:{operationId:'job',completion:{operationId:'job',state:'ready'},mediaAfterCompletion:[{paused:true,advanced:false}]}};return {title,tests:[{projectName:'live-chromium',results:[{status:'passed',attachments:[{name:'live-listening-evidence',body:Buffer.from(JSON.stringify(e)).toString('base64')}]}]}]};})}]};}
const mutate=(r,fn)=>{const a=r.suites[0].specs[0].tests[0].results[0].attachments[0];const e=JSON.parse(Buffer.from(a.body,'base64'));fn(e);a.body=Buffer.from(JSON.stringify(e)).toString('base64');};
test('complete synthetic validator fixture accepted; this is not browser evidence',()=>assert.equal(verify(report(),opts).ok,true));
test('missing, skipped, expected-failure or retried outcome cannot pass',()=>{for(const mode of ['missing','skipped','expected','retry']){const r=report(),t=r.suites[0].specs[0].tests[0];if(mode==='missing')r.suites[0].specs.pop();if(mode==='skipped')t.results[0].status='skipped';if(mode==='expected')t.expectedStatus='failed';if(mode==='retry')t.results.push(t.results[0]);assert.equal(verify(r,opts).ok,false,mode);}});
test('reject wrong full commit, cached shell, wrong origin, P1, missing native clock',()=>{for(const fn of [e=>e.networkVersion.commit='b'.repeat(40),e=>e.loadedRelease='old',e=>e.origin='https://fiaguide.app',e=>e.packId='eng.MRK-1-1-13',e=>e.nativePlayback=[],e=>e.nativePlayback[0].after[0].time=1,e=>e.claims.nextPlayed=false]){const r=report();mutate(r,fn);assert.equal(verify(r,opts).ok,false);}});
test('configuration and runner failure fail closed',()=>{assert.equal(verify(report(),{}).ok,false);const r=report();r.errors=[{message:'crash'}];assert.equal(verify(r,opts).ok,false);});

test('top-level rejects forged sequence, absent clocks, malformed digest and unrelated owner',()=>{for(const fn of [e=>e.nativePlayback[0].currentActivityId=e.nativePlayback[0].binding.activityId='wrong',e=>delete e.nativePlayback[0].media[0].before,e=>e.nativePlayback[0].binding.sha256='x',e=>e.nativePlayback[0].after[0].src='blob:unrelated']){const r=report();mutate(r,fn);assert.equal(verify(r,opts).ok,false);}});
