import {test} from 'node:test';import assert from 'node:assert/strict';import {required,verify} from '../../scripts/live-listening/verify.mjs';
const commit='a'.repeat(40),controlled={mode:'controlled-local-protocol-fixture',commit,loadedCommit:commit,outcome:'passed',mediaSha256:'0f3fa9e77215f5050f9e22b7abee329c47e0e9ff71a5f0c4d248926a8f42268d',descriptorSha256:'186956fb526a0671025180f637c0f6e6b336129085e21951da6e59e89b33fcee',claims:[{mode:'cancel',loadedCommit:commit,outcome:'passed',completion:{operationId:'job',state:'ready',at:1},observedAt:2,before:[],after:[],registryObserved:true},{mode:'manual',loadedCommit:commit,outcome:'passed',completion:{operationId:'job',state:'ready',at:1},observedAt:2,readySilence:{before:[],after:[]},pauseCount:1,activityId:'S01-U001',range:{startSeconds:0,endSeconds:10},before:[{src:'blob:actual',time:1}],after:[{src:'blob:actual',time:1.5,paused:false}]}]},opts={commit,environment:'dev',controlled};
controlled.claims.push({...structuredClone(controlled.claims[0]),mode:'cancel-button',cancellationAction:'Cancel button'});
function report(){return {suites:[{specs:[...required].map(([title,claims])=>{const sample={binding:{activityId:'S01-U002',sourceUnitId:'u2',sourceTextSha256:'b'.repeat(64),sha256:'a'.repeat(64),range:{startSeconds:0,endSeconds:5}},currentActivityId:'S01-U002',controls:[{label:'Pause'}],media:[{src:'blob:actual',paused:false,sha256:'a'.repeat(64),sourceUnitId:'u2',sourceTextSha256:'b'.repeat(64),before:1,after:1.5}],before:[{src:'blob:actual',time:1}],after:[{src:'blob:actual',time:1.5,paused:false,readyState:4}]};const e={schemaVersion:1,outcome:'passed',environment:'dev',origin:'https://dev.fiaguide.app',expectedCommit:commit,loadedCommit:commit,networkVersion:{commit,version:'test'},loadedRelease:'test+aaaaaaa',packId:'eng.MRK-1-14-20',claims:Object.fromEntries(['firstUnitVisible',...claims].map(c=>[c,true])),observations:[],nativePlayback:(claims.includes('warmReplay')?['S01-U001','S01-U001']:claims.includes('offlineScripture')?['S01-U002-reading-1']:claims.includes('nextPlayed')?['S01-U001','S01-U002']:claims.includes('scripturePlayed')?['S01-U002-reading-1']:claims.includes('explicitPlay')?['S01-U001']:[]).map(id=>({...structuredClone(sample),currentActivityId:id,binding:{...sample.binding,activityId:id}})),offline:{savedVerified:true,navigatorOnline:false,serviceWorkerControlled:true,loadedCommit:commit},cancellation:{operationId:'job',completion:{operationId:'job',state:'ready'},mediaAfterCompletion:[{paused:true,advanced:false}]}};return {title,tests:[{projectName:'live-chromium',results:[{status:'passed',attachments:[{name:'live-listening-evidence',body:Buffer.from(JSON.stringify(e)).toString('base64')}]}]}]};})}]};}
const mutate=(r,fn)=>{const a=r.suites[0].specs[0].tests[0].results[0].attachments[0];const e=JSON.parse(Buffer.from(a.body,'base64'));fn(e);a.body=Buffer.from(JSON.stringify(e)).toString('base64');};
test('complete synthetic validator fixture accepted; this is not browser evidence',()=>assert.equal(verify(report(),opts).ok,true));
test('missing, skipped, expected-failure or retried outcome cannot pass',()=>{for(const mode of ['missing','skipped','expected','retry']){const r=report(),t=r.suites[0].specs[0].tests[0];if(mode==='missing')r.suites[0].specs.pop();if(mode==='skipped')t.results[0].status='skipped';if(mode==='expected')t.expectedStatus='failed';if(mode==='retry')t.results.push(t.results[0]);assert.equal(verify(r,opts).ok,false,mode);}});
test('reject wrong full commit, cached shell, wrong origin, P1, missing native clock',()=>{for(const fn of [e=>e.networkVersion.commit='b'.repeat(40),e=>e.loadedRelease='old',e=>e.origin='https://fiaguide.app',e=>e.packId='eng.MRK-1-1-13',e=>e.nativePlayback=[],e=>e.nativePlayback[0].after[0].time=1,e=>e.claims.nextPlayed=false]){const r=report();mutate(r,fn);assert.equal(verify(r,opts).ok,false);}});
test('configuration and runner failure fail closed',()=>{assert.equal(verify(report(),{}).ok,false);const r=report();r.errors=[{message:'crash'}];assert.equal(verify(r,opts).ok,false);});

test('top-level rejects forged sequence, absent clocks, malformed digest and unrelated owner',()=>{for(const fn of [e=>e.nativePlayback[0].currentActivityId=e.nativePlayback[0].binding.activityId='wrong',e=>delete e.nativePlayback[0].media[0].before,e=>e.nativePlayback[0].binding.sha256='x',e=>e.nativePlayback[0].after[0].src='blob:unrelated']){const r=report();mutate(r,fn);assert.equal(verify(r,opts).ok,false);}});

test('selected paused owner cannot borrow unrelated advancing owner',()=>{const r=report();mutate(r,e=>{const s=e.nativePlayback[0];s.after[0].paused=true;s.after[0].readyState=0;s.before.push({src:'blob:other',time:1});s.after.push({src:'blob:other',time:2,paused:false,readyState:4});});assert.equal(verify(r,opts).ok,false);});
test('controlled receipt required and terminal ordering enforced',()=>{assert.equal(verify(report(),{...opts,controlled:undefined}).ok,false);const c=structuredClone(controlled);c.claims[0].observedAt=0;assert.equal(verify(report(),{...opts,controlled:c}).ok,false);});

test('full executing-document commit is mandatory',()=>{for(const fn of [e=>delete e.loadedCommit,e=>e.loadedCommit='b'.repeat(40)]){const r=report();mutate(r,fn);assert.equal(verify(r,opts).ok,false);}});

test('controlled receipt binds the full document in every fresh browser',()=>{for(const change of [c=>delete c.loadedCommit,c=>c.loadedCommit='b'.repeat(40),c=>delete c.claims[0].loadedCommit,c=>c.claims[1].loadedCommit=commit.slice(0,7)]){const c=structuredClone(controlled);change(c);assert.equal(verify(report(),{...opts,controlled:c}).ok,false);}});

test('distinct actual Cancel scenario cannot be replaced by OFF/ON',()=>{const c=structuredClone(controlled);c.claims=c.claims.filter(x=>x.mode!=='cancel-button');assert.equal(verify(report(),{...opts,controlled:c}).ok,false);});

test('offline and replay receipts require their distinct actual observations',()=>{for(const title of ['P2 warm Replay restarts the current guide recording','P2 saved Scripture plays after isolated offline reload']){const r=report(),a=r.suites[0].specs.find(x=>x.title===title).tests[0].results[0].attachments[0],e=JSON.parse(Buffer.from(a.body,'base64'));if(title.includes('Replay'))e.nativePlayback[1].before[0].time=2;else e.offline.navigatorOnline=true;a.body=Buffer.from(JSON.stringify(e)).toString('base64');assert.equal(verify(r,opts).ok,false);}});
