import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdtemp,rm,writeFile,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {buildGeneralizedSnapshot} from '../../server/fia/publication/generalized.mjs';
import {exportGuideSources} from '../../server/fia/compiler/presentation/export-guide-sources.mjs';
import {buildApprovedAudioProofIndex} from '../../scripts/approved-audio-proof-index.mjs';
import {createRetainedApprovedAudio} from '../../server/fia/preparation/approved-audio-runtime.mjs';
const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),hash=b=>createHash('sha256').update(b).digest('hex');
test('actual MCP demand adopts retained approved Scripture; reads and restart never acquire or repair',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'fia-approved-integration-')),publicRoot=process.env.FIA_APPROVED_PROOF_ROOT||'apps/web/public',authority=JSON.parse(await readFile('server/fia/publication/trusted-generalized.json')),extension=buildGeneralizedSnapshot(publicRoot,authority),canonicalSources=exportGuideSources({outputRoot:dir,sourceRevision:authority.sourceCommit});
 const proof=await buildApprovedAudioProofIndex({publicRoot,authority:{registrySha256:authority.catalog.sha256,sourceRevision:authority.sourceCommit}}),snapshot={schema:'fia.worker-read-snapshot.v1',records:extension.records,current:extension.current,staticArtifacts:extension.staticArtifacts,artifacts:[],canonicalSources,generalizedAuthority:extension.authority,approvedAudioProofIndex:proof.descriptor};
 const bundled=await build({entryPoints:[resolve('server/faces/worker/entry.mjs')],bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false,plugins:[{name:'trusted-test-snapshot',setup(b){b.onResolve({filter:/generated\/snapshot\.json$/},()=>({path:'snapshot',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({contents:JSON.stringify(snapshot),loader:'json'}));}}]});
 const counts={external:0,canonical:0},options={...convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{FIA_API_ORIGIN:'https://dev.fiaguide.app'},durableObjects:{FIA_PREPARATION_JOBS:{className:'FiaPreparationJobs',useSQLite:true}},r2Buckets:['FIA_ORIGINALS'],serviceBindings:{ASSETS:async req=>{const path=new URL(req.url).pathname;assert.ok(/^\/content\/[a-zA-Z0-9._/-]+$/.test(path)&&!path.includes('..'));if(path.startsWith('/content/source-guides/'))counts.canonical++;let bytes;if(path===proof.descriptor.path)bytes=proof.bytes;else bytes=await readFile((path.startsWith('/content/source-guides/')?dir:publicRoot)+path);return new Response(bytes,{headers:{'Content-Type':'application/json','Content-Length':String(bytes.length)}});}},outboundService:()=>{counts.external++;throw Error('External work forbidden');}}),resourcePersistencePath:join(dir,'storage')};let mf=new Miniflare(options);
 const fetch=async(path,init)=>{const r=await mf.dispatchFetch('https://dev.fiaguide.app'+path,init),bytes=await r.arrayBuffer();return new Response(init?.method==='HEAD'?null:bytes,{status:r.status,headers:r.headers});};
 const rpc=async(name,args)=>{const r=await fetch('/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})}),b=await r.json();assert.equal(r.status,200);assert.ok(b.result?.structuredContent,JSON.stringify(b));return b.result.structuredContent;};
 const presentation=async record=>{const a=await rpc('read_artifact',{sha256:record.artifact.sha256});assert.equal(a.status,'ready',JSON.stringify(a));return JSON.parse(a.content);};
 try{
  const packId='eng.MRK-1-14-20',base=await rpc('read_pack',{packId}),demand=base.preparationDemand;
  const absent=await rpc('prepare_presentation',demand);assert.equal(absent.status,'ready',JSON.stringify(absent));const p0=await presentation(absent.record),a0=p0.activities.find(a=>a.id==='S01-U002-reading-1');assert.equal(a0.execution.narration.reason,'approved-audio-not-retained');
  const binding=proof.index.bindings.find(b=>b.packId===packId),source=await readFile(process.env.FIA_APPROVED_AUDIO||'/tmp/fia-client-01a10fba/product-journeys/offline-generation/fixtures/0599996af6b15cf55853cfee33d2b4405e5ee95bd9068f297c5b4b4c24284235.oga');
  let bucket=await mf.getR2Bucket('FIA_ORIGINALS');const store=createRetainedApprovedAudio({bucket,validateBinding:async()=>false});assert.equal((await store.retain({media:binding.media,bytes:source,provenance:{kind:'retained-reviewed-trace',sha256:hash(source)}})).status,'ready');
  const keysBefore=(await bucket.list()).objects.map(x=>x.key);assert.equal((await rpc('read_presentation_preparation',{jobId:absent.jobId})).status,'ready');assert.deepEqual((await bucket.list()).objects.map(x=>x.key),keysBefore,'status does not adopt newly seeded bytes');
  const ready=await rpc('prepare_presentation',demand);assert.equal(ready.status,'ready',JSON.stringify(ready));assert.notEqual(ready.jobId,absent.jobId,'new retained context supersedes warm blocked narration');const p=await presentation(ready.record),activity=p.activities.find(a=>a.id===a0.id);assert.equal(activity.execution.narration.action,'play-bound-audio');
  const descriptor=ready.record.execution.artifacts.find(a=>a.id===activity.execution.narration.artifact.id),raw=await rpc('read_artifact',{sha256:descriptor.sha256}),bound=JSON.parse(raw.content);assert.equal(bound.delivery.mime,'audio/ogg');assert.deepEqual(bound.playbackRange,{startSeconds:96.8,endSeconds:144.375});assert.equal(p.activities.filter(a=>a.execution.narration.action==='prepare-original').length,8,'guide demand bindings preserved');
  const route=bound.delivery.url,before=counts.canonical,keys=(await bucket.list()).objects.map(x=>x.key);
  for(const method of ['GET','HEAD']){const r=await fetch(route,{method});assert.equal(r.status,200);assert.equal(r.headers.get('Content-Type'),'audio/ogg');assert.equal(r.headers.get('ETag'),`"${hash(source)}"`);assert.equal(r.headers.get('Content-Length'),String(source.length));assert.equal(r.headers.get('Cache-Control'),'private, no-store');const body=new Uint8Array(await r.arrayBuffer());assert.equal(body.byteLength,method==='GET'?source.length:0);if(method==='GET')assert.equal(hash(body),binding.media.sha256);}
  assert.equal((await fetch(route,{headers:{Range:'bytes=0-1'}})).status,416);assert.equal((await fetch(route,{headers:{Origin:'https://evil.invalid'}})).status,403);assert.equal((await fetch(route+'?x=1')).status,400);
  assert.equal((await rpc('read_presentation_preparation',{jobId:ready.jobId})).status,'ready');assert.equal((await rpc('read_pack',{packId})).revision,ready.record.revision);assert.equal(counts.canonical,before);assert.deepEqual((await bucket.list()).objects.map(x=>x.key),keys);
  await mf.dispose();mf=new Miniflare(options);bucket=await mf.getR2Bucket('FIA_ORIGINALS');assert.equal((await fetch(route)).status,200);assert.equal((await rpc('read_pack',{packId})).revision,ready.record.revision);assert.equal(counts.canonical,before);assert.deepEqual((await bucket.list()).objects.map(x=>x.key),keys);
  await bucket.put(`approved-audio/media/${binding.media.sha256}.ogg`,new Uint8Array([1]));assert.equal((await fetch(route)).status,404);const range=await fetch(route,{headers:{Range:'bytes=0-1'}});assert.equal(range.status,404);assert.equal(range.headers.get('Content-Range'),null);assert.equal(counts.external,0);
  if(process.env.FIA_APPROVED_PROOF_DIR){const out=process.env.FIA_APPROVED_PROOF_DIR;await mkdir(out,{recursive:true});await writeFile(join(out,'presentation.json'),JSON.stringify(p));await writeFile(join(out,'bound.json'),raw.content);await writeFile(join(out,'record.json'),JSON.stringify(ready.record));await writeFile(join(out,'receipt.json'),JSON.stringify({base:base.revision,jobId:ready.jobId,revision:ready.record.revision,route,media:binding.media,counts,blockedJob:absent.jobId,scope:'actual MCP Worker SQLite/R2, retained local Opus fixture; no browser or deployment claim'},null,2));}
 }finally{await mf.dispose();await rm(dir,{recursive:true,force:true});}
});

test('public binary proxy refuses oversize and never waits for a stuck error-body cancellation',async()=>{
 const {serveApprovedAudioWorker}=await import('../../server/fia/preparation/executable-presentation-runtime.mjs'),h='a'.repeat(64),request=new Request(`https://dev.fiaguide.app/v1/approved-audio/${h}/${h}.ogg`);
 for(const response of [new Response(new ReadableStream({cancel(){return new Promise(()=>{});}}),{status:404}),new Response(new Uint8Array([1]),{headers:{'Content-Length':'16777217','Content-Type':'audio/ogg'}})]){
  const env={FIA_API_ORIGIN:'https://dev.fiaguide.app',FIA_ORIGINALS:{},FIA_PREPARATION_JOBS:{idFromName:()=>1,get:()=>({fetch:async()=>response})}};
  let timer;try{const result=await Promise.race([serveApprovedAudioWorker(request,env),new Promise((_,reject)=>{timer=setTimeout(()=>reject(Error('proxy-stalled')),1000);})]);assert.equal(result.status,404);await result.arrayBuffer();}finally{clearTimeout(timer);}
 }
});
