import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {createHash} from 'node:crypto';
import {buildApprovedAudioProofIndex} from '../../scripts/approved-audio-proof-index.mjs';import {createApprovedAudioBindings,validateApprovedDependencies} from '../../server/fia/preparation/approved-audio-bindings.mjs';
const root=new URL('../../apps/web/public/',import.meta.url),hash=b=>createHash('sha256').update(b).digest('hex');
async function fixture(){const reg=await readFile(new URL('content/registry.json',root)),r=JSON.parse(reg);const built=await buildApprovedAudioProofIndex({publicRoot:root.pathname,authority:{registrySha256:hash(reg),sourceRevision:r.sourceRevision}});const binding=built.index.bindings.find(b=>b.packId==='eng.MRK-1-14-20');assert.ok(binding);const readDependency=d=>readFile(new URL('.'+d.path,root));const baseBytes=await readDependency(binding.dependencies.find(d=>d.id==='base'));const context={packId:binding.packId,baseRevision:binding.baseRevision,sourceRevision:binding.sourceRevision,basePresentation:JSON.parse(baseBytes)};return {...built,binding,readDependency,context};}
test('actual proof closure validates; absent retained bytes stays typed blocked',async()=>{const f=await fixture(),port=createApprovedAudioBindings({...f,index:f.index,readRetained:async()=>null,eligible:async()=>true});assert.equal(await port.validateBinding(f.binding),true);const result=await port.resolve(f.context);assert.equal(result.narrationBindings['S01-U002-reading-1'].reason,'approved-audio-not-retained');assert.equal(result.boundArtifacts.length,0);assert.ok(f.binding.dependencies.length<=64);});
test('actual retained approved opus produces deterministic local bound artifact, no acquisition',async()=>{const f=await fixture(),bytes=await readFile('/tmp/fia-client-01a10fba/product-journeys/offline-generation/fixtures/0599996af6b15cf55853cfee33d2b4405e5ee95bd9068f297c5b4b4c24284235.oga');const port=createApprovedAudioBindings({...f,readRetained:async()=>bytes,eligible:async()=>true});const r=await port.resolve(f.context);assert.equal(r.narrationBindings['S01-U002-reading-1'].action,'play-bound-audio');const a=JSON.parse(new TextDecoder().decode(r.boundArtifacts[0].bytes));assert.match(a.delivery.url,/^\/v1\/approved-audio\/[a-f0-9]{64}\/[a-f0-9]{64}\.ogg$/);assert.deepEqual(a.playbackRange,{startSeconds:96.8,endSeconds:144.375});assert.equal(a.delivery.sha256,hash(bytes));});
test('proof corruption, revoked authority and forged activity refuse',async()=>{const f=await fixture();for(const change of [{eligible:async()=>false},{readDependency:async()=>new Uint8Array([1])}]){const p=createApprovedAudioBindings({...f,readRetained:async()=>null,eligible:async()=>true,...change});assert.equal(await p.validateBinding(f.binding),false);}const changed=structuredClone(f.binding);changed.playbackRange.endSeconds++;assert.equal(await createApprovedAudioBindings({...f,readRetained:async()=>null,eligible:async()=>true}).validateBinding(changed),false);});
test('dependency limits refuse without trimming and registry authority is mandatory',async()=>{assert.throws(()=>validateApprovedDependencies(Array(65).fill({})));await assert.rejects(()=>buildApprovedAudioProofIndex({publicRoot:root.pathname,authority:{registrySha256:'0'.repeat(64)}}));});
test('wrong activity identity, altered canonical asset, corrupt bytes and final revocation never become playable',async()=>{const f=await fixture(),retained=await readFile('/tmp/fia-client-01a10fba/product-journeys/offline-generation/fixtures/0599996af6b15cf55853cfee33d2b4405e5ee95bd9068f297c5b4b4c24284235.oga');for(const mutation of [p=>{p.activities.find(a=>a.id==='S01-U002-reading-1').id='invented';},p=>{p.assets['scripture-BereanStandardBible'].text+=' changed';}]){const context=structuredClone(f.context);mutation(context.basePresentation);const port=createApprovedAudioBindings({...f,eligible:async()=>true,readRetained:async()=>retained});assert.equal((await port.resolve(context)).boundArtifacts.length,0);}for(const readRetained of [async()=>new Uint8Array([1]),async()=>{throw Error('storage failed');}]){const port=createApprovedAudioBindings({...f,eligible:async()=>true,readRetained});assert.equal((await port.resolve(f.context)).narrationBindings['S01-U002-reading-1'].reason,'approved-audio-invalid');}let calls=0;const revoked=createApprovedAudioBindings({...f,eligible:async()=>++calls<3,readRetained:async()=>retained});assert.equal((await revoked.resolve(f.context)).boundArtifacts.length,0);});
test('duplicate, oversize, aggregate overflow and unsorted dependencies reject',async()=>{const f=await fixture(),d=f.binding.dependencies[0];for(const deps of [[d,d],[{...d,bytes:1048577}],Array.from({length:9},(_,i)=>({...d,id:`x${i}`,path:`/content/x${i}.json`,bytes:1048576})),[...f.binding.dependencies].reverse()])assert.throws(()=>validateApprovedDependencies(deps));});
