import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {buildGeneralizedSnapshot} from '../../server/fia/publication/generalized.mjs';
import {exportGuideSources} from '../../server/fia/compiler/presentation/export-guide-sources.mjs';
const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),hash=b=>createHash('sha256').update(b).digest('hex');
test('real P2/P3 ENES actual MCP SQLite/R2 runtime preserves source and typed unknown across restart',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'fia-execution-runtime-')),authority=JSON.parse(await readFile('server/fia/publication/trusted-generalized.json')),extension=buildGeneralizedSnapshot('apps/web/public',authority),canonicalSources=exportGuideSources({outputRoot:dir,sourceRevision:authority.sourceCommit}),snapshot={schema:'fia.worker-read-snapshot.v1',records:extension.records,current:extension.current,staticArtifacts:extension.staticArtifacts,artifacts:[],canonicalSources};
 const bundled=await build({entryPoints:[resolve('server/faces/worker/entry.mjs')],bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false,plugins:[{name:'isolated-real-snapshot',setup(b){b.onResolve({filter:/generated\/snapshot\.json$/},()=>({path:'generated/snapshot.json',namespace:'test-snapshot'}));b.onLoad({filter:/.*/,namespace:'test-snapshot'},()=>({contents:JSON.stringify(snapshot),loader:'json'}));}}]});
 const counts={assets:0,canonical:0,external:0},options={...convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{FIA_API_ORIGIN:'https://dev.fiaguide.app'},durableObjects:{FIA_PREPARATION_JOBS:{className:'FiaPreparationJobs',useSQLite:true}},r2Buckets:['FIA_ORIGINALS'],serviceBindings:{ASSETS:async request=>{counts.assets++;const path=new URL(request.url).pathname;assert.ok(/^\/content\/(?:source-guides\/|packs\/|registry\.json)/.test(path));if(path.startsWith('/content/source-guides/'))counts.canonical++;const bytes=await readFile(path.startsWith('/content/source-guides/')?dir+path:'apps/web/public'+path);return new Response(bytes,{headers:{'Content-Type':'application/json','Content-Length':String(bytes.length)}});}},outboundService:()=>{counts.external++;throw Error('No external network allowed');}}),resourcePersistencePath:join(dir,'storage')};let mf=new Miniflare(options);const receipts=[];
 const rpc=async(name,args)=>{const response=await mf.dispatchFetch('https://dev.fiaguide.app/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.ok(body.result?.structuredContent,JSON.stringify(body));return body.result.structuredContent;};
 try{for(const packId of ['eng.MRK-1-14-20','spa.MRK-1-14-20','eng.MRK-1-21-28','spa.MRK-1-21-28']){
  const record=await rpc('read_pack',{packId}),base=await rpc('read_artifact',{sha256:record.artifact.sha256}),original=JSON.parse(base.content);assert.equal(hash(base.content),record.revision);const before=counts.canonical;
  const prepared=await rpc('prepare_presentation',record.preparationDemand);assert.equal(prepared.status,'ready',JSON.stringify(prepared));const artifact=await rpc('read_artifact',{sha256:prepared.record.artifact.sha256});assert.equal(artifact.status,'ready',JSON.stringify(artifact));assert.equal(hash(artifact.content),prepared.record.revision);const presentation=JSON.parse(artifact.content);
  assert.equal(counts.canonical,before+1);assert.deepEqual(presentation.activities.map(a=>a.id),original.activities.map(a=>a.id));assert.deepEqual(presentation.assets,original.assets);assert.deepEqual(presentation.sections,original.sections);assert.deepEqual(presentation.activities.map(a=>a.sourceText),original.activities.map(a=>a.sourceText));assert.deepEqual(presentation.activities.filter(a=>a.kind==='scripture').map(a=>a.id),original.activities.filter(a=>a.kind==='scripture').map(a=>a.id));assert.equal(presentation.execution.schema,'fia-executable-presentation@1');assert.ok(presentation.activities.every(a=>a.execution));
  const current=await rpc('read_pack',{packId});assert.equal(current.revision,prepared.record.revision);const status=await rpc('read_presentation_preparation',{jobId:prepared.jobId});assert.equal(status.status,'ready');assert.equal(counts.canonical,before+1,'reads never re-resolve source or run preparation');receipts.push({packId,prepared,artifact,presentation,baseRevision:record.revision});
 }
 const canonicalBefore=counts.canonical;await mf.dispose();mf=new Miniflare(options);for(const item of receipts){const record=await rpc('read_pack',{packId:item.packId}),artifact=await rpc('read_artifact',{sha256:record.artifact.sha256});assert.equal(record.revision,item.prepared.record.revision);assert.equal(artifact.content,item.artifact.content);assert.equal((await rpc('read_presentation_preparation',{jobId:item.prepared.jobId})).status,'ready');}assert.equal(counts.canonical,canonicalBefore);assert.equal(counts.external,0);
 const out=process.env.FIA_EXECUTION_PROOF_DIR;if(out){await mkdir(out,{recursive:true});const p2=receipts[0];await writeFile(join(out,'p2-presentation.json'),p2.artifact.content);await writeFile(join(out,'p2-record.json'),JSON.stringify(p2.prepared.record,null,2));await writeFile(join(out,'runtime-proof.json'),JSON.stringify({scope:'real source actual MCP Worker SQLite/R2 no semantic provider; Product flow remains unresolved',counts,modelCalls:0,receipts:receipts.map(r=>({packId:r.packId,baseRevision:r.baseRevision,revision:r.prepared.record.revision,jobId:r.prepared.jobId,activities:r.presentation.activities.length,execution:r.presentation.execution}))},null,2));}
 }finally{await mf.dispose();await rm(dir,{recursive:true,force:true});}
});
