import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {readFile,mkdtemp,rm,mkdir,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {buildGeneralizedSnapshot} from '../../server/fia/publication/generalized.mjs';
import {canonicalJSONString} from '../../server/fia/preparation/contract.mjs';
import {exportGuideSources} from '../../server/fia/compiler/presentation/export-guide-sources.mjs';
const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),hash=b=>createHash('sha256').update(b).digest('hex');
test('real P2/P3 ENES actual MCP SQLite/R2 runtime preserves source and typed unknown across restart',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'fia-execution-runtime-')),authority=JSON.parse(await readFile('server/fia/publication/trusted-generalized.json')),extension=buildGeneralizedSnapshot('apps/web/public',authority),canonicalSources=exportGuideSources({outputRoot:dir,sourceRevision:authority.sourceCommit}),snapshot={schema:'fia.worker-read-snapshot.v1',records:extension.records,current:extension.current,staticArtifacts:extension.staticArtifacts,artifacts:[],canonicalSources};
 const bundled=await build({entryPoints:[resolve('server/faces/worker/entry.mjs')],bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false,plugins:[{name:'isolated-real-snapshot',setup(b){b.onResolve({filter:/generated\/snapshot\.json$/},()=>({path:'generated/snapshot.json',namespace:'test-snapshot'}));b.onLoad({filter:/.*/,namespace:'test-snapshot'},()=>({contents:JSON.stringify(snapshot),loader:'json'}));}}]});
 const mediaRoot=process.env.FIA_MEDIA_PROOF_ROOT,counts={assets:0,canonical:0,external:0},options={...convertV4MiniflareOptions({modules:true,script:bundled.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{FIA_API_ORIGIN:'https://dev.fiaguide.app'},durableObjects:{FIA_PREPARATION_JOBS:{className:'FiaPreparationJobs',useSQLite:true}},r2Buckets:['FIA_ORIGINALS'],serviceBindings:{ASSETS:async request=>{counts.assets++;const path=new URL(request.url).pathname;assert.ok(/^\/content\/(?:source-guides\/|packs\/|registry\.json)/.test(path)||/^\/offline\/[a-zA-Z0-9.-]+\.json$/.test(path));if(path.startsWith('/content/source-guides/'))counts.canonical++;let bytes;try{bytes=await readFile(path.startsWith('/content/source-guides/')?dir+path:'apps/web/public'+path);}catch(error){if(error.code!=='ENOENT')throw error;if(mediaRoot&&path.startsWith('/offline/')){try{bytes=await readFile(mediaRoot+path);}catch(error){if(error.code!=='ENOENT')throw error;}}if(!bytes)return new Response('Not found',{status:404});}return new Response(bytes,{headers:{'Content-Type':'application/json','Content-Length':String(bytes.length)}});}},outboundService:()=>{counts.external++;throw Error('No external network allowed');}}),resourcePersistencePath:join(dir,'storage')};let mf=new Miniflare(options);const receipts=[];
 const rpc=async(name,args)=>{const response=await mf.dispatchFetch('https://dev.fiaguide.app/mcp',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json, text/event-stream','MCP-Protocol-Version':'2025-06-18'},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});const body=await response.json();assert.equal(response.status,200,JSON.stringify(body));assert.ok(body.result?.structuredContent,JSON.stringify(body));return body.result.structuredContent;};
 try{for(const packId of ['eng.MRK-1-14-20','spa.MRK-1-14-20','eng.MRK-1-21-28','spa.MRK-1-21-28']){
  const record=await rpc('read_pack',{packId}),base=await rpc('read_artifact',{sha256:record.artifact.sha256}),original=JSON.parse(base.content);assert.equal(hash(base.content),record.revision);const before=counts.canonical;
  const prepared=await rpc('prepare_presentation',record.preparationDemand);assert.equal(prepared.status,'ready',JSON.stringify(prepared));const artifact=await rpc('read_artifact',{sha256:prepared.record.artifact.sha256});assert.equal(artifact.status,'ready',JSON.stringify(artifact));assert.equal(hash(artifact.content),prepared.record.revision);const presentation=JSON.parse(artifact.content);
  assert.equal(counts.canonical,before+1);assert.deepEqual(presentation.activities.map(a=>a.id),original.activities.map(a=>a.id));assert.deepEqual(presentation.assets,original.assets);assert.deepEqual(presentation.sections,original.sections);assert.deepEqual(presentation.activities.map(a=>a.sourceText),original.activities.map(a=>a.sourceText));assert.deepEqual(presentation.activities.filter(a=>a.kind==='scripture').map(a=>a.id),original.activities.filter(a=>a.kind==='scripture').map(a=>a.id));assert.equal(presentation.execution.schema,'fia-executable-presentation@1');assert.ok(presentation.activities.every(a=>a.execution));
  assert.deepEqual(prepared.record.execution.mediaIdentity,{packId,revision:record.revision});assert.equal(prepared.record.execution.mediaAssetsSha256,hash(canonicalJSONString(original.assets)));const bound=[];for(const descriptor of prepared.record.execution.artifacts){const value=await rpc('read_artifact',{sha256:descriptor.sha256});assert.equal(value.status,'ready');assert.equal(hash(value.content),descriptor.sha256);assert.equal(Buffer.byteLength(value.content),descriptor.bytes);const json=JSON.parse(value.content);assert.equal(json.schema,'fia-bound-narration-demand@1');assert.equal(json.id,descriptor.id);assert.equal(json.identity.packId,packId);assert.equal(json.identity.presentationRevision,record.revision);const owner=original.activities.find(a=>a.id===json.identity.activityId);assert.ok(owner);assert.equal(json.identity.sourceUnitId,owner.sourceUnitId??owner.fulfills);assert.equal(json.identity.sourceTextSha256,owner.sourceSha256??owner.sourceTextSha256);bound.push({descriptor,content:value.content});}const manifestResponse=await mf.dispatchFetch(`https://dev.fiaguide.app/offline/${prepared.record.execution.mediaIdentity.packId}.json`);const manifestContent=await manifestResponse.text();const mediaReceipt={identity:prepared.record.execution.mediaIdentity,manifestStatus:manifestResponse.status,reason:manifestResponse.status===404?'packaged offline manifest absent; actual media status/playback unproved':null};if(mediaRoot){assert.equal(manifestResponse.status,200);const manifest=JSON.parse(manifestContent);assert.equal(manifest.packId,packId);assert.equal(manifest.presentationRevision,prepared.record.execution.mediaIdentity.revision);mediaReceipt.manifestSha256=hash(manifestContent);mediaReceipt.mediaDescriptors=manifest.files.filter(f=>f.group!=='core');mediaReceipt.verifiedFiles=[];for(const file of manifest.files){let bytes;try{bytes=await readFile(mediaRoot+file.path);}catch(error){if(error.code!=='ENOENT')throw error;continue;}assert.equal(hash(bytes),file.sha256);assert.equal(bytes.length,file.bytes);mediaReceipt.verifiedFiles.push({path:file.path,sha256:file.sha256,bytes:file.bytes});}mediaReceipt.reason=mediaReceipt.mediaDescriptors.some(f=>f.group==='image')?'image descriptors available':'no image/map descriptors in this actual packaged manifest; visual playback unproved';}else assert.equal(manifestResponse.status,404,'unbuilt checkout has no offline manifests; supply FIA_MEDIA_PROOF_ROOT to exercise actual build');const current=await rpc('read_pack',{packId});assert.equal(current.revision,prepared.record.revision);const status=await rpc('read_presentation_preparation',{jobId:prepared.jobId});assert.equal(status.status,'ready');assert.equal(counts.canonical,before+1,'reads never re-resolve source or run preparation');receipts.push({packId,prepared,artifact,presentation,bound,mediaReceipt,manifestContent,baseRevision:record.revision});
 }
 const canonicalBefore=counts.canonical;await mf.dispose();mf=new Miniflare(options);for(const item of receipts){const record=await rpc('read_pack',{packId:item.packId}),artifact=await rpc('read_artifact',{sha256:record.artifact.sha256});assert.equal(record.revision,item.prepared.record.revision);assert.equal(artifact.content,item.artifact.content);assert.equal((await rpc('read_presentation_preparation',{jobId:item.prepared.jobId})).status,'ready');}assert.equal(counts.canonical,canonicalBefore);assert.equal(counts.external,0);
 const out=process.env.FIA_EXECUTION_PROOF_DIR;if(out){await mkdir(out,{recursive:true});const p2=receipts[0];await writeFile(join(out,'p2-presentation.json'),p2.artifact.content);await writeFile(join(out,'p2-record.json'),JSON.stringify(p2.prepared.record,null,2));await mkdir(join(out,'artifacts'),{recursive:true});for(const r of receipts){if(r.mediaReceipt.manifestStatus===200)await writeFile(join(out,r.packId+'-offline.json'),r.manifestContent);await writeFile(join(out,'artifacts',r.prepared.record.artifact.sha256+'.json'),r.artifact.content);for(const b of r.bound)await writeFile(join(out,'artifacts',b.descriptor.sha256+'.json'),b.content);}await writeFile(join(out,'catalog.json'),JSON.stringify({schema:'fia-execution-proof-catalog@1',records:receipts.map(r=>r.prepared.record)},null,2));await writeFile(join(out,'runtime-proof.json'),JSON.stringify({scope:'real source actual MCP Worker SQLite/R2 no semantic provider; Product flow remains unresolved',counts,modelCalls:0,receipts:receipts.map(r=>({packId:r.packId,baseRevision:r.baseRevision,revision:r.prepared.record.revision,jobId:r.prepared.jobId,activities:r.presentation.activities.length,media:r.mediaReceipt,boundArtifacts:r.bound.map(b=>b.descriptor),execution:r.presentation.execution}))},null,2));}
 }finally{await mf.dispose();await rm(dir,{recursive:true,force:true});}
});
