#!/usr/bin/env node
// Generates src/tokens/alpha.css from design/tokens.json.
// design/tokens.json is a copy of the cookbook's design/alpha-system/tokens.json
// (fia-alpha-tokens 0.1.0-draft). The JSON is the source of truth; never edit the CSS by hand.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(readFileSync(resolve(root, 'design/tokens.json'), 'utf8'));
const out = resolve(root, 'src/tokens/alpha.css');

const lines = [];
const push = (...s) => lines.push(...(s.length ? s : ['']));

push(`/* GENERATED by scripts/build-tokens.mjs from design/tokens.json`);
push(
  ` * ${tokens.$meta.name} ${tokens.$meta.version} (${tokens.$meta.date}), kit ${tokens.$meta.kit}`,
);
push(` * Do not edit by hand. */`);
push();

// --- colors -----------------------------------------------------------------
const colorVars = (theme) => {
  const rows = [];
  for (const [name, v] of Object.entries(tokens.color)) {
    if (typeof v[theme] === 'string') rows.push(`  --fia-${name}: ${v[theme]};`);
    if (v.text_on_tint) rows.push(`  --fia-${name}-text: ${v.text_on_tint[theme]};`);
    if (v.text_on_chip) rows.push(`  --fia-${name}-text: ${v.text_on_chip[theme]};`);
  }
  return rows;
};
const glass = (set) =>
  Object.entries(set)
    .filter(([k]) => k !== 'dark')
    .map(([k, v]) => `  --fia-glass-${k}: ${v};`);

// --- type -------------------------------------------------------------------
const t = tokens.type;
const typeVars = [];
typeVars.push(`  --fia-text-scale: ${t.scale_steps.base};`);
for (const [k, rem] of Object.entries(t.sizes_rem)) {
  typeVars.push(`  --fia-fs-${k}: calc(${rem}rem * var(--fia-text-scale));`);
}
for (const [k, w] of Object.entries(t.weights)) typeVars.push(`  --fia-fw-${k}: ${w};`);
typeVars.push(`  --fia-lh: ${t.fonts.latin.lh};`);
typeVars.push(`  --fia-lh-scripture: ${t.fonts.latin.lh_scripture};`);
typeVars.push(`  --fia-font-ui: ${t.fonts.latin.ui};`);
typeVars.push(`  --fia-font-scripture: ${t.fonts.latin.scripture};`);
typeVars.push(`  --fia-min-rendered-px: ${t.min_rendered_px}px;`);

// --- spacing / radius / motion / interaction --------------------------------
const s = tokens.spacing;
const spaceVars = s.kit_ladder_px.map((px, i) => `  --fia-space-${i + 1}: ${px}px;`);
spaceVars.push(
  `  --fia-gutter: ${s.gutter}px;`,
  `  --fia-gutter-wide: ${s.gutter_wide}px;`,
  `  --fia-gap-stack: ${s.gap_stack}px;`,
  `  --fia-gap-inline: ${s.gap_inline}px;`,
  `  --fia-card-pad: ${s.card_pad}px;`,
  `  --fia-card-pad-wide: ${s.card_pad_wide}px;`,
  `  --fia-dock-h: ${s.dock_h}px;`,
  `  --fia-dock-h-stacked: ${s.dock_h_stacked}px;`,
  `  --fia-safe-top: ${s.safe_top};`,
  `  --fia-safe-bottom: ${s.safe_bottom};`,
  `  --fia-content-max-width: ${s.content_max_width}px;`,
);
const radiusVars = Object.entries(tokens.radius).map(([k, v]) => `  --fia-r-${k}: ${v}px;`);
const blurVars = Object.entries(tokens.elevation.blur_px).map(
  ([k, v]) => `  --fia-blur-${k}: ${v}px;`,
);
const m = tokens.motion;
const motionVars = Object.entries(m.dur_ms).map(([k, v]) => `  --fia-dur-${k}: ${v}ms;`);
motionVars.push(
  `  --fia-ease-liquid: ${m.ease.liquid};`,
  `  --fia-ease-damp: ${m.ease.damp};`,
  `  --fia-press-scale: ${m.press_scale};`,
);
const i = tokens.interaction;
const interVars = [
  `  --fia-tap-min: ${i.tap_min_px}px;`,
  `  --fia-tap-primary: ${i.tap_primary_px}px;`,
  `  --fia-tap-close: ${i.tap_close_px}px;`,
  `  --fia-long-press: ${i.long_press_ms}ms;`,
  `  --fia-primary-slot-h: 72px;`,
];

push(`:root {`);
push(`  color-scheme: light dark;`);
push(...colorVars('light'));
push(...glass(tokens.elevation.glass_fill));
push(...typeVars, ...spaceVars, ...radiusVars, ...blurVars, ...motionVars, ...interVars);
push(`}`);
push();
push(`/* dark: system preference unless the app pins light; explicit pin wins */`);
push(`@media (prefers-color-scheme: dark) {`);
push(`  :root:not([data-theme='light']) {`);
push(...colorVars('dark').map((l) => '  ' + l));
push(...glass(tokens.elevation.glass_fill.dark).map((l) => '  ' + l));
push(`  }`);
push(`}`);
push(`:root[data-theme='dark'] {`);
push(...colorVars('dark'));
push(...glass(tokens.elevation.glass_fill.dark));
push(`}`);
push();
push(
  `/* large-print steps (R-601): data-text-step on <html>; caption hides at ${t.hide_at_steps.caption.join('/')} */`,
);
for (const [step, mult] of Object.entries(t.scale_steps)) {
  if (step === 'base') continue;
  push(`:root[data-text-step='${step}'] { --fia-text-scale: ${mult}; }`);
}
for (const step of t.hide_at_steps.caption) {
  push(`:root[data-text-step='${step}'] .fia-caption { display: none; }`);
}
push();
push(`/* per-script fonts and line-heights (R-607) */`);
for (const [script, f] of Object.entries(t.fonts)) {
  if (script === 'latin') continue;
  const sel = f.langs.map((l) => `:lang(${l})`).join(', ');
  push(`${sel} {`);
  push(`  --fia-font-ui: ${f.ui};`);
  push(`  --fia-font-scripture: ${f.scripture};`);
  push(`  --fia-lh: ${f.lh};`);
  push(`  --fia-lh-scripture: ${f.lh_scripture};`);
  push(`  letter-spacing: ${t.letter_spacing_non_latin};`);
  push(`}`);
}
push();
push(`/* reduced motion: ${m.reduced_motion} */`);
push(`@media (prefers-reduced-motion: reduce) {`);
push(`  :root {`);
for (const k of Object.keys(m.dur_ms)) push(`    --fia-dur-${k}: 1ms;`);
push(`    --fia-press-scale: 1;`);
push(`  }`);
push(`}`);
push();
push(`/* base: ground, text, focus ring (${i.focus_ring}) */`);
push(
  `html { background: var(--fia-ground); color: var(--fia-text-body); font-family: var(--fia-font-ui); font-size: ${t.root_px}px; line-height: var(--fia-lh); }`,
);
push(`body { margin: 0; min-height: 100dvh; background: var(--fia-surface-app); }`);
push(`:focus-visible { outline: 3px solid var(--fia-focus-ring); outline-offset: 3px; }`);
push(
  `:root { --fia-theme-color-light: ${tokens.color['pwa-theme-color'].light}; --fia-theme-color-dark: ${tokens.color['pwa-theme-color'].dark}; }`,
);

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join('\n') + '\n');
console.log(`tokens: wrote ${out} (${lines.length} lines)`);
