import test from 'node:test';import assert from 'node:assert/strict';
import {canonicalJSONString,sha256} from '../../server/fia/preparation/contract.mjs';
import {projectExecutablePresentation,validateExecutablePresentation} from '../../server/fia/compiler/presentation/source-action-projector.mjs';
import {createExecutablePresentationService} from '../../server/fia/preparation/executable-presentation-service.mjs';
import {executableFixture} from './fixtures/executable-presentation-fixture.mjs';
const project=f=>projectExecutablePresentation({...f.context,decisions:[f.decision]});
function ports(){const values=new Map(),blobs=new Map();return {values,blobs,storage:{transaction:async fn=>fn({get:async k=>structuredClone(values.get(k)),put:async(k,v)=>values.set(k,structuredClone(v))})},artifacts:{async write(bytes){const digest=await sha256(bytes),reference=`preparation/executor/${digest}.json`;if(!blobs.has(reference))blobs.set(reference,new Uint8Array(bytes));return{reference,sha256:digest};},async read(d){return new Uint8Array(blobs.get(d.reference)??[]);}}};}
test('portable full presentation has exact focal order, manual adjacent resources and one bound source narration',async()=>{
 for(const language of ['eng','spa'])for(const reverseCandidates of [false,true]){const f=await executableFixture({language,reverseCandidates,suffix:language}),out=await project(f),[intro,primary,secondary,next]=out.presentation.activities;assert.equal(intro.execution.completion.action,'advance-after-narration');assert.equal(primary.assetId,f.ids.image);assert.equal(primary.kind,'discussion');assert.equal(primary.completion,'confirm');assert.equal(primary.narration,f.context.canonicalUnits[1].text);assert.equal(primary.execution.narration.action,'prepare-original');assert.equal(secondary.id,`${f.ids.cue}-resource-${f.ids.map}`);assert.equal(secondary.assetId,f.ids.map);assert.equal(secondary.narration,'');assert.equal(secondary.audioSrc,null);assert.deepEqual(secondary.execution.narration,{action:'none'});assert.equal(next.id,f.ids.next);assert.equal(secondary.completion,'confirm');assert.deepEqual(out.presentation.assets,f.context.basePresentation.assets);assert.deepEqual((await project(f)),out);}
});
test('independent partial slots preserve image while map unresolved and unknown opener remains manual with narration',async()=>{
 const f=await executableFixture({ambiguousMap:true,unknownTransition:true}),out=await project(f);assert.equal(out.presentation.activities.length,3);assert.equal(out.presentation.activities[1].assetId,f.ids.image);assert.equal(out.provenance.unresolved[0].resourceKind,'map');assert.equal(out.provenance.transitions[0].status,'transition-unknown');assert.equal(out.presentation.activities[0].completion,'confirm');assert.equal(out.presentation.activities[0].execution.narration.action,'prepare-original');
});
test('forged anchor, invented kind/ID, compound pause, invalid bound reference and ID collision fail before executable output',async()=>{
 for(const mutation of [f=>f.decision.input.sourceAnchor.unitOrdinal++,f=>f.decision.result.resourceAssociations[0].candidateResourceIds=['invented'],f=>f.decision.result.cueRoles.roles.pauseOnly=true,f=>f.context.narrationBindings[f.ids.cue].demand.sha256='f'.repeat(64),f=>f.context.basePresentation.activities.push({...f.context.basePresentation.activities[2],id:`${f.ids.cue}-resource-${f.ids.map}`})]){const f=await executableFixture();mutation(f);await assert.rejects(project(f));}
 const f=await executableFixture(),out=await project(f);out.presentation.activities[2].execution.narration=out.presentation.activities[1].execution.narration;await assert.rejects(validateExecutablePresentation(out.presentation,{boundArtifacts:f.context.boundArtifacts}));
});
test('service explicit demand persists decisions/sidecars; read and warm demand invoke zero provider work; revoked read refuses',async()=>{
 const f=await executableFixture(),p=ports();let calls=0,resolves=0,enabled=true;
 const context=structuredClone(f.context);delete context.decisions[0].explicitResult;
 const service=()=>createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>{resolves++;return structuredClone(context);},eligible:async()=>enabled,interpret:{dependencySha256:'b'.repeat(64),run:async()=>{calls++;return structuredClone(f.decision.result);}}});
 let s=service();const first=await s.request(f.args);assert.equal(first.status,'ready');assert.equal(calls,1);assert.equal(first.presentation.activities[1].assetId,f.ids.image);s=service();const warm=await s.read({jobId:first.jobId});assert.equal(warm.status,'ready');assert.equal(calls,1);assert.equal(resolves,1);assert.deepEqual(warm.presentation,first.presentation);assert.equal((await s.request(f.args)).status,'ready');assert.equal(calls,1);enabled=false;assert.equal((await s.read({jobId:first.jobId})).status,'blocked');
});
test('unavailable provider produces typed uncertainty and safe script rather than fabricating resource/transition flow',async()=>{
 const f=await executableFixture({unknownTransition:true}),p=ports(),context=structuredClone(f.context);delete context.decisions[0].explicitResult;const s=createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>context,eligible:async()=>true});const outcome=await s.request(f.args);assert.equal(outcome.status,'ready');assert.equal(outcome.presentation.activities.length,3);assert.equal(outcome.provenance.unresolved.length,2);assert.equal(outcome.provenance.transitions[0].status,'transition-unknown');assert.equal(outcome.presentation.activities[1].execution.narration.action,'prepare-original');
});
test('service refuses corrupted immutable context on read without resolving or interpreting',async()=>{
 const f=await executableFixture(),p=ports(),s=createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>structuredClone(f.context),eligible:async()=>true});const out=await s.request(f.args),row=p.values.get('executable-presentation:job:'+out.jobId);p.blobs.set(row.context.reference,new TextEncoder().encode('corrupt'));await assert.rejects(s.read({jobId:out.jobId}),/execution-artifact-integrity/);
});
test('explicitly confirmed multiple views survive one slot; ambiguous alternatives never select one',async()=>{
 const f=await executableFixture(),input=f.decision.input,result=f.decision.result,map=f.context.basePresentation.assets[f.ids.map];map.kind='image';const candidate=input.candidates.find(c=>c.resourceId===f.ids.map);candidate.kind='image';
 input.intentSlots=[{slotId:'views',resourceKind:'image',relation:'requested-medium',candidateResourceIds:[f.ids.map,f.ids.image]}];result.inputSha256=await sha256(canonicalJSONString(input));result.resourceAssociations=[{slotId:'views',resourceKind:'image',relation:'requested-medium',outcome:'matched',candidateResourceIds:[f.ids.map,f.ids.image],evidenceUnitIds:[f.ids.cue],reason:'requested-candidate-match'}];
 const accepted=await project(f);assert.deepEqual(accepted.presentation.activities.slice(1,3).map(a=>a.assetId),[f.ids.image,f.ids.map]);result.resourceAssociations[0].outcome='ambiguous';result.resourceAssociations[0].reason='competing-candidates';const ambiguous=await project(f);assert.equal(ambiguous.presentation.activities.length,3);assert.equal(ambiguous.presentation.activities[1].assetId,undefined);assert.deepEqual(ambiguous.provenance.unresolved[0].candidateResourceIds,[f.ids.map,f.ids.image]);
});
test('candidate prose/revision/title/language must be canonical metadata, not a self-hashed fabrication',async()=>{
 for(const mutate of [c=>{c.title='Invented meaning';},c=>{c.sourceRevision='e'.repeat(40);},c=>{c.language='spa';},async c=>{c.sourceText='Fabricated definition';c.sourceTextSha256=await sha256(c.sourceText);}]){const f=await executableFixture();await mutate(f.decision.input.candidates[0]);f.decision.result.inputSha256=await sha256(canonicalJSONString(f.decision.input));await assert.rejects(project(f),/execution-candidate-canonical-binding/);}
});
test('bound original demand for another pack, revision or language cannot borrow same unit ID/text',async()=>{
 for(const changed of [{packId:'eng.MRK-9-1-9'},{presentationRevision:'f'.repeat(64)},{language:'spa'}]){const f=await executableFixture(),a=f.context.boundArtifacts[0],doc=JSON.parse(new TextDecoder().decode(a.bytes));Object.assign(doc.identity,changed);a.bytes=new TextEncoder().encode(canonicalJSONString(doc));a.sha256=await sha256(a.bytes);f.context.narrationBindings[f.ids.intro].demand.sha256=a.sha256;await assert.rejects(project(f),/execution-narration-binding/);}
});
test('trusted restart recovery marks persisted in-flight decisions uncertain without interpreting or projecting',async()=>{
 const f=await executableFixture(),p=ports();let calls=0;const context=structuredClone(f.context);delete context.decisions[0].explicitResult;
 const factory=()=>createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>structuredClone(context),eligible:async()=>true,interpret:{dependencySha256:'b'.repeat(64),run:async()=>{calls++;return structuredClone(f.decision.result);}}});
 const first=await factory().request(f.args);const entry=[...p.values].find(([key])=>key.startsWith('decision-job:'));p.values.set(entry[0],{...entry[1],state:'preparing',reason:null,artifact:null});const recovered=await factory().recoverInterrupted({jobIds:[first.jobId]});assert.equal(recovered[0].status,'reconciled');assert.equal((await factory().read({jobId:first.jobId})).status,'blocked');assert.equal(calls,1);
});
test('rehashing a cached sidecar cannot replace verified provenance while preserving its presentation result',async()=>{
 const f=await executableFixture(),p=ports(),s=createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>structuredClone(f.context),eligible:async()=>true}),out=await s.request(f.args);
 const [key,pointer]=[...p.values].find(([key])=>key.startsWith('request-sidecar:')),value=JSON.parse(new TextDecoder().decode(p.blobs.get(pointer.artifact.reference)));value.decision.reason='forged';value.decision.evidence=[{reference:'missing-evidence',sha256:'f'.repeat(64)}];const bytes=new TextEncoder().encode(canonicalJSONString(value)),artifact=await p.artifacts.write(bytes);p.values.set(key,{...pointer,artifact});await assert.rejects(s.read({jobId:out.jobId}),/sidecar-evidence-refused/);
});
test('immutable job ID cannot be rebound to a different valid retained context',async()=>{
 const f=await executableFixture(),p=ports(),s=createExecutablePresentationService({...p,policySha256:f.policySha256,resolve:async()=>structuredClone(f.context),eligible:async()=>true}),out=await s.request(f.args),key='executable-presentation:job:'+out.jobId,row=p.values.get(key),context=JSON.parse(new TextDecoder().decode(p.blobs.get(row.context.reference)));context.transitionEvidence=[];const artifact=await p.artifacts.write(new TextEncoder().encode(canonicalJSONString(context)));p.values.set(key,{...row,context:artifact});await assert.rejects(s.read({jobId:out.jobId}),/execution-request-integrity/);
});
test('existing engine executes supplied auto opener and adjacent manual resources without completion shortcuts',async()=>{
 const {createSession,reduceSession,presentStage}=await import('../../apps/web/src/lib/engine.js');
 for(const mode of ['scripted','conversation']){const f=await executableFixture(),{presentation}=await project(f),activities=presentation.activities;let state=createSession(activities);const send=type=>state=reduceSession(state,{type},activities);state=reduceSession(state,{type:'SET_MODE',mode},activities);send('PLAY');send('NARRATION_END');assert.equal(state.index,1);assert.equal(presentStage(state,activities).focal,f.ids.image);send('NARRATION_END');send('MEDIA_END');assert.equal(state.index,1);send('CONTINUE');assert.equal(state.index,2);assert.equal(presentStage(state,activities).focal,f.ids.map);assert.equal(activities[state.index].execution.narration.action,'none');send('NARRATION_END');send('MEDIA_END');assert.equal(state.index,2);send('CONTINUE');assert.equal(activities[state.index].id,f.ids.next);}
});
