import test from'node:test';import assert from'node:assert/strict';import{createRequire}from'node:module';import{resolve,join}from'node:path';import{readFile,mkdtemp,rm,mkdir,writeFile}from'node:fs/promises';import{createReadStream}from'node:fs';import{tmpdir}from'node:os';import{createHash}from'node:crypto';import{createLocalWindowAdapter}from'../../server/fia/preparation/executor/local-window-adapter.mjs';import{createBoundedSourceReader}from'../../server/fia/preparation/executor/observed-stream-acquisition.mjs';
const sha=b=>createHash('sha256').update(b).digest('hex'),root=resolve('.');
const modulePath=name=>JSON.stringify(resolve('server/fia/preparation/executor/'+name+'.mjs'));
const worker=`import{qualifyUnitDerivative}from ${JSON.stringify(resolve('server/fia/preparation/unit-derivative-qualification.mjs'))};import{FiaPreparationJobs as Base,servePreparation}from ${JSON.stringify(resolve('server/fia/preparation/worker.mjs'))};import{GUIDE_SOURCE_EXECUTION_POLICY}from ${JSON.stringify(resolve('server/fia/preparation/guide-dispatch.mjs'))};import{bindStreamedGuideCapabilities}from ${modulePath('streamed-guide-factory')};import{createVerifiedPcmStore}from ${modulePath('verified-pcm-store')};import{createUnitDerivativePreparation}from ${modulePath('unit-derivative-preparation')};import{planRecognitionWindows,projectRecognitionWindows}from ${modulePath('recognition-window-plan')};import{canonicalJSONString,sha256}from ${JSON.stringify(resolve('server/fia/preparation/contract.mjs'))};
let admitted=true,revokeOnWav=false;const eligible=()=>admitted,profile=e=>({...JSON.parse(e.PROFILE),sourceExecutionPolicy:GUIDE_SOURCE_EXECUTION_POLICY}),encode=x=>new TextEncoder().encode(canonicalJSONString(x));
export class FiaPreparationJobs extends Base{constructor(ctx,env){super(ctx,{...env,FIA_ORIGINALS:{get:async(...args)=>{const object=await env.FIA_ORIGINALS.get(...args);if(revokeOnWav&&args[0].endsWith('.wav')){revokeOnWav=false;admitted=false;}return object;},put:env.FIA_ORIGINALS.put.bind(env.FIA_ORIGINALS)}});}guideExecutionCapabilities(){const env=this.env,p=profile(env),base=bindStreamedGuideCapabilities({...p,acquisitionPolicy:JSON.parse(env.ACQUISITION_POLICY),eligibility:eligible,fetchSource:(url,options)=>env.SOURCE.fetch(new Request(url,options)),recognitionFactory:({artifacts})=>({paid:false,dependencySha256:p.recognitionSha256,resultSchema:'fia-window-guide-recognition@1',async run({input,nodeOutputs}){await(await env.COUNT.fetch('https://count.invalid/')).text();const rawBytes=await Promise.all(['raw0','raw1'].map(async path=>new Uint8Array(await(await env.INPUT.fetch('https://input.invalid/'+path)).arrayBuffer()))),raws=rawBytes.map(b=>JSON.parse(new TextDecoder().decode(b))),{policy,...planInput}=raws[0].planIdentity,plan=await planRecognitionWindows(planInput),source=await artifacts.verifySource(nodeOutputs.acquire),records=[],stored=[];for(let i=0;i<raws.length;i++){const a=await artifacts.write(rawBytes[i]);stored.push({...a,windowSha256:raws[i].windowSha256});records.push({state:'completed',windowSha256:raws[i].windowSha256,rawSha256:a.sha256,rawBytes:rawBytes[i]});}return artifacts.write(encode({schema:'fia-window-guide-recognition@1',status:'candidate',recognitionInput:{language:input.language,modelRecipe:input.modelRecipe},source:{sha256:source.sha256,bytes:source.bytes},plan,artifacts:stored,projection:await projectRecognitionWindows(plan,records)}));}})});
return{...base,unitDerivativeSha256:env.UNIT_POLICY,unitPlayback:{contractSha256:env.QUALIFICATION_SHA,async project({candidate,consumer}){const result=await qualifyUnitDerivative({candidate,consumer,qualificationBytes:new TextEncoder().encode(env.QUALIFICATION_TEXT),qualificationSha256:env.QUALIFICATION_SHA});return{outcome:'accept',reason:'retained-development-byte-equivalence',capability:'original-unit-audio',evidence:[candidate.wav],result};},async validate(value,{candidate,consumer}){const expected=await qualifyUnitDerivative({candidate,consumer,qualificationBytes:new TextEncoder().encode(env.QUALIFICATION_TEXT),qualificationSha256:env.QUALIFICATION_SHA});return canonicalJSONString(value.decision.result)===canonicalJSONString(expected);}},create(ports){const adapters=base.create(ports),pcmStore=createVerifiedPcmStore({storage:ports.storage,bucket:ports.bucket,dependencySha256:env.PCM_POLICY,eligibility:eligible,verifySource:ports.artifacts.verifySource,decode:async(req,{signal})=>{const r=await env.PCM.fetch('https://local.invalid/decode',{method:'POST',body:JSON.stringify(req),signal});if(!r.ok)throw Error('decode');return{receipt:JSON.parse(r.headers.get('X-PCM-Receipt')),stream:r.body,dispose:async()=>{}};}});const readPCM=async(d,{maxBytes})=>{const o=await ports.bucket.get(d.reference);if(!o||o.size>maxBytes)throw Error('pcm');const reader=o.body.getReader(),parts=[];let n=0;for(;;){const p=await reader.read();if(p.done)break;n+=p.value.length;if(n>maxBytes)throw Error('pcm');parts.push(p.value);}const b=new Uint8Array(n);let offset=0;for(const p of parts){b.set(p,offset);offset+=p.length;}return b;};return{...adapters,unitDerivativePreparation:createUnitDerivativePreparation({storage:ports.storage,artifacts:ports.artifacts,pcmStore,readPCM,eligibility:eligible,dependencySha256:env.UNIT_POLICY})};}};}}
export default{async fetch(r,e){if(new URL(r.url).pathname==='/test-revoke-on-wav'){revokeOnWav=true;return Response.json({armed:true});}if(new URL(r.url).pathname==='/test-revoke'){admitted=false;return Response.json({revoked:true});}return await servePreparation(r,e,{guideExecutionProfile:profile(e),guideExecutionEligibility:eligible,guideUnitDependencySha256:e.UNIT_POLICY})||new Response('missing',{status:404});}};`;

test('qualified actual unit routes serve only verified whole-file WAV with live authority',{skip:!process.env.FIA_WINDOW_RAW_PROOF||!process.env.FIA_WINDOW_PYTHON||!process.env.FIA_RETAINED_P3},async()=>{
 const require=createRequire(resolve(process.env.FIA_WORKER_DEPENDENCIES||'package.json')),{build}=require('esbuild'),{Miniflare,convertV4MiniflareOptions}=require('miniflare'),dir=await mkdtemp(join(tmpdir(),'fia-public-unit-')),workDirectory=join(dir,'local');await mkdir(workDirectory);
 const rawDir=resolve(process.env.FIA_WINDOW_RAW_PROOF),proof=JSON.parse(await readFile(join(rawDir,'p3-dispatch-proof.json'))),source=await readFile(process.env.FIA_RETAINED_P3),rawPaths=proof.rawSha256s.map(h=>join(rawDir,h+'.json')),firstRaw=JSON.parse(await readFile(rawPaths[0]));assert.equal(sha(source),firstRaw.planIdentity.sourceSha256);
 const scriptPath=resolve('server/fia/preparation/executor/local-window-runtime.py'),local=await createLocalWindowAdapter({pythonPath:process.env.FIA_WINDOW_PYTHON,scriptPath,scriptSha256:sha(await readFile(scriptPath)),modelDirectory:process.env.FIA_WINDOW_MODEL,modelId:'Systran/faster-whisper-tiny.en',modelManifestSha256:firstRaw.planIdentity.modelSha256,runtimeManifest:JSON.parse(await readFile(process.env.FIA_WINDOW_RUNTIME_MANIFEST)),workDirectory});assert.equal(local.decoderSha256,firstRaw.planIdentity.decoderSha256);
 const policy={revision:'public-unit-test@1',maxBytes:2097152,totalMs:30000,progressMs:15000},profile={schema:'fia-guide-execution-profile@1',acquisitionSha256:sha(Buffer.from(JSON.stringify({policy,schema:'fia-observed-stream-acquisition@1'}))),recognitionSha256:'c'.repeat(64),artifactPolicySha256:'a'.repeat(64),modelRecipe:{modelId:'Systran/faster-whisper-tiny.en',modelRevision:firstRaw.planIdentity.modelSha256,configSha256:firstRaw.planIdentity.configSha256}};
 // Canonical hashing matches the real acquisition constructor.
 const {canonicalJSONString}=await import('../../server/fia/preparation/contract.mjs');profile.acquisitionSha256=sha(Buffer.from(canonicalJSONString({schema:'fia-observed-stream-acquisition@1',policy})));
 let mf,bucket;const counts={source:0,recognition:0,decode:0,external:0},bundle=await build({stdin:{contents:worker,resolveDir:root},bundle:true,platform:'browser',format:'esm',external:['node:*'],write:false});
 const options={...convertV4MiniflareOptions({modules:true,script:bundle.outputFiles[0].text,compatibilityDate:'2026-09-01',compatibilityFlags:['nodejs_compat'],bindings:{QUALIFICATION_SHA:sha(await readFile(resolve('server/fia/preparation/fixtures/p3-unit-derivative-qualification.json'))),QUALIFICATION_TEXT:await readFile(resolve('server/fia/preparation/fixtures/p3-unit-derivative-qualification.json'),'utf8'),FIA_API_ORIGIN:'https://dev.fiaguide.app',PROFILE:JSON.stringify(profile),ACQUISITION_POLICY:JSON.stringify(policy),PCM_POLICY:sha(await readFile(resolve('server/fia/preparation/executor/verified-pcm-store.mjs'))),UNIT_POLICY:sha(await readFile(resolve('server/fia/preparation/executor/unit-derivative-preparation.mjs')))},durableObjects:{FIA_PREPARATION_JOBS:{className:'FiaPreparationJobs',useSQLite:true}},r2Buckets:['FIA_ORIGINALS'],serviceBindings:{ASSETS:async r=>new Response(await readFile(resolve('apps/web/public'+new URL(r.url).pathname))),INPUT:async r=>new Response(await readFile(rawPaths[Number(new URL(r.url).pathname.slice(-1))])),SOURCE:()=>{counts.source++;return new Response(source,{headers:{'Content-Type':'audio/mpeg','Content-Length':String(source.length)}});},COUNT:()=>{counts.recognition++;return new Response('counted');},PCM:async r=>{counts.decode++;const req=await r.json(),producer=createBoundedSourceReader({bucket}),decoded=await local.decodeStream({source:req.source,openSource:producer.openSource,signal:r.signal}),iterator=createReadStream(decoded.pcmPath,{highWaterMark:65536})[Symbol.asyncIterator](),receipt=Object.fromEntries(['sourceSha256','pcmSha256','totalSamples','sampleRate','decoderSha256'].map(k=>[k,decoded.receipt[k]]));return new Response(new ReadableStream({async pull(c){try{const p=await iterator.next();if(p.done){await decoded.dispose();c.close();}else c.enqueue(new Uint8Array(p.value));}catch(e){await decoded.dispose();c.error(e);}},async cancel(){await iterator.return();await decoded.dispose();}}),{headers:{'Content-Length':String(decoded.receipt.totalSamples*4),'X-PCM-Receipt':JSON.stringify(receipt)}});}},outboundService:()=>{counts.external++;throw Error('No external');}}),resourcePersistencePath:join(dir,'storage')};
 const call=async(path,body)=>{const r=await mf.dispatchFetch('https://dev.fiaguide.app'+path,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),text=await r.text();return{status:r.status,body:JSON.parse(text)};},metadata=JSON.parse(await readFile(resolve('server/fia/preparation/guide-sources.json'))),row=metadata.rows.find(r=>r.packId==='eng.MRK-1-21-28'&&r.stepId==='S01'),consumer=id=>({packId:row.packId,presentationRevision:row.presentationRevision,language:row.language,edition:row.edition,...row.sourceUnits.find(u=>u.sourceUnitId===id)}),terminal=async path=>{for(let n=0;n<500;n++){const r=await call(path);if(!['queued','preparing'].includes(r.body.state))return r;await new Promise(r=>setTimeout(r,20));}throw Error('unit-status-timeout');};
 try{mf=new Miniflare(options);bucket=await mf.getR2Bucket('FIA_ORIGINALS');for(const change of [{language:'spa'},{edition:'wrong'},{sourceTextSha256:'f'.repeat(64)}]){const refused=await call('/v1/guide-unit-preparations',{...consumer('S01-U008'),...change});assert(refused.status>=400);}assert.deepEqual(counts,{source:0,recognition:0,decode:0,external:0});
 const a=await call('/v1/guide-unit-preparations',consumer('S01-U008'));assert.equal(a.status,202,JSON.stringify(a));const b=await call('/v1/guide-unit-preparations',consumer('S01-U006'));assert.equal(b.status,202,JSON.stringify(b));const first=await terminal(a.body.statusUrl);assert.equal(first.body.state,'ready',JSON.stringify(first));assert.deepEqual(first.body.consumer,consumer('S01-U008'));assert.equal(first.body.candidateProjection.provenance.sourceUnitId,'S01-U008');assert.equal(first.body.result.schema,'fia-qualified-unit-derivative@1');assert.deepEqual(first.body.acceptedPlaybackRanges,[]);
 const second=await terminal(b.body.statusUrl);assert.equal(second.body.state,'ready',JSON.stringify(second));assert.equal(second.body.candidateProjection.provenance.sourceUnitId,'S01-U006');assert.equal(a.body.sourceJobId,b.body.sourceJobId);assert.notEqual(a.body.statusUrl,b.body.statusUrl);assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
 const unresolvedPost=await call('/v1/guide-unit-preparations',consumer('S01-U001'));assert.equal(unresolvedPost.status,202);const unresolved=await terminal(unresolvedPost.body.statusUrl);assert.equal(unresolved.body.state,'blocked');assert.equal(unresolved.body.candidateProjection,null);const warmPost=await call('/v1/guide-unit-preparations',consumer('S01-U008'));assert.equal(warmPost.body.state,'ready');assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
 for(const ready of [first,second]){const url=ready.body.result.delivery.url,audio=await mf.dispatchFetch('https://dev.fiaguide.app'+url),bytes=new Uint8Array(await audio.arrayBuffer());assert.equal(audio.status,200);assert.equal(audio.headers.get('content-type'),'audio/wav');assert.equal(sha(bytes),ready.body.result.delivery.sha256);const head=await mf.dispatchFetch('https://dev.fiaguide.app'+url,{method:'HEAD'});assert.equal(head.status,200);assert.equal((await head.arrayBuffer()).byteLength,0);const partial=await mf.dispatchFetch('https://dev.fiaguide.app'+url,{headers:{Range:'bytes=0-99'}});assert.equal(partial.status,416);await partial.arrayBuffer();const wrong=await mf.dispatchFetch('https://dev.fiaguide.app'+url.replace(/[^/]+$/, 'f'.repeat(64)+'.wav'));assert.equal(wrong.status,404);await wrong.arrayBuffer();}
 await mf.dispose();mf=new Miniflare(options);bucket=await mf.getR2Bucket('FIA_ORIGINALS');for(const initial of [first,second]){const warm=await call(initial.body.statusUrl);assert.equal(warm.body.state,'ready');assert.deepEqual(warm.body.candidateProjection,initial.body.candidateProjection);}assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
 const wavKey=first.body.candidateProjection.wav.reference,savedObject=await bucket.get(wavKey),savedWav=new Uint8Array(await savedObject.arrayBuffer());await bucket.put(wavKey,new Uint8Array([1,2,3]));const tampered=await call(first.body.statusUrl);assert(tampered.status>=400,JSON.stringify(tampered));assert.equal(tampered.body.candidateProjection??null,null);assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});await bucket.put(wavKey,savedWav);
 const sourceStatus='/v1/guide-preparations/'+a.body.sourceJobId;
 for(const pin of ['f'.repeat(64),null]){await mf.dispose();const historicalOptions={...options,workers:options.workers.map(w=>{const env={...w.config.env};if(pin===null)delete env.UNIT_POLICY;else env.UNIT_POLICY={type:'text',value:pin};return{...w,config:{...w.config,env}};})};mf=new Miniflare(historicalOptions);bucket=await mf.getR2Bucket('FIA_ORIGINALS');const sourceWarm=await call(sourceStatus);assert.equal(sourceWarm.status,200,JSON.stringify(sourceWarm));assert.equal(sourceWarm.body.state,'review-required');const oldUnit=await call(first.body.statusUrl);assert(oldUnit.status>=400,JSON.stringify(oldUnit));assert.equal(oldUnit.body.candidateProjection??null,null);assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});}
 await mf.dispose();mf=new Miniflare(options);bucket=await mf.getR2Bucket('FIA_ORIGINALS');assert.equal((await call(first.body.statusUrl)).body.state,'ready');
 await call('/test-revoke-on-wav');const revokedDuringRead=await call(first.body.statusUrl);assert(revokedDuringRead.status>=400);assert.equal(revokedDuringRead.body.candidateProjection,undefined);
 await call('/test-revoke');assert((await call(first.body.statusUrl)).status>=400);assert((await call('/v1/guide-unit-preparations',consumer('S01-U008'))).status>=400);assert.deepEqual(counts,{source:1,recognition:1,decode:1,external:0});
 if(process.env.FIA_WINDOW_PROOF_DIR){await mkdir(process.env.FIA_WINDOW_PROOF_DIR,{recursive:true});await writeFile(join(process.env.FIA_WINDOW_PROOF_DIR,'qualified-public-unit-route.json'),JSON.stringify({status:'PASS',counts,modelInvocations:0,first:first.body,second:second.body,scope:'Injected development verifier only; no new production semantic acceptance. Actual public Worker routes, SQLite/R2, original retained bytes via local service transport, unchanged retained window raw candidates, actual local decode, two concurrent units, restart warm reuse, revocation; candidate-only no playback grant.'},null,2));}
 }finally{await mf?.dispose();await rm(dir,{recursive:true,force:true});}
});
