import test from 'node:test';import assert from 'node:assert/strict';import {readFile,mkdtemp,rm} from 'node:fs/promises';import {resolve,join}from'node:path';import{tmpdir}from'node:os';import {runtime,terminal} from './guide-active.test.mjs';
const origin='https://dev.fiaguide.app',metadata=JSON.parse(await readFile(resolve('server/fia/preparation/guide-sources.json'))),row=metadata.rows.find(r=>r.packId==='eng.MRK-1-21-28'&&r.stepId==='S01'),request={packId:row.packId,presentationRevision:row.presentationRevision,language:row.language,edition:row.edition,...row.sourceUnits[0]};
const executionProfile={schema:'fia-guide-execution-profile@1',acquisitionSha256:'a'.repeat(64),recognitionSha256:'b'.repeat(64),artifactPolicySha256:'c'.repeat(64),modelRecipe:{modelId:'Systran/faster-whisper-tiny.en',modelRevision:'60a1e73109aa75058f81191da437d3fa4ea57f1127bef81d4500e242988ad16d',configSha256:'b59c2ba55316966aa336a33535efb0240db19e16bdafcf76288926016cd0e6ca'}};
const post=mf=>mf.dispatchFetch(origin+'/v1/guide-preparations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(request)});
test('P3 execution policy admits literal audited source beyond playback catalog; retained bytes/raw produce only review evidence',{skip:!process.env.FIA_RETAINED_P3},async()=>{const directory=await mkdtemp(join(tmpdir(),'fia-guide-p3-'));let f;try{f=await runtime({directory,sourceBytes:await readFile(process.env.FIA_RETAINED_P3),executionProfile,executionPolicy:true,rawPath:resolve('tests/preparation-executor/fixtures/p3-raw-recognition.json')});const first=await(await post(f.mf)).json();assert.equal(first.state,'queued');const done=await terminal(f.mf,first.statusUrl);assert.equal(done.state,'review-required');assert.equal(done.result,null);assert.equal(f.counts.source,1);assert.equal(f.counts.raw,1);await f.mf.dispose();f=await runtime({directory,executionProfile,executionPolicy:true,offline:true});const warm=await(await f.mf.dispatchFetch(origin+first.statusUrl)).json();assert.equal(warm.state,'review-required');await f.mf.dispatchFetch(origin+'/test-known-bad?sha=faa40ccc1704033ee23679aff097f64f271c07cb9f1474640d1070f9a9739ba4');assert.equal((await f.mf.dispatchFetch(origin+first.statusUrl)).status,409);assert.equal(f.counts.source,0);assert.equal(f.counts.raw,0);}finally{if(f)await f.mf.dispose();await rm(directory,{recursive:true,force:true});}});

test('execution authority rejects asynchronous and truthy callbacks before source dispatch',async()=>{for(const eligibilityMode of ['promise','truthy']){const f=await runtime({executionProfile,executionPolicy:true,eligibilityMode});try{assert.equal((await post(f.mf)).status,422);assert.equal(f.counts.source,0);assert.equal(f.counts.raw,0);}finally{await f.mf.dispose();}}});
test('execution-only terminal missing observed provenance is corrupt, not reusable evidence',{skip:!process.env.FIA_RETAINED_P3},async()=>{const f=await runtime({sourceBytes:await readFile(process.env.FIA_RETAINED_P3),executionProfile,executionPolicy:true,rawPath:resolve('tests/preparation-executor/fixtures/p3-raw-recognition.json')});try{const first=await(await post(f.mf)).json();assert.equal((await terminal(f.mf,first.statusUrl)).state,'review-required');await f.mf.dispatchFetch(origin+'/test-clear-observed?id='+first.jobId);assert.equal((await f.mf.dispatchFetch(origin+first.statusUrl)).status,409);}finally{await f.mf.dispose();}});
test('unknown hash is observed before known-bad policy blocks recognition, without playback catalog admission',async()=>{const f=await runtime({executionProfile,executionPolicy:true});try{await f.mf.dispatchFetch(origin+'/test-known-bad?sha=039058c6f2c0cb492c533b0a4d14ef77cc0f78abccced5287d84a1a2011cfb81');const first=await(await post(f.mf)).json();assert.equal(first.state,'queued');const done=await terminal(f.mf,first.statusUrl);assert.equal(done.state,'uncertain');assert.equal(done.candidateEvidenceSha256,null);assert.equal(f.counts.source,1);assert.equal(f.counts.raw,0);}finally{await f.mf.dispose();}});

test('retained pipeline source verification refuses missing acquisition or source-reference provenance',{skip:!process.env.FIA_RETAINED_P3},async()=>{for(const prefix of ['originals/acquisitions/','originals/refs/']){const f=await runtime({sourceBytes:await readFile(process.env.FIA_RETAINED_P3),executionProfile,executionPolicy:true,rawPath:resolve('tests/preparation-executor/fixtures/p3-raw-recognition.json')});try{const first=await(await post(f.mf)).json();assert.equal((await terminal(f.mf,first.statusUrl)).state,'review-required');assert.equal((await(await f.mf.dispatchFetch(origin+'/test-delete-provenance?prefix='+encodeURIComponent(prefix))).json()).count,1);await f.mf.dispatchFetch(origin+'/test-requeue-retained-stages?id='+first.jobId);assert.notEqual((await terminal(f.mf,first.statusUrl)).state,'review-required');assert.equal(f.counts.source,1);assert.equal(f.counts.raw,1);}finally{await f.mf.dispose();}}});
