import test from 'node:test';import assert from 'node:assert/strict';import {readFile}from'node:fs/promises';
import {qualifyUnitDerivative,P3_UNIT_QUALIFICATION_SHA256}from'../../server/fia/preparation/unit-derivative-qualification.mjs';
import{canonicalJSONString,sha256}from'../../server/fia/preparation/contract.mjs';
const bytes=new Uint8Array(await readFile(new URL('../../server/fia/preparation/fixtures/p3-unit-derivative-qualification.json',import.meta.url))),bundle=JSON.parse(new TextDecoder().decode(bytes)),manifest=JSON.parse(bundle.manifestText);
function args(id='S01-U006'){const h=manifest.units.find(x=>x.sourceUnitId===id);return{qualificationBytes:new Uint8Array(bytes),qualificationSha256:P3_UNIT_QUALIFICATION_SHA256,consumer:{...bundle.consumerScope,sourceUnitId:id,sourceTextSha256:h.provenance.sourceTextSha256},candidate:{state:'candidate',qualifiedForPlayback:false,acceptedPlaybackRanges:[],wav:{sha256:h.deliverySha256,reference:'retained/'+h.deliverySha256},preparation:{identity:{canonicalSha256:h.provenance.canonicalSha256,sourceUnitId:id,sourceTextSha256:h.provenance.sourceTextSha256}},projection:[{sourceUnitId:id,sourceTextSha256:h.provenance.sourceTextSha256,status:'exact-unique',qualifiedForPlayback:false,candidate:{sha256:h.deliverySha256,reference:'retained/'+h.deliverySha256}}],provenance:structuredClone(h.provenance)}};}
test('all four exact tested deliveries qualify finite original whole-file playback without highlights',async()=>{assert.equal(await sha256(bytes),P3_UNIT_QUALIFICATION_SHA256);for(const h of manifest.units){const r=await qualifyUnitDerivative(args(h.sourceUnitId));assert.equal(r.delivery.sha256,h.deliverySha256);assert.equal(r.delivery.rate,1);assert.equal(r.delivery.wordHighlight,false);assert.equal(r.nativeDacTimingQualified,false);assert.equal(r.bridgeSha256,await sha256(canonicalJSONString(r.bridge)));assert.equal(r.bridge.currentProvenanceSha256,r.bridge.historicalProvenanceSha256);assert(!Object.hasOwn(r.delivery,'url'));}});
test('new independently verified recipe pins retain historical proof and bind current provenance',async()=>{const a=args();for(const k of ['rawSha256','windowSha256','planSha256','measurementSha256','correspondenceSha256'])a.candidate.provenance[k]='1'.repeat(64);a.candidate.provenance.planIdentity.decoderSha256='2'.repeat(64);const r=await qualifyUnitDerivative(a);assert.notEqual(r.bridge.currentProvenanceSha256,r.bridge.historicalProvenanceSha256);assert.equal(r.bridge.currentPins.rawSha256,'1'.repeat(64));assert.equal(r.delivery.sha256,a.candidate.wav.sha256);});
test('wrong authority hash, changed bundle bytes, consumer or unresolved units refuse',async()=>{for(const change of [a=>a.qualificationSha256='0'.repeat(64),a=>a.qualificationBytes[0]^=1,a=>a.consumer.sourceUnitId='S01-U001',a=>a.consumer.sourceUnitId='S01-U999',a=>a.consumer.language='spa',a=>a.consumer.sourceTextSha256='0'.repeat(64),a=>a.consumer.extra=true]){const a=args();change(a);await assert.rejects(qualifyUnitDerivative(a));}});
test('changed source PCM slice quiet evidence or WAV cannot borrow old qualification',async()=>{for(const change of [p=>p.sourceSha256='0'.repeat(64),p=>p.pcmSha256='0'.repeat(64),p=>p.canonicalSha256='0'.repeat(64),p=>p.sourceSampleRange.startSample++,p=>p.quietEvidence.left.cutSample++,p=>p.delivery.sha256='0'.repeat(64),p=>p.delivery.wordHighlight=true,p=>p.delivery.durationSeconds+=.001]){const a=args();change(a.candidate.provenance);await assert.rejects(qualifyUnitDerivative(a));}});
test('even trusted repinned malformed EOF/profile/decode receipts refuse',async()=>{for(const change of [r=>r.profile.platform='other',r=>r.inputs.controllerSha256='0'.repeat(64),r=>r.trials[1].decodedPcmSha256='0'.repeat(64),r=>r.trials[1].endCount=2,r=>r.trials[1].events.find(e=>e.type==='ended').currentTime=0,r=>r.trials[1].events.find(e=>e.type==='playing').muted=true]){const a=args(),b=JSON.parse(new TextDecoder().decode(a.qualificationBytes)),r=JSON.parse(b.browserReceiptText);change(r);b.browserReceiptText=JSON.stringify(r);a.qualificationBytes=new TextEncoder().encode(JSON.stringify(b));a.qualificationSha256=await sha256(a.qualificationBytes);await assert.rejects(qualifyUnitDerivative(a));}});
test('caller mutation after invocation cannot alter captured evidence',async()=>{const a=args(),p=qualifyUnitDerivative(a);a.qualificationBytes.fill(0);a.consumer.language='spa';a.candidate.provenance.sourceSha256='0'.repeat(64);assert.equal((await p).consumer.language,'eng');});

test('actual retained public-route current canonical recipe bridges identical qualified WAVs',async()=>{const fixture=JSON.parse(await readFile(new URL('./fixtures/retained-unit-public-candidates.json',import.meta.url)));for(const item of fixture.cases){const r=await qualifyUnitDerivative({...item,qualificationBytes:bytes,qualificationSha256:P3_UNIT_QUALIFICATION_SHA256});assert.notEqual(r.bridge.currentCanonicalSha256,r.bridge.historicalCanonicalSha256);assert.equal(r.delivery.sha256,item.candidate.wav.sha256);const bad=structuredClone(item);bad.candidate.preparation.identity.canonicalSha256='0'.repeat(64);await assert.rejects(qualifyUnitDerivative({...bad,qualificationBytes:bytes,qualificationSha256:P3_UNIT_QUALIFICATION_SHA256}));}});
test('current projection must isolate exact selected canonical unit and delivery',async()=>{for(const mutate of [a=>a.candidate.projection[0].status='unmatched',a=>a.candidate.projection[0].sourceTextSha256='0'.repeat(64),a=>a.candidate.projection[0].candidate.sha256='0'.repeat(64),a=>a.candidate.projection.push(structuredClone(a.candidate.projection[0]))]){const a=args();mutate(a);await assert.rejects(qualifyUnitDerivative(a));}});
