// C-13 rights records: one per source repo, licence fields verbatim from <lang>/metadata.json resource_metadata.
// Discrepancies are recorded, never resolved by code (R-312).
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { DATA_ROOT, fetchJson, loadSources, plainText, stableJson } from './lib.mjs';

function holdersIn(rm) {
  const holders = new Set();
  const h = rm.license_info?.copyright?.holder?.name; if (h) holders.add(h);
  const notice = rm.adaptation_notice ? plainText(rm.adaptation_notice) : '';
  for (const m of notice.matchAll(/©\s*\d{4}\s+([A-Z][A-Za-z]+(?:\s[A-Z][A-Za-z]+)*)/g)) holders.add(m[1].replace(/\s+(Released|Adapted)$/, ''));
  for (const m of notice.matchAll(/\bby\s+(Mission Mutual)\b/g)) holders.add(m[1]);
  return [...holders];
}

export async function rightsRecord(sources, repo, sha, language) {
  const r = await fetchJson(sources, repo, sha, `${language}/metadata.json`);
  const rm = r.json.resource_metadata;
  const holders = holdersIn(rm);
  const discrepancies = [];
  const licHolder = rm.license_info?.copyright?.holder?.name;
  const noticeHolders = holders.filter((h) => h !== licHolder && h !== 'Mission Mutual');
  if (licHolder && noticeHolders.length) discrepancies.push(`holder differs between license_info ("${licHolder}") and adaptation_notice (${noticeHolders.map((h) => `"${h}"`).join(', ')})`);
  if (rm.license_info?.title && rm.title && rm.license_info.title.toLowerCase() !== rm.title.toLowerCase()) discrepancies.push(`license_info.title ("${rm.license_info.title}") differs from resource title ("${rm.title}")`);
  const record = {
    schemaVersion: 1,
    id: `${repo}@${sha.slice(0, 7)}`,
    collection: repo,
    revision: sha,
    licenseInfo: JSON.stringify(rm.license_info),
    ...(rm.adaptation_notice ? { adaptationNotice: rm.adaptation_notice } : {}),
    holders: holders.length ? holders : ['(no holder named in metadata)'],
    url: `https://github.com/BibleAquifer/${repo}`,
    metadataSha256: r.sha256,
    ...(discrepancies.length ? { discrepancies } : {}),
  };
  return { record, extra: { title: rm.title, language, licenses: rm.license_info?.licenses, showAdaptationNoticeForNonEnglish: rm.license_info?.showAdaptationNoticeForNonEnglish ?? null } };
}

export async function buildRights({ log = console.error } = {}) {
  const sources = await loadSources();
  const records = [], extras = {};
  for (const [repo, pin] of Object.entries(sources.fia)) { const { record, extra } = await rightsRecord(sources, repo, pin.commitSha, 'eng'); records.push(record); extras[record.id] = extra; log(`${record.id}: ${record.holders.join(' | ')}${record.discrepancies ? ' — ' + record.discrepancies.join('; ') : ''}`); }
  for (const b of sources.bibles) { try { const { record, extra } = await rightsRecord(sources, b.repo, b.commitSha, b.language); records.push(record); extras[record.id] = extra; log(`${record.id}: ${record.holders.join(' | ')}`); } catch (e) { log(`${b.repo}: rights metadata unreadable (${e.message})`); records.push({ schemaVersion: 1, id: `${b.repo}@${b.commitSha.slice(0, 7)}`, collection: b.repo, revision: b.commitSha, licenseInfo: '', holders: ['(metadata unreadable)'], url: `https://github.com/BibleAquifer/${b.repo}`, metadataSha256: '0'.repeat(64), discrepancies: [`metadata.json unreadable at pin: ${e.message}`] }); } }
  const outDir = path.join(DATA_ROOT, 'rights');
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'records.json'), stableJson(records));
  await writeFile(path.join(outDir, 'NOTICE.md'), noticeMarkdown(records, extras));
  return records;
}

function noticeMarkdown(records, extras) {
  const lines = ['# NOTICE — content sources and licences (generated, verbatim fields)', '', 'Generated by `@fia-app/pipeline` (`npm run rights`) from each BibleAquifer repository\'s `metadata.json` at the pinned commit. Licence fields are reproduced verbatim; discrepancies are listed, not resolved (R-312). App code is MIT (see repo LICENSE); this file covers content only.', ''];
  for (const r of records) {
    const x = extras[r.id] || {};
    const lic = (x.licenses || []).map((l) => Object.values(l).map((v) => `${v.name} <${v.url}>`).join(', ')).join('; ');
    lines.push(`## ${x.title || r.collection} (${r.id})`, '', `- Repository: ${r.url}`, `- Revision: \`${r.revision}\``, `- Licence: ${lic || '(none stated)'}`, `- Holder(s): ${r.holders.join(' · ')}`, `- \`license_info\` (verbatim JSON): \`${r.licenseInfo}\``);
    if (r.adaptationNotice) lines.push(`- Adaptation notice (verbatim HTML): ${r.adaptationNotice}`, `- Show adaptation notice for non-English: ${x.showAdaptationNoticeForNonEnglish}`);
    if (r.discrepancies) lines.push(`- **Discrepancies (unresolved):** ${r.discrepancies.join('; ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

// BL8 (F3a S15): the holder and licence lines a pack carries for each of its sources, read from the C-13 records.
// Nothing is invented: a missing record, a placeholder holder or an absent licence stays null. Discrepancies are
// carried verbatim (R-312): [] when the record lists none, null when there is no record.
const HOLDER_PLACEHOLDERS = new Set(['(no holder named in metadata)', '(metadata unreadable)']);
const isObj = (v) => v !== null && typeof v === 'object' && !Array.isArray(v);
const hasLicence = (v) => isObj(v) && (v.name != null || v.url != null);

// Reads licenseInfo the way the app's parseLicenseInfo does (src/settings/rights.ts:26-46): JSON text of
// license_info, or — when it is not a JSON object — a plain licence name (the C-13 schema example form).
// The pipeline additionally prefers the pack language entry, then eng, then the first stated licence.
export function licenceFrom(licenseInfo, language) {
  if (typeof licenseInfo !== 'string' || licenseInfo === '') return null;
  let info;
  try { info = JSON.parse(licenseInfo); } catch { return { name: licenseInfo, url: null }; }
  if (!info || typeof info !== 'object') return { name: licenseInfo, url: null };
  const entries = Array.isArray(info.licenses) ? info.licenses.filter(isObj) : [];
  const pick = entries.map((l) => l[language]).find(hasLicence) || entries.map((l) => l.eng).find(hasLicence) || entries.flatMap((l) => Object.values(l)).find(hasLicence) || null;
  return pick ? { name: pick.name ?? null, url: pick.url ?? null } : null;
}

export function packRightsLines(ids, records, language) {
  const byId = new Map(records.map((r) => [r.id, r]));
  return ids.map((id) => {
    const rec = byId.get(id);
    if (!rec) return { id, collection: id.split('@')[0], revision: null, holders: null, licence: null, url: null, discrepancies: null };
    const holders = Array.isArray(rec.holders) ? rec.holders.filter((h) => typeof h === 'string' && !HOLDER_PLACEHOLDERS.has(h)) : [];
    const discrepancies = Array.isArray(rec.discrepancies) ? rec.discrepancies.filter((d) => typeof d === 'string') : [];
    // C-13 1.1.0: revisionKind (absent = git) and licenceUrl are copied only when the record carries them, so git lines stay byte-identical.
    return {
      id, collection: rec.collection, ...(rec.revisionKind ? { revisionKind: rec.revisionKind } : {}), revision: rec.revision ?? null,
      holders: holders.length ? holders : null, licence: licenceFrom(rec.licenseInfo, language), ...(rec.licenceUrl ? { licenceUrl: rec.licenceUrl } : {}),
      url: rec.url ?? null, discrepancies,
    };
  });
}

// Absent → throw; stale (a pinned source in sources.json has no record at its pin, e.g. `npm run pin` without
// `npm run rights`) → throw, instead of writing a rights.json of nulls with exit 0.
export async function loadRightsRecords({ file = path.join(DATA_ROOT, 'rights', 'records.json'), sources } = {}) {
  if (!existsSync(file)) throw new Error(`rights: ${file} is missing; run \`npm run rights\` first (C-13 records are required for pack rights lines)`);
  const records = JSON.parse(await readFile(file, 'utf8'));
  const pins = sources ?? await loadSources();
  const have = new Set(records.map((r) => r.id));
  const want = [...Object.entries(pins.fia || {}).map(([repo, p]) => `${repo}@${p.commitSha.slice(0, 7)}`), ...(pins.bibles || []).map((b) => `${b.repo}@${b.commitSha.slice(0, 7)}`)];
  const missing = want.filter((id) => !have.has(id));
  if (missing.length) throw new Error(`rights: ${file} is stale — no C-13 record for ${missing.join(', ')}; run \`npm run rights\` after \`npm run pin\``);
  return records;
}
