// C-13 rights records: one per source repo, licence fields verbatim from <lang>/metadata.json resource_metadata.
// Discrepancies are recorded, never resolved by code (R-312).
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { DATA_ROOT, fetchJson, loadSources, plainText, stableJson } from './lib.mjs';

function holdersIn(rm) {
  const holders = new Set();
  const h = rm.license_info?.copyright?.holder?.name; if (h) holders.add(h);
  const notice = rm.adaptation_notice ? plainText(rm.adaptation_notice) : '';
  for (const m of notice.matchAll(/©\s*\d{4}\s+([A-Z][A-Za-z]+(?:\s[A-Z][A-Za-z]+)*)/g)) holders.add(m[1].replace(/\s+(Released|Adapted)$/, ''));
  for (const m of notice.matchAll(/\bby\s+(Mission Mutual)\b/g)) holders.add(m[1]);
  return [...holders];
}

export async function rightsRecord(sources, repo, sha, language) {
  const r = await fetchJson(sources, repo, sha, `${language}/metadata.json`);
  const rm = r.json.resource_metadata;
  const holders = holdersIn(rm);
  const discrepancies = [];
  const licHolder = rm.license_info?.copyright?.holder?.name;
  const noticeHolders = holders.filter((h) => h !== licHolder && h !== 'Mission Mutual');
  if (licHolder && noticeHolders.length) discrepancies.push(`holder differs between license_info ("${licHolder}") and adaptation_notice (${noticeHolders.map((h) => `"${h}"`).join(', ')})`);
  if (rm.license_info?.title && rm.title && rm.license_info.title.toLowerCase() !== rm.title.toLowerCase()) discrepancies.push(`license_info.title ("${rm.license_info.title}") differs from resource title ("${rm.title}")`);
  const record = {
    schemaVersion: 1,
    id: `${repo}@${sha.slice(0, 7)}`,
    collection: repo,
    revision: sha,
    licenseInfo: JSON.stringify(rm.license_info),
    ...(rm.adaptation_notice ? { adaptationNotice: rm.adaptation_notice } : {}),
    holders: holders.length ? holders : ['(no holder named in metadata)'],
    url: `https://github.com/BibleAquifer/${repo}`,
    metadataSha256: r.sha256,
    ...(discrepancies.length ? { discrepancies } : {}),
  };
  return { record, extra: { title: rm.title, language, licenses: rm.license_info?.licenses, showAdaptationNoticeForNonEnglish: rm.license_info?.showAdaptationNoticeForNonEnglish ?? null } };
}

export async function buildRights({ log = console.error } = {}) {
  const sources = await loadSources();
  const records = [], extras = {};
  for (const [repo, pin] of Object.entries(sources.fia)) { const { record, extra } = await rightsRecord(sources, repo, pin.commitSha, 'eng'); records.push(record); extras[record.id] = extra; log(`${record.id}: ${record.holders.join(' | ')}${record.discrepancies ? ' — ' + record.discrepancies.join('; ') : ''}`); }
  for (const b of sources.bibles) { try { const { record, extra } = await rightsRecord(sources, b.repo, b.commitSha, b.language); records.push(record); extras[record.id] = extra; log(`${record.id}: ${record.holders.join(' | ')}`); } catch (e) { log(`${b.repo}: rights metadata unreadable (${e.message})`); records.push({ schemaVersion: 1, id: `${b.repo}@${b.commitSha.slice(0, 7)}`, collection: b.repo, revision: b.commitSha, licenseInfo: '', holders: ['(metadata unreadable)'], url: `https://github.com/BibleAquifer/${b.repo}`, metadataSha256: '0'.repeat(64), discrepancies: [`metadata.json unreadable at pin: ${e.message}`] }); } }
  const outDir = path.join(DATA_ROOT, 'rights');
  await mkdir(outDir, { recursive: true });
  await writeFile(path.join(outDir, 'records.json'), stableJson(records));
  await writeFile(path.join(outDir, 'NOTICE.md'), noticeMarkdown(records, extras));
  return records;
}

function noticeMarkdown(records, extras) {
  const lines = ['# NOTICE — content sources and licences (generated, verbatim fields)', '', 'Generated by `@fia-app/pipeline` (`npm run rights`) from each BibleAquifer repository\'s `metadata.json` at the pinned commit. Licence fields are reproduced verbatim; discrepancies are listed, not resolved (R-312). App code is MIT (see repo LICENSE); this file covers content only.', ''];
  for (const r of records) {
    const x = extras[r.id] || {};
    const lic = (x.licenses || []).map((l) => Object.values(l).map((v) => `${v.name} <${v.url}>`).join(', ')).join('; ');
    lines.push(`## ${x.title || r.collection} (${r.id})`, '', `- Repository: ${r.url}`, `- Revision: \`${r.revision}\``, `- Licence: ${lic || '(none stated)'}`, `- Holder(s): ${r.holders.join(' · ')}`, `- \`license_info\` (verbatim JSON): \`${r.licenseInfo}\``);
    if (r.adaptationNotice) lines.push(`- Adaptation notice (verbatim HTML): ${r.adaptationNotice}`, `- Show adaptation notice for non-English: ${x.showAdaptationNoticeForNonEnglish}`);
    if (r.discrepancies) lines.push(`- **Discrepancies (unresolved):** ${r.discrepancies.join('; ')}`);
    lines.push('');
  }
  return lines.join('\n');
}
